### PR TITLE
[clang] Reject 'auto' storage class with type specifier in C++

### PR DESCRIPTION
**Pull request by osamakader**
Fixes #164273

### CODE REVIEW

**Comment by shafik** [comment]
I am going to be at the wg21 meeting next week, so I may not have a chance to look at this.

File: clang/test/CXX/drs/cwg3xx.cpp [hunk 1]
```diff
@@ -1732,11 +1732,13 @@ namespace cwg395 { // cwg395: 3.0
 namespace cwg396 { // cwg396: 3.0
   void f() {
     auto int a();
-    // since-cxx11-error@-1 {{'auto' storage class specifier is not permitted in C++11, and will not be supported in future releases}}
-    // expected-error@-2 {{illegal storage class on function}}
+    // since-cxx11-error@-1 {{'auto' cannot be combined with a type specifier in C++}}
+    // cxx98-error@-2 {{illegal storage class on function}}
```
Comment (Endilll) [inline clang/test/CXX/drs/cwg3xx.cpp]: I'd prefer to see C++98 diagnostic first. This way expected directives are in chronological order.

**Review by Endilll — COMMENTED** [review]
Changes to C++ DR tests LGTM otherwise.

File: clang/test/CXX/drs/cwg3xx.cpp (hunk 1 above)
Comment (osamakader) [reply clang/test/CXX/drs/cwg3xx.cpp]: OK

File: clang/lib/Parse/ParseDecl.cpp [hunk 2]
```diff
@@ -4095,11 +4095,22 @@ void Parser::ParseDeclarationSpecifiers(
...
       if (getLangOpts().CPlusPlus11 || getLangOpts().C23) {
         if (isKnownToBeTypeSpecifier(GetLookAheadToken(1))) {
-          isInvalid = DS.SetStorageClassSpec(Actions, DeclSpec::SCS_auto, Loc,
-                                             PrevSpec, DiagID, Policy);
-          if (!isInvalid && !getLangOpts().C23)
-            Diag(Tok, diag::ext_auto_storage_class)
-              << FixItHint::CreateRemoval(DS.getStorageClassSpecLoc());
+          // In C++ (not C23), 'auto' cannot be combined with a type specifier.
+          // However, OpenCL has its own error handling for this case.
+          if (getLangOpts().CPlusPlus && !getLangOpts().C23 &&
```
Comment (zygoloid) [inline clang/lib/Parse/ParseDecl.cpp]: No need to check both CPlusPlus and C23 here; they're mutually exclusive.

File: clang/lib/Parse/ParseDecl.cpp [hunk 3]
```diff
@@ -4095,11 +4095,22 @@ void Parser::ParseDeclarationSpecifiers(
     case tok::kw_auto:
       if (getLangOpts().CPlusPlus11 || getLangOpts().C23) {
         if (isKnownToBeTypeSpecifier(GetLookAheadToken(1))) {
-          isInvalid = DS.SetStorageClassSpec(Actions, DeclSpec::SCS_auto, Loc,
-                                             PrevSpec, DiagID, Policy);
-          if (!isInvalid && !getLangOpts().C23)
-            Diag(Tok, diag::ext_auto_storage_class)
-              << FixItHint::CreateRemoval(DS.getStorageClassSpecLoc());
+          // In C++ (not C23), 'auto' cannot be combined with a type specifier.
+          // However, OpenCL has its own error handling for this case.
```
Comment (zygoloid) [inline clang/lib/Parse/ParseDecl.cpp]: What is the OpenCL handling? If it's the same as the general C++ handling, can we remove the OpenCL handling and enable the new code for OpenCL too?

File: clang/include/clang/Basic/DiagnosticParseKinds.td [hunk 4]
```diff
@@ -399,6 +399,8 @@ def err_requires_clause_on_declarator_not_declaring_a_function : Error<
   "trailing requires clause can only be used when declaring a function">;
 def err_requires_clause_inside_parens : Error<
   "trailing requires clause should be placed outside parentheses">;
+def err_auto_type_specifier : Error<
+  "'auto' cannot be combined with a type specifier">;
 def ext_auto_storage_class : ExtWarn<
   "'auto' storage class specifier is not permitted in C++11, and will not "
```
Comment (Sirraide) [inline clang/include/clang/Basic/DiagnosticParseKinds.td]: This pr makes `ext_auto_storage_class` unused, so we should remove it

File: clang/test/Parser/cxx-auto-type-specifier.cpp [hunk 5]
```diff
@@ -0,0 +1,22 @@
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c++11 %s
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c++14 %s
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c++17 %s
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c++20 %s
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c++23 %s
+
+// Test that 'auto' cannot be combined with a type specifier in C++.
+void f() {
+  auto int x = 1;        // expected-error {{'auto' cannot be combined with a type specifier}}
```
Comment (AaronBallman) [inline clang/test/Parser/cxx-auto-type-specifier.cpp]: One more test to add:
```
template <typename Ty>
void g() {
  auto Ty x;
}

void test() {
  g<float>();
}
```

File: clang/test/CXX/dcl.dcl/dcl.spec/dcl.type/dcl.spec.auto/p3.cpp [hunk 6]
```diff
@@ -42,7 +42,12 @@ void p3example() {
   static auto y = 0.0;
```
[the remark this answers is not in the document]
Comment (AaronBallman) [reply clang/test/CXX/dcl.dcl/dcl.spec/dcl.type/dcl.spec.auto/p3.cpp]: > I see a diagnostic for it appearing in all of your test cases:

Ugh, yeah, I am seeing that now, I think I was looking at the wrong output before. :-D

Yeah, I think the table just needs to be updated, that doesn't need to be a part of this PR though. Thanks!

File: clang/lib/Parse/ParseDecl.cpp (hunk 3 above)
Comment (svenvh) [reply clang/lib/Parse/ParseDecl.cpp]: Yes, I think we can drop the OpenCL specific diagnostic in favor of the C++ diagnostic.

File: clang/test/Parser/cxx-auto-type-specifier.cpp (hunk 5 above)
Comment (osamakader) [reply clang/test/Parser/cxx-auto-type-specifier.cpp]: @AaronBallman

Comment (AaronBallman) [reply clang/test/Parser/cxx-auto-type-specifier.cpp]: This might not be an easy thing to fix. One thing to try investigating is: we have this `annot_typename` token that is an annotation token saying "the token is a type". This is produced from calling one of the `TryAnnotate*()` functions in the parser; that basically does some tentative parsing and other tricks to potentially produce the annotation token so when the parser gets the next token, it gets the annotation that did all of the heavy lifting. What I'd try is to see if we can get a `TryAnnotate*()` function to replace the call to `GetLookAheadToken(1)`. The check for the type specifier will work correctly with an `annot_typename` token, but none of the existing try-annotation functions work off a given token, they all start from the current token.

Does that make sense?

Comment (osamakader) [reply clang/test/Parser/cxx-auto-type-specifier.cpp]: So, I tried that:

```
     TentativeParsingAction TPA(*this);
     ConsumeToken(); 
     TryAnnotateTypeOrScopeToken()
     NextIsTypeSpecifier = isKnownToBeTypeSpecifier(Tok);
     TPA.Revert();
```

TryAnnotate* incorrectly annotates some syntax e.g. in llvm-project/clang/test/Parser/cxx-concepts-requires-clause.cpp:

```
template <typename T> T Foo;
template <typename T> auto C(Foo<T>);
```

As true which breaks this test and many other tests.

Comment (mizvekov) [reply clang/test/Parser/cxx-auto-type-specifier.cpp]: Yeah, I don't see what annotation we would need. For this example:
```
template <typename Ty>
void g() {
  auto Ty x;
}
```

We know `Ty` is a type, and we know there is no type which could be substituted here making this definition valid, so we can diagnose this right away.

Comment (osamakader) [reply clang/test/Parser/cxx-auto-type-specifier.cpp]: Latest commit has that template test case passing without annotation.

Comment (zygoloid) [reply clang/test/Parser/cxx-auto-type-specifier.cpp]: You don't need to diagnose conflicts from `Finish`. Here's one approach:

* When consuming `auto`, treat it as specified by the underlying language (either a type specifier or a storage class specifier).
* If we encounter a conflict between storage classes, if one of them is `auto` and there is no type specifier yet, then set the type specifier to `auto` and keep the other storage class as the "real" storage class specifier.
* In `Finish`, if there is a storage class of `auto` and no type specifier at all, and we're in a language mode without "implicit int", then convert the storage class to a type specifier.

Finally, if we have a type specifier of `TST_auto` in a language that doesn't support it, then produce a warning.

In fact, looking at the `DeclSpec` implementation, we already do all of that. So I'm a bit confused about what we're discussing.

**Comment by osamakader** [comment]
ping :)

File: clang/include/clang/Sema/DeclSpec.h [hunk 7]
```diff
@@ -415,6 +415,12 @@ class DeclSpec {
   SourceLocation FriendLoc, ModulePrivateLoc, ConstexprLoc;
   SourceLocation TQ_pipeLoc;
 
+  // Track conflicting type specifier when 'auto' is set (for Finish()
+  // detection)
+  LLVM_PREFERRED_TYPE(TST)
+  unsigned ConflictingTypeSpecifier : 7;
```
Comment (AaronBallman) [inline clang/include/clang/Sema/DeclSpec.h]: This should be moved up so it's grouped with the other bit-fields, otherwise it won't pack together. I'd put it up with the other type-specifier fields.

File: clang/lib/Parse/ParseDecl.cpp [hunk 8]
```diff
@@ -3861,6 +3876,47 @@ void Parser::ParseDeclarationSpecifiers(
...
+      if (DS.getTypeSpecType() == DeclSpec::TST_auto && TypeRep) {
+        // Check if the next token indicates this is a declarator
+        tok::TokenKind NextKind = NextToken().getKind();
+        if (NextKind == tok::equal || NextKind == tok::l_paren ||
+            NextKind == tok::l_square || NextKind == tok::amp ||
+            NextKind == tok::ampamp || NextKind == tok::star ||
+            NextKind == tok::coloncolon || NextKind == tok::comma ||
+            NextKind == tok::semi || NextKind == tok::colon ||
+            NextKind == tok::greater || NextKind == tok::r_paren ||
+            NextKind == tok::arrow) {
```
Comment (AaronBallman) [inline clang/lib/Parse/ParseDecl.cpp]:
```suggestion
        Token Next = NextToken();
        if (Next.isOneOf(tok::equal, tok::l_paren, tok::l_square, ...)) {
```
I think this will be a cleaner way to express the list.

**Review by AaronBallman — COMMENTED** [review]
(Some feedback, I've not had the chance to do a thorough review of all the parsing changes though.)

File: clang/test/SemaCXX/auto-cxx0x.cpp [hunk 9]
```diff
@@ -1,8 +1,8 @@
 // RUN: %clang_cc1 -fsyntax-only -verify %s -std=c++11
 // RUN: %clang_cc1 -fsyntax-only -verify %s -std=c++1y
 void f() {
-  auto int a; // expected-warning {{'auto' storage class specifier is not permitted in C++11, and will not be supported in future releases}}
-  int auto b; // expected-error{{cannot combine with previous 'int' declaration specifier}}
+  auto int a; // expected-error {{'auto' cannot be combined with a type specifier}}
+  int auto b; // expected-error {{'auto' cannot be combined with a type specifier}}
```
[the remark this answers is not in the document]
Comment (osamakader) [reply clang/test/SemaCXX/auto-cxx0x.cpp]: sorry for the late reply, done.

File: clang/lib/Parse/ParseDecl.cpp [hunk 10]
```diff
@@ -3860,6 +3875,44 @@ void Parser::ParseDeclarationSpecifiers(
...
+        if (Next.is(tok::identifier)) {
+          // Look ahead to see if this is followed by ')' (function parameter)
+          Token AfterNext = GetLookAheadToken(2);
+          if (AfterNext.is(tok::r_paren)) {
+            // This might be concept constraint syntax, skip conflict detection
+            goto DoneWithDeclSpec;
+          }
+        }
+      }
+
```
Comment (to268) [inline clang/lib/Parse/ParseDecl.cpp]: I would rather move this part in Sema if possible.

File: clang/lib/Parse/ParseDecl.cpp [hunk 11]
```diff
@@ -4093,15 +4146,33 @@ void Parser::ParseDeclarationSpecifiers(
...
+              // This is concept constraint syntax (C<T> auto), don't treat as
+              // conflict. The concept constraint will be handled elsewhere
+              goto DoneWithDeclSpec;
+            }
+          }
+        }
+        // Always set 'auto' as a type specifier in C++11+ and C23.
+        // Conflicts will be detected in DeclSpec::Finish().
+        isInvalid = DS.SetTypeSpecType(DeclSpec::TST_auto, Loc, PrevSpec,
+                                       DiagID, Policy);
```
Comment (to268) [inline clang/lib/Parse/ParseDecl.cpp]: > I would rather move this part in Sema if possible.

Same for here.

**Review by to268 — COMMENTED** [review]
I would like to move some checks as much as possible from the Parsing stage to the Sema stage primarily for maintainability reasons, as we probably have code that parses templates and concept constraints already, and it would be easier to acquire the "parts" you need.

I also would like to see this patch rebased on `main` due to the following commits:
- https://github.com/llvm/llvm-project/commit/211b88b64b0e409a2e294a1fe444b305aa94a2a6
- https://github.com/llvm/llvm-project/commit/42b6a6faaa0014f7e39c57c6221fec1855ec4409

**Comment by shafik** [comment]
ping

File: clang/test/CXX/drs/cwg3xx.cpp [hunk 12]
```diff
@@ -1704,13 +1704,23 @@ namespace cwg395 { // cwg395: 3.0
 namespace cwg396 { // cwg396: 3.0
   void f() {
     auto int a();
-    // since-cxx11-error@-1 {{'auto' storage class specifier is not permitted in C++11, and will not be supported in future releases}}
-    // expected-error@-2 {{illegal storage class on function}}
+#if __cplusplus >= 201103L
+    // expected-error@-2 {{'auto' cannot be combined with a type specifier}}
```
Comment (Endilll) [inline clang/test/CXX/drs/cwg3xx.cpp]:
```suggestion
    // since-cxx11-error@-1 {{'auto' cannot be combined with a type specifier}}
```
No need to use `#if __cplusplus` for expected directives.

**Comment by osamakader** [comment]
I'm going to address the recent reviews ASAP, sorry was a bit sick.

File: clang/test/CXX/drs/cwg3xx.cpp (hunk 12 above)
Comment (osamakader) [reply clang/test/CXX/drs/cwg3xx.cpp]: Done.

File: clang/lib/Parse/ParseDecl.cpp (hunk 10 above)
Comment (osamakader) [reply clang/lib/Parse/ParseDecl.cpp]: I moved the auto conflict handling/diagnostic into DeclSpec::Finish() in Sema. I think this remaining part needs to stay in the parser because it decides where declaration-specifiers end before consuming the identifier. Once the parser consumes a typedef-name-looking identifier as a type specifier, Sema can diagnose the conflict but cannot recover the intended declarator-id parse for cases like [](auto c), template<auto V>, or for (auto Arg : range).

File: clang/lib/Parse/ParseDecl.cpp (hunk 11 above)
Comment (osamakader) [reply clang/lib/Parse/ParseDecl.cpp]: removed from parser.

**Comment by osamakader** [comment]
The PR is ready for review.

File: clang/lib/Sema/DeclSpec.cpp [hunk 13]
```diff
@@ -1198,6 +1242,164 @@ void DeclSpec::Finish(Sema &S, const PrintingPolicy &Policy) {
...
+        StorageClassSpec = SCS_auto;
+        StorageClassSpecLoc = TSTLoc;
+        TypeSpecType = ConflictingTypeSpecifier;
+        TSTLoc = ConflictingTypeSpecifierLoc;
+        // Clear the conflict tracking
+        ConflictingTypeSpecifier = TST_unspecified;
+        ConflictingTypeSpecifierLoc = SourceLocation();
+      } else if (ConflictingTypeSpecifier == TST_auto) {
+        // "int auto" case: Convert 'auto' to storage class specifier
+        // In C23, if 'constexpr' is present, treat 'auto' as a type specifier
```
Comment (to268) [inline clang/lib/Sema/DeclSpec.cpp]: TODO: Is it only a type specifier when the `constexpr` keyword is involved in C23?

File: clang/lib/Sema/DeclSpec.cpp [hunk 14]
```diff
@@ -759,6 +759,17 @@ bool DeclSpec::SetTypeSpecType(TST T, SourceLocation TagKwLoc,
   if (TypeSpecType == TST_error)
     return false;
   if (TypeSpecType != TST_unspecified) {
+    // Store conflicting type specifier for Finish() to detect:
```
Comment (shafik) [inline clang/lib/Sema/DeclSpec.cpp]: This code is repeated four times, this is a maintainability problem. Identical code segments tend to drift over time generating more bugs and uneven updates. 

Please factor out in some way.

File: clang/lib/Parse/ParseDecl.cpp [hunk 15]
```diff
@@ -3775,7 +3775,9 @@ void Parser::ParseDeclarationSpecifiers(
       // This identifier can only be a typedef name if we haven't already seen
       // a type-specifier.  Without this check we misparse:
       //  typedef int X; struct Y { short X; };  as 'short int'.
-      if (DS.hasTypeSpecifier())
+      // However, if 'auto' is set, we need to check if this identifier is a
+      // type name to detect conflicts (e.g., "auto MyInt").
+      if (DS.hasTypeSpecifier() && DS.getTypeSpecType() != DeclSpec::TST_auto)
```
Comment (shafik) [inline clang/lib/Parse/ParseDecl.cpp:3780]: It is not clear to me what function these changes in `ParseDeclarationSpecifiers` have. Can you explain? 

This should really be explained in the summary, what are you changing and why.

**Review by shafik — COMMENTED** [review]
Please also add a release note.

**Review by to268 — COMMENTED** [review]
I would like to see some tests cases on the C side (for both pre-C23 and C23).

File: clang/lib/Parse/ParseDecl.cpp (hunk 15 above)
Comment (osamakader) [reply clang/lib/Parse/ParseDecl.cpp:3780]: This parser change exists to let Sema see auto combined with a following typedef-name type specifier.

Previously, once auto was already parsed as a type specifier, this early exit stopped parsing declaration specifiers before looking up the next identifier. That meant cases like
```
typedef int MyInt;
auto MyInt x;
```
would stop at MyInt as if it were the declarator-id, instead of recognizing MyInt as a second type specifier and letting DeclSpec::Finish() diagnose auto plus another type specifier.

File: clang/lib/Sema/DeclSpec.cpp (hunk 14 above)
Comment (osamakader) [reply clang/lib/Sema/DeclSpec.cpp]: Done.

**Comment by osamakader** [comment]
> I would like to see some tests cases on the C side (for both pre-C23 and C23).

Done.

**Comment by shafik** [comment]
ping @to268

**Comment by osamakader** [comment]
ping.

**Review by to268 — APPROVED** [review]
LGTM on the way it is implemented + tested with C23's `auto`.

**Comment by osamakader** [comment]
Thanks @to268, can we merge this PR cleanly? or should I resolve the conflicts in (ReleaseNotes.rst, p3-generic-lambda-1y.cpp test) first?

**Comment by to268** [comment]
It would be better to resolve the conflicts first.

**Comment by osamakader** [comment]
I just rebased the changes, could you please merge it if it is okay since I don't have permission to do that.

**Comment by to268** [comment]
I will wait for tomorrow or someone else will merge it in your behalf, since it needs to be monitored if a revert is needed.

**Comment by asb** [comment]
This seems to be causing failures on all of my two-stage builders when compiling X86LoadValueInjectionLoadHardening.cpp.

I believe this repro.cpp should demonstrate the issue:
```
  namespace llvm {
  class Use;

  namespace rdf {
  template <class T> struct NodeAddr {};
  class UseNode;
  using Use = NodeAddr<UseNode *>;
  }
  }

  using namespace llvm;

  namespace {
  void f() {
    using namespace rdf;
    auto Use = 0;
  }
  }
```
Output:
```
./bin/clang++ -target x86_64-unknown-linux-gnu -std=c++17 -fsyntax-only repro.cpp
repro.cpp:16:8: error: reference to 'Use' is ambiguous
   16 |   auto Use = 0;
      |        ^
repro.cpp:7:7: note: candidate found by name lookup is 'llvm::rdf::Use'
    7 | using Use = NodeAddr<UseNode *>;
      |       ^
repro.cpp:2:7: note: candidate found by name lookup is 'llvm::Use'
    2 | class Use;
      |       ^
1 error generated.
exit code: 1
```

Checked manually, but minimised case and narrowing down the bad commit was assisted by LLM.

**Comment by to268** [comment]
Interesting, I did not thought these build failures on LLVM where related but they looked weird.

**Comment by osamakader** [comment]
Thanks for the repo.cpp, I'm fixing that locally, and added that test case to the tests.
The follow-up PR is coming soon.

**Comment by osamakader** [comment]
The follow-up PR https://github.com/llvm/llvm-project/pull/208552
The stage-2 build is ok locally, appreciate your review there @to268 @asb
