### ISSUE TITLE
unexpected syntax error: operator[] mistaken for lambda capture

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24535]
|  |  |
| --- | --- |
| Bugzilla Link | [24161](https://llvm.org/bz24161) |
| Version | 3.4 |
| OS | Linux |
| Attachments | [Reproduces unexpected syntax error](https://user-images.githubusercontent.com/60944935/143751723-53c3c15c-a20b-4f14-80eb-e1092bb7b9e8.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 

Vec is a class that has a default constructor and operator[](int) defined. This construct (resulting from a macro expansion) fails to compile with clang 3.4 C++11, but succeeds with gcc 4.8.2 and VS2015:

if ((std::abs(((Vec())[0]))/3. > 0))
   printf("hi\n");

The error is:

c++ -std=c++11 crash2.cpp
crash2.cpp:61:28: error: expected variable name or 'this' in lambda capture list
    if ((std::abs(((Vec())[0]))/3. > 0))
                           ^

Removing the extra set of parentheses around Vec() eliminates the error.

I've attached a complete program that fails to compile.

**Comment by llvmbot** [comment]
@llvm/issue-subscribers-clang-frontend

Author: None (llvmbot)

<details>
|  |  |
| --- | --- |
| Bugzilla Link | [24161](https://llvm.org/bz24161) |
| Version | 3.4 |
| OS | Linux |
| Attachments | [Reproduces unexpected syntax error](https://user-images.githubusercontent.com/60944935/143751723-53c3c15c-a20b-4f14-80eb-e1092bb7b9e8.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 


Vec is a class that has a default constructor and operator[](int) defined. This construct (resulting from a macro expansion) fails to compile with clang 3.4 C++11, but succeeds with gcc 4.8.2 and VS2015:

if ((std::abs(((Vec())[0]))/3. &gt; 0))
   printf("hi\n");

The error is:

c++ -std=c++11 crash2.cpp
crash2.cpp:61:28: error: expected variable name or 'this' in lambda capture list
    if ((std::abs(((Vec())[0]))/3. &gt; 0))
                           ^

Removing the extra set of parentheses around Vec() eliminates the error.

I've attached a complete program that fails to compile.
</details>
