### PR TITLE
  [CIR] Implement missing __sync_* atomic builtins

### LINKED ISSUE #214445: [CIR] `__sync_*` compare-and-swap, swap and lock builtins unimplemented; NYI diagnostic mislabels them as "X86 builtin call"
[CIR] `__sync_*` compare-and-swap, swap and lock builtins unimplemented; NYI diagnostic mislabels them as "X86 builtin call"

## Summary

Two related issues in CIRGen's handling of the legacy GCC `__sync_*` atomic
builtins:

1. **Five `__sync_*` builtins are unimplemented.**
   `__sync_bool_compare_and_swap`, `__sync_val_compare_and_swap`,
   `__sync_swap`, `__sync_lock_test_and_set` and `__sync_lock_release` all emit
   `error: ClangIR code gen Not Yet Implemented`. The other thirteen members of
   the same family are implemented and work, so support is currently partial.
2. **The diagnostic says "X86 builtin call" for builtins that are not
   X86-specific.** These are generic GCC builtins available on every target,
   and the same message appears verbatim when targeting aarch64. The helper
   that emits it lives in the target-independent `CIRGenBuiltin.cpp` but
   hardcodes "X86", so it mislabels every builtin routed through it.

Issue 2 is cosmetic, but it actively misleads triage — it suggests a
target-specific problem where none exists. It is a two-line fix, independent of
issue 1.

## Reduced test case

```c
// sync.c
int  cas_bool(int *p)     { return __sync_bool_compare_and_swap(p, 0, 1); }
int  cas_val(int *p)      { return __sync_val_compare_and_swap(p, 0, 1); }
int  swap(int *p)         { return __sync_swap(p, 1); }
int  test_and_set(int *p) { return __sync_lock_test_and_set(p, 1); }
void lock_release(int *p) { __sync_lock_release(p); }
```

```console
$ clang -fclangir -emit-cir -c sync.c -o /dev/null
sync.c:2:36: error: ClangIR code gen Not Yet Implemented: unimplemented X86 builtin call: __sync_bool_compare_and_swap_4
    2 | int  cas_bool(int *p)     { return __sync_bool_compare_and_swap(p, 0, 1); }
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

No headers required. Compilation stops at the first error, so each of the five
must be compiled separately to see its own diagnostic; all five behave the same
way.

The result is identical for every operand width (1, 2, 4, 8 bytes) and at every
optimization level from `-O0` to `-O3`.

### Mislabelled diagnostic on a non-x86 target

```console
$ clang -fclangir -emit-cir --target=aarch64-linux-gnu -c sync.c -o /dev/null
sync.c:2:36: error: ClangIR code gen Not Yet Implemented: unimplemented X86 builtin call: __sync_bool_compare_and_swap_4
                                                                       ^^^ targeting aarch64
```

## Component triage

Per [How to submit an LLVM bug report](https://llvm.org/docs/HowToSubmitABug.html),
this is a **front-end (CIRGen)** issue. The classic pipeline compiles the same
file without complaint:

| Command | Result |
|---|---|
| `clang -emit-llvm -Xclang -disable-llvm-passes -O2 -c sync.c` | ok |
| `clang -emit-llvm -O2 -c sync.c` | ok |
| `clang -O2 -c sync.c` | ok |
| `clang -fclangir -emit-cir -O2 -c sync.c` | **NYI error** |

Classic CodeGen lowers these to ordinary atomic IR. For `cas_bool`:

```llvm
%2 = cmpxchg ptr %0, i32 0, i32 1 seq_cst seq_cst, align 4
```

This is a missing-feature report, not a crash — codegen stops cleanly at the
diagnostic.

## Which `__sync_*` builtins work

Support is partial. The arithmetic operations are implemented; the
compare-and-swap, swap and lock operations are not.

| Builtin | Status |
|---|---|
| `__sync_fetch_and_add` / `_sub` / `_or` / `_and` / `_xor` / `_nand` | works |
| `__sync_add_and_fetch` / `_sub_and_fetch` / `_and_and_fetch` | works |
| `__sync_or_and_fetch` / `_xor_and_fetch` / `_nand_and_fetch` | works |
| `__sync_synchronize` | works |
| `__sync_bool_compare_and_swap` | **NYI** |
| `__sync_val_compare_and_swap` | **NYI** |
| `__sync_swap` | **NYI** |
| `__sync_lock_test_and_set` | **NYI** |
| `__sync_lock_release` | **NYI** |

For contrast, the modern `__atomic_*` equivalents are all implemented and
compile fine, including `__atomic_compare_exchange_n`, `__atomic_exchange_n`,
`__atomic_store_n` and `__atomic_fetch_add`. Only the legacy spellings are
missing, so this affects codebases that predate C11 atomics or deliberately
target older compilers.

## Where this happens

In `clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp`, the arithmetic cases dispatch to
a real implementation:

```c++
  case Builtin::BI__sync_fetch_and_add_1:
  ...
  case Builtin::BI__sync_fetch_and_add_16:
    return emitBinaryAtomic(*this, cir::AtomicFetchKind::Add, e);
```

while the CAS, swap and lock cases fall through to the NYI helper:

```c++
  case Builtin::BI__sync_val_compare_and_swap_1:
  ...
  case Builtin::BI__sync_lock_release_16:
    return errorBuiltinNYI(*this, e, builtinID);
```

Both the unsuffixed forms (`BI__sync_bool_compare_and_swap`) and the
size-suffixed forms (`BI__sync_bool_compare_and_swap_1` … `_16`) route to
`errorBuiltinNYI`.

Since `emitBinaryAtomic` and `emitBinaryAtomicPost` already exist for the
arithmetic cases, and CIR already supports `__atomic_compare_exchange_n` and
`__atomic_exchange_n`, implementing these should largely be a matter of mapping
the legacy builtins onto machinery that is already present.

### The "X86" label

`errorBuiltinNYI` is defined in the target-independent `CIRGenBuiltin.cpp` and
unconditionally says "X86":

```c++
static RValue errorBuiltinNYI(CIRGenFunction &cgf, const CallExpr *e,
                              unsigned builtinID) {
  if (cgf.getContext().BuiltinInfo.isLibFunction(builtinID)) {
    cgf.cgm.errorNYI(
        e->getSourceRange(),
        std::string("unimplemented X86 library function builtin call: ") +
            cgf.getContext().BuiltinInfo.getName(builtinID));
  } else {
    cgf.cgm.errorNYI(e->getSourceRange(),
                     std::string("unimplemented X86 builtin call: ") +
                         cgf.getContext().BuiltinInfo.getName(builtinID));
  }
  ...
```

There are 20 call sites of this helper in that file, all for target-independent
builtins. `__builtin_thread_pointer` is another one affected: it also reports
"unimplemented X86 builtin call" when targeting aarch64. Dropping `"X86 "` from
both strings would fix it.

## Impact: GNU binutils

Building [GNU binutils](https://sourceware.org/git/binutils-gdb.git) with
ClangIR, this is the **only** thing that fails. Of 1122 translation units in an
`--enable-targets=all` build, 1116 compile. The 6 failures are three source
files in the vendored `libbacktrace`, each compiled twice by libtool (PIC and
non-PIC):

| Source file | Line | Builtin |
|---|---|---|
| `libbacktrace/dwarf.c` | 4060 | `__sync_bool_compare_and_swap` |
| `libbacktrace/elf.c` | 7445 | `__sync_bool_compare_and_swap` |
| `libbacktrace/mmap.c` | 135 | `__sync_lock_test_and_set` |
| `libbacktrace/mmap.c` | 162 | `__sync_lock_release` |

`libbacktrace` uses the legacy spellings deliberately, for compatibility with
compilers predating C11 atomics.

To reproduce:

```bash
git clone https://sourceware.org/git/binutils-gdb.git
mkdir binutils-build && cd binutils-build
../binutils-gdb/configure --disable-gdb --disable-gdbserver --disable-sim \
                          --disable-gprofng --disable-werror --disable-nls
make                       # generates the config.h libbacktrace needs
cd libbacktrace            # the compile runs from this directory

for f in dwarf.c elf.c mmap.c; do
  path/to/clang -fclangir -emit-cir -O2 -DHAVE_CONFIG_H -I. \
    -I../../binutils-gdb/libbacktrace \
    -I../../binutils-gdb/libbacktrace/../include \
    -c ../../binutils-gdb/libbacktrace/$f -o /dev/null
done
```

## Environment

- **Source**: upstream `https://github.com/llvm/llvm-project`, commit `91b781417ecdf354afa0c80450b970db11d63130` (`main`)
- **Target**: `x86_64-unknown-linux-gnu` (also reproduced with `--target=aarch64-linux-gnu`)
- **Host**: Debian, gcc 15.2.0 as host compiler
- **Build**:
  ```bash
  cmake -G Ninja -S llvm -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS="clang;mlir" \
    -DCLANG_ENABLE_CIR=ON
  ninja -C build clang
  ```

### PR DESCRIPTION
**Pull request by dingcyrus**
Add CIR codegen support for five legacy __sync_* builtins that
  previously emitted "Not Yet Implemented" errors:

    __sync_val_compare_and_swap  ->  cir.atomic.cmpxchg (seq_cst)
    __sync_bool_compare_and_swap ->  cir.atomic.cmpxchg + cmp (seq_cst)
    __sync_swap                  ->  cir.atomic.xchg (seq_cst)
    __sync_lock_test_and_set     ->  cir.atomic.xchg (seq_cst)
    __sync_lock_release          ->  cir.store 0 (release)

  Size-suffixed forms (_1, _2, _4, _8) are handled, covering 20 builtin
  variants in total; the unsuffixed forms are rewritten by Sema and the
  _16 variants fall back to errorBuiltinNYI.

  The existing emitBinaryAtomic / emitBinaryAtomicPost infrastructure
  already handled the arithmetic __sync_* family (fetch_and_add, etc.).
  This patch adds the remaining compare-and-swap, exchange, and
  lock-release helpers: emitAtomicCmpXchgValue, emitAtomicCmpXchgBool,
  emitAtomicXchg, and emitAtomicLockRelease.

  Also fix a cosmetic issue in errorBuiltinNYI: the diagnostic
  hardcoded "X86" in the message even for target-independent builtins
  such as __sync_* compiled with --target=aarch64.  Replace
  "unimplemented X86 builtin call" with "unimplemented builtin call".

  AI assistance was used for code review analysis and local build verification. 

  Fixes #214445.

### CODE REVIEW

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp [hunk 1]
```diff
@@ -247,6 +247,73 @@ static RValue emitBinaryAtomicPost(CIRGenFunction &cgf,
...
+  mlir::Value old =
+      emitAtomicCmpXchgValue(cgf, e, cir::MemOrder::SequentiallyConsistent,
+                             cir::MemOrder::SequentiallyConsistent);
+  CIRGenBuilderTy &builder = cgf.getBuilder();
+  // __sync_bool_compare_and_swap returns true on success.
+  // The classic llvm/cmpxchg produces {old, success}. We only have old here,
+  // so compare old == expected.
+  mlir::Value expected = cgf.emitScalarExpr(e->getArg(1));
+  mlir::Value cmp = builder.createCompare(cgf.getLoc(e->getSourceRange()),
+                                          cir::CmpOpKind::eq, old, expected);
```
Comment (bcardosolopes) [inline clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: This re-evaluates getArg(1) (already emitted inside emitAtomicCmpXchgValue), so a side-effecting expected arg runs twice. Better to use the cmpxchg's success result directly (getSuccess() if the op exposes it), which also drops the extra compare. If there's no success result, at least reuse the expected Value you already computed instead of re-emitting the arg.

**Review by bcardosolopes — CHANGES_REQUESTED** [review]
Nice, thanks for the contribution! The orderings look right (acquire for lock_test_and_set, release for lock_release, seq_cst for the rest). A few things:

- bool_compare_and_swap has a real bug (see comment inline).
- No alignment is set on any of the cmpxchg/xchg/release store (alignment=nullptr). Atomics need it and OG sets it from the pointee, please confirm the op defaults to natural alignment, otherwise set it.
- The _16 variants go through the same native path. OG falls back to __atomic_* libcalls when there's no native 128-bit support, so these will likely break on most targets. Needs handling (or errorNYI).
- 30 new builtin variants and no new tests beyond the one-line tweak. Please add coverage, at least one per family, checking the emitted op and its memory order (that's the part most likely to regress).

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp (hunk 1 above)
Comment (dingcyrus) [reply clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: Thank  you for the review. 

  1. bool_compare_and_swap  bug

  Good catch, fixed.  Now using `cmpxchg.getSuccess()` directly
  instead of re-emitting `getArg(1)` and comparing.

  2. alignment

  `AtomicCmpXchgOp::alignment` (and `AtomicXchgOp`) defaults to
  natural alignment when not set.  This matches what the existing
  `makeBinaryAtomicValue` does for `AtomicFetchOp`, which has no
  alignment parameter at all.  If you'd prefer an explicit alignment
  set from `destAddr`, I can add that.

 3. _16 variants

  Moved `_16` variants back to `errorBuiltinNYI` — they need
  `__atomic_*` libcall fallback which isn't wired up yet.

  4. tests

  Added `builtin-sync.cpp` — one test per family checking the
  emitted CIR op and memory order, plus LLVM IR checks.

**Comment by bcardosolopes** [comment]
@dingcyrus looks like some tests are still failing

**Comment by dingcyrus** [comment]
> @dingcyrus looks like some tests are still failing

  Thanks for the review — the four points are addressed in the latest revision (bool CAS now uses `cmpxchg.getSuccess()`, the `_16` variants fall back to `errorBuiltinNYI`, alignment defaults to natural alignment matching the existing `AtomicFetchOp` path, and `builtin-sync.cpp` was added with one test per family).

  Regarding "some tests are still failing": the only red check is `Build and Test Linux AArch64`, and its failure is a single timeout

      Timed Out Tests (1):
        lldb-api :: tools/lldb-dap/attach/TestDAP_attach.py

  That's an LLDB debug-adapter attach test, unrelated to this change (which only touches `clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp` plus CIR tests). Linux x64 premerge reported all tests passing, and Windows / macOS are green. Could you re-run that job, or should I push a trivial commit to re-trigger it?

File: clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp
Comment (Lancern) [inline clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp:1]: Please also add OGCG checks to make sure LLVMIR generated through CIR is aligned with the LLVMIR generated through clang CodeGen. See other CIR codegen test files for examples.

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp [hunk 2]
```diff
@@ -2063,11 +2120,19 @@ RValue CIRGenFunction::emitBuiltinExpr(const GlobalDecl &gd, unsigned builtinID,
   case Builtin::BI__sync_xor_and_fetch:
   case Builtin::BI__sync_nand_and_fetch:
   case Builtin::BI__sync_val_compare_and_swap:
+    return RValue::get(
```
Comment (Lancern) [inline clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: The switch-cases for `__sync_fetch_and_*` and `__sync_*_and_fetch` above would also fallthrough to here.

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp [hunk 3]
```diff
@@ -247,6 +247,78 @@ static RValue emitBinaryAtomicPost(CIRGenFunction &cgf,
...
+  auto cmpxchg = cir::AtomicCmpXchgOp::create(
+      builder, cgf.getLoc(e->getSourceRange()), destValue, expected, desired,
+      succOrder, failOrder, cir::SyncScopeKind::System,
+      /*alignment=*/nullptr, /*weak=*/false, /*is_volatile=*/false);
+  return cmpxchg.getOld();
+}
+
+/// Emit a `cir.atomic.cmpxchg` for __sync_bool_compare_and_swap_N.
+/// Returns a boolean: true if the exchange succeeded.
+static RValue emitAtomicCmpXchgBool(CIRGenFunction &cgf, const CallExpr *e) {
```
Comment (Lancern) [inline clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: I think we could just merge this function with `emitAtomicCmpXchgValue`. They look all the same except for the return value.

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp [hunk 4]
```diff
@@ -247,6 +247,78 @@ static RValue emitBinaryAtomicPost(CIRGenFunction &cgf,
...
+  // cir.atomic.cmpxchg already returns (old, success).  Use the success
+  // flag directly instead of re-emitting getArg(1) and comparing.
+  mlir::Value success = cmpxchg.getSuccess();
+  mlir::Value result =
+      builder.createIntCast(success, cgf.convertType(e->getType()));
+  return RValue::get(result);
+}
+
+/// Emit a `cir.atomic.xchg` for __sync_swap_N and __sync_lock_test_and_set_N.
+static mlir::Value emitAtomicXchg(CIRGenFunction &cgf, const CallExpr *e,
```
Comment (Lancern) [inline clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: Why return `mlir::Value` instead of `RValue`?

File: clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp
Comment (Lancern) [inline clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp:1]: The test coverage is not enough. We should have at least one test case for each builtin function you covered.

File: clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+
+// CIR-LABEL: @test_sync_swap(
+// CIR: cir.atomic.xchg seq_cst syncscope(system) %{{[0-9]+}}, %{{[0-9]+}} : (!cir.ptr<!s32i>, !s32i) -> !s32i
+// CIR: cir.return
+int test_sync_swap(int *p, int val) {
+  return __sync_swap(p, val);
+}
+
+// CIR-LABEL: @test_sync_lock_test_and_set(
+// CIR: cir.atomic.xchg acquire syncscope(system) %{{[0-9]+}}, %{{[0-9]+}} : (!cir.ptr<!s32i>, !s32i) -> !s32i
```
Comment (Lancern) [inline clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp]: Is `acquire` right? The OGCG would emit `seq_cst` instead.

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp (hunk 2 above)
Comment (Lancern) [inline clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: The OGCG contains an `llvm_unreachable` here instead. Looks like sema would transform all `__sync_val_compare_and_swap` to `__sync_val_compare_and_swap_2/4/8/16`. Let's follow the OGCG's approach.

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp [hunk 6]
```diff
@@ -2063,11 +2120,19 @@ RValue CIRGenFunction::emitBuiltinExpr(const GlobalDecl &gd, unsigned builtinID,
   case Builtin::BI__sync_xor_and_fetch:
   case Builtin::BI__sync_nand_and_fetch:
   case Builtin::BI__sync_val_compare_and_swap:
+    return RValue::get(
+        emitAtomicCmpXchgValue(*this, e, cir::MemOrder::SequentiallyConsistent,
+                               cir::MemOrder::SequentiallyConsistent));
   case Builtin::BI__sync_bool_compare_and_swap:
+    return emitAtomicCmpXchgBool(*this, e);
```
Comment (Lancern) [inline clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: Same here, the OGCG contains an `llvm_unreachable` here.

**Review by Lancern — CHANGES_REQUESTED** [review]

File: clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp
Comment (dingcyrus) [reply clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp:1]: > Please also add OGCG checks to make sure LLVMIR generated through CIR is aligned with the LLVMIR generated through clang CodeGen. See other CIR codegen test files for examples.

  Thanks for the review! All comments addressed:

  1. Unsuffixed __sync_* cases (the two comments on __sync_val_compare_and_swap / __sync_bool_compare_and_swap): right — Sema rewrites the unsuffixed forms before CodeGen, and the previous code also had an incorrect fallthrough (the unsuffixed __sync_fetch_and_* / __sync_*_and_fetch labels would land in the cmpxchg handler).
  I've grouped all unsuffixed cases into a single llvm_unreachable("Shouldn't make it through sema"), matching OGCG.
  2. Merged emitAtomicCmpXchgBool into emitAtomicCmpXchgValue: done — now a single emitAtomicCmpXchg(cgf, e, /*returnBool=*/...), mirroring OGCG's MakeAtomicCmpXchgValue.
  3. emitAtomicXchg returning mlir::Value: changed to return RValue for consistency with the other helpers.
  4. __sync_lock_test_and_set ordering: good catch — OGCG lowers it through EmitBinaryAtomic (i.e. SequentiallyConsistent), so I changed acquire → seq_cst to match.
  5. Test coverage / OGCG checks: rewrote builtin-sync.cpp to cover every size variant (_1/_2/_4/_8) of all five builtins, and added OGCG -emit-llvm checks so the LLVM IR emitted through CIR is verified against clang's regular CodeGen.

  Verified locally with a full clang build (CIR enabled); builtin-sync.cpp and the existing atomic.c both pass.

File: clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp [hunk 7]
```diff
@@ -0,0 +1,230 @@
+// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -fclangir -emit-cir %s -o %t.cir
+// RUN: FileCheck --check-prefix=CIR --input-file=%t.cir %s
+// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -fclangir -emit-llvm %s -o %t-cir.ll
+// RUN: FileCheck --check-prefix=LLVM --input-file=%t-cir.ll %s
+// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm %s -o %t.ll
+// RUN: FileCheck --check-prefix=OGCG --input-file=%t.ll %s
```
Comment (Lancern) [inline clang/test/CIR/CodeGenBuiltins/builtin-sync.cpp]: Are all OGCG checks identical with the LLVM checks? If so, you could use the `LLVM` label on OGCG so we're confident that they are identical:

```suggestion
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm %s -o %t.ll
// RUN: FileCheck --check-prefix=LLVM --input-file=%t.ll %s
```

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp [hunk 8]
```diff
@@ -247,6 +247,64 @@ static RValue emitBinaryAtomicPost(CIRGenFunction &cgf,
...
+      cir::MemOrder::SequentiallyConsistent,
+      cir::MemOrder::SequentiallyConsistent, cir::SyncScopeKind::System,
+      /*alignment=*/nullptr, /*weak=*/false, /*is_volatile=*/false);
+
+  if (returnBool) {
+    // cir.atomic.cmpxchg already returns (old, success). Use the success flag
+    // directly instead of re-emitting the expected argument and comparing.
+    mlir::Value success = cmpxchg.getSuccess();
+    mlir::Value result =
+        builder.createIntCast(success, cgf.convertType(e->getType()));
```
Comment (Lancern) [inline clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: I think this cast is unnecessary.

**Review by Lancern — CHANGES_REQUESTED** [review]
Two more nits

File: clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp (hunk 8 above)
Comment (dingcyrus) [reply clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp]: Thanks for the review! Both remaining comments are addressed:

  1. Merging the OGCG checks into LLVM — confirmed, the OGCG output is byte-for-byte identical to the CIR→LLVM output for every case in this test. I've removed all the OGCG-* lines and changed the last FileCheck to --check-prefix=LLVM, so %t-cir.ll and %t.ll are now checked against the same prefix. This guarantees the LLVM IR emitted through CIR stays aligned with clang's native CodeGen. Verified with llvm-lit — the test passes.
  2. Unnecessary cast in emitAtomicCmpXchg — right, cir.atomic.cmpxchg's success result is already !cir.bool, and __sync_bool_compare_and_swap returns bool which also maps to !cir.bool, so the createIntCast was an i1→i1 no-op. Removed it; the returnBool path now returns cmpxchg.getSuccess() directly.

**Review by Lancern — APPROVED** [review]
LGTM

**Review by bcardosolopes — APPROVED** [review]
Sorry for sitting on this, my "changes-requested" was the only thing left holding it.

On the alignment question you asked back: leave it as it is, no explicit alignment needed. `checkAtomicAlignment` is a faithful port of OG's, force-to-natural path included:

```cpp
  // Force address to be at least naturally-aligned.
  return ptr.withAlignment(CharUnits::fromQuantity(bytes));
```

so classic lands on natural alignment for these builtins whatever the pointer's declared alignment was. Setting it from `destAddr` would be the thing that could diverge, not the default. Your test pins it either way now, and since the third RUN line reuses the `LLVM` prefix over classic's output, both columns have to produce the same `align N`.

Two things in the description, which is what ends up in the log:

- It still says `__sync_lock_test_and_set -> cir.atomic.xchg (acquire)`. The code emits `seq_cst` now, which is right, `EmitBinaryAtomic` uses seq_cst for it, but the summary did not follow the fix.
- "covering 30 builtin variants" is 20 at this point, with the unsuffixed forms now `llvm_unreachable` and `_16` back on `errorBuiltinNYI`.

**Comment by dingcyrus** [comment]
> Sorry for sitting on this, my "changes-requested" was the only thing left holding it.
> 
> On the alignment question you asked back: leave it as it is, no explicit alignment needed. `checkAtomicAlignment` is a faithful port of OG's, force-to-natural path included:
> 
> ```c++
>   // Force address to be at least naturally-aligned.
>   return ptr.withAlignment(CharUnits::fromQuantity(bytes));
> ```
> 
> so classic lands on natural alignment for these builtins whatever the pointer's declared alignment was. Setting it from `destAddr` would be the thing that could diverge, not the default. Your test pins it either way now, and since the third RUN line reuses the `LLVM` prefix over classic's output, both columns have to produce the same `align N`.
> 
> Two things in the description, which is what ends up in the log:
> 
>     * It still says `__sync_lock_test_and_set -> cir.atomic.xchg (acquire)`. The code emits `seq_cst` now, which is right, `EmitBinaryAtomic` uses seq_cst for it, but the summary did not follow the fix.
> 
>     * "covering 30 builtin variants" is 20 at this point, with the unsuffixed forms now `llvm_unreachable` and `_16` back on `errorBuiltinNYI`.

Thanks! Description updated — __sync_lock_test_and_set now reads seq_cst, and the summary now says 20 size-suffixed variants, with a note that the unsuffixed forms are rewritten by Sema and _16 falls back to errorBuiltinNYI.

**Comment by aferr** [comment]
Thank you!!
