### PR TITLE
[BOLT] Report flow conservation scores

### PR DESCRIPTION
**Pull request by ShatianWang**
Add two additional profile quality stats for CG (call graph) and CFG (control flow graph) flow conservations besides the CFG discontinuity stats introduced in #109683. The two new stats quantify how different "in-flow" is from "out-flow" in the following cases where they should be equal. The smaller the reported stats, the better the flow conservations are.

CG flow conservation: for each function that is not a program entry, the number of times the function is called according to CG ("in-flow") should be equal to the number of times the transition from an entry basic block of the function to another basic block within the function is recorded ("out-flow"). 

CFG flow conservation: for each basic block that is not a function entry or exit, the number of times the transition into this basic block from another basic block within the function is recorded ("in-flow") should be equal to the number of times the transition from this basic block to another basic block within the function is recorded ("out-flow"). 

Use `-v=1` for more detailed bucketed stats, and use `-v=2` to dump functions / basic blocks with bad flow conservations.

### CODE REVIEW

File: bolt/lib/Rewrite/BinaryPassManager.cpp [hunk 1]
```diff
@@ -58,10 +58,10 @@ extern cl::opt<bolt::IdenticalCodeFolding::ICFLevel, false,
                llvm::bolt::DeprecatedICFNumericOptionParser>
     ICF;
 
-static cl::opt<bool>
```
Comment (aaupov) [inline bolt/lib/Rewrite/BinaryPassManager.cpp:61]: Can we leave formatting as-is here and below, or it's added by clang-format?

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 2]
```diff
@@ -0,0 +1,579 @@
...
+                             iterator_range<function_iterator> &Functions) {
+  // Given a perfect profile, every positive-execution-count BB should be
+  // connected to an entry of the function through a positive-execution-count
+  // directed path in the control flow graph.
+  std::vector<size_t> NumUnreachables;
+  std::vector<size_t> SumECUnreachables;
+  std::vector<double> FractionECUnreachables;
+
+  for (auto it = Functions.begin(); it != Functions.end(); ++it) {
+    const BinaryFunction *Function = *it;
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:98]: nit: 
```suggestion
  for (const BinaryFunction *Function : Functions) {
```

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 3]
```diff
@@ -0,0 +1,579 @@
...
+    if (Function->size() <= 1)
+      continue;
+
+    // Compute the sum of all BB execution counts (ECs).
+    size_t NumPosECBBs = 0;
+    size_t SumAllBBEC = 0;
+    for (const BinaryBasicBlock &BB : *Function) {
+      const size_t BBEC = BB.getKnownExecutionCount();
+      NumPosECBBs += BBEC > 0 ? 1 : 0;
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:107]: nit:
```suggestion
      NumPosECBBs += !!BBEC;
```

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 4]
```diff
@@ -0,0 +1,579 @@
...
+    // Compute the number of BBs reachable from the entry(s) of the function and
+    // the sum of their execution counts (ECs).
+    std::unordered_map<unsigned, const BinaryBasicBlock *> IndexToBB;
+    std::unordered_set<unsigned> Visited;
+    std::queue<unsigned> Queue;
+    for (const BinaryBasicBlock &BB : *Function) {
+      // Make sure BB.getIndex() is not already in IndexToBB.
+      assert(IndexToBB.find(BB.getIndex()) == IndexToBB.end());
+      IndexToBB[BB.getIndex()] = &BB;
+      if (BB.isEntryPoint() && BB.getKnownExecutionCount() > 0) {
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:121]: Use `Function->forEachEntry`

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 5]
```diff
@@ -0,0 +1,579 @@
...
+    for (const BinaryBasicBlock &BB : *Function) {
+      const size_t BBEC = BB.getKnownExecutionCount();
+      NumPosECBBs += BBEC > 0 ? 1 : 0;
+      SumAllBBEC += BBEC;
+    }
+
+    // Perform BFS on subgraph of CFG induced by positive weight edges.
+    // Compute the number of BBs reachable from the entry(s) of the function and
+    // the sum of their execution counts (ECs).
+    std::unordered_map<unsigned, const BinaryBasicBlock *> IndexToBB;
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:114]: Use `BF.getLayout()` and `Layout.getBlock()`

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 6]
```diff
@@ -0,0 +1,579 @@
...
+        Queue.push(Succ->getIndex());
+        ++SuccBIIter;
+      }
+    }
+
+    const size_t NumReachableBBs = Visited.size();
+
+    // Loop through Visited, and sum the corresponding BBs' execution counts
+    // (ECs).
+    size_t SumReachableBBEC = 0;
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:150]: Can compute during traversal

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 7]
```diff
@@ -0,0 +1,579 @@
...
+  }
+}
+
+void printCallGraphFlowConservationStats(
+    raw_ostream &OS, iterator_range<function_iterator> &Functions,
+    FlowInfo &TotalFlowMap) {
+  std::vector<double> CallGraphGaps;
+
+  for (auto it = Functions.begin(); it != Functions.end(); ++it) {
+    const BinaryFunction *Function = *it;
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:204]: Same as above

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 8]
```diff
@@ -0,0 +1,579 @@
...
+    if (Function->size() <= 1 || !Function->isSimple())
+      continue;
+
+    const uint64_t FunctionNum = Function->getFunctionNumber();
+    FlowMapTy &IncomingMap = TotalFlowMap.TotalIncomingMaps[FunctionNum];
+    FlowMapTy &OutgoingMap = TotalFlowMap.TotalOutgoingMaps[FunctionNum];
+    FunctionFlowMapTy &CallGraphIncomingMap = TotalFlowMap.CallGraphIncomingMap;
+
+    // Only consider functions that are not a program entry.
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:213]: Is the assumption here that a program entry point should be unique? If so, please use `BC.StartFunctionAddress` explicitly.

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 9]
```diff
@@ -0,0 +1,579 @@
...
+             << " observed in function " << Function->getPrintName() << "\n";
+          LLVM_DEBUG(Function->dump());
+        }
+
+        CallGraphGaps.push_back(CallGraphGap);
+      }
+    }
+  }
+
+  if (!CallGraphGaps.empty()) {
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:263]: Exit early

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 10]
```diff
@@ -0,0 +1,579 @@
...
+
+void printCFGFlowConservationStats(raw_ostream &OS,
+                                   iterator_range<function_iterator> &Functions,
+                                   FlowInfo &TotalFlowMap) {
+  std::vector<double> CFGGapsWeightedAvg;
+  std::vector<double> CFGGapsWorst;
+  std::vector<uint64_t> CFGGapsWorstAbs;
+
+  for (auto it = Functions.begin(); it != Functions.end(); ++it) {
+    const BinaryFunction *Function = *it;
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:285]: ditto

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 11]
```diff
@@ -0,0 +1,579 @@
...
+
+    // Update MaxCountMap, MinCountMap, and CallGraphIncomingMap
+    auto recordCall = [&](const BinaryBasicBlock *SourceBB,
+                          const MCSymbol *DestSymbol, uint64_t Count) {
+      if (Count == BinaryBasicBlock::COUNT_NO_PROFILE)
+        Count = 0;
+      const BinaryFunction *DstFunc =
+          DestSymbol ? BC.getFunctionForSymbol(DestSymbol) : nullptr;
+      if (DstFunc)
+        CallGraphIncomingMap[DstFunc->getFunctionNumber()] += Count;
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:438]: Do we care about secondary entry points having distinct exec counts, or only the total? If the former, please also check `EntryID`.

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 12]
```diff
@@ -0,0 +1,579 @@
...
+    // Get pairs of (symbol, count) for each target at this callsite.
+    // If the call is to an unknown function the symbol will be nullptr.
+    // If there is no profiling data the count will be COUNT_NO_PROFILE.
+    using TargetDesc = std::pair<const MCSymbol *, uint64_t>;
+    using CallInfoTy = std::vector<TargetDesc>;
+    auto getCallInfo = [&](const BinaryBasicBlock *BB, const MCInst &Inst) {
+      CallInfoTy Counts;
+      const MCSymbol *DstSym = BC.MIB->getTargetSymbol(Inst);
+
+      // If this is an indirect call use perf data directly.
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:455]: I think it's a bit misleading to say we use perf data directly as we use attached annotation. I would drop the comment.

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 13]
```diff
@@ -0,0 +1,579 @@
...
+    };
+
+    // If the function has an invalid profile, try to use the perf data
+    // directly. The call EC is only used to update CallGraphIncomingMap.
+    if (!Function->hasValidProfile() && !Function->getAllCallSites().empty()) {
+      for (const IndirectCallProfile &CSI : Function->getAllCallSites()) {
+        if (!CSI.Symbol)
+          continue;
+        recordCall(nullptr, CSI.Symbol, CSI.Count);
+      }
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:477]: nit
```suggestion
      for (const IndirectCallProfile &CSI : Function->getAllCallSites())
        if (CSI.Symbol)
          recordCall(nullptr, CSI.Symbol, CSI.Count);
```

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 14]
```diff
@@ -0,0 +1,579 @@
...
+          if (!BC.MIB->isCall(Inst))
+            continue;
+          // Find call instructions and extract target symbols from each
+          // one.
+          const CallInfoTy CallInfo = getCallInfo(&BB, Inst);
+          for (const TargetDesc &CI : CallInfo) {
+            recordCall(&BB, CI.first, CI.second);
+          }
+        }
+      }
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:492]: nit
```suggestion
      for (const BinaryBasicBlock &BB : *Function)
        for (const MCInst &Inst : BB)
          if (BC.MIB->isCall(Inst))
            // Find call instructions and extract target symbols from each
            // one.
            for (const TargetDesc &CI : getCallInfo(&BB, Inst))
              recordCall(&BB, CI.first, CI.second);
```

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 15]
```diff
@@ -0,0 +1,579 @@
...
+#include "bolt/Passes/ProfileQualityStats.h"
+#include "bolt/Core/BinaryBasicBlock.h"
+#include "bolt/Core/BinaryFunction.h"
+#include "bolt/Utils/CommandLineOpts.h"
+#include "llvm/Support/CommandLine.h"
+#include <queue>
+#include <unordered_map>
+#include <unordered_set>
+
+#define DEBUG_TYPE "bolt-opts"
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:22]: Let's specialize DEBUG_TYPE to something like `bolt-prof-stats`.

File: bolt/lib/Rewrite/BinaryPassManager.cpp (hunk 1 above)
Comment (ShatianWang) [reply bolt/lib/Rewrite/BinaryPassManager.cpp:61]: They are added by VSCode -- every time I `command s` to save the file, it does automatic formatting.

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 16]
```diff
@@ -0,0 +1,579 @@
...
+
+using namespace llvm;
+using namespace bolt;
+
+namespace opts {
+extern cl::opt<unsigned> Verbosity;
+cl::opt<unsigned> NumFunctionsForProfileQualityCheck(
```
[the remark this answers is not in the document]
Comment (ShatianWang) [reply bolt/lib/Passes/ProfileQualityStats.cpp:29]: Did you mean to change `NumFunctionsForProfileQualityCheck` to something like `NumTopFunctionsForProfileQualityCheck` to make it more descriptive?

File: bolt/lib/Passes/ProfileQualityStats.cpp (hunk 3 above)
Comment (ShatianWang) [reply bolt/lib/Passes/ProfileQualityStats.cpp:107]: Nice trick to learn :)

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 17]
```diff
@@ -0,0 +1,579 @@
...
+    const size_t NumPosECBBsUnreachableFromEntry =
+        NumPosECBBs - NumReachableBBs;
+    const size_t SumUnreachableBBEC = SumAllBBEC - SumReachableBBEC;
+    const double FractionECUnreachable =
+        (double)SumUnreachableBBEC / SumAllBBEC;
+
+    if (opts::Verbosity >= 2 && FractionECUnreachable >= 0.05) {
+      OS << "Non-trivial CFG discontinuity observed in function "
+         << Function->getPrintName() << "\n";
+      LLVM_DEBUG(Function->dump());
```
Comment (maksfb) [inline bolt/lib/Passes/ProfileQualityStats.cpp:165]: Instead of using `LLVM_DEBUG()`, I suggest bumping the verbosity level. I.e. `if (opts::Verbosity >= 3)...`.

File: bolt/test/X86/profile-quality-reporting.test [hunk 18]
```diff
@@ -0,0 +1,6 @@
+## Check profile quality stats reporting
+RUN: yaml2obj %p/Inputs/blarge_new.yaml &> %t.exe
+RUN: llvm-bolt %t.exe -o %t.out --pa -p %p/Inputs/blarge_new.preagg.txt | FileCheck %s
+CHECK: among the hottest 5 functions top 5% function CFG discontinuity is 100.00%
+CHECK: among the hottest 5 functions top 5% call graph flow conservation gap is 60.00%
+CHECK: among the hottest 5 functions top 5% CFG flow conservation gap is 45.53% (weighted) and 96.87% (worst)
```
Comment (maksfb) [inline bolt/test/X86/profile-quality-reporting.test:6]: @ShatianWang, does it make sense to group stats? I.e. add stats after a header that says `profile quality metrics for hottest/top N functions...`.

File: bolt/lib/Passes/ProfileQualityStats.cpp (hunk 11 above)
Comment (ShatianWang) [reply bolt/lib/Passes/ProfileQualityStats.cpp:438]: We only care about the total. So leaving this as is.

File: bolt/lib/Passes/ProfileQualityStats.cpp (hunk 15 above)
Comment (ShatianWang) [reply bolt/lib/Passes/ProfileQualityStats.cpp:22]: Removing line 22 due to replacing all `LLVM_DEBUG(...)` with `if (opts::Verbosity >= 3`

File: bolt/lib/Passes/ProfileQualityStats.cpp (hunk 8 above)
Comment (aaupov) [reply bolt/lib/Passes/ProfileQualityStats.cpp:206]: There can be, e.g. signal handlers not directly reachable from ELF start.
Let's keep that as is then.

File: bolt/lib/Passes/ProfileQualityStats.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (aaupov) [reply bolt/lib/Passes/ProfileQualityStats.cpp:27]: I meant `TopFunctionsForProfileQualityCheck` to make it obvious which functions are checked.

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 19]
```diff
@@ -0,0 +1,575 @@
...
+             "functions to report."),
+    cl::init(95), cl::ZeroOrMore, cl::Hidden, cl::cat(BoltOptCategory));
+} // namespace opts
+
+namespace {
+using FunctionListType = std::vector<const BinaryFunction *>;
+using function_iterator = FunctionListType::iterator;
+
+// BB index -> flow count
+using FlowMapTy = std::unordered_map<unsigned, uint64_t>;
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:44]: Basic block indices are pretty compact/contiguous, so we can use a vector.

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 20]
```diff
@@ -0,0 +1,575 @@
...
+    // Perform BFS on subgraph of CFG induced by positive weight edges.
+    // Compute the number of BBs reachable from the entry(s) of the function and
+    // the sum of their execution counts (ECs).
+    std::unordered_set<unsigned> Visited;
+    std::queue<unsigned> Queue;
+    size_t SumReachableBBEC = 0;
+
+    Function->forEachEntryPoint([&](uint64_t Offset, const MCSymbol *Label) {
+      const BinaryBasicBlock *EntryBB = Function->getBasicBlockAtOffset(Offset);
+      if (EntryBB && EntryBB->getKnownExecutionCount() > 0) {
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:117]: Exit early

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 21]
```diff
@@ -0,0 +1,575 @@
...
+    });
+
+    const FunctionLayout &Layout = Function->getLayout();
+
+    while (!Queue.empty()) {
+      const unsigned BBIndex = Queue.front();
+      const BinaryBasicBlock *BB = Layout.getBlock(BBIndex);
+      Queue.pop();
+      auto SuccBIIter = BB->branch_info_begin();
+      for (const BinaryBasicBlock *Succ : BB->successors()) {
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:132]: Use llvm::zip to simplify iteration?

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 22]
```diff
@@ -0,0 +1,575 @@
...
+
+    NumUnreachables.push_back(NumPosECBBsUnreachableFromEntry);
+    SumECUnreachables.push_back(SumUnreachableBBEC);
+    FractionECUnreachables.push_back(FractionECUnreachable);
+  }
+
+  if (FractionECUnreachables.empty())
+    return;
+
+  std::sort(FractionECUnreachables.begin(), FractionECUnreachables.end());
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:171]: nit
```suggestion
  llvm::sort(FractionECUnreachables);
```

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 23]
```diff
@@ -0,0 +1,575 @@
...
+    FlowMapTy &OutgoingMap = TotalFlowMap.TotalOutgoingMaps[FunctionNum];
+    FunctionFlowMapTy &CallGraphIncomingMap = TotalFlowMap.CallGraphIncomingMap;
+
+    // Only consider functions that are not a program entry.
+    if (CallGraphIncomingMap.find(FunctionNum) != CallGraphIncomingMap.end()) {
+      uint64_t EntryInflow = 0;
+      uint64_t EntryOutflow = 0;
+      uint32_t NumConsideredEntryBlocks = 0;
+      for (const BinaryBasicBlock &BB : *Function) {
+        if (BB.isEntryPoint()) {
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:212]: Use forEachEntryPoint

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 24]
```diff
@@ -0,0 +1,575 @@
...
+      uint64_t NetEntryOutflow = 0;
+      if (EntryOutflow < EntryInflow) {
+        if (opts::Verbosity >= 2) {
+          // We expect entry blocks' CFG outflow >= inflow, i.e., it has a
+          // non-negative net outflow. If this is not the case, then raise a
+          // warning if requested.
+          OS << "BOLT WARNING: unexpected entry block CFG outflow < inflow "
+                "in "
+                "function "
+             << Function->getPrintName() << "\n";
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:232]: format

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 25]
```diff
@@ -0,0 +1,575 @@
...
+      if (NumConsideredEntryBlocks > 0) {
+        const uint64_t CallGraphInflow =
+            TotalFlowMap.CallGraphIncomingMap[Function->getFunctionNumber()];
+        const uint64_t Min = std::min(NetEntryOutflow, CallGraphInflow);
+        const uint64_t Max = std::max(NetEntryOutflow, CallGraphInflow);
+        const double CallGraphGap = 1 - (double)Min / Max;
+
+        if (opts::Verbosity >= 2 && CallGraphGap >= 0.5) {
+          OS << "Nontrivial call graph gap of size "
+             << format("%.2lf%%", 100 * CallGraphGap)
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:248]: Here and in other places
> For example, to format a floating point value as a percentage, you can use the style option P.

https://llvm.org/docs/ProgrammersManual.html#simple-formatting

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 26]
```diff
@@ -0,0 +1,575 @@
...
+
+      CFGGapsWeightedAvg.push_back(WeightedGap);
+      CFGGapsWorst.push_back(WorstGap);
+      CFGGapsWorstAbs.push_back(WorstGapAbs);
+    }
+  }
+
+  if (CFGGapsWeightedAvg.empty())
+    return;
+  std::sort(CFGGapsWeightedAvg.begin(), CFGGapsWeightedAvg.end());
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:345]: llvm::sort

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 27]
```diff
@@ -0,0 +1,575 @@
...
+  }
+}
+
+void computeFlowMappings(const BinaryContext &BC, FlowInfo &TotalFlowMap) {
+  // Increment block inflow and outflow with CFG jump counts.
+  TotalFlowMapTy &TotalIncomingMaps = TotalFlowMap.TotalIncomingMaps;
+  TotalFlowMapTy &TotalOutgoingMaps = TotalFlowMap.TotalOutgoingMaps;
+  for (const auto &BFI : BC.getBinaryFunctions()) {
+    const BinaryFunction *Function = &BFI.second;
+    if (Function->empty() || !Function->hasValidProfile())
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:373]: I'm thinking how useful would it be to include functions with stale profile. Perhaps not so much since in this case we should be running with `infer-stale-profile` which should set that the profile is valid.
Do you have any thoughts on this?

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 28]
```diff
@@ -0,0 +1,575 @@
...
+      continue;
+    FlowMapTy &IncomingMap = TotalIncomingMaps[Function->getFunctionNumber()];
+    FlowMapTy &OutgoingMap = TotalOutgoingMaps[Function->getFunctionNumber()];
+    for (const BinaryBasicBlock &BB : *Function) {
+      uint64_t TotalOutgoing = 0ULL;
+      auto SuccBIIter = BB.branch_info_begin();
+      for (BinaryBasicBlock *Succ : BB.successors()) {
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:380]: zip

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 29]
```diff
@@ -0,0 +1,575 @@
...
+    using TargetDesc = std::pair<const MCSymbol *, uint64_t>;
+    using CallInfoTy = std::vector<TargetDesc>;
+    auto getCallInfo = [&](const BinaryBasicBlock *BB, const MCInst &Inst) {
+      CallInfoTy Counts;
+      const MCSymbol *DstSym = BC.MIB->getTargetSymbol(Inst);
+
+      if (!DstSym && BC.MIB->hasAnnotation(Inst, "CallProfile")) {
+        const auto &ICSP = BC.MIB->getAnnotationAs<IndirectCallSiteProfile>(
+            Inst, "CallProfile");
+        for (const IndirectCallProfile &CSI : ICSP)
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:454]: nit
```suggestion
        for (const auto &CSI : BC.MIB->getAnnotationAs<IndirectCallSiteProfile>(Inst, "CallProfile"))
```

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 30]
```diff
@@ -0,0 +1,575 @@
...
+      return Counts;
+    };
+
+    // If the function has an invalid profile, try to use the perf data
+    // directly. The call EC is only used to update CallGraphIncomingMap.
+    if (!Function->hasValidProfile() && !Function->getAllCallSites().empty()) {
+      for (const IndirectCallProfile &CSI : Function->getAllCallSites()) {
+        if (CSI.Symbol)
+          recordCall(nullptr, CSI.Symbol, CSI.Count, CSI.Count);
+      }
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:471]:
```suggestion
      for (const IndirectCallProfile &CSI : Function->getAllCallSites())
        if (CSI.Symbol)
          recordCall(nullptr, CSI.Symbol, CSI.Count, CSI.Count);
```

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 31]
```diff
@@ -0,0 +1,575 @@
...
+      continue;
+    } else {
+      // If the function has a valid profile
+      for (const BinaryBasicBlock &BB : *Function) {
+        for (const MCInst &Inst : BB) {
+          if (BC.MIB->isCall(Inst)) {
```
Comment (aaupov) [inline bolt/lib/Passes/ProfileQualityStats.cpp:477]: exit early

File: bolt/lib/Rewrite/BinaryPassManager.cpp (hunk 1 above)
Comment (aaupov) [reply bolt/lib/Rewrite/BinaryPassManager.cpp:61]: Can you please exclude these changes from this diff?

**Review by aaupov — COMMENTED** [review]
Thank you for the effort. Left a few more comments, but otherwise looks good.

**Review by aaupov — APPROVED** [review]
Looks good now, with a couple of minor nits and the comment about whether or not to include stale functions. Please address before landing.

File: bolt/lib/Passes/ProfileQualityStats.cpp [hunk 32]
```diff
@@ -0,0 +1,577 @@
...
+
+    const FunctionLayout &Layout = Function->getLayout();
+
+    while (!Queue.empty()) {
+      const unsigned BBIndex = Queue.front();
+      const BinaryBasicBlock *BB = Layout.getBlock(BBIndex);
+      Queue.pop();
+      for (const auto &Tuple : llvm::zip(BB->successors(), BB->branch_info())) {
+        const auto *Succ = std::get<0>(Tuple);
+        const auto &BI = std::get<1>(Tuple);
```
[the remark this answers is not in the document]
Comment (ShatianWang) [reply bolt/lib/Passes/ProfileQualityStats.cpp:131]: Ah nice. Thanks!

File: bolt/lib/Passes/ProfileQualityStats.cpp (hunk 27 above)
Comment (ShatianWang) [reply bolt/lib/Passes/ProfileQualityStats.cpp:378]: Ah sorry I wasn't being very clear. I meant including functions with stale profile whose profile are later inferred by stale profile matching (hence being set valid), and excluding functions with stale profile that stale profile matching failed to infer (hence remains invalid). I.e., leaving the filter as it is.

Comment (aaupov) [reply bolt/lib/Passes/ProfileQualityStats.cpp:381]: Sounds good. I may experiment with that as part of the effort to improve stale matching/continuous mode.
