### PR TITLE
[clang] improved preservation of template keyword

### PR DESCRIPTION
**Pull request by mizvekov**
This makes it so clang can better represent the abscence of the template keyword for a template which cannot be resolved due to a dependent prefix.

The tracking of the template keyword is removed from the NestedNameSpecifier, and added to the last type node which had it missing, the DependentTemplateSpecializationType (DTST).

The DTST and the DependentTemplateName are refactored to share most of their implementation.

That refactoring along with the removal of the TypeSpecWithTemplate kind from the nested name specifiers amounts to a large amount of code removed, making this patch a small performance improvement overall.

image

This will also enable future further simplifications.

As a drive-by, this removes some special cases from the type printer, allowing template arguments within NestedNameSpecifiers to not have their nested names suppressed when printing.

### CODE REVIEW

**Comment by zwuis** [comment]
I tested this branch locally. It fixes #43179, #68670 and #92757.

File: clang/lib/AST/TemplateName.cpp [hunk 1]
```diff
@@ -124,6 +124,31 @@ void SubstTemplateTemplateParmPackStorage::Profile(
   ID.AddBoolean(Final);
 }
 
+IdentifierOrOverloadedOperator::IdentifierOrOverloadedOperator(
+    const IdentifierInfo *II)
+    : PtrOrOp(reinterpret_cast<uintptr_t>(II)) {
+  static_assert(NUM_OVERLOADED_OPERATORS <= 4096,
+                "NUM_OVERLOADED_OPERATORS is too large");
```
Comment (zyn0217) [inline clang/lib/AST/TemplateName.cpp:131]: How did you determine the upper limit?

File: clang/include/clang/AST/TemplateName.h [hunk 2]
```diff
@@ -544,6 +545,35 @@ class QualifiedTemplateName : public llvm::FoldingSetNode {
...
+    if (getOperator() != OO_None)
+      return nullptr;
+    return reinterpret_cast<const IdentifierInfo *>(PtrOrOp);
+  }
+
+  /// Return the overloaded operator to which this template name refers.
+  OverloadedOperatorKind getOperator() const {
+    uintptr_t OOK = -PtrOrOp;
+    return OOK < NUM_OVERLOADED_OPERATORS ? OverloadedOperatorKind(OOK)
+                                          : OO_None;
```
Comment (zyn0217) [inline clang/include/clang/AST/TemplateName.h:564]: IIRC this pointer/integer mechanism is also used in that lambda patch. We probably want to extract a generic implementation of it.

File: clang/lib/Parse/ParseExprCXX.cpp [hunk 3]
```diff
@@ -587,12 +587,12 @@ bool Parser::ParseOptionalCXXScopeSpecifier(
...
               << FixItHint::CreateInsertion(Tok.getLocation(), "template ");
         }
-
-        SourceLocation TemplateNameLoc = ConsumeToken();
+        ConsumeToken();
 
         TemplateNameKind TNK = Actions.ActOnTemplateName(
-            getCurScope(), SS, TemplateNameLoc, TemplateName, ObjectType,
-            EnteringContext, Template, /*AllowInjectedClassName*/ true);
+            getCurScope(), SS, /*TemplateKWLoc=*/SourceLocation(), TemplateName,
```
Comment (zyn0217) [inline clang/lib/Parse/ParseExprCXX.cpp:593]: We don't want to track the `template` keyword's location following an NNS prefix anymore? Even that is never used, I think we need to mention the change in the release note.

Or am I missing any code that would track the location instead?

**Review by zyn0217 — APPROVED** [review]
Thanks for the improvement.

File: clang/lib/Parse/ParseExprCXX.cpp (hunk 3 above)
Comment (mizvekov) [reply clang/lib/Parse/ParseExprCXX.cpp:593]: This part of the parser is dealing with the case where the template keyword was not used. This call was using a fake location for the template keyword, which defeats the purpose of the patch.

File: clang/lib/AST/TemplateName.cpp (hunk 1 above)
Comment (mizvekov) [reply clang/lib/AST/TemplateName.cpp:131]: It's just a reasonable assumption on my part. 4096 is the smallest page size for anything you would expect to be running clang.

I don't know if it would be worth the complexity to use the actual page size, where we are nowhere near needing that much.

For this application the actual maximum is much smaller, I think there are less than 32 elements in this enum.

Comment (zyn0217) [reply clang/lib/AST/TemplateName.cpp:131]: Yeah, in that sense 4096 is a sufficiently fair number to hold less than a hundred enum. Though I was not expecting it to be related to the page size :P

File: libcxx/test/std/utilities/smartptr/adapt/inout_ptr/inout_ptr.verify.cpp [hunk 4]
```diff
@@ -26,7 +26,7 @@ int main(int, char**) {
 
     // expected-error-re@*:* {{static assertion failed due to requirement {{.*}}std::shared_ptr<> is not supported}}
     std::ignore = std::inout_ptr(sPtr);
-    // expected-error@*:* {{no matching conversion for functional-style cast from 'std::shared_ptr<int>' to 'std::inout_ptr_t<shared_ptr<int>, _Ptr>' (aka 'inout_ptr_t<std::shared_ptr<int>, int *>'}}
+    // expected-error-re@*:* {{no matching conversion for functional-style cast from 'std::shared_ptr<int>' to 'std::inout_ptr_t<{{(std::)?}}shared_ptr<int>, _Ptr>'{{( \(aka 'inout_ptr_t<std::shared_ptr<int>, int *>')?}}}}
```
Comment (erichkeane) [inline libcxx/test/std/utilities/smartptr/adapt/inout_ptr/inout_ptr.verify.cpp:29]: Can you explain these differences?  I don't really get why this is happening but only 'sometimes' instead of always?

**Review by erichkeane — APPROVED** [review]
Ooof... this is a big patch again.  Seems like you have a minimum patch size of 50 files these days :D Reviewed best I can, but didn't see anything problematic best I could tell.  I question why we are now a regex match on some tests, else LGTM.

File: libcxx/test/std/utilities/smartptr/adapt/inout_ptr/inout_ptr.verify.cpp (hunk 4 above)
Comment (mizvekov) [reply libcxx/test/std/utilities/smartptr/adapt/inout_ptr/inout_ptr.verify.cpp:29]: It is because libcxx is tested against stable clang in addition to trunk, so we have to make sure the test expects both the **before** and the **after** clang diagnostic outputs.

File: clang/include/clang/AST/TemplateName.h (hunk 2 above)
Comment (mizvekov) [reply clang/include/clang/AST/TemplateName.h:564]: Sure, I'll leave it to a follow up, before we introduce a second user of such a facility.

**Comment by amykhuang** [comment]
Hi we're seeing some msan failures after this patch in tests such as clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp

Here's the top of the stack trace
```
==6262==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x560847d4ff8a in clang::DependentTemplateSpecializationTypeLoc::getQualifierLoc() const [third_party/llvm/llvm-project/clang/include/clang/AST/TypeLoc.h:2502](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/include/clang/AST/TypeLoc.h?l=2502&ws=akhuang/7402&snapshot=28):9
    #1 0x56084edfb6ff in clang::DependentTemplateSpecializationTypeLoc::getLocalSourceRange() const [third_party/llvm/llvm-project/clang/include/clang/AST/TypeLoc.h:2578](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/include/clang/AST/TypeLoc.h?l=2578&ws=akhuang/7402&snapshot=28):14
    #2 0x56084edfb1d0 in (anonymous namespace)::TypeLocRanger::VisitDependentTemplateSpecializationTypeLoc(clang::DependentTemplateSpecializationTypeLoc) blaze-out/k8-fastbuild-msan/bin/third_party/llvm/llvm-project/clang/include/clang/AST/TypeNodes.inc:47:1
    #3 0x56084edf0bcd in Visit blaze-out/k8-fastbuild-msan/bin/third_party/llvm/llvm-project/clang/include/clang/AST/TypeNodes.inc:47:1
    #4 0x56084edf0bcd in clang::TypeLoc::getLocalSourceRangeImpl(clang::TypeLoc) [third_party/llvm/llvm-project/clang/lib/AST/TypeLoc.cpp:56](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/lib/AST/TypeLoc.cpp?l=56&ws=akhuang/7402&snapshot=28):26
    #5 0x56084edf82a5 in getLocalSourceRange [third_party/llvm/llvm-project/clang/include/clang/AST/TypeLoc.h:161](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/include/clang/AST/TypeLoc.h?l=161&ws=akhuang/7402&snapshot=28):12
    #6 0x56084edf82a5 in clang::TypeLoc::getBeginLoc() const [third_party/llvm/llvm-project/clang/lib/AST/TypeLoc.cpp:223](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/lib/AST/TypeLoc.cpp?l=223&ws=akhuang/7402&snapshot=28):15
    #7 0x56084ebf05c5 in clang::NestedNameSpecifierLoc::getLocalSourceRange() const [third_party/llvm/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp:443](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp?l=443&ws=akhuang/7402&snapshot=28):27
    #8 0x56084ebf02f9 in clang::NestedNameSpecifierLoc::getSourceRange() const [third_party/llvm/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp:418](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp?l=418&ws=akhuang/7402&snapshot=28):22
    #9 0x56084c6582a3 in getSourceRange [third_party/llvm/llvm-project/clang/include/clang/AST/NestedNameSpecifier.h:480](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/include/clang/AST/NestedNameSpecifier.h?l=480&ws=akhuang/7402&snapshot=28):59
    #10 0x56084c6582a3 in clang::CXXScopeSpec::Extend(clang::ASTContext&, clang::TypeLoc, clang::SourceLocation) [third_party/llvm/llvm-project/clang/lib/Sema/DeclSpec.cpp:58](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/lib/Sema/DeclSpec.cpp?l=58&ws=akhuang/7402&snapshot=28):3
    #11 0x56084c7b25ea in clang::Sema::ActOnCXXNestedNameSpecifier(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::OpaquePtr<clang::TemplateName>, clang::SourceLocation, clang::SourceLocation, llvm::MutableArrayRef<clang::ParsedTemplateArgument>, clang::SourceLocation, clang::SourceLocation, bool) [third_party/llvm/llvm-project/clang/lib/Sema/SemaCXXScopeSpec.cpp:883](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/clang/lib/Sema/SemaCXXScopeSpec.cpp?l=883&ws=akhuang/7402&snapshot=28):8
```

**Comment by mizvekov** [comment]
@amykhuang does it still happen in current main branch? I pushed a follow up fix a while ago.

**Comment by amykhuang** [comment]
oh, sorry, yes, it does fix it

**Comment by rnk** [comment]
We have internal reports of incorrect mangling substitutions after updating to 537b6541e8067d7ef7aa38791989fca6303b7fd from 799e9053641a6478d3144866a97737b37b87c260, and this change seems like the likely culprit because it's touching the Itanium mangling code. We'll see if that can be confirmed.

**Comment by alexfh** [comment]
We're seeing another problem after this commit: seemingly bogus `class member cannot be redeclared` errors. I'll try to provide a reduced repro on Monday.

**Comment by alexfh** [comment]
> We're seeing another problem after this commit: seemingly bogus `class member cannot be redeclared` errors. I'll try to provide a reduced repro on Monday.

My cvise has been running for quite a while. I'll post the test once it concludes.

**Comment by DKLoehr** [comment]
We're also seeing `class member cannot be redeclared` errors when trying to build chromium:
```
In file included from ../../components/system_cpu/cpu_probe.cc:16:
In file included from ../../components/system_cpu/cpu_probe_linux.h:14:
../../base/threading/sequence_bound.h:281:8: error: class member cannot be redeclared
  281 |   void PostTaskWithThisObject(
      |        ^
../../base/threading/sequence_bound.h:264:8: note: previous definition is here
  264 |   void PostTaskWithThisObject(
      |        ^
```
The file in question can be viewed [here](https://source.chromium.org/chromium/chromium/src/+/main:base/threading/sequence_bound.h;l=263;drc=72ba73a81b090ee221a9f107333c3e5e964cf750). It seems like the compiler is getting confused between `const UnwrappedT&` and `UnwrappedT*`, where `UnwrappedT` is, ultimately, a templated type. I'm also looking for a reduced repro, though I expect alexfh will produce one that works for both of us.

**Comment by DKLoehr** [comment]
I ended up with the following reproducer:
```
template <typename T> struct S {
  template <typename T2>
    using Arg = T::template Arg<T2>;
  void f(Arg<void>);
  void f(Arg<int>);
};
```

Running this with `clang++ repro.cc -fsyntax-only -std=c++20` yields
```
repro.cc:5:8: error: class member cannot be redeclared
    5 |   void f(Arg<int>);
      |        ^
repro.cc:4:8: note: previous declaration is here
    4 |   void f(Arg<void>);
      |        ^
```

The same error occurs regardless of which types are inside the < >.

**Comment by mizvekov** [comment]
@DKLoehr this will be fixed here: https://github.com/llvm/llvm-project/pull/134748

**Comment by alexfh** [comment]
My test case: https://gcc.godbolt.org/z/a5no94d39

```
$ cat q.cc
namespace ns {
enum class E : unsigned char {
  KA,
  kB,
};
template <typename P>
struct A {
  using Parent = P;
  struct B;
  using typename Parent::Res;
  template <E e>
  using Source = typename Parent::template Source<e>;
  Res M(Source<E::KA>, const typename B::S& event);
  Res M(Source<E::kB>, const typename B::S& event);
};
}
$ ./clang-bad -fsyntax-only -std=c++20 q.cc
q.cc:14:7: error: class member cannot be redeclared
   14 |   Res M(Source<E::kB>, const typename B::S& event);
      |       ^
q.cc:13:7: note: previous declaration is here
   13 |   Res M(Source<E::KA>, const typename B::S& event);
      |       ^
1 error generated.
```

**Comment by alexfh** [comment]
#134748 doesn't fix errors in the original code, unfortunately. Now we're getting `out-of-line definition of 'X' does not match any declaration in 'Y'`. It's hard to tell whether the original code is correct, but I suppose that the purpose of this change was not to make Clang stricter?

I'm re-running reduction with Clang after #134748

**Comment by slackito** [comment]
I have a reduced test case for the mangling issue mentioned [here](https://github.com/llvm/llvm-project/pull/133610#issuecomment-2784039483). It's still a bit long (118 lines), so apologies for that.

[hash_mangling.txt](https://github.com/user-attachments/files/19654889/hash_mangling.txt)

Rename the attached file to `hash_mangling.ii` (github wouldn't let me attach it with a .ii extension), then build with `clang++ -c hash_mangling.ii`. With an affected version of `clang` (just checked at HEAD) the resulting object file contains the wrong mangled name:
```
$ llvm-readelf -s -W hash_mangling.o | grep hashable
    33: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND _ZN4absl18container_internal13AbslHashValueINS_13hash_internal15MixingHashStateEEEN12_GLOBAL__N_19enable_ifIXsrNT_S6_11is_hashableIiEE5valueES6_E4typeES6_NS0_12raw_hash_setINS0_17FlatHashSetPolicyEiEE
```
(note the spurious `S6_` mentioned in the comment above)

With a good version of clang, the output looks like this instead
```
    33: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND _ZN4absl18container_internal13AbslHashValueINS_13hash_internal15MixingHashStateEEEN12_GLOBAL__N_19enable_ifIXsrNT_11is_hashableIiEE5valueES6_E4typeES6_NS0_12raw_hash_setINS0_17FlatHashSetPolicyEiEE
```

**Comment by mizvekov** [comment]
Ack, I see. I will try to reduce this example further.

It's not likely I will have a solution in less than 2 hours this time due to personal commitments, so feel free to revert if this is blocking you.

In any case I will pick this up tomorrow.

**Comment by alexfh** [comment]
> #134748 doesn't fix errors in the original code, unfortunately. Now we're getting `out-of-line definition of 'X' does not match any declaration in 'Y'`. It's hard to tell whether the original code is correct, but I suppose that the purpose of this change was not to make Clang stricter?
> 
> I'm re-running reduction with Clang after #134748

Reduced test case (https://gcc.godbolt.org/z/qezPYcW93):
```
$ cat q3.cc
template <typename T>
class SM;
enum class S { kA };
template <typename T>
struct N {
  using State = S;
  using P = SM<N>;
  struct E;
  template <typename P::template FromSources<State::kA> = 0>
  void F(const typename E::S& e);
};
template <typename T>
template <typename N<T>::P::template FromSources<N<T>::State::kA>>
inline void N<T>::F(const typename E::S& e) {}
$ ./clang-bad2 -fsyntax-only -std=c++20 q3.cc
q3.cc:14:19: error: out-of-line definition of 'F' does not match any declaration in 'N<T>'
   14 | inline void N<T>::F(const typename E::S& e) {}
      |                   ^
q3.cc:5:8: note: N defined here
    5 | struct N {
      |        ^
1 error generated.
$ ./clang-good -fsyntax-only -std=c++20 q3.cc
```

**Comment by mizvekov** [comment]
@alexfh the last one will be fixed here: https://github.com/llvm/llvm-project/pull/135067

**Comment by mizvekov** [comment]
@slackito this will be fixed here: https://github.com/llvm/llvm-project/pull/135111

**Comment by slackito** [comment]
> @slackito this will be fixed here: #135111

Thanks for the quick fix!
