### ISSUE TITLE
[OpenMP] offload linking issue

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#56752]
Broken since d61d72dae604c3258e25c00622b1a85861450303
```console
$ clang++ -fopenmp -fopenmp-targets=nvptx64 -O3 complex.cpp 
nvlink error   : Undefined reference to '__kmpc_kernel_parallel' in '/tmp/complex-496a9f-nvptx64-nvidia-cuda-sm_80-4864b4.cubin'
nvlink error   : Undefined reference to '__kmpc_kernel_end_parallel' in '/tmp/complex-496a9f-nvptx64-nvidia-cuda-sm_80-4864b4.cubin'
/soft/llvm/main-patched/bin/clang-linker-wrapper: error: 'nvlink' failed
```
[code](https://github.com/ye-luo/openmp-target/blob/master/tests/complex/complex.cpp)
affecting main and 15 release

**Comment by ye-luo** [comment]
Keep this open until 15.x picks up the fix (revert).
