### ISSUE TITLE
Failed to build llvm libc 14.0.5 on Oracle Ampere A1 Arm with GCC 8.5.0

### ISSUE THREAD

**Issue by Tomcruseal** [llvm/llvm-project#60473]
Hi there,

I was trying to build LLVM 14.0.5 and all the subprojects from source on Oracle Ampere A1 Arm. The OS is Oracle Linux arm-server-beta-2022 5.4.17-2102.204.4.4.el8uek.aarch64 with 4 cores 24GB ram.

My cmake configure was 
```bash
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/home/opc/library -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;cross-project-tests;libc;libclc;lld;lldb;openmp;polly;pstl" DLLVM_ENABLE_RUNTIMES="compiler-rt;libc;libcxx;libcxxabi;libunwind" ../llvm
```
CMake went well, but it crashed at Make. The error information is shown below,

```console
Consolidate compiler generated dependencies of target libc.src.fenv.fegetexcept
[ 42%] Building CXX object projects/libc/src/fenv/CMakeFiles/libc.src.fenv.fegetexcept.dir/fegetexcept.cpp.o
In file included from /home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/FEnvUtils.h:17,
                 from /home/opc/Downloads/llvm-project-14.0.5.src/libc/src/fenv/fegetexcept.cpp:10:
/home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/aarch64/FEnvImpl.h: In static member function 'static uint32_t __llvm_libc::fputil::FEnv::getControlWord()':
/home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:69:45: error: '__arm_rsr' was not declared in this scope
   static uint32_t getControlWord() { return __arm_rsr("fpcr"); }
                                             ^~~~~~~~~
/home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/aarch64/FEnvImpl.h: In static member function 'static void __llvm_libc::fputil::FEnv::writeControlWord(uint32_t)':
/home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:71:49: error: '__arm_wsr' was not declared in this scope
   static void writeControlWord(uint32_t fpcr) { __arm_wsr("fpcr", fpcr); }
                                                 ^~~~~~~~~
/home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/aarch64/FEnvImpl.h: In static member function 'static uint32_t __llvm_libc::fputil::FEnv::getStatusWord()':
/home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:73:44: error: '__arm_rsr' was not declared in this scope
   static uint32_t getStatusWord() { return __arm_rsr("fpsr"); }
                                            ^~~~~~~~~
/home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/aarch64/FEnvImpl.h: In static member function 'static void __llvm_libc::fputil::FEnv::writeStatusWord(uint32_t)':
/home/opc/Downloads/llvm-project-14.0.5.src/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:75:48: error: '__arm_wsr' was not declared in this scope
   static void writeStatusWord(uint32_t fpsr) { __arm_wsr("fpsr", fpsr); }
                                                ^~~~~~~~~
make[2]: *** [projects/libc/src/fenv/CMakeFiles/libc.src.fenv.fegetexcept.dir/build.make:76: projects/libc/src/fenv/CMakeFiles/libc.src.fenv.fegetexcept.dir/fegetexcept.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:42575: projects/libc/src/fenv/CMakeFiles/libc.src.fenv.fegetexcept.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
Could you please give some suggestions? Many thanks

**Comment by DimitryAndric** [comment]
What is your host compiler, and which version is it? E.g. what does the CMake stage print when it detects `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER`?

**Comment by sivachandra** [comment]
The minimum version of gcc required for building the libc is 12.2. Also, I do no think anyone has actually done an arm64 host build of the libc. We have a CI builder for x86_64 which builds using gcc-12.2: https://lab.llvm.org/buildbot/#/builders/250

**Comment by DavidSpickett** [comment]
Seems like the function is present for C but not C++ when using gcc https://godbolt.org/z/Gjr1bfWx3.

**Comment by Tomcruseal** [comment]
> Seems like the function is present for C but not C++ when using gcc https://godbolt.org/z/Gjr1bfWx3.

Yes, thanks for it! and seems the function works well with C++ when using clang [https://godbolt.org/z/cG8GsEMs3](https://godbolt.org/z/cG8GsEMs3)

**Comment by DavidSpickett** [comment]
There are two AArch64 bots that I presume compile this code, https://lab.llvm.org/buildbot/#/builders/138, https://lab.llvm.org/buildbot/#/builders/223. However they both use clang.

I will see what's going on with gcc/g++ and at least raise a bug for it.

**Comment by DavidSpickett** [comment]
Filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108642.

As far as I can tell it's always worked for clang and `arm_acle.h` is correct.

I'm a but surprised your initial cmake command wasn't using the newly built clang to build libc, because it looks a lot like https://libcxx.llvm.org/BuildingLibcxx.html#bootstrapping-build. Either way, if you've got a clang that works that's the important thing.

**Comment by sivachandra** [comment]
A correction to my previous comment: It would be the suggested way after https://reviews.llvm.org/D141460 lands.

**Comment by Tomcruseal** [comment]
> Filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108642.
> 
> As far as I can tell it's always worked for clang and `arm_acle.h` is correct.
> 
> I'm a but surprised your initial cmake command wasn't using the newly built clang to build libc, because it looks a lot like https://libcxx.llvm.org/BuildingLibcxx.html#bootstrapping-build. Either way, if you've got a clang that works that's the important thing.

@DavidSpickett Thanks! I will have a look at Bootstrapping build, it is quite new to me.

**Comment by Tomcruseal** [comment]
> A correction to my previous comment: It would be the suggested way after https://reviews.llvm.org/D141460 lands.

@sivachandra Thanks for the link!

**Comment by DavidSpickett** [comment]
Fix the full build with gcc: https://reviews.llvm.org/D143261

I also found that the overlay mode has been broken with gcc on any platform for a while. In case you were trying to use that too. Stick with clang if you can.

**Comment by DavidSpickett** [comment]
For the overlay build see https://github.com/llvm/llvm-project/issues/60481.

**Comment by DavidSpickett** [comment]
The fix is on `main` for this. We could cherry pick it to 16.x but I'm not sure how useful that is.

@Tomcruseal unless you're looking to build some kind of release off of this, are you happy to use the libc from the `main` branch instead? Which is/will be 17.x.

**Comment by DavidSpickett** [comment]
Great, then I will close this.
