### ISSUE TITLE
libc++ tests are failing on Windows after #69431

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#70225]
`libcxx/fuzzing/random.pass.cpp`, `std/depr/depr.c.headers/math_h.pass.cpp` and `std/numerics/c.math/cmath.pass.cpp` are all failing with tip-of-tree Clang after #69431 landed:
```
# .---command stderr------------
# | In file included from C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:12:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\cmath:319:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\math.h:301:
# | In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\math.h:11:
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:413:16: error: call to 'fpclassify' is ambiguous
# |   413 |         return fpclassify(_X) == FP_NAN;
# |       |                ^~~~~~~~~~
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:162:12: note: in instantiation of function template specialization 'isnan<short>' requested here
# |   162 |   if (std::isnan(res)) {
# |       |            ^
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:174:10: note: in instantiation of function template specialization 'helper<std::uniform_int_distribution<short>>' requested here
# |   174 |   return helper<std::uniform_int_distribution<std::int16_t>>(data, size)       ||
# |       |          ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:288:31: note: candidate function
# |   288 |     _Check_return_ inline int fpclassify(_In_ float _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:293:31: note: candidate function
# |   293 |     _Check_return_ inline int fpclassify(_In_ double _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:298:31: note: candidate function
# |   298 |     _Check_return_ inline int fpclassify(_In_ long double _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:413:16: error: call to 'fpclassify' is ambiguous
# |   413 |         return fpclassify(_X) == FP_NAN;
# |       |                ^~~~~~~~~~
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:162:12: note: in instantiation of function template specialization 'isnan<bool>' requested here
# |   162 |   if (std::isnan(res)) {
# |       |            ^
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:176:10: note: in instantiation of function template specialization 'helper<std::bernoulli_distribution>' requested here
# |   176 |          helper<std::bernoulli_distribution>(data, size)                       ||
# |       |          ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:288:31: note: candidate function
# |   288 |     _Check_return_ inline int fpclassify(_In_ float _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:293:31: note: candidate function
# |   293 |     _Check_return_ inline int fpclassify(_In_ double _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:298:31: note: candidate function
# |   298 |     _Check_return_ inline int fpclassify(_In_ long double _X) throw()
# |       |                               ^
# | In file included from C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:16:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\random:1686:
# | C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\__random/clamp_to_integral.h:35:87: error: shift count is negative [-Werror,-Wshift-count-negative]
# |    35 |   return _FloatBigger ? numeric_limits<_IntT>::max() :  (numeric_limits<_IntT>::max() >> _Bits << _Bits);
# |       |                                                                                       ^  ~~~~~
# | C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\__random/clamp_to_integral.h:46:27: note: in instantiation of function template specialization 'std::__max_representable_int_for_float<short, double, true, -38>' requested here
# |    46 |   const _IntT __max_val = __max_representable_int_for_float<_IntT, _RealT>();
# |       |                           ^
# | C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\__random/poisson_distribution.h:181:31: note: in instantiation of function template specialization 'std::__clamp_to_integral<short, double>' requested here
# |   181 |                 return _VSTD::__clamp_to_integral<result_type>(__tx);
# |       |                               ^
# | C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\__random/poisson_distribution.h:95:17: note: in instantiation of function template specialization 'std::poisson_distribution<short>::operator()<std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>>' requested here
# |    95 |         {return (*this)(__g, __p_);}
# |       |                 ^
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:161:23: note: in instantiation of function template specialization 'std::poisson_distribution<short>::operator()<std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>>' requested here
# |   161 |   volatile auto res = d(engine);
# |       |                       ^
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:177:10: note: in instantiation of function template specialization 'helper<std::poisson_distribution<short>>' requested here
# |   177 |          helper<std::poisson_distribution<std::int16_t>>(data, size)           ||
# |       |          ^
# | In file included from C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:16:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\random:1686:
# | C:/b/s/w/ir/x/w/llvm_build/include/c++/v1\__random/clamp_to_integral.h:35:96: error: shift count is negative [-Werror,-Wshift-count-negative]
# |    35 |   return _FloatBigger ? numeric_limits<_IntT>::max() :  (numeric_limits<_IntT>::max() >> _Bits << _Bits);
# |       |                                                                                                ^  ~~~~~
# | 4 errors generated.
# `-----------------------------
```

**Comment by H-G-Hristov** [comment]
The failing tests were XFAILED in https://github.com/llvm/llvm-project/pull/79619
This is still an issue IMO.

**Comment by jyknight** [comment]
Just ran into this issue when migrating to Clang c++20 for some windows code. I've retitled the bug to indicate what it's actually about now.

In the MSVC UCRT headers, their math.h is actually intended to implement the full C++ spec requirements for the header. They _don't_ expect the C++ stdlib to provide its own wrapper math.h for C++-specific functionality, and their STL does not do so -- unlike Unix implementations, where libc provides a math.h which only implement the C standard functions, and the C++ stdlib is expected to wrap it.

Unfortunately, as the very-old https://github.com/microsoft/STL/issues/519 issue records, their header is non-compliant with C++11, by not providing integer overloads for any of the floating-point functions like `isnan`/`isinf`/etc. Apparently the C++ standard didn't clearly-enough require the integer overloads in C++11 (though it now does), and so they've been dragging their feet.

Thus, libc++ currently defines `fpclassify` and `signbit` overloads for MSVC, to add this support.

Unfortunately, the libc++ workaround to the MSVC header bug relies upon `-fdelayed-template-parsing` to function.

Because the MSVC math.h defines `std::isnan` in terms of fpclassify, libc++'s addition of more overloads for `std::fpclassify` _after_ the MSVC header was included should not be visible to the MSVC math.h's isnan function template -- but they were previously, only because of the nonstandard `-fdelayed-template-parsing`.

Now that we aren't using that nonstandard mode by default in `-std=c++20`, that means that std::isnan(integer-type) no longer works in C++20.

In my opinion, the best thing for libc++ to do here would actually be to stop trying to workaround math.h bugs in MSVC -- and therefore become buggy by missing the integer overloads for isnan/etc _unconditionally_ in MSVC mode, until MSVC fixes its math.h header.

**Comment by jmr** [comment]
> Unfortunately, as the very-old https://github.com/microsoft/STL/issues/519 issue records, their header is non-compliant with C++11, by not providing integer overloads for any of the floating-point functions like isnan/isinf/etc. 

This has been fixed by adding the overloads to `<cmath>`.

https://github.com/microsoft/STL/issues/519#issuecomment-2045938731

https://github.com/microsoft/STL/issues/4747#issuecomment-2190192852

**Comment by ldionne** [comment]
Is this still an issue? I don't see any MSVC-specific code around how we handle `fpclassify` anymore. Can this be closed?

**Comment by jyknight** [comment]
This is still an issue.

On all platforms other than Windows, the C library's math.h header only provides the functions with C semantics. libc++ then adds all the C++-specific parts in its wrapper math.h header. However, on Windows, the C runtime attempts to provide fully C++-compliant <math.h> header. The MS C++ STL library doesn't provide math.h at all, only cmath. However, MS UCRT's math.h has not yet implemented the "new" C++11 functionality. This issue was reported as https://developercommunity.visualstudio.com/t/10294165, but closed apparently due to disinterest (despite MS STL having comments about its workaround, pointing to that bug as the solution).

Anyhow, the _specific_ problem is that `std::isnan` (which is defined in the MS ucrt's math.h as a template valid for all types) calls `std::fpclassify` (also defined by ucrt's math.h). However, that definition of `fpclassify` is only defined for the 3 types `float`, `double`, and `long double`.

This previously worked for libc++, because we define our own `std::fpclassify` in libc++, including for integer types. Here, we were careful to avoid conflicting with the MS CRT's definitions. We then expected MS CRT's definition of `isnan` to use our newly-defined `fpclassify` overloads. But, this depended upon the nonstandard delayed-template-parsing mode being enabled. With standard-compliant template parsing behavior, our new `fpclassify` definitions cannot affect the _previously-defined_ `isnan` template from MS CRT math.h. That nonstandard mode is enabled by default for windows targets -- but only for C++17 and earlier.

And, because the MS UCRT already provides a definition of `isnan`, we [disable](https://github.com/llvm/llvm-project/blob/887222e3526fbe08e748a33f740296ac22bf1ab1/libcxx/include/math.h#L419) our `isnan` implementation.

The MS STL cmath header did workaround this issue with https://github.com/microsoft/STL/pull/4537/files -- but the workaround is rather complicated by needing to avoid conflicting with the UCRT definitions. https://github.com/microsoft/STL/pull/4648/files seems a bit related too. 

We could do similar hacks for Windows platforms. But, ideally this'd be fixed in the MS UCRT math.h header, and I'd be worried that changes we make might actually conflict with a future fixed MS UCRT. Although, https://developercommunity.visualstudio.com/t/10294165 was the bug filed for that, but that's now been closed due to inactivity...so who knows if it'll ever be fixed.

**Comment by ilovepi** [comment]
I'm seeing this in our CI now. 

Bot: https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci/clang-windows-x64/b8709267330516788049/overview

Logs: https://logs.chromium.org/logs/fuchsia/buildbucket/cr-buildbucket/8709267330516788049/+/u/clang/test/stdout

<details>
<summary>Test failure log output</summary>

```
******************** TEST 'llvm-libc++-static-clangcl.cfg.in :: libcxx/fuzzing/random.pass.cpp' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
# COMPILED WITH
C:/b/s/w/ir/x/w/llvm_build/./bin/clang-cl.exe C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp --driver-mode=g++ --target=x86_64-pc-windows-msvc -fms-runtime-lib=static -nostdinc++ -I C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/x86_64-pc-windows-msvc/c++/v1 -I C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1 -I C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/test/support -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_STDIO_ISO_WIDE_SPECIFIERS -DNOMINMAX -std=c++26 -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wshift-negative-value -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -Wno-nullability-completeness -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -Wuser-defined-warnings  -llibc++experimental -nostdlib -L C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/lib/x86_64-pc-windows-msvc -llibc++ -llibcpmt -o C:\b\s\w\ir\x\w\llvm_build\runtimes\runtimes-x86_64-pc-windows-msvc-bins\libcxx\test\libcxx\fuzzing\Output\random.pass.cpp.dir\t.tmp.exe
# executed command: C:/b/s/w/ir/x/w/llvm_build/./bin/clang-cl.exe 'C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp' --driver-mode=g++ --target=x86_64-pc-windows-msvc -fms-runtime-lib=static -nostdinc++ -I C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/x86_64-pc-windows-msvc/c++/v1 -I C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1 -I C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/test/support -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_STDIO_ISO_WIDE_SPECIFIERS -DNOMINMAX -std=c++26 -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wshift-negative-value -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -Wno-nullability-completeness -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -Wuser-defined-warnings -llibc++experimental -nostdlib -L C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/lib/x86_64-pc-windows-msvc -llibc++ -llibcpmt -o 'C:\b\s\w\ir\x\w\llvm_build\runtimes\runtimes-x86_64-pc-windows-msvc-bins\libcxx\test\libcxx\fuzzing\Output\random.pass.cpp.dir\t.tmp.exe'
# .---command stderr------------
# | In file included from C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:16:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\cmath:331:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\math.h:304:
# | In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\math.h:11:
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:413:16: error: call to 'fpclassify' is ambiguous
# |   413 |         return fpclassify(_X) == FP_NAN;
# |       |                ^~~~~~~~~~
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:166:12: note: in instantiation of function template specialization 'isnan<short>' requested here
# |   166 |   if (std::isnan(res)) {
# |       |            ^
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:178:10: note: in instantiation of function template specialization 'helper<std::uniform_int_distribution<short>>' requested here
# |   178 |   return helper<std::uniform_int_distribution<std::int16_t>>(data, size)       ||
# |       |          ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:288:31: note: candidate function
# |   288 |     _Check_return_ inline int fpclassify(_In_ float _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:293:31: note: candidate function
# |   293 |     _Check_return_ inline int fpclassify(_In_ double _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:298:31: note: candidate function
# |   298 |     _Check_return_ inline int fpclassify(_In_ long double _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:413:16: error: call to 'fpclassify' is ambiguous
# |   413 |         return fpclassify(_X) == FP_NAN;
# |       |                ^~~~~~~~~~
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:166:12: note: in instantiation of function template specialization 'isnan<bool>' requested here
# |   166 |   if (std::isnan(res)) {
# |       |            ^
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:180:10: note: in instantiation of function template specialization 'helper<std::bernoulli_distribution>' requested here
# |   180 |          helper<std::bernoulli_distribution>(data, size)                       ||
# |       |          ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:288:31: note: candidate function
# |   288 |     _Check_return_ inline int fpclassify(_In_ float _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:293:31: note: candidate function
# |   293 |     _Check_return_ inline int fpclassify(_In_ double _X) throw()
# |       |                               ^
# | C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h:298:31: note: candidate function
# |   298 |     _Check_return_ inline int fpclassify(_In_ long double _X) throw()
# |       |                               ^
# | In file included from C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:20:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\random:1696:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/geometric_distribution.h:14:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/negative_binomial_distribution.h:17:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/poisson_distribution.h:13:
# | C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/clamp_to_integral.h:36:86: error: shift count is negative [-Werror,-Wshift-count-negative]
# |    36 |   return _FloatBigger ? numeric_limits<_IntT>::max() : (numeric_limits<_IntT>::max() >> _Bits << _Bits);
# |       |                                                                                      ^  ~~~~~
# | C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/clamp_to_integral.h:46:32: note: in instantiation of function template specialization 'std::__max_representable_int_for_float<short, double, true, -38>' requested here
# |    46 |   const _IntT __max_val = std::__max_representable_int_for_float<_IntT, _RealT>();
# |       |                                ^
# | C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/poisson_distribution.h:153:21: note: in instantiation of function template specialization 'std::__clamp_to_integral<short, double>' requested here
# |   153 |         return std::__clamp_to_integral<result_type>(__tx);
# |       |                     ^
# | C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/poisson_distribution.h:83:12: note: in instantiation of function template specialization 'std::poisson_distribution<short>::operator()<std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>>' requested here
# |    83 |     return (*this)(__g, __p_);
# |       |            ^
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:165:23: note: in instantiation of function template specialization 'std::poisson_distribution<short>::operator()<std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>>' requested here
# |   165 |   volatile auto res = d(engine);
# |       |                       ^
# | C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:181:10: note: in instantiation of function template specialization 'helper<std::poisson_distribution<short>>' requested here
# |   181 |          helper<std::poisson_distribution<std::int16_t>>(data, size)           ||
# |       |          ^
# | In file included from C:\b\s\w\ir\x\w\llvm-llvm-project\libcxx\test\libcxx\fuzzing\random.pass.cpp:20:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\random:1696:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/geometric_distribution.h:14:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/negative_binomial_distribution.h:17:
# | In file included from C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/poisson_distribution.h:13:
# | C:/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/test-suite-install/include/c++/v1\__random/clamp_to_integral.h:36:95: error: shift count is negative [-Werror,-Wshift-count-negative]
# |    36 |   return _FloatBigger ? numeric_limits<_IntT>::max() : (numeric_limits<_IntT>::max() >> _Bits << _Bits);
# |       |                                                                                               ^  ~~~~~
# | 4 errors generated.
# `-----------------------------
# error: command failed with exit status: 1

--

********************
```

</details>

The blame list has two changes to libc++, but I'm not sure if those are the issue or not. the preceeding build succeeded, so it should be something in this set of things. https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci/clang-windows-x64/b8709267330516788049/blamelist

**Comment by jyknight** [comment]
The trigger was the switch of the Clang version to 22. (Because the impacted tests list clang-21 as XFAIL but not clang-22).

**Comment by ilovepi** [comment]
> The trigger was the switch of the Clang version to 22. (Because the impacted tests list clang-21 as XFAIL but not clang-22).

Ah, thank you.  I've uploaded https://github.com/llvm/llvm-project/pull/149124 to address that.

**Comment by frederick-vs-ja** [comment]
> Now that we aren't using that nonstandard mode by default in `-std=c++20`, that means that std::isnan(integer-type) no longer works in C++20.

Given this is problematic mainly since C++20, can we add overloads constrained by `requires` to resolve the ambiguity?
