### ISSUE TITLE
[C++20][Modules] Multiple definitions of v-table

### ISSUE THREAD

**Issue by DanielaE** [llvm/llvm-project#62465]
During my efforts of making [my module test suite of the {fmt} library](https://github.com/DanielaE/fmt/tree/test-with-modules) compile with Clang 16.0 I ran into this issue. I have stripped it down as much as I can, the [result is here on CE](https://godbolt.org/z/jTK71s8fY).

Building it manually like so
```shell
clang++ -std=c++20 -O1 -DNDEBUG -fmodule-output -c fmt.cppm
clang++ -std=c++20 -O1 -DNDEBUG -fprebuilt-module-path=. fmt.pcm main.cpp os.cpp
```
I get

```console
E:/msys64/bin/ld: E:/msys64/tmp/main.o:main.cpp:(.rdata+0x0):
 multiple definition of `vtable for fmt::detail::file_buffer@fmt';
 E:/msys64/tmp/fm.o:fmt.pcm:(.rdata+0x0): first defined here
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
The compiler seems to place a 2nd copy of the v-table of non-exported `class file_buffer final : public buffer<char>` with non-exported polymorphic base `template<typename T> class buffer` into the object files. That class `file_buffer` is a member of exported `class ostream`.

Compiling `os.cpp` in the second line (above) is _not_ necessary to trigger the issue. It's just a further complication because it emits a _different_ v-table of the same classes, but this time attached to the global module rather than module fmt.

Compilation succeeds if optimization is disabled by `-O0`. 🎉

(Only for reference: MSVC is compiling this example and mentioned test suite just fine.)

[repro.zip](https://github.com/llvm/llvm-project/files/11361505/repro.zip)

**Comment by DanielaE** [comment]
BTW: the issue is still present in Clang 17.

**Comment by AaronBallman** [comment]
CC @ChuanqiXu9

**Comment by ChuanqiXu9** [comment]
I feel like this is a duplication of https://github.com/llvm/llvm-project/issues/61940, which is a ABI issue. I guess you can fix (workaround) the problem by adding an `inline` specifier to the definition of the destructor of `file_buffer`. Feel free to reopen this if it is not the case.

**Comment by DanielaE** [comment]
Thanks for looking into this!

I'm pretty sure @vitaut made the destructor non-inline for a reason (most likely to avoid code bloat).
Besides that, the expectation is code that works in the traditional world continues to work identically in the modular world (apart from the implications that arise from the split between visibility and reachability). If there happens to be a difference you're possibly not implementing the C++ semantics correctly: `class filebuffer` and `class filebuffer@fmt` are _different entities_ with _identical behaviour_ (in this particular case) in _all aspects_.

**Comment by ChuanqiXu9** [comment]
> If there happens to be a difference you're possibly not implementing the C++ semantics correctly: class filebuffer and class filebuffer@fmt are different entities with identical behaviour (in this particular case) in all aspects.

It is true from the user's perspective (I agree with you that this is problematic too). But from the perspective of implementors, correctness need to be defined carefully. And I think the current clang's behavior matches the current wording in Itanium ABI. So one path is: check the ABI rules formally, update the rules and change the clang's behavior.
I don't mind changing clang's behavior directly for the specific case too much. But as an implementor, it is scary for me to do something different from the wording intentionally even if I have a strong feeling we're doing things right.

**Comment by dwblaikie** [comment]
This is invalid, isn't it - that the type is both defined in the module purview and outside it? The strong ownership model of modules would disallow this, right?

I thought this would potentially compile because the symbol defined/exported from the module would be distinct from the non-modular version of the type... but I guess maybe not for non-exported entities? I'm not sure/confused a bit.

**Comment by dwblaikie** [comment]
Also reduced the test case a bit: https://godbolt.org/z/G7Wr4Wcr6

**Comment by ChuanqiXu9** [comment]
> This is invalid, isn't it - that the type is both defined in the module purview and outside it? The strong ownership model of modules would disallow this, right?

The private module fragment should be a part of the module purview too according to http://eel.is/c++draft/module#unit-5.

> Also reduced the test case a bit: https://godbolt.org/z/G7Wr4Wcr6

Thanks. But it lacks an #ifdef. Here is the reproducer for the issue: https://godbolt.org/z/466zas8bG. Now I am sure this is a duplication of https://github.com/llvm/llvm-project/issues/61940

**Comment by DanielaE** [comment]
@dwblaikie : the PMF _is_ part of the module purview. Entities declared in there are also attached to the module.

But different attachment is besides the point here: the issue doesn't require to involve `class filebuffer` from the additional TU `os.cpp` (compiled in traditional mode) at all, it manifests with `class filebuffer@fmt` from TU `fmt.cppm` alone just the same.
(And yes, you _can_ have entities with the _same name_ but attached to _different modules_ (including the global module) in a program as long as they are used _in different TUs_ of that program. That's one of the benefits of strong module ownership.)

Did you consider this particular and important info _"Compilation succeeds if optimization is disabled by -O0. 🎉"_ from my initial post?

So, the situation is best summarized as:

- compiled in traditional mode, without optimization: compiles
- compiled in traditional mode, with optimization: compiles
- compiled as named module, without optimization: compiles 🚀
- compiled as _named module, with optimization_: **doesn't** compile 😭

**Comment by ChuanqiXu9** [comment]
Oh, I didn't recognize you compile and link `os.cpp` standalone. Now I think this example is invalid. This is different from our reproducer in the godbolt.

> (And yes, you can have entities with the same name but attached to different modules (including the global module) in a program as long as they are used in different TUs of that program. That's one of the benefits of strong module ownership.)

No, the non-inline external entities with the same name appears in different TUs are not allowed for sure. They may compile but it is not legal. See http://eel.is/c++draft/basic.def.odr#14. And specifically according to http://eel.is/c++draft/basic.def.odr#14.3, the original example is invalid in the language level.

BTW, it happens sometimes that some invalid things compiles (and even works). For example, there have been rules about ODR for a long time. But the compiler frontend are not good for ODR detection really. So we depends on the linker to perform some little ODR violation detections. But that doesn't always works.

**Comment by DanielaE** [comment]
Please forget about the separate TU `os.cpp` from my initial post. Strike it from your mind. It was a bad idea to even include it in my example. Now that the whole alleged ODR issue (that I don't even want to discuss here, we may discuss it elsewhere if you like) is hopefully gone, let's concentrate on the single entitity `class filebuffer@fmt` and the real issue.

The code is perfectly valid.
The issue is all (and only) about my summary from two posts earlier.

**Comment by ChuanqiXu9** [comment]
Oh, it is confusing. For the issue in our Godbolt's reproducer, the issue in the compiler's perspective is how to handle the linkage of virtual table. When the virtual functions are not inline, the linkage of the virtual function will be `dso_local`. This matches the existing ABI behavior. Clearly it doesn't work well after we introduced modules. But we need to check the ABI standard before we do anything in the compiler side. 

And I feel the optimization related result is a noise simply.

**Comment by DanielaE** [comment]
At least it served well to exhibit the issue 😊

**Comment by ChuanqiXu9** [comment]
Reopening this although https://github.com/llvm/llvm-project/issues/61940 got closed. Since I find it is tricky that this bug report comes from windows. And itanium ABI doesn't apply to windows...
