### ISSUE TITLE
`strtoll` undefined

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35197]
|  |  |
| --- | --- |
| Bugzilla Link | [35849](https://llvm.org/bz35849) |
| Version | 3.5 |
| OS | FreeBSD |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DimitryAndric |

## Extended Description 
Somebody riddle me this: ever since 3.5.0 llvm+cfe doesn't build on FreeBSD 8.4. Due to this:
```
[  5%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/TGLexer.cpp.o
/data/nfs/tgp/src/llvm-3.5.0.src/lib/TableGen/TGLexer.cpp: In member function 'llvm::tgtok::TokKin
/data/nfs/tgp/src/llvm-3.5.0.src/lib/TableGen/TGLexer.cpp:392:19: error: 'strtoll' was not declare
      CurIntVal = strtoll(NumStart, nullptr, 16);
                  ^~~~~~~
```
But earlier in the output there's this:
```
-- Looking for strtoll
-- Looking for strtoll - found
```
So what gives? I've tried all GCC from 4 to 7.2.0.

LLVM+CFE 3.4.2 builds OK.

**Comment by Endilll** [comment]
Both LLVM 3.5 and FreeBSD 8.4 are too old at this point. Feel free to reopen if it still reproduces on modern versions of LLVM and FreeBSD.
