### ISSUE TITLE
Failed to build llvm using i686-w64-mingw32-gcc 9.3

### ISSUE THREAD

**Issue by fanghuaqi** [llvm/llvm-project#121090]
Hi there,

I tried to build llvm 19.x using i686-w64-mingw32-gcc, but met with following bug, see

```
[  1%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/raw_socket_stream.cpp.obj
/work/llvm/llvm/lib/Support/raw_socket_stream.cpp:34:10: fatal error: afunix.h: No such file or directory
   34 | #include <afunix.h>
      |          ^~~~~~~~~~
compilation terminated.
```

I cannot find this header file in `/usr/i686-w64-mingw32/include`, it seems this is introduced by https://github.com/llvm/llvm-project/pull/73603 , so is it not possible to cross build llvm windows in a linux machine using this 9.3 version of gcc? How should I do to make it work.

Thanks

**Comment by fanghuaqi** [comment]
I can work around it by add a new file called `llvm/lib/Support/afunix.h` copy from https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-headers/include/afunix.h for above mingw gcc 9.3 in ubuntu 20.04.
