### PR TITLE
[Clang] [Sema] Handle `this` in `__restrict`-qualified member functions properly

### LINKED ISSUE #18121: member function `void foo() __restrict__;` incorrectly applies restrict to type, not pointer
|  |  |
| --- | --- |
| Bugzilla Link | [17747](https://llvm.org/bz17747) |
| Version | trunk |
| OS | Linux |
| CC | @majnemer,@DougGregor,@imallett,@rnk |

## Extended Description 
struct Foo {
  void member() __restrict__ {
    Foo *__restrict__ This = this;
  }
};

Clang gives the diagnostic:

test.cpp:3:23: error: cannot initialize a variable of type 'Foo *restrict' with
      an rvalue of type 'restrict Foo *'
    Foo *__restrict__ This = this;
                      ^      ~~~~
1 error generated.

Clang seems to think that `this` has type `restrict Foo *` (restrict on Foo, rather than the pointer)

The GCC extension says:

<http://gcc.gnu.org/onlinedocs/gcc/Restricted-Pointers.html#Restricted-Pointers>

"Within the body of T::fn, this has the effective definition T *__restrict__ const this."

### LINKED ISSUE #82941: "1st argument ('__restrict int') would lose restrict qualifier" when passing (this restrict *)->int to int& argument
```cpp
void f(int& x) {
    (void)x;
}

class C {
    int x;
    void g() __restrict;
};

void C::g() __restrict {
    f(this->x);
}
```
(same for `void f(int const& x)`) compiles fine on GCC, but Clang 17 and 19.0.0 (++20240212105217+93cdd1b5cfa3-1\~exp1\~20240212225341.524) rejects it with
```
a.cpp:11:5: error: no matching function for call to 'f'
   11 |     f(this->x);
      |     ^
a.cpp:1:6: note: candidate function not viable: 1st argument ('__restrict int') would lose restrict qualifier
    1 | void f(int& x) {
      |      ^ ~~~~~~
1 error generated.
```

I don't think this is valid – this looks like `this` is of type `C restrict *`, and thus `x` is compatible with `int restrict &`, and it's treating restrict like a cv-qualifier, which I don't think it is (and isn't for pointers), and even if it were I haven't found a position where you *could* make f take an `int restrict &`.

### PR DESCRIPTION
**Pull request by Sirraide**
When resolving the type of `this` inside a member function, we were attaching all qualifiers present on the member function to the class type and then making it a pointer; however, `__restrict`, unlike `const` and `volatile`, needs to be attached to the pointer type rather than the pointee type.

This fixes #82941, #42411, and #18121.

### CODE REVIEW

**Comment by Sirraide** [comment]
CC @shafik, @AaronBallman

**Review by AaronBallman — APPROVED** [review]
Thank you for the fix! This seems to fix quite a few issues because it also addresses:

https://github.com/llvm/llvm-project/issues/42411
https://github.com/llvm/llvm-project/issues/18121
https://github.com/llvm/llvm-project/issues/11039

(which should be added to test cases if there's something unique there, and mentioned in the release notes and commit message).

Otherwise, LGTM!

**Comment by Sirraide** [comment]
> Thank you for the fix! This seems to fix quite a few issues because it also addresses:
> 
> #42411 #18121 #11039

I also checked for other open issues, but I see you were more successful than me in finding some; I’ll take a look at those and add tests for them as well.

**Comment by Sirraide** [comment]
> #11039

It does not fix this one because whereas GCC supports this, we don’t:
```c++
struct foo {
    void f();
};

void foo::f() __restrict {

}
```
because `__restrict` here is treated like `const`, so it has to be present on both the declaration and definition; however, GCC accepts this; should we do so as well?

The other two issues seem to be fixed by this, though.

**Comment by Sirraide** [comment]
> > however, GCC accepts this; should we do so as well?
> 
> If so, should that be a separate pr, perhaps?

@AaronBallman If you think it’s related enough I can look into this as well for this pr; otherwise, I’m gonna go ahead and merge this one and then probably look into that next because it would make sense to support that imo if it’s not too complicated to implement.

**Review by AaronBallman — APPROVED** [review]
LGTM! I think the other work should be done in a follow-up patch as it is slightly different than this fix.
