### PR TITLE
[libc++] Re-enable the clang_modules_include test for Objective-C++

### PR DESCRIPTION
**Pull request by ldionne**
This reverts commit aa60b2687, which was a temporary workaround.
The underlying issue was fixed in Clang via c2c840bd92cf.

This was originally https://reviews.llvm.org/D158694.

### CODE REVIEW

**Comment by ldionne** [comment]
@mordante I'm not certain what's going on here, I get

```
[...]/clang_modules_include.gen.py/__std_clang_module.compile.pass.mm:22:2: error: import of module 'std' imported non C++20 importable modules
   22 | @import std;
      |  ^
1 error generated.
```

Can you assist? It only happens with Clang trunk.

**Comment by mordante** [comment]
> @mordante I'm not certain what's going on here, I get
> 
> ```
> [...]/clang_modules_include.gen.py/__std_clang_module.compile.pass.mm:22:2: error: import of module 'std' imported non C++20 importable modules
>    22 | @import std;
>       |  ^
> 1 error generated.
> ```
> 
> Can you assist? It only happens with Clang trunk.

I tested this locally and indeed it works with clang-17 and fails with clang-18

@ChuanqiXu9 This seems to be introduced in 574ee1c02ef73b66c5957cf93888234b0471695f.

This test uses a Objective-C++ file. Is it easy for you to fix or should I file a bug report?

**Comment by ChuanqiXu9** [comment]
> https://reviews.llvm.org/D158694

The motivation of my change is that I find multiple people are trying to fake `import std` from clang modules. This is not wanted. So I tried to ban it. I'll try to fix it or revert it later today if I didn't.

**Comment by ChuanqiXu9** [comment]
I tried to fix this in https://github.com/llvm/llvm-project/commit/c2c840bd92cfac155f6205ff7505b109b301d389. Sorry for disturbing.

**Comment by mordante** [comment]
> I tried to fix this in [c2c840b](https://github.com/llvm/llvm-project/commit/c2c840bd92cfac155f6205ff7505b109b301d389). Sorry for disturbing.

Thanks for the quick fix! I've tested the fix with this patch locally and it passes.

**Comment by ldionne** [comment]
Thanks folks! I rebased and I'm re-running the CI. I'll merge once it's green.

**Comment by ldionne** [comment]
I rebased again. Last time I rebased there was still the same Clang issue.

**Comment by mordante** [comment]
> I rebased again. Last time I rebased there was still the same Clang issue.

I guess nobody ever updated our Docker image. I want to look at that soon so we can start testing LLVM-19 in the CI.

**Comment by ldionne** [comment]
Merging since the relevant tests have passed.
