### ISSUE TITLE
/usr/ports/devel/llvm-devel/work-default/llvm-project-9d1bcb70ec8830ad85c0756a03022d3811537284/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_freebsd.cpp:569:1: error: static assertion failed due to requirement 'sizeof(__sanitizer::__sanitizer_cpuset) >= sizeof(_cpuset)':

### ISSUE THREAD

**Issue by pkubaj** [llvm/llvm-project#63485]
17.0.d20230622 (from devel/llvm-devel port) currently fails to build on FreeBSD 14.0-CURRENT on powerpc64* platforms with:
```console
/usr/ports/devel/llvm-devel/work-default/llvm-project-9d1bcb70ec8830ad85c0756a03022d3811537284/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_freebsd.cpp:569:1: error: static assertion failed due to requirement 'sizeof(__sanitizer::__sanitizer_cpuset) >= sizeof(_cpuset)':
COMPILER_CHECK(sizeof(__sanitizer_cpuset_t) >= sizeof(cpuset_t));
^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/devel/llvm-devel/work-default/llvm-project-9d1bcb70ec8830ad85c0756a03022d3811537284/compiler-rt/lib/sanitizer_common/sanitizer_internal_defs.h:350:30: note: expanded from macro 'COMPILER_CHECK'
#define COMPILER_CHECK(pred) static_assert(pred, "")
                             ^             ~~~~
/usr/ports/devel/llvm-devel/work-default/llvm-project-9d1bcb70ec8830ad85c0756a03022d3811537284/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_freebsd.cpp:569:45: note: expression evaluates to '32 >= 128'
COMPILER_CHECK(sizeof(__sanitizer_cpuset_t) >= sizeof(cpuset_t));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/usr/ports/devel/llvm-devel/work-default/llvm-project-9d1bcb70ec8830ad85c0756a03022d3811537284/compiler-rt/lib/sanitizer_common/sanitizer_internal_defs.h:350:44: note: expanded from macro 'COMPILER_CHECK'
#define COMPILER_CHECK(pred) static_assert(pred, "")
                                           ^~~~
1 error generated.
```

**Comment by VoxSciurorum** [comment]
FreeBSD recently increased the size of cpuset_t from 256 to 1024, encoded in the macro CPU_MAXSIZE which you get if you include <sys/cpuset.h>.   This is only in the latest development version of FreeBSD 14.  It is not in any released version.

**Comment by VoxSciurorum** [comment]
This fixes the compilation error.  I have not tested the resulting sanitizer libraries.

[cpuset.diff.txt](https://github.com/llvm/llvm-project/files/11873287/cpuset.diff.txt)
