### PR TITLE
[MLIR] Enabling Intel GPU Integration.

### PR DESCRIPTION
**Pull request by silee2**
MLIR currently doesn't have a gpu runtime for Intel GPU. 
This PR adds components required to enable lowering from GPU dialect and execute on Intel GPU including a new Sycl runtime wrapper.

**List of changes:**
- Add new runtime wrapper library mlir_sycl_runtime that is used along with gpu-to-llvm pass
- Update gpu-to-llvm pass to support host shared memory allocation and address limitations from using spirv binary blob. Spirv blob does not have size embedded and size information has to be passed separately. Also number of parameters need to be passed as an additional argument then doing a kernel launch.
- Add new bool pass option "use-opencl" to convert-gpu-to-spirv pass for OpenCL
- Add gpu-serialize-to-spirv pass that wraps spirv serializer as a pass
- Add cmake modules, FindSyclRuntime.cmake and FindLevelZero.cmake that helps find sycl runtime and level zero runtime. They are required for building sycl runtime wrapper. 
- Add unit test for serializer pass
- Add GPU/Sycl Integration test

This PR is monolithic for now and will be broken down to smaller pieces as needed.

**Integration workflow:**
GPU dialect lowering and execution workflow for Intel GPU added by this PR works as follows. It is similar to CUDA and ROCm workflow but uses spirv dialect for device code IR instead of llvm dialect.

Device code is lowered from gpu.func to spirv dialect using existing convert-gpu-to-spirv pass.
Then gpu-serialize-to-spirv pass is called to serialize spirv and attach serialized binary blob as an attribute to gpu.module
Host code is lowered by gpu-to-llvm pass and gpu dialect ops are converted in to llvm calls to various entries in the sycl runtime wrapper.
The resulting lowered code from both host and device code is now entirely in LLVM dialect and that is piped into mlir-cpu-runner for JIT execution with sycl runtime wrapper loaded as a shared library.

**Limitations:**
Sycl runtime wrapper in the PR is an initial version and does not implement all entries supported by CUDA and ROCm.
Intel GPU's share local memory is not supported.
Bare pointers are used for passing parameters to device kernels and lacks support for handling dynamic shaped memrefs.

### CODE REVIEW

**Comment by Jianhui-Li** [comment]
@rengolin  @joker-eph  @Hardcode84  

FYI that this PR enables the current GPU dialect on Intel GPU as is, without introducing stream/queue to the current GPU dialect.

**Comment by Hardcode84** [comment]
I suggest to extract `mgpu` interface changes and `serializetoSpirv` pass to 2 separate PRs.

**Comment by silee2** [comment]
> I suggest to extract `mgpu` interface changes and `serializetoSpirv` pass to 2 separate PRs.

Agree. And the changes are originally from different authors so should be splitted.

File: mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+    for (mlir::gpu::GPUModuleOp gpuMod : mod.getOps<gpu::GPUModuleOp>()) {
+      auto name = gpuMod.getName();
+      // check that the spv module has the same name with gpu module except the
+      // prefix "__spv__"
+      auto isSameMod = [&](spirv::ModuleOp spvMod) -> bool {
+        auto spvModName = spvMod.getName();
+        return spvModName->consume_front("__spv__") && spvModName == name;
+      };
+      auto spvMods = mod.getOps<spirv::ModuleOp>();
+      auto it = llvm::find_if(spvMods, isSameMod);
```
Comment (joker-eph) [inline mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp:45]: This is really costly, can you build a symbol table once at the beginning of the function and use it for the queries instead?

File: mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+      // attach the spv binary to the gpu module
+      auto spvData =
+          llvm::StringRef(reinterpret_cast<const char *>(spvBinary.data()),
+                          spvBinary.size() * sizeof(uint32_t));
+      auto spvAttr = mlir::StringAttr::get(&getContext(), spvData);
+      gpuMod->setAttr(gpu::getDefaultGpuBinaryAnnotation(), spvAttr);
+      spvMod->erase();
+    }
+  }
+};
```
Comment (joker-eph) [inline mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp:70]: @fabianmcg : how would that fit in the new serialization flow?

File: mlir/lib/Conversion/GPUToSPIRV/GPUToSPIRVPass.cpp [hunk 3]
```diff
@@ -71,7 +71,8 @@ void GPUToSPIRVPass::runOnOperation() {
       std::unique_ptr<ConversionTarget> target =
           spirv::getMemorySpaceToStorageClassTarget(*context);
       spirv::MemorySpaceToStorageClassMap memorySpaceMap =
-          spirv::mapMemorySpaceToVulkanStorageClass;
+          this->useOpenCL ? spirv::mapMemorySpaceToOpenCLStorageClass :
+              spirv::mapMemorySpaceToVulkanStorageClass;
```
Comment (joker-eph) [inline mlir/lib/Conversion/GPUToSPIRV/GPUToSPIRVPass.cpp:75]: Can you point out which unit-test is covering this? Can you send this in a separate PR?

File: mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp [hunk 4]
```diff
@@ -1158,7 +1178,7 @@ LogicalResult ConvertLaunchFuncOpToGpuRuntimeCallPattern::matchAndRewrite(
       {function.getResult(), adaptor.getGridSizeX(), adaptor.getGridSizeY(),
        adaptor.getGridSizeZ(), adaptor.getBlockSizeX(), adaptor.getBlockSizeY(),
        adaptor.getBlockSizeZ(), dynamicSharedMemorySize, stream, kernelParams,
-       /*extra=*/nullpointer});
+       /*extra=*/nullpointer, paramsCount});
```
Comment (joker-eph) [inline mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp:1181]: I see a unit-test for this: but can you send everything related, but can you send everything related to paramsCount in a separate PR?

File: mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp [hunk 5]
```diff
@@ -811,8 +812,13 @@ LogicalResult ConvertAllocOpToGpuRuntimeCallPattern::matchAndRewrite(
...
   Type elementPtrType = this->getElementPtrType(memRefType);
   auto stream = adaptor.getAsyncDependencies().front();
+
+  auto isHostShared = rewriter.create<mlir::LLVM::ConstantOp>(
+      loc, llvmInt64Type, rewriter.getI64IntegerAttr(isShared));
+
   Value allocatedPtr =
-      allocCallBuilder.create(loc, rewriter, {sizeBytes, stream}).getResult();
+      allocCallBuilder.create(loc, rewriter, {sizeBytes, stream, isHostShared})
+          .getResult();
```
Comment (joker-eph) [inline mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp:821]: I see a unit-test for this: but can you send everything related to `isHostShared` in a separate PR?

**Review by joker-eph — COMMENTED** [review]
LGTM overall, this should likely get reviewed by @antiagainst / @kuhar ; and it's be great if you can split the independent changes and send them ahead of the e2e integration.

File: mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+      auto it = llvm::find_if(spvMods, isSameMod);
+      if (it == spvMods.end()) {
+        gpuMod.emitError() << "Unable to find corresponding SPIR-V module";
+        signalPassFailure();
+        return;
+      }
+      auto spvMod = *it;
+
+      spvBinary.clear();
+      // serialize the spv module to spv binary
```
Comment (keryell) [inline mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp:54]:
```suggestion
      // serialize the SPIR-V module to SPIR-V binary
```
everywhere.

**Review by keryell — COMMENTED** [review]
Quite interesting!
At some point it would be nice to have some design document or documentation somewhere explaining how all these MLIR runners works, including this one.
Globally this PR add a SYCL runner, but it is very specific for Intel Level 0.
It would be nice to have in the future some generalization, like SYCL using OpenCL interoperability interface to run the SPIR-V kernels or even native kernels.

File: mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp (hunk 5 above)
Comment (grypp) [reply mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp:821]: Regarding `host_shared`, I noticed this code in the examples:

```
%memref, %asyncToken = gpu.alloc async [%0] host_shared (): memref<3x3xi64>
```

Can SYCL's runtime allocate `host_shared` data asynchronously? It might be a good idea to prevent the use of `host_shared` and `async` together. FWIW, CUDA and HIP cannot do that. As far as I can see from the PR, the queue is not used when allocating `host_shared`.

Nonetheless, having `async` on `gpu.alloc` is perfectly acceptable. CUDA does support asynchronous device memory allocation.

**Comment by rengolin** [comment]
> At some point it would be nice to have some design document or documentation somewhere explaining how all these MLIR runners works, including this one.

The idea is to eventually consolidate all runners into one. This PR is just another piece of the puzzle.

Once we're all happy with how the runners work, we should common them up using command line options to select the "type" and CMake options to enable particular runner types (depending on the runtimes and hardware available).

> Globally this PR add a SYCL runner, but it is very specific for Intel Level 0. It would be nice to have in the future some generalization, like SYCL using OpenCL interoperability interface to run the SPIR-V kernels or even native kernels.

Agreed! The SYCL runtime here is just being used to abstract the LevelZero calls, but this work will be helpful when adding a full SYCL runner (actual language extensions and libraries) to other CPUs/GPUs later.

**Comment by rengolin** [comment]
CI failure looks like Buildkite issue?
```
$ /etc/buildkite-agent/hooks/pre-checkout
--
  | BUILDKITE_REPO: https://github.com/llvm/llvm-project.git
  | fatal: not a git repository (or any parent up to mount point /var/lib)
  | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  | 🚨 Error: The global pre-checkout hook exited with status 128
```

**Comment by Jianhui-Li** [comment]
> > At some point it would be nice to have some design document or documentation somewhere explaining how all these MLIR runners works, including this one.
> 
> The idea is to eventually consolidate all runners into one. This PR is just another piece of the puzzle.
> 
> Once we're all happy with how the runners work, we should common them up using command line options to select the "type" and CMake options to enable particular runner types (depending on the runtimes and hardware available).
> 
> > Globally this PR add a SYCL runner, but it is very specific for Intel Level 0. It would be nice to have in the future some generalization, like SYCL using OpenCL interoperability interface to run the SPIR-V kernels or even native kernels.
> 
> Agreed! The SYCL runtime here is just being used to abstract the LevelZero calls, but this work will be helpful when adding a full SYCL runner (actual language extensions and libraries) to other CPUs/GPUs later.

Agree. The key point of this PR is not to create yet another runner, but just enable the existing mlir-cpu-runner to runs llvm + device kernel on SYCL platform. The current implementation uses L0 but could be extended. 

I won't call this as adding a "SYCL runner", it is add SYCL backend to mlir-cpu-runner.  The term "xxx runner" in MLIR is a bit overused. mlir-cpu-runner doesn't mean it runs only on CPU, instead it runs both the host and device kernel.   mlir-cpu-runner currently does that but the name is a bit misleading.  We really just need a "mlir-runner" with target-platform as command parameters.

File: mlir/lib/ExecutionEngine/SyclRuntimeWrappers.cpp [hunk 7]
```diff
@@ -0,0 +1,223 @@
...
+    if (!isLevelZero)
+      continue;
+
+    return platform.get_devices()[0];
+  }
+  throw std::runtime_error("getDefaultDevice failed");
+}
+
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wglobal-constructors"
```
Comment (joker-eph) [inline mlir/lib/ExecutionEngine/SyclRuntimeWrappers.cpp:80]: I don't think we have this anywhere in the codebase right now, can you remove it and use lazy initialization instead?

**Comment by joker-eph** [comment]
> I won't call this as adding a "SYCL runner", it is add SYCL backend to mlir-cpu-runner. The term "xxx runner" in MLIR is a bit overused. mlir-cpu-runner doesn't mean it runs only on CPU, instead it runs both the host and device kernel. mlir-cpu-runner currently does that but the name is a bit misleading. 


This naming stems originally that there was a `mlir-cuda-runner` which was actually implementing some “complex logic” that goes beyond just translating to LLVM and setting up the environment: they take an input in higher-level dialects (func+arith+gpu+…) and perform all the lowering. 
We killed it to merge it into mlir-cpu-runner: [⚙ D98396 [mlir] Remove mlir-cuda-runner](https://reviews.llvm.org/D98396)
This means that all the "target specific" transformation are done with `mlir-opt` (or other tools) and `mlir-cpu-runner` is a "host" entry point without any complex logic: it won't do other transformation on the IR and just setup the JIT, load some runtime, and invoke the code through the LLVM JIT infra.
(this PR follows this model, and it's great!)

Vulkan and Spirv still have dedicated runners on the model of the original cuda-runner, but I suspect this is just legacy?

> We really just need a "mlir-runner" with target-platform as command parameters.

What kind of "target-platform" command parameters do you have in mind? (other than what we do now)

File: mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp (hunk 2 above)
Comment (joker-eph) [reply mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp:70]: Awesome! @silee2 : can you adjust in this direction? I'm sure Fabian can support you if you have more questions!

Comment (fabianmcg) [reply mlir/lib/Dialect/GPU/Transforms/SerializeToSPIRV.cpp:70]: @silee2 here are the steps:
1. Implement a target attribute, see for example: [NVVMTargetAttr](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/LLVMIR/NVVMOps.td#L1679-L1741). The idea of this attribute is to hold properties intrinsic to the target, like triple, chip, flags, etc.
2.  Add a pass to attach the target to a module, see: [GpuNVVMAttachTarget](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/GPU/Transforms/Passes.td#L85-L128) and [Dialect/GPU/Transforms/NVVMAttachTarget.cpp](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/GPU/Transforms/NVVMAttachTarget.cpp). The idea of this pass is to attach the SPIRV target to GPU modules, so it must know how to create them.
3. We're currently implementing `TargetAttrs` as external models to keep libraries separated, see [NVVM/Target.cpp](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Target/LLVM/NVVM/Target.cpp#L44-L50), so `GpuSerializeToSPIRVPass::run` would be there.
4. Modify `getModuleLoadFn` & `createKernelLaunch` appropriately in [SelectObjectAttr.cpp#L125-L15](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Target/LLVMIR/Dialect/GPU/SelectObjectAttr.cpp#L125-L152) instead of adding the changes in `GPUToLLVMCommon`.
5. Then the compilation workflow should look something similar to this: [GPU: Compilation Overview](https://mlir.llvm.org/docs/Dialects/GPU/#compilation-overview)

I'll take care of adding a pointer to the top module symbol table so it can be used be the `SPIRVTarget`.

If you have any questions just ping me in discord or discourse `@fabianmc`.

File: mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp (hunk 5 above)
Comment (keryell) [reply mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp:821]: Technically, SYCL provides a more abstract memory management with `sycl::buffer` and `sycl::accessor` defining an implicit asynchronous task graph. The allocation details are left to the implementation, asynchronous or synchronous allocation is left to the implementers.
Here the lower-level synchronous USM memory management API of SYCL is used instead, similar to CUDA/HIP memory management.
So, should the `async` allocation in the example be synchronous instead?

**Comment by Jianhui-Li** [comment]
> > We really just need a "mlir-runner" with target-platform as command parameters.
> 
> What kind of "target-platform" command parameters do you have in mind? (other than what we do now)

The current way of mlir-cpu-runner using the share library name to indicate target-platform looks good to me: Cuda, Rocm, and SYCL with this PR.  Vulkan could be added same way.  mlir-cpu-spirv-runner could be refactored to be mlir-opt passes generating spirv binary and feed to mlir-cpu-runner.  

If we reach that state, the name "mlir-cpu-runner" could be promoted to "mlir-runner". That would clear up a lot of misunderstanding.  The "mlir-runner" is really running MLIR programs on a target platform, and has little to do with enabling specific language or runtime features of a target platform.  For example, we say "SYCL runner", people think it is about running SYCL program on top of MLIR.

File: mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp (hunk 5 above)
Comment (grypp) [reply mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp:821]: > Technically, SYCL provides a more abstract memory management with sycl::buffer and sycl::accessor defining an implicit asynchronous task graph. The allocation details are left to the implementation, asynchronous or synchronous allocation is left to the implementers.

I haven't touched SYCL much, thanks for the explanation. Creating a task graph implicitly sounds interesting. In this case, SYCL users are ware of asynchrony while writing their program. In CUDA (or HIP), users choose sync or async execution. 

> Here the lower-level synchronous USM memory management API of SYCL is used instead, similar to CUDA/HIP memory management.

Yes that's correct. I don't think there is an USM that can do allocation asynchronously. 

> So, should the async allocation in the example be synchronous instead?

Yes, I think this is the correct behaviour. We can disallow `host_shared` and `async` on the Op. 

Here are the possible IRs: 

```
// Valid
%memref = gpu.alloc host_shared (): memref<3x3xi64>

// Valid
%memref = gpu.alloc (): memref<3x3xi64>

// Invalid, USM managers don't allocate async  
%memref, %asyncToken = gpu.alloc async [%0] host_shared (): memref<3x3xi64>

// Valid, only for CUDA. Afaik, SYCL or HIP cannot do that
%memref, %asyncToken = gpu.alloc async [%0] (): memref<3x3xi64>
```

Comment (nbpatel) [reply mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp:821]: the upstream GPUToLLVMConversion lowering does not support lowering of gpu.alloc which is not async? 
https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp#L797

Comment (keryell) [reply mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp:821]: I guess that if the runtime uses actually synchronous allocation behind the scene and produces an always-ready async token, it works, even if non optimal.

Comment (grypp) [reply mlir/lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp:821]: > the upstream GPUToLLVMConversion lowering does not support lowering of gpu.alloc which is not async.

Would that work if omit that check when `host_shared` is present?

File: mlir/lib/Conversion/GPUToSPIRV/GPUToSPIRVPass.cpp (hunk 3 above)
Comment (silee2) [reply mlir/lib/Conversion/GPUToSPIRV/GPUToSPIRVPass.cpp:75]: Created #66445 which includes the code change and unit-test for covering.

**Comment by silee2** [comment]
Closing as all sub-components has been merged.

File: mlir/include/mlir/Dialect/GPU/Transforms/Passes.td [hunk 8]
```diff
@@ -187,4 +187,8 @@ def GpuROCDLAttachTarget: Pass<"rocdl-attach-target", ""> {
   ];
 }
 
+def GpuSerializeToSPIRVPass : Pass<"gpu-serialize-to-spirv", "ModuleOp"> {
+  let summary = "Serialize spirv dialect to spirv binary";
```
[the remark this answers is not in the document]
Comment (jbrodman) [reply mlir/include/mlir/Dialect/GPU/Transforms/Passes.td:191]: Missing a space?
