### ISSUE TITLE
[flang][runtime] compilation error on the flang-rt for cuda

### ISSUE THREAD

**Issue by Nir-Cohen-2003** [llvm/llvm-project#160534]
I'm facing problems with compiling the flang-rt for cuda.
I'm working on version 21.1.2, though the most recent commit had the same problems.
I'm working based on the instructions here [https://flang.llvm.org/docs/GettingStarted.html#cuda-build](url) and building "out of tree" (though building "in tree" had the same error messages). building clang and flang went without errors, as did building the flang-rt for cpus, but the cuda version gives me errors such as:
"/work/nircoh/libraries_for_parsec/llvm/source/llvm-project-21.1.2.src/flang-rt/lib/runtime/matmul-transpose.cpp:345:83: error: 
      expected '>'
  345 | return DoMatmulTranspose< IS_ALLOCATING, {GetResultType(XCAT, XKIND, YCAT, YKIND)}->first, {GetResultType(XCAT, XKIND, YCAT...
      |                                                                                   ^
/work/nircoh/libraries_for_parsec/llvm/source/llvm-project-21.1.2.src/flang-rt/lib/runtime/matmul-transpose.cpp:345:25: note: 
      to match this '<'
  345 | return DoMatmulTranspose< IS_ALLOCATING, {GetResultType(XCAT, XKIND, YCAT, YKIND)}->first, {GetResultType(XCAT, XKIND, YCAT...
      |                         ^
1 error generated.
make[3]: *** [flang-rt/lib/runtime/CMakeFiles/flang_rt.runtime.static.dir/build.make:545: flang-rt/lib/runtime/CMakeFiles/flang_rt.runtime.static.dir/matmul-transpose.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/work/nircoh/libraries_for_parsec/llvm/source/llvm-project-21.1.2.src/flang-rt/lib/runtime/matmul.cpp:445:74: error: 
      expected '>'
  445 | return DoMatmul< IS_ALLOCATING, {GetResultType(XCAT, XKIND, YCAT, YKIND)}->first, {GetResultType(XCAT, XKIND, YCAT, YKIND)}...
      |                                                                          ^
/work/nircoh/libraries_for_parsec/llvm/source/llvm-project-21.1.2.src/flang-rt/lib/runtime/matmul.cpp:445:16: note: 
      to match this '<'
  445 | return DoMatmul< IS_ALLOCATING, {GetResultType(XCAT, XKIND, YCAT, YKIND)}->first, {GetResultType(XCAT, XKIND, YCAT, YKIND)}...
      |                ^
1 error generated."
in the matmul.cpp and matmul-transpose.cpp files under flang-rt/lib/runtime/

I've tried also using clang as the cuda compiler, but it errors because of host function beign called by host/device functions, which i wasn't able to find the flag to turn off (unlike in nvcc).
Any advice or useful stuff to try?
Additional info:
My cuda toolkit is 12.6, and when using nvcc I've disabled the warning about a host compiler mismatch from nvidia, as the needed flang+cuda support doesn't exist in llvm 18, which is the most up to date version nvidia says is supported.
This is all being done on my university cluster, which runs redhat linux.

**Comment by Nir-Cohen-2003** [comment]
sorry, those: https://flang.llvm.org/docs/GettingStarted.html#cuda-build

**Comment by clementval** [comment]
Are you using clang? Are you sure it is compatible with the CUDA toolkit you are using? Have you try with gcc as the host compiler as well?

**Comment by Nir-Cohen-2003** [comment]
Clang is compatible, as clang 20 is compatible with cuda 12.6, and I'm using clang 21.
I tried using gcc, it still resulted in similar errors regarding the template.

**Comment by Nir-Cohen-2003** [comment]
a note on the template error:
I changed (with the help of Github copilot, as I lack experience with c++ templates) the templates i nthe 2 offending files, and applied those changes:
matmul.cpp:
"
// ...existing code...
    RUNTIME_CHECK(terminator,
        (xCatKind->first == XCAT && yCatKind->first == YCAT) ||
            (XCAT == TypeCategory::Integer && YCAT == TypeCategory::Integer &&
                ((xCatKind->first == TypeCategory::Integer ||
                     xCatKind->first == TypeCategory::Unsigned) &&
                    (yCatKind->first == TypeCategory::Integer ||
                        yCatKind->first == TypeCategory::Unsigned))));
    constexpr ResultTy resultType{GetResultType(XCAT, XKIND, YCAT, YKIND)};
    if constexpr (resultType) {
      return DoMatmul<IS_ALLOCATING, resultType->first, resultType->second,
          CppTypeFor<XCAT, XKIND>, CppTypeFor<YCAT, YKIND>>(
          result, x, y, terminator);
    }
// ...existing code...
"
and matmul-transpose.cpp:
"
// ...existing code...
    RUNTIME_CHECK(terminator, xCatKind->first == XCAT);
    RUNTIME_CHECK(terminator, yCatKind->first == YCAT);
    constexpr ResultTy resultType{GetResultType(XCAT, XKIND, YCAT, YKIND)};
    if constexpr (resultType) {
      return DoMatmulTranspose<IS_ALLOCATING, resultType->first,
          resultType->second, CppTypeFor<XCAT, XKIND>, CppTypeFor<YCAT, YKIND>>(
          result, x, y, terminator);
    }
// ...existing code...
"
which worked and compiled, with g++ as host compiler (haven't tested other configuration ATM, trying an in-tree build which is currently running). Haven't got the change to make sure the offloading works, due to the compiler requiring an openmp library to offload to cuda, for which I'll open a new issue. 
Now, is there some glaring issue with this change that I didn't see (due to my complete lack of knowledge in this area)? If not, I'll try to create a pull request to implement those changes.
