### ISSUE TITLE
undefined reference to `__builtin_stdarg_start' with g++-4.4.0

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#3442]
|  |  |
| --- | --- |
| Bugzilla Link | [3070](https://llvm.org/bz3070) |
| Version | unspecified |
| OS | Linux |
| CC | @isanbard |

## Extended Description 
This testcase works with g++ 4.3.2 as system compiler, but doesn't work with gcc version 4.4.0 20081114 (experimental) [trunk revision 141857]:

/home/edwin/gcc_inst/bin/gcc -I/home/edwin/llvm-svn/llvm-commit/projects/llvm-test/SingleSource/Regression/C -I/home/edwin/llvm-svn/llvm-commit/projects/llvm-test/SingleSource/Regression/C -I/home/edwin/llvm-svn/llvm-commit/include -I/home/edwin/llvm-svn/llvm-commit/projects/llvm-test/include -I../../../include -I/home/edwin/llvm-svn/llvm-commit/include -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -DNDEBUG  -O3  /home/edwin/llvm-svn/llvm-commit/projects/llvm-test/SingleSource/Regression/C/#640 .c -lm -o Output/#640 .native
/tmp/ccsk0D8r.o: In function `test_stdarg_builtin_va':
llvm/llvm-project#1012 .c:(.text+0xb1): undefined reference to `__builtin_stdarg_start'
collect2: ld returned 1 exit status
make: [Output/#640 .native] Error 1 (ignored)

**Comment by efriedma-quic** [comment]
This is all resolved, as far as I can tell.
