### PR TITLE
[libc++][test][NFC] remove unused and global variables in the test

### LINKED ISSUE #178855: [libc++][test] `-Wunused-variable` warning in thread.semaphore/lost_wakeup.timed.pass.cpp
Introduced by #172214, FYI @huixie90.

https://github.com/llvm/llvm-project/blob/369e78774aef4f576a4fce37b55b8179170ce3f8/libcxx/test/std/thread/thread.semaphore/lost_wakeup.timed.pass.cpp#L28

emits:

```
D:\GitHub\STL\llvm-project\libcxx\test\std\thread\thread.semaphore\lost_wakeup.timed.pass.cpp(28,23): error: unused variable 'b' [-Werror,-Wunused-variable]
   28 | static std::barrier<> b(num_acquirer + 1);
      |                       ^
```

This is a problem for microsoft/STL's use of the libc++ test suite because we build the tests with warnings-as-errors to be good kitties.

### PR DESCRIPTION
**Pull request by huixie90**
Fixes #178855

### CODE REVIEW

File: libcxx/test/std/thread/thread.semaphore/lost_wakeup.timed.pass.cpp [hunk 1]
```diff
@@ -14,39 +14,37 @@
...
 
 #include "make_test_thread.h"
 
-static std::counting_semaphore<> s(0);
 constexpr auto num_acquirer   = 100;
 constexpr auto num_iterations = 5000;
-static std::barrier<> b(num_acquirer + 1);
 
-void acquire() {
+void acquire(std::counting_semaphore<>& s) {
```
Comment (Thibault-Monnier) [inline libcxx/test/std/thread/thread.semaphore/lost_wakeup.timed.pass.cpp]: Why not keep `s` at the global scope?

Comment (huixie90) [reply libcxx/test/std/thread/thread.semaphore/lost_wakeup.timed.pass.cpp]: I don't think global variables are any good. If one day, these classes become `constexpr`, global variables will just make the test harder to become `constexpr`

**Review by Thibault-Monnier — APPROVED** [review]

**Review by philnik777 — COMMENTED** [review]
While I'm fine with this in general, I do feel like the title doesn't really reflect the changes in the tests. The actual changes are much more than just removing an unused variable. That seems to be more of a side effect at this point.

**Review by ldionne — APPROVED** [review]
