### PR TITLE
[OpenCL] Disable __opencl_c_ext_fp64_* features if cl_khr_fp64 is not supported

### PR DESCRIPTION
**Pull request by wenju-he**
Fix kernel build when cl_khr_fp64 is not enabled:
opencl-c.h:13785:50: error: unknown type name 'atomic_double'
 13785 | double __ovld atomic_fetch_min(volatile __global atomic_double *, double);
opencl-c.h:13785:67: error: use of type 'double' requires cl_khr_fp64 and __opencl_c_fp64 support
 13785 | double __ovld atomic_fetch_min(volatile __global atomic_double *, double);

This is a regression introduced by 423bdb2b. Before that commit, __opencl_c_ext_fp64_global_atomic_add was guarded by cl_khr_fp64 in opencl-c-base.h.

### CODE REVIEW

File: clang/lib/Headers/opencl-c.h [hunk 1]
```diff
@@ -13781,6 +13781,7 @@ float __ovld atomic_fetch_max_explicit(volatile atomic_float *,
     defined(__opencl_c_ext_fp32_local_atomic_min_max)
 
 #if defined(cl_khr_int64_base_atomics) && defined(cl_khr_int64_extended_atomics)
+#ifdef cl_khr_fp64
 #if defined(__opencl_c_ext_fp64_global_atomic_min_max)
```
Comment (bader) [inline clang/lib/Headers/opencl-c.h]: Interesting... maybe `__opencl_c_ext_fp64_global_atomic_min_max` should not be defined if `cl_khr_fp64` is not supported.

**Review by bader — APPROVED** [review]
Thanks. 
Looks good to me, but I'd like to know what @svenvh thinks.

**Review by svenvh — APPROVED** [review]
