### PR TITLE
[flang] add fir.box_offset operation

### PR DESCRIPTION
**Pull request by jeanPerier**
This operation allows computing the address of descriptor fields. It is needed to help attaching descriptors in OpenMP/OpenACC target region. The pointers inside the descriptor structure must be mapped too, but the fir.box is abstract, so these fields cannot be computed with fir.coordinate_of.

To preserve the abstraction of the descriptor layout in FIR, introduce an operation specifically to !fir.ref<fir.box<>> address fields based on field names (base_addr or derived_type).

### CODE REVIEW

File: flang/test/Fir/box-offset-codegen.fir [hunk 1]
```diff
@@ -0,0 +1,44 @@
+// Test fir.box_offset parse/print/parse/print identity.
+// RUN: fir-opt %s | fir-opt | FileCheck %s
```
Comment (kiranchandramohan) [inline flang/test/Fir/box-offset-codegen.fir:2]: I guess you meant this to be a codegen and not parse/print test.

**Review by kiranchandramohan — APPROVED** [review]
Thanks @jeanPerier for this helpful operation.

I have one comment about the test.

**Review by tblah — COMMENTED** [review]
LGTM with one nit. Please add the correct codegen test as Kiran mentioned.

**Review by agozillon — APPROVED** [review]
LGTM, thank you very much for your help and hard work on this patch!

**Review by razvanlupusoru — APPROVED** [review]
Thank you for adding this!

**Review by clementval — APPROVED** [review]

File: flang/test/Fir/box-offset-codegen.fir (hunk 1 above)
Comment (jeanPerier) [reply flang/test/Fir/box-offset-codegen.fir]: Absolutely, thanks for the review! I updated the test with the actual codegen test.

File: flang/lib/Optimizer/CodeGen/CodeGen.cpp [hunk 2]
```diff
@@ -3656,6 +3656,27 @@ struct NegcOpConversion : public FIROpConversion<fir::NegcOp> {
...
+    mlir::Type pty = ::getLlvmPtrType(boxOffset.getContext());
+    mlir::Type boxType = fir::unwrapRefType(boxOffset.getBoxRef().getType());
+    mlir::Type llvmBoxTy =
+        lowerTy().convertBoxTypeAsStruct(mlir::cast<fir::BaseBoxType>(boxType));
+    unsigned fieldId = boxOffset.getField() == fir::BoxFieldAttr::derived_type
+                           ? getTypeDescFieldId(boxType)
+                           : kAddrPosInBox;
+    rewriter.replaceOpWithNewOp<mlir::LLVM::GEPOp>(
+        boxOffset, pty, llvmBoxTy, adaptor.getBoxRef(),
+        llvm::ArrayRef<mlir::LLVM::GEPArg>{0, fieldId});
```
Comment (psteinfeld) [inline flang/lib/Optimizer/CodeGen/CodeGen.cpp:3675]: I get a warning on this line about a narrowing conversion, and, since I build with warnings treated as errors, this breaks my build.  I build with GCC 9.3.0.

Here's the relevant text of the error message:
```
/local/home/psteinfeld/up/standalone/llvm-project/flang/lib/Optimizer/CodeGen/CodeGen.cpp: In member function ‘virtual mlir::LogicalResult {anonymous}::BoxOffsetOpConversion::matchAndRewrite(fir::BoxOffsetOp, mlir::ConvertOpToLLVMPattern<fir::BoxOffsetOp>::OpAdaptor, mlir::ConversionPatternRewriter&) const’:
/local/home/psteinfeld/up/standalone/llvm-project/flang/lib/Optimizer/CodeGen/CodeGen.cpp:3675:54: error: narrowing conversion of ‘fieldId’ from ‘unsigned int’ to ‘int32_t’ {aka ‘int’} inside { } [-Werror=narrowing]
         llvm::ArrayRef<mlir::LLVM::GEPArg>{0, fieldId});
                                                      ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-ctad-maybe-unsupported’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-deprecated-copy’ [-Werror]
cc1plus: all warnings being treated as errors
```

**Review by psteinfeld — COMMENTED** [review]
@jeanPerier, can you please look at the warning in lib/Optimizer/CodeGen/CodeGen.cpp?

File: flang/lib/Optimizer/CodeGen/CodeGen.cpp (hunk 2 above)
Comment (jeanPerier) [reply flang/lib/Optimizer/CodeGen/CodeGen.cpp:3675]: https://github.com/llvm/llvm-project/pull/73808
