### ISSUE TITLE
[flang] llvm-flang won't build with gcc 7.5.0 (minimum LLVM required gcc version)

### ISSUE THREAD

**Issue by dpalermo** [llvm/llvm-project#68593]
To build LLVM, gcc 7.5 appears to be the agreed upon minimum requirement:
https://discourse.llvm.org/t/require-gcc-7-4-as-gcc-7-3-cannot-build-llvm-16-x-or-main/72310/52

but llvm-flang has build errors when built with gcc 7.5.0 (causing problems with builds on SLES 15)

Error seen:
```
 llvm-project/flang/include/flang/Common/enum-class.h: In static member function 'static std::string_view Fortran::parser::DefinedOperator::EnumToString(Fortran::parser::DefinedOperator::IntrinsicOperator)':

 llvm-project/flang/include/flang/Parser/parse-tree.h:597:3:   in constexpr expansion of 'Fortran::common::EnumNames<17>(((const char*)(& vaArgs)))'

 llvm-project/flang/include/flang/Common/enum-class.h:51:16: error: '(((const char*)(& vaArgs)) == 0)' is not a constant expression
     } else if (!start) {
                ^~~~~~
```

**Comment by dpalermo** [comment]
Thanks Raghu!
