### PR TITLE
[compiler-rt] Fix default builtins target _Float16 detection on x86_64/i386

### PR DESCRIPTION
**Pull request by ndrewh**
This fixes errors from the following on x86 freebsd:

```
cmake -G 'Ninja' \
      -DCMAKE_BUILD_TYPE=Release \
      ../compiler-rt/lib/builtins
```

```
[2/280] Building C object CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o
FAILED: [code=1] CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o
/usr/bin/cc -DVISIBILITY_HIDDEN -I/root/llvm-project/compiler-rt/lib/builtins/../../../third-party/siphash/include -O3 -DNDEBUG -std=gnu11 -m32 -fno-lto -nostdinc++ -Wno-c2y-extensions -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -DCOMPILER_RT_HAS_FLOAT16 -MD -MT CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o -MF CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o.d -o CMakeFiles/clang_rt.builtins-i386.dir/extendhfsf2.c.o -c /root/llvm-project/compiler-rt/lib/builtins/extendhfsf2.c
In file included from /root/llvm-project/compiler-rt/lib/builtins/extendhfsf2.c:11:
In file included from /root/llvm-project/compiler-rt/lib/builtins/fp_extend_impl.inc:38:
/root/llvm-project/compiler-rt/lib/builtins/fp_extend.h:57:9: error: _Float16 is not supported on this target
   57 | typedef _Float16 src_t;
      |         ^
1 error generated.
```

Caused by #171941.

rdar://178447969

### CODE REVIEW

**Review by etcwilde — COMMENTED** [review]
This looks right. Do we have access to `${BUILTIN_CFLAGS_${arch}}`? The original code before https://github.com/llvm/llvm-project/pull/171941 also passed that as part of the `CMAKE_REQUIRED_FLAGS`.

**Comment by ndrewh** [comment]
> Do we have access to ${BUILTIN_CFLAGS_${arch}}? 

It doesn't look to me like those have been initialized yet when `builtin-config-ix` is included [at the top](https://github.com/llvm/llvm-project/blob/93e03fc2666e10b4e32091bc27d35709f49c9443/compiler-rt/lib/builtins/CMakeLists.txt#L73).

One other tricky thing about this code is that it's included by both `compiler-rt/lib/builtins/`, which sets `BUILTIN_CFLAGS_${arch}`, and `compiler-rt/test/builtins`, which does not (and currently the builtins _tests_ are included with the runtimes build, for _reasons_, see #166837) 

I don't think the extra flags should matter for the purposes of this check. Arguably, builtins-specific flags shouldn't influence a variable called `COMPILER_RT_HAS_${arch}_FLOAT16` (which seems to imply that it's compiler-rt-wide), and there's probably a case for moving this feature detection out of the builtins-specific cmake entirely.

**Review by etcwilde — APPROVED** [review]

**Review by petrhosek — APPROVED** [review]
