### ISSUE TITLE
[OpenMP] OvO breakage on NVIDIA GPUs

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#70944]
OvO failure with a396fb247e0719f56a830a9e4aab0449be7f843a but a8d0c86174b4e7355e250b3eb266e055df224f48 was good.
something happened between. Behaves the same with sm_70, sm_80, sm_86 and sm_90.

reproducer https://github.com/TApplencourt/OvO
```
$ OMP_TARGET_OFFLOAD=mandatory CXX="clang++" CXXFLAGS="-fopenmp --offload-arch=sm_80 -O3" ./ovo.sh run test_src/cpp/hierarchical_parallelism
$ ./ovo.sh report --summary  --tablefmt github
>> Overall result for test_result/2023-11-01_09-22_epyc-server
|   pass rate(%) |   test(#) |   success(#) |   compilation error(#) |   runtime error(#) |   wrong value(#) |   timeout(#) |
|----------------|-----------|--------------|------------------------|--------------------|------------------|--------------|
|          87.8% |        74 |           65 |                      0 |                  0 |                9 |            0 |

 >> Summary
| language   | category                 | name                |   pass rate(%) |   test(#) |   success(#) |   compilation error(#) |   runtime error(#) |   wrong value(#) |   timeout(#) |
|------------|--------------------------|---------------------|----------------|-----------|--------------|------------------------|--------------------|------------------|--------------|
| cpp        | hierarchical_parallelism | reduction_add-float |          87.8% |        74 |           65 |                      0 |                  0 |                9 |            0 |
```

`reduction_add-complex_double` also has 1 failure.

**Comment by ye-luo** [comment]
@jdoerfert 
66152f4eed4d5d380e199a75f861d9ea4c1d296e turns OK
and 5f5f82af966e6edcc72df02b36fb54401ab76266 is broken again.

**Comment by shiltian** [comment]
We reverted a bunch of patches about reduction. Does this issue still exist?

**Comment by ye-luo** [comment]
Good since my nightly on 573fa770d07bacd9276370454be32731fca99eea
