### PR TITLE
[Clang] Transform SubstNonTypeTemplateParmExpr replacements in a constant-evaluated context

### LINKED ISSUE #175831: [Clang] clang 22 still has problems with mp_units
Similar to #170856 Clang 22 fails with a simple example: https://godbolt.org/z/c7vE8x6Wh which is accepted by GCC and Clang 21. It was also broken by e9972debc98ce5d00db47409248bbcf06fafaf73 (#161671), but not fixed with a5bfe8e5c3c4c5bb46f53e093caf6aa01d56aeab (#172251).

The example (also used in the godbolt link):
``` c++
#include <mp-units/systems/isq/space_and_time.h>
#include <mp-units/systems/si/unit_symbols.h>
#include <mp-units/systems/si/units.h>

using namespace mp_units::si::unit_symbols;

mp_units::quantity distance = mp_units::isq::distance(5 * km);
```

The reported error:
```
<source>:7:31: error: no matching function for call to object of type 'const struct distance'
    7 | mp_units::quantity distance = mp_units::isq::distance(5 * km);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/framework/quantity_spec.h:217:41: note: candidate template ignored: constraints not satisfied [with Self = struct distance, FwdQ = quantity<mp_units::si::kilo_<mp_units::si::metre>{}, int>, Q = std::remove_cvref_t<quantity<mp_units::si::kilo_<mp_units::si::metre>{}, int>>]
  217 |   [[nodiscard]] constexpr Quantity auto operator()(this Self, FwdQ&& q)
      |                                         ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/framework/quantity_spec.h:216:33: note: because 'typename quantity<make_reference(Self{}, Q::unit), typename Q::rep>' would be invalid: constraints not satisfied for class template 'quantity' [with R = reference<mp_units::isq::distance, mp_units::si::kilo_<mp_units::si::metre>>{}, Rep = typename std::remove_cvref_t<quantity<mp_units::si::kilo_<mp_units::si::metre>{}, int>>::rep]
  216 |             requires { typename quantity<make_reference(Self{}, Q::unit), typename Q::rep>; }
      |                                 ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/framework/quantity_spec.h:226:46: note: candidate template ignored: constraints not satisfied [with Self = struct distance, FwdQP = quantity<mp_units::si::kilo_<mp_units::si::metre>{}, int>, QP = std::remove_cvref_t<quantity<mp_units::si::kilo_<mp_units::si::metre>{}, int>>]
  226 |   [[nodiscard]] constexpr QuantityPoint auto operator()(this Self self, FwdQP&& qp)
      |                                              ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/framework/quantity_spec.h:223:43: note: because 'std::remove_cvref_t<quantity<mp_units::si::kilo_<mp_units::si::metre>{}, int>>' (aka 'mp_units::quantity<mp_units::si::kilo_<mp_units::si::metre>{{{{}, {}}}}, int>') does not satisfy 'QuantityPoint'
  223 |   template<typename Self, typename FwdQP, QuantityPoint QP = std::remove_cvref_t<FwdQP>>
      |                                           ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/framework/quantity_point_concepts.h:51:25: note: because 'detail::is_quantity_point<mp_units::quantity<mp_units::si::kilo_<mp_units::si::metre>{{{{}, {}}}}, int>>' evaluated to false
   51 | concept QuantityPoint = detail::is_quantity_point<T>;
      |                         ^
1 error generated.
Compiler returned: 1
```

I know it's not minimal, but I honestly don't know how to minimize it, maybe @mpusz can help?

CC @cor3ntin @zyn0217

### PR DESCRIPTION
**Pull request by wx257osn2**
Fixes #175831.

When transforming a `SubstNonTypeTemplateParmExpr`, `TreeTransform::TransformSubstNonTypeTemplateParmExpr` calls `Sema::CheckTemplateArgument` so that any sema annotations (such as implicit casts) that were stripped from the replacement are recovered.
This is done in whatever evaluation context the node happens to appear in after substitutions.

Since the normalization of constraints, a `SubstNonTypeTemplateParmExpr` can end up inside an unevaluated operand, so the replacement gets rebuilt in an unevaluated context.
Entities it refers to are then not odr-used: for example, when a call materializes a by-value function parameter of class type, the copy constructor is never marked odr-used and its definition is never instantiated.
The constant evaluation performed by `CheckTemplateArgument` afterwards then fails for otherwise valid arguments.
This caused rejects-valid regressions on real code such as mp-units.

This PR inserts a constant-evaluated context in `TransformSubstNonTypeTemplateParmExpr`, so that the replacement is rebuilt and re-checked on the context, regardless of where normalization has placed it.

--

Co-authored-by: A. Jiang <de34@live.cn>
Co-authored-by: Matheus Izvekov <mizvekov@gmail.com>

### CODE REVIEW

**Comment by wx257osn2** [comment]
@zyn0217 First, sorry for sending a PR without giving you a heads-up, even though [the issue](https://github.com/llvm/llvm-project/issues/175831) is assigned to you.

Regarding the fix itself, this patch seems to resolve the issue, but I'm a bit concerned that it may be too ad hoc. I’d appreciate your thoughts.

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -16746,13 +16736,23 @@ ExprResult TreeTransform<Derived>::TransformSubstNonTypeTemplateParmExpr(
...
         CanonicalConverted,
         /*StrictCheck=*/false, Sema::CTAK_Specified);
-    if (Replacement.isInvalid())
-      return true;
+    if (Checked.isInvalid()) {
+      if (!SemaRef.isUnevaluatedContext())
+        return true;
+    } else {
+      Replacement = Checked;
+    }
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h]:
```suggestion
    if (Checked.isInvalid() && !SemaRef.isUnevaluatedContext()) {
        return true;
```

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -543,6 +543,7 @@ Bug Fixes in This Version
 - Fixed a crash when parsing invalid ``static_assert`` declarations with string-literal messages (#GH187690).
 - Fixed a potential stack-use-after-return issue in Clang when copy-initializing
   an array via an element-at-a-time copy loop (#GH192026)
+- Fixed a regression where calling a function that takes a class-type parameter by value inside ``decltype`` of a concept could be incorrectly rejected when used as a non-type template argument. (#GH175831)
```
Comment (zyn0217) [inline clang/docs/ReleaseNotes.rst:734]: We might want to backport it to clang 22 if possible, as it breaks mpunits in some way

**Review by zyn0217 — COMMENTED** [review]
Thanks, while I'm not opposed to adding some workarounds to get the behavior back, I think I need @mizvekov's thought on this (He fixed this function)

Strictly speaking one shouldn't expect that they are able to instantiate anything from an unevaluated context, however given that we're still lack of the instantiation-on-demand machineary #173537 I think tolerating the behavior is ... harmless?

File: clang/lib/Sema/TreeTransform.h (hunk 1 above)
Comment (wx257osn2) [reply clang/lib/Sema/TreeTransform.h]: The key point of this PR is that when `Checked.isInvalid() && SemaRef.isUnevaluatedContext()` holds, we **do not** update `Replacement` with `Checked`. So I think merging that part would be difficult.

As an alternative, we could reduce the nesting by writing something like:

```cpp
if (!Checked.isInvalid())
  Replacement = Checked;
else if (!SemaRef.isUnevaluatedContext())
  return true;
```

That said, this is not entirely pleasant either, since `!Checked.isInvalid()` is a double negative. But `ActionResult` does not have an `isValid()` method, so if we want to reduce the nesting, this seems to be about the only reasonable option.

File: clang/docs/ReleaseNotes.rst (hunk 2 above)
Comment (wx257osn2) [reply clang/docs/ReleaseNotes.rst:734]: [The previous (and my first) PR](https://github.com/llvm/llvm-project/pull/184406) wasn't backported, so I'm not familiar with the process. Would you mind walking me through the steps?

**Review by mizvekov — COMMENTED** [review]
So this expression has been transformed twice, first when checking the template arguments for the concept/template specialization, and then in the second time for the SubstNonTypeTemplateParmExpr transform.

Why does it fail the second time but not the first? Supposedly the first time around it was also an Unevaluated context. Have we messed up the contexts somehow?

**Comment by zyn0217** [comment]
> So this expression has been transformed twice, first when checking the template arguments for the concept/template specialization, and then in the second time for the SubstNonTypeTemplateParmExpr transform.
> 
> Why does it fail the second time but not the first? Supposedly the first time around it was also an Unevaluated context. Have we messed up the contexts somehow?

AFAIK the first transform happens in the parameter building where all of the template arguments are dependent. Therefore it doesn't fail.

The underlying issue is that, whether we want to allow users to instantiate templates from a decltype expression; technically we shouldn't but before our normalization patch it was accidentally allowed (we instantiated the constexpr functions before substituting into decltypes whereas we normalize decltype first and then substitute now) and mpunits seems to rely on that behavior.

File: clang/docs/ReleaseNotes.rst (hunk 2 above)
Comment (zyn0217) [reply clang/docs/ReleaseNotes.rst:734]: Sure, we can always go ahead as is and remove the release note in the PR targeting to the 22.x branch (the regressions don't need a release note)

File: clang/lib/Sema/TreeTransform.h (hunk 1 above)
Comment (zyn0217) [reply clang/lib/Sema/TreeTransform.h]: Oh I see, I remembered how Replacement was a problem for us when we worked on the normalization patch in the first place :(

**Comment by mizvekov** [comment]
> The underlying issue is that, whether we want to allow users to instantiate templates from a decltype expression; technically we shouldn't but before our normalization patch it was accidentally allowed (we instantiated the constexpr functions before substituting into decltypes whereas we normalize decltype first and then substitute now) and mpunits seems to rely on that behavior.

But there are some situations where we have to instantiate templates from a decltype expression: https://compiler-explorer.com/z/ebc58Yq8z
```C++
template<class T> struct A {
    static_assert(false);
};
using X = decltype(A<int>::m);
```

Or closer to the example here: https://compiler-explorer.com/z/nGxbhM96n
```C++
template<class T> consteval auto f() {
    static_assert(false);
    return 3;
}
using X = decltype(f<int>());
```

Ie with a placeholder return type, you still have to instantiate a consteval function in an unevaluated context.

I suspect this patch does not handle a test case such as:
```C++
template<class>
struct reference {};
template<class Q>
consteval auto get_spec(reference<Q>) { return Q{}; }

template<class T>
concept repr_impl = sizeof(T) > 0;
template<class, auto V>
concept representation_of = repr_impl<decltype(V)>;
template<auto V, representation_of<get_spec(V)>>
struct quantity {};

auto x = quantity<reference<int>{}, int>{};
```

Does it?

Ie the above is the same as the test case currently in the PR, but `get_spec` now has a placeholder return type.

**Comment by wx257osn2** [comment]
> I suspect this patch does not handle a test case such as:
>
> ```cpp
> template<class>
> struct reference {};
> template<class Q>
> consteval auto get_spec(reference<Q>) { return Q{}; }
> 
> template<class T>
> concept repr_impl = sizeof(T) > 0;
> template<class, auto V>
> concept representation_of = repr_impl<decltype(V)>;
> template<auto V, representation_of<get_spec(V)>>
> struct quantity {};
> 
> auto x = quantity<reference<int>{}, int>{};
> ```

Actually it passes that case, but with this patch it looks like the constraints are not being evaluated properly (yes, it doesn't handle constraints correctly).
Even if I change it to something like `concept repr_impl = sizeof(T) > 10;` , it still compiles without any issues.

That seems far too broken, so I'm going to mark this patch as Draft and I will think a bit more. Sorry...

**Comment by zyn0217** [comment]
> But there are some situations where we have to instantiate templates from a decltype expression: https://compiler-explorer.com/z/ebc58Yq8z
> 
> ```c++
> template<class T> struct A {
>     static_assert(false);
> };
> using X = decltype(A<int>::m);
> ```
> 
> Or closer to the example here: https://compiler-explorer.com/z/nGxbhM96n
> 
> ```c++
> template<class T> consteval auto f() {
>     static_assert(false);
>     return 3;
> }
> using X = decltype(f<int>());
> ```
> 
> Ie with a placeholder return type, you still have to instantiate a consteval function in an unevaluated context.

@mizvekov These are instantiated from a different path, where the function body is needed regardless of the evaluation context, i.e. they are instantiated from DeduceReturnType/RequireCompleteType

But for the example that this PR is trying to fix, we have to instantiate the function body through `MarkFunctionReferenced` where the evaluation context is considered, and that evaluation context has been changed in the transfrom of Decltype expression. (The decltype expression occurs first before `get_spec(V)` after our normalization patch, which was not the case before that patch.)

**Comment by zyn0217** [comment]
A workaround I'm considering is that, we do not push an Unevaluated context if we're instantiating a constraint, in 

https://github.com/llvm/llvm-project/blob/3fb3383f453109cab772005739f5f6ad1a0f7266/clang/lib/Sema/TreeTransform.h#L7061-L7069

i.e. we probably want to guard the evaluation context with `!S.inConstraintSubstitution()`.

@wx257osn2 can you help us explore that? thanks!

**Comment by wx257osn2** [comment]
Above issue appears to be resolved by not storing the result of `SemaRef.CheckTemplateArgument()` in `Replacement` for an evaluated context regardless of the result of `isInvalid()`.
I also added a test to verify that, when constraint satisfaction fails, the diagnostic is emitted correctly.

File: clang/lib/Sema/TreeTransform.h [hunk 3]
```diff
@@ -16746,13 +16736,15 @@ ExprResult TreeTransform<Derived>::TransformSubstNonTypeTemplateParmExpr(
...
-      return true;
+    if (!SemaRef.isUnevaluatedContext()) {
+      TemplateArgument SugaredConverted, CanonicalConverted;
+      Replacement = SemaRef.CheckTemplateArgument(
+          Param, ParamType, Replacement.get(), SugaredConverted,
+          CanonicalConverted,
+          /*StrictCheck=*/false, Sema::CTAK_Specified);
+      if (Replacement.isInvalid())
+        return true;
+    }
```
Comment (mizvekov) [inline clang/lib/Sema/TreeTransform.h]: I believe you can get away with this for the given test case, because `decltype` looks through implicit nodes, only the as-written expression matters, so its not a problem that we skip the semantic analysis here.

But what about other unevaluated contexts where it does matter?

For sizeof and typeid, we care about the exact type.
I believe for `noexcept` expression, this could avoid the introduction of a user-defined conversion which could throw.

I think it should be possible, with the above, to construct an example that would be broken by this change.

For the conversion cases, this would have to be an example that doesn't involve constraint substitution, because normalization is currently broken for constant template parameters, because it doesn't consider conversions between constant template parameters of different types.

**Comment by zyn0217** [comment]
@mizvekov Did your #200850 handle this issue?

**Comment by mizvekov** [comment]
> @mizvekov Did your #200850 handle this issue?

I haven't tested but I wouldn't believe so, this problem doesn't have to do with the parameter type being incorrect.

**Comment by wx257osn2** [comment]
Sorry for the late reply.

> Did your https://github.com/llvm/llvm-project/pull/200850 handle this issue?

I checked, but it still seems to be failing.

---

I've been thinking about this for a while and reworked the implementation: instead of skipping `CheckTemplateArgument` entirely, the new version still applies the conversions to the parameter type (`BuildConvertedConstantExpression`) and only skips the constant evaluation (`EvaluateConvertedConstantExpression`), taking the same early-return path as a value-dependent argument.
The evaluation is the only part that can spuriously fail in unevaluated contexts, and its result is not needed there.

Since the conversions are still applied, the type, value category, and any potentially-throwing conversion nodes of the replacement are preserved, so the `sizeof`/`typeid`/`noexcept` cases you mentioned should behave as before.

I would appreciate your feedback on this implementation.

File: clang/lib/Sema/TreeTransform.h [hunk 4]
```diff
@@ -16727,11 +16727,19 @@ ExprResult TreeTransform<Derived>::TransformSubstNonTypeTemplateParmExpr(
...
+    // entities they refer to are not odr-used in such a context (e.g. the
+    // implicit copy of a function argument of class type cannot be constant
+    // folded when the special members were never instantiated).
     TemplateArgument SugaredConverted, CanonicalConverted;
     Replacement = SemaRef.CheckTemplateArgument(
         Param, ParamType, Replacement.get(), SugaredConverted,
         CanonicalConverted,
-        /*StrictCheck=*/false, Sema::CTAK_Specified);
+        /*StrictCheck=*/false, Sema::CTAK_Specified,
+        /*SkipConstantEvaluation=*/SemaRef.isUnevaluatedContext());
```
Comment (mizvekov) [inline clang/lib/Sema/TreeTransform.h]: We can probably skip adding the new parameter and check this directly in the implementation.

**Review by mizvekov — COMMENTED** [review]
I think this is much better than the previous approach.

Though I am not entirely convinced this is the right solution.

The problem is, a SubstNonTypeTemplateParmExpr node represents the template argument as it appeared in a template specialization type, converted to it's corresponding template parameter type.

That conversion has to happen in an evaluated context, because the value of the template argument is part of the identity of the template specialization.

So I am wondering, have we simply forgot to set an appropriate evaluation context when checking the template argument in the `SubstNonTypeTemplateParmExpr` transform?

**Comment by mizvekov** [comment]
FWIW I think this would boil down to this test case: https://compiler-explorer.com/z/dh9z68j3P
```C++
template<class> struct reference {};
template<class Q> consteval Q get_spec(reference<Q>) { throw; }

template<class T> concept repr_impl = sizeof(T) > 0;
template<class, auto V> concept representation_of = repr_impl<decltype(V)>;
template<auto V, representation_of<get_spec(V)>> struct quantity {};

auto x = quantity<reference<int>{}, int>{};
```

Should we reject this or accept?

I think we should reject, so GCC is wrong and Clang-20 is right, because `get_spec(V)` appears as a template argument to `representation_of`, and that's an evaluated context.

**Comment by mizvekov** [comment]
I submitted an issue to core about this, let's see what happens.

**Comment by wx257osn2** [comment]
> I think we should reject, so GCC is wrong and Clang-20 is right, because get_spec(V) appears as a template argument to representation_of, and that's an evaluated context.

I agree. The approach of skipping evaluation seems unlikely to work well, so I've reworked the implementation once more. By entering a constant-evaluated context before transforming the replacement, the copy constructor can now be instantiated properly. I think this version looks reasonable (at least more than the previous one), and I would appreciate your feedback.

File: clang/lib/Sema/TreeTransform.h (hunk 4 above)
Comment (wx257osn2) [reply clang/lib/Sema/TreeTransform.h]: I haven’t tried it, so I’m not sure, but my concern is that skipping evaluation in every `CheckTemplateArgument` call might break other places. Anyway, I' reverted this change.

File: clang/lib/Sema/TreeTransform.h [hunk 5]
```diff
@@ -16701,6 +16701,19 @@ template <typename Derived>
...
+  // Otherwise, when a normalized constraint places the replacement inside
+  // an unevaluated operand (e.g. decltype), entities it refers to are not
+  // odr-used, and the constant evaluation performed by CheckTemplateArgument
+  // below can spuriously fail for otherwise valid replacements,
+  // e.g. when a call materializes a function parameter of class type whose
+  // special members were never instantiated.
+  EnterExpressionEvaluationContext ConstantEvaluated(
+      SemaRef, Sema::ExpressionEvaluationContext::ConstantEvaluated,
+      /*LambdaContextDecl=*/nullptr,
+      Sema::ExpressionEvaluationContextRecord::EK_TemplateArgument);
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h]: Maybe we should use ReuseLambdaContextDecl flag, but I don't have a test for it

Comment (wx257osn2) [reply clang/lib/Sema/TreeTransform.h]: done. Thank you!

Comment (mizvekov) [reply clang/lib/Sema/TreeTransform.h]: I don't have a test right now, I am busy in committee, but I believe the ContextDecl for such a lambda would be the template parameter referred by this node.

Comment (wx257osn2) [reply clang/lib/Sema/TreeTransform.h]: So we should be passing `E->getParameter()` instead of `Sema::ReuseLambdaContextDecl`, right?

**Comment by shafik** [comment]
> I submitted an issue to core about this, let's see what happens.

Any updates here?

**Comment by mizvekov** [comment]
I created a GitHub issue, but the corresponding core issue has not been created yet: https://github.com/cplusplus/CWG/issues/913

**Review by mizvekov — APPROVED** [review]
LGTM

**Comment by shafik** [comment]
Please be ready to revert in case breakages come in.
