### PR TITLE
Add symbol locator time for each module in statistics

### PR DESCRIPTION
**Pull request by GeorgeHuyubo**
Identical PR to: https://github.com/llvm/llvm-project/pull/134563
Previous PR was approved and landed but broke the build due to bad merge.
Manually resolve the merge conflict and try to land again.

### CODE REVIEW

**Review by kazutakahirata — COMMENTED** [review]
I've locally applied your change on the top of tree, but I still get:
```
lldb/source/Target/Statistics.cpp:75:39: error: use of undeclared identifier 'num_symbols_loaded'
  module.try_emplace("symbolsLoaded", num_symbols_loaded);
                                      ^
1 error generated.
```
Would you mind looking into this?  Thanks!

**Comment by GeorgeHuyubo** [comment]
> I've locally applied your change on the top of tree, but I still get:
> 
> ```
> lldb/source/Target/Statistics.cpp:75:39: error: use of undeclared identifier 'num_symbols_loaded'
>   module.try_emplace("symbolsLoaded", num_symbols_loaded);
>                                       ^
> 1 error generated.
> ```
> 
> Would you mind looking into this? Thanks!

should be fixed now
