### PR TITLE
[SPIR-V] Add missing ScalarOpts library

### PR DESCRIPTION
**Pull request by svenvh**
Fixes an "undefined reference to `llvm::createRegToMemWrapperPass()'" linker error introduced by cba70550ccf5 ("[SPIR-V] Fix BB ordering & register lifetime (#111026)", 2024-10-30).

### CODE REVIEW

**Review by VyacheslavLevytskyy — APPROVED** [review]
Thank you! I was digging in the same problem right now.

**Comment by Keenuts** [comment]
Oh thanks for the fix!
