### ISSUE TITLE
[clang] template template argument has different template parameters

### ISSUE THREAD

**Issue by bobby3605** [llvm/llvm-project#95732]
I'm trying to make a class that takes a container that takes a template as a template parameter for the class.
The following compiles in gcc, but not clang on 18.1.0. Clang trunk gives a different compilation error, which I am creating a separate [issue](https://github.com/llvm/llvm-project/issues/95733) for.
https://godbolt.org/z/j7cn3rd59
My guess is that it has something to do with the fact that std::vector takes two template arguments, one for the type, and one for the allocator. However, std::vector has a default argument for the allocator, so it only needs a single argument, but clang doesn't detect that.

**Comment by cor3ntin** [comment]
Fixed in trunk (Clang 19) or with -frelaxed-template-template-args https://godbolt.org/z/1Kah8zKGT
