### PR TITLE
[Hexagon] Fix unused variable in non-assert builds (KCFI)

### PR DESCRIPTION
**Pull request by androm3da**
Without asserts, we see failures like so:

    /repo/llvm/llvm/lib/Target/Hexagon/HexagonAsmPrinter.cpp:982:43: error: unused variable 'NextI' [-Werror,-Wunused-variable]
      982 |   MachineBasicBlock::const_instr_iterator NextI = std::next(MI.getIterator());
          |                                           ^~~~~
    1 error generated.

Mark NextI `maybe_unused` to address the issue.

Fixes a regression introduced by f8aa5f66209d.

### CODE REVIEW

**Review by mikaelholmen — APPROVED** [review]
Thanks, LGTM!
