### ISSUE TITLE
lli fails to build with GCC 8

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#36834]
|  |  |
| --- | --- |
| Bugzilla Link | [37486](https://llvm.org/bz37486) |
| Version | 5.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lhames |

## Extended Description 
I'm working with llvm-5.0.1.src.tar.xz, using gcc 8.1.1 under Fedora 28:

Error message:

In file included from /home/naourr/work/instance-2/output/build/host-llvm-5.0.1/tools/lli/lli.cpp:30:
/home/naourr/work/instance-2/output/build/host-llvm-5.0.1/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h: In member function 'llvm::Expected<std::vector<char> > llvm::orc::remote::OrcRemoteTargetClient<ChannelT>::readMem(char*, llvm::JITTargetAddress, uint64_t)':
/home/naourr/work/instance-2/output/build/host-llvm-5.0.1/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h:722:26: error: could not convert '((llvm::orc::remote::OrcRemoteTargetClient<ChannelT>*)this)->callB<llvm::orc::remote::OrcRemoteTargetRPCAPI::ReadMem>(Src, Size)' from 'Expected<vector<unsigned char,allocator<unsigned char>>>' to 'Expected<vector<char,allocator<char>>>'
     return callB<ReadMem>(Src, Size);

Full log: 

http://autobuild.buildroot.net/results/824c70e982d8ec7e518cf4db058767df42db6b04/build-end.log

**Comment by arsenm** [comment]
Old build issue
