### ISSUE TITLE
Negative floating point constants not permitted in initializer

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#13368]
|  |  |
| --- | --- |
| Bugzilla Link | [12996](https://llvm.org/bz12996) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @AaronBallman,@asl |

## Extended Description 
The following declaration no longer compiles with clang since updating from 3.0 to 3.1:

static char c = -1.0;

f.c:1:17: error: initializer element is not a compile-time constant
