### ISSUE TITLE
[x86] After 4edb9983cb8, invalid operand for inline asm constraint 'i'

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#53868]
As reported in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261742#c9, with clang 14 php-opcache fails to compile for 32-bit x86, with the following rather confusing error:

```
In file included from /wrkdirs/usr/ports/www/php80-opcache/work/php-8.0.15/ext/opcache/jit/zend_jit.c:19:
In file included from /usr/local/include/php/main/php.h:31:
In file included from /usr/local/include/php/Zend/zend.h:357:
/usr/local/include/php/Zend/zend_operators.h:531:3: error: invalid operand for inline asm constraint 'i'
                "addl $1,(%0)\n\t"
                ^
/usr/local/include/php/Zend/zend_operators.h:594:3: error: invalid operand for inline asm constraint 'i'
                "subl $1,(%0)\n\t"
                ^
/usr/local/include/php/Zend/zend_operators.h:531:3: error: invalid operand for inline asm constraint 'i'
                "addl $1,(%0)\n\t"
                ^
/usr/local/include/php/Zend/zend_operators.h:594:3: error: invalid operand for inline asm constraint 'i'
                "subl $1,(%0)\n\t"
                ^
4 errors generated.
```

However, the code in question (https://github.com/php/php-src/blob/master/Zend/zend_operators.h#L500) does not use 'i' constraints at all:

```c
static zend_always_inline void fast_long_increment_function(zval *op1)
{
#if ZEND_USE_ASM_ARITHMETIC && defined(__i386__) && !(4 == __GNUC__ && 8 == __GNUC_MINOR__)
	__asm__ goto(
		"addl $1,(%0)\n\t"
		"jo  %l1\n"
		:
		: "r"(&op1->value)
		: "cc", "memory"
		: overflow);
	return;
overflow: ZEND_ATTRIBUTE_COLD_LABEL
	ZVAL_DOUBLE(op1, (double)ZEND_LONG_MAX + 1.0);
```

This compiled fine with clang 13, and it seems to have regressed with 4edb9983cb8c8b850083ee5941468f5d0ef6fe2c (ping @nickdesaulniers and @nikic might also want to know about this).

Minimal test case, to compile with `clang -m32 -fPIC -c zend-op-min.c` (the PIC option is essential): 

```
typedef union {
  long lval;
  double dval;
  void *obj;
} zend_value;

typedef struct {
  zend_value value;
  union {
    unsigned type_info;
    struct {
      unsigned char type;
      unsigned char type_flags;
      union {
        unsigned short extra;
      } u;
  } v;
 } u1;
} zval;

void fast_long_increment_function(zval *op1)
{
  __asm__ goto(
    "addl $1,(%0)\n\t"
    "jo  %l1\n"
    :
    : "r"(&op1->value)
    : "cc", "memory"
    : overflow);
  return;
overflow:
  do {
    zval *__z = (op1);
    (*(__z)).value.dval = (double)0x7fffffff + 1.0;
    (*(__z)).u1.type_info = 5;
  } while (0);
}
```

**Comment by nickdesaulniers** [comment]
cc @jyknight @efriedma-quic @isanbard

**Comment by nickdesaulniers** [comment]
reduced test case:
```
// clang -m32 -fPIC
void x(void) {
  asm goto("#  %l0\n" ::::overflow);
  return;
overflow:
  return;
}
```
(looks like BOTH `-m32` and `fPIC` are necessary)

**Comment by nickdesaulniers** [comment]
I suspect this has to do with `X86TargetLowering::LowerAsmOperandForConstraint`'s custom handling of `i`.
```
54791     // In any sort of PIC mode addresses need to be computed at runtime by                                                                                                
54792     // adding in a register or some sort of table lookup.  These can't                                                                                                    
54793     // be used as immediates.                                                                                                                                             
54794     if (Subtarget.isPICStyleGOT() || Subtarget.isPICStyleStubPIC())
```

**Comment by nickdesaulniers** [comment]
```diff
diff --git a/llvm/lib/Target/X86/X86ISelLowering.cpp b/llvm/lib/Target/X86/X86ISelLowering.cpp                                                                                  
index 3366b45615ba..ed933c16e115 100644
--- a/llvm/lib/Target/X86/X86ISelLowering.cpp
+++ b/llvm/lib/Target/X86/X86ISelLowering.cpp
@@ -54790,7 +54790,7 @@ void X86TargetLowering::LowerAsmOperandForConstraint(SDValue Op,
     // In any sort of PIC mode addresses need to be computed at runtime by
     // adding in a register or some sort of table lookup.  These can't
     // be used as immediates.
-    if (Subtarget.isPICStyleGOT() || Subtarget.isPICStyleStubPIC())
+    if (Subtarget.isPICStyleStubPIC())
       return;
 
     // If we are in non-pic codegen mode, we allow the address of a global (with
```
seems to fix the reduced test case. Let's see what kind of death & destruction that causes on the test suite.

**Comment by nickdesaulniers** [comment]
no test failed...perhaps there's no coverage of that.

https://reviews.llvm.org/D119905

**Comment by tstellar** [comment]
@topperc What do you think about backporting this? https://github.com/llvm/llvm-project/commit/027c16bef4b727095eea00bbef9266f1f4a78c27

**Comment by topperc** [comment]
> @topperc What do you think about backporting this? [027c16b](https://github.com/llvm/llvm-project/commit/027c16bef4b727095eea00bbef9266f1f4a78c27)

I think it is ok to backport.

**Comment by tstellar** [comment]
Merged: 41d4f89e38b7
