### ISSUE TITLE
Unnecessary instantiation of templated function passed as a template parameter causes valid C++ code to fail compilation

### ISSUE THREAD

**Issue by TRDario** [llvm/llvm-project#138420]
The following code snippet compiles with MSVC and GCC, but fails to compile with Clang 20.1.0:

```
#include <unordered_map>
#include <vector>

template <class T>
concept standard_layout = std::is_standard_layout_v<T>;
template <class T, template <class...> class Z> struct is_specialization_of : std::false_type {};
template <class... Args, template <class...> class Z> struct is_specialization_of<Z<Args...>, Z> : std::true_type {};
template <class T, template <class...> class Z>
concept specialization_of = is_specialization_of<T, Z>::value;

template <class T> using fn = T (*)();

template <class T> T foo()
{
	static_assert(!specialization_of<T, std::pair>, "Compilation error!");
	return T{};
}

template <specialization_of<std::vector> T, fn<typename T::value_type> D> T bar()
{
	D();
	return T{};
}

template <specialization_of<std::unordered_map> T, fn<typename T::key_type> D1, fn<typename T::mapped_type> D2> T bar()
{
	D1();
	D2();
	return T{};
}

int main()
{
	bar<std::unordered_map<int, char>, foo, foo>();
}
```

It appears that in this example despite the std::vector overload of 'bar' not being chosen, 'foo<std::pair<int, char>>' is still instantiated and the error it emits causes the compilation to fail.

The error does not occur if 'foo' is a regular overloaded function, i.e replacing it with:
```
void foo(int) {}

void foo(char) {}

void foo(std::pair<int, char>) = delete;
```
does not result in any compilation errors.

**Comment by TRDario** [comment]
Some futher observations:

More minimal example where Clang fails to compile but the others don't:
```
#include <concepts>

struct D {
	using A = int;
	using B = char;
	using C = float;
};

template <class T>
concept failed_constraint = !std::same_as<T, D>;

template <class T> T foo()
{
	static_assert(!std::same_as<T, int>, "Compilation error!");
	return T{};
}

template <failed_constraint T, T::A (*)()> void bar() {}

template <class T, T::B (*)(), T::C (*)()> void bar() {}

int main()
{
	bar<D, foo, foo>();
}
```


Example where all 3 of the above compilers fail to compile:
```
#include <concepts>

struct D {
	using A = int;
	using B = char;
	using C = float;
};

template <class T>
concept failed_constraint = !std::same_as<T, D>;

template <class T> T foo()
{
	static_assert(!std::same_as<T, int>, "Compilation error!");
	return T{};
}

template <failed_constraint T, T::A (*)()> void bar() {}

template <class T, T::B (*)()> void bar() {}

int main()
{
	bar<D, foo>();
}
```

Some examples that _do_ compile on Clang:
Using a typename that isn't present in the actual class:
```
#include <concepts>

struct D {
	using A = int;
	using B = char;
	using C = float;
};

template <class T>
concept failed_constraint = !std::same_as<T, D>;

template <class T> T foo()
{
	static_assert(!std::same_as<T, int>, "Compilation error!");
	return T{};
}

template <failed_constraint T, T::NOT_REAL (*)()> void bar() {}

template <class T, T::B (*)()> void bar() {}

int main()
{
	bar<D, foo>();
}
```
Explicitly deleted function overload:
```
#include <concepts>

struct D {
	using A = int;
	using B = char;
	using C = float;
};

template <class T>
concept failed_constraint = !std::same_as<T, D>;

template <class T> T foo()
{
	static_assert(!std::same_as<T, int>, "Compilation error!");
	return T{};
}
int foo() = delete;

template <failed_constraint T, T::A (*)()> void bar() {}

template <class T, T::B (*)()> void bar() {}

int main()
{
	bar<D, foo>();
}
```

**Comment by cor3ntin** [comment]
@zyn0217

**Comment by zyn0217** [comment]
It looks like GCC (and other compilers) are avoiding instantiating the overload that ends up instantiating `foo<int>`, by checking the (explicit?) template arguments earlier to rule out invalid overloads without going through substitution. So in this example, the constraint isn't necessary to elaborate the difference:

```cpp
struct D {
  using A = int;
  using B = char;
  using C = float;
};

template <class T> T foo() {
  static_assert(!__is_same(T, int), "Compilation error!");
  return T{};
}

template <class T, T::A (*)()> void bar() {}

template <class T, T::B (*)(), T::C (*)()> void bar() {}

int main() {
  bar<D, foo, foo>();
}
```

https://godbolt.org/z/P4M11s1rE

As you have observed, if we make overloads harder to distinguish, e.g. by giving them the same length of template parameters, then that early checking fails, and they end up instantiating `foo<int>` as well, same as what we're doing.

**Comment by zyn0217** [comment]
More interesting example:

```cpp
#if __GNUC__

#else

#include <type_traits>

#endif

struct D {
  using A = int;
  using B = char;
  using C = float;
};

template <class T> T foo() {
#if __GNUC__
  static_assert(!__is_same(T, int), "Compilation error!");
#else
  static_assert(!std::is_same_v<T, int>, "Compilation error!");
#endif

  return T{};
}

template <class T, T::B (*)()> void bar() {} // #1

template <class T, T::C (*)(), T::A (*)()> void bar() {} // #2

int main() {
  bar<D, foo>();
}
```

https://godbolt.org/z/osaf4451G

Both MSVC and GCC are accepting it. But if we swapped the order of parameters in `#2` to `template <class T, T::A (*)(), T::C (*)()> void bar() {}` then they would reject.
