### ISSUE TITLE
Aligned comments after closed brace is throwing error 

### ISSUE THREAD

**Issue by RajeshDasari** [llvm/llvm-project#93820]
#include <stdio.h>

int main()
{
    int x;
    if (x >= 1)
    {
        if (x > 1)
        {
            printf("x is greater");
        } /*2ndtif*/
    }     /*1stif*/
}
the above snippet works well with the clang-17.0.6 but where as with clang-format 18.1.1 , I get the below error
test.c:12:6: error: code should be clang-formatted [-Wclang-format-violations]
    }     /*1stif*/
     ^
     I have used the same .clang-format file for both the versions
