### ISSUE TITLE
libc build on s390x is failing on `Unsupported architecture`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#118967]
```
FAILED: projects/libc/utils/gpu/server/CMakeFiles/llvmlibc_rpc_server.dir/build/source/libc/src/stdio/printf_core/writer.cpp.o 
/opt/sccache//sccache /build/source/build-llvm/bin/clang++ -DLIBC_COPT_ARRAY_ARG_LIST -DLIBC_COPT_MEMCPY_USE_EMBEDDED_TINY -DLIBC_COPT_PRINTF_DISABLE_INDEX_MODE -DLIBC_COPT_PRINTF_DISABLE_STRERROR -DLIBC_COPT_PRINTF_DISABLE_WRITE_INT -DLIBC_COPT_USE_C_ASSERT -DLIBC_NAMESPACE=__llvm_libc_20_0_0_ -DLIBC_TYPES_LONG_DOUBLE_IS_FLOAT64 -I/build/source/build-llvm/tools/clang/stage2-bins/projects/libc/utils/gpu/server -I/build/source/libc/utils/gpu/server -I/build/source/libc -I/build/source/libc/include -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/source/build-llvm/tools/clang/stage2-bins=../../../../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -O2 -DNDEBUG -g1 -std=c++17 -MD -MT projects/libc/utils/gpu/server/CMakeFiles/llvmlibc_rpc_server.dir/build/source/libc/src/stdio/printf_core/writer.cpp.o -MF projects/libc/utils/gpu/server/CMakeFiles/llvmlibc_rpc_server.dir/build/source/libc/src/stdio/printf_core/writer.cpp.o.d -o projects/libc/utils/gpu/server/CMakeFiles/llvmlibc_rpc_server.dir/build/source/libc/src/stdio/printf_core/writer.cpp.o -c /build/source/libc/src/stdio/printf_core/writer.cpp
In file included from /build/source/libc/src/stdio/printf_core/writer.cpp:9:
In file included from /build/source/libc/src/stdio/printf_core/writer.h:17:
/build/source/libc/src/string/memory_utils/inline_memset.h:34:2: error: "Unsupported architecture"
   34 | #error "Unsupported architecture"
      |  ^
1 error generated.
```

Regression range: b8daa45a566b..dd7a3d4d798e

Maybe it makes sense but it should be blocked at the cmake level, not when compiling

@nickdesaulniers I guess it is caused by #117220 too (or one of the follow up change)

**Comment by michaelrj-google** [comment]
Can you provide a bit more information on what exactly you're trying to do? Are you trying to build for a GPU with a s390x host? Currently our cmake only checks if we support the current target, so that's why there's no error at that stage. @jhuber6 would it be reasonable to add a check that the host is also a supported target for GPU builds?

**Comment by jhuber6** [comment]
> Can you provide a bit more information on what exactly you're trying to do? Are you trying to build for a GPU with a s390x host? Currently our cmake only checks if we support the current target, so that's why there's no error at that stage. [@jhuber6](https://github.com/jhuber6) would it be reasonable to add a check that the host is also a supported target for GPU builds?

Highly doubt that we will be running GPU programs on 32-bit systems.

**Comment by jhuber6** [comment]
I don't know the s390x very well, is it supposed to be going through the x64 paths?

**Comment by sylvestre** [comment]
> Can you provide a bit more information on what exactly you're trying to do? 

Just build libc for apt.llvm.org 
See the full log:
https://llvm-jenkins.debian.net/job/llvm-toolchain-oracular-binaries/architecture=s390x,distribution=oracular,label=s390x/103/consoleFull

I don't mind disabling libc+gpu on s390x 

The point of my bug was to get a check in cmake and to have a better error message :)

**Comment by ecnelises** [comment]
I don't think s390x is supported by libc. From source code, it seems only aarch64/x86/riscv are supported (or being supported).

> I don't know the s390x very well, is it supposed to be going through the x64 paths?

s390x means 'SystemZ' in LLVM.

**Comment by jhuber6** [comment]
The issue is that this comes from the GPU build support, which until now kind of had an implicit assumption that the host could include the headers. It's "technically" not building libc for that target, but it's trying to build the host-side handling for 'syscalls' the GPU uses. We can either make this a more obvious error, or just fix up the few places where this is unhandled and have some more deliberate fallbacks. As far as I can tell this is mostly coming from a lack of string functions (memcpy) and `fenv` implementation.
