### PR TITLE
[offload] Fix build with debug libomptarget

### PR DESCRIPTION
**Pull request by sarnex**
Currently get this error
```
offload/plugins-nextgen/common/src/PluginInterface.cpp:859:63: error: member reference type 'StringRef' is not a pointer; did you mean to use '.'?
```

We pass the full image binary now so we can't really print anything useful here.

Seems introduced in https://github.com/llvm/llvm-project/pull/158748.

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]

File: offload/plugins-nextgen/common/src/PluginInterface.cpp [hunk 1]
```diff
@@ -856,7 +856,7 @@ Error GenericDeviceTy::deinit(GenericPluginTy &Plugin) {
 }
 Expected<DeviceImageTy *> GenericDeviceTy::loadBinary(GenericPluginTy &Plugin,
                                                       StringRef InputTgtImage) {
-  DP("Load data from image " DPxMOD "\n", DPxPTR(InputTgtImage->ImageStart));
+  DP("Load data from image\n");
```
[the remark this answers is not in the document]
Comment (jhuber6) [reply offload/plugins-nextgen/common/src/PluginInterface.cpp:859]: This should work if we want to keep the debug message unique to the images loaded. Though honestly I think all of this debug handling should be torn out and redone.
