### PR TITLE
[clang][ssaf] Fix missing library dependency

### PR DESCRIPTION
**Pull request by steakhal**
Caused by #186442
Similar to #186475
Addresses:
https://github.com/llvm/llvm-project/pull/186475#issuecomment-4057355167

```
/usr/bin/ld: tools/clang/unittests/ScalableStaticAnalysisFramework/CMakeFiles/ClangScalableAnalysisTests.dir/ASTEntityMappingTest.cpp.o: undefined reference to symbol '_ZN4llvm3omp27isAllowedClauseForDirectiveENS0_9DirectiveENS0_6ClauseEj'
/usr/bin/ld: /home/botworker/builds/openmp-offload-amdgpu-runtime-2/llvm.build/lib/libLLVMFrontendOpenMP.so.23.0git: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

### CODE REVIEW

**Review by aviralg — APPROVED** [review]

**Review by Kewen12 — APPROVED** [review]
Thank you!
