### ISSUE TITLE
fails to link `error: undefined reference to 'llvm::checkRegister`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#123817]
On linux amd64:

```

FAILED: bin/llvm-ar
: && /usr/bin/g++ -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=3 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fdebug-prefix-map=/build/source/build-llvm=../ -fdebug-prefix-map=/build/source/= -no-canonical-prefixes -ffile-prefix-map=/build/source/build-llvm=../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -O3 -DNDEBUG -Wl,-z,relro -Wl,--build-id -fuse-ld=gold    -Wl,--gc-sections tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar.cpp.o tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar-driver.cpp.o -o bin/llvm-ar  -Wl,-rpath,"\$ORIGIN/../lib:"  lib/libLLVMM68kAsmParser.a  lib/libLLVMXtensaAsmParser.a  lib/libLLVMX86AsmParser.a  lib/libLLVMM68kDesc.a  lib/libLLVMXtensaDesc.a  lib/libLLVMX86Desc.a  lib/libLLVMM68kInfo.a  lib/libLLVMXtensaInfo.a  lib/libLLVMX86Info.a  lib/libLLVMBinaryFormat.a  lib/libLLVMCore.a  lib/libLLVMDlltoolDriver.a  lib/libLLVMLibDriver.a  lib/libLLVMObject.a  lib/libLLVMSupport.a  lib/libLLVMTargetParser.a  lib/libLLVMM68kCodeGen.a  lib/libLLVMM68kDesc.a  lib/libLLVMM68kInfo.a  lib/libLLVMAsmPrinter.a  lib/libLLVMGlobalISel.a  lib/libLLVMSelectionDAG.a  lib/libLLVMCodeGen.a  lib/libLLVMCGData.a  lib/libLLVMBitWriter.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMTransformUtils.a  lib/libLLVMTarget.a  lib/libLLVMAnalysis.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoBTF.a  lib/libLLVMCodeGenTypes.a  lib/libLLVMMCDisassembler.a  lib/libLLVMObject.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMIRReader.a  lib/libLLVMAsmParser.a  lib/libLLVMTextAPI.a  lib/libLLVMOption.a  lib/libLLVMBitReader.a  lib/libLLVMCore.a  lib/libLLVMBinaryFormat.a  lib/libLLVMRemarks.a  lib/libLLVMTargetParser.a  lib/libLLVMBitstreamReader.a  lib/libLLVMSupport.a  lib/libLLVMDemangle.a  -lrt  -ldl  -lm  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libzstd.so && :
lib/libLLVMXtensaAsmParser.a(XtensaAsmParser.cpp.o):XtensaAsmParser.cpp:function XtensaAsmParser::parseRegister(llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand> > >&, bool, bool):(.text._ZN15XtensaAsmParser13parseRegisterERN4llvm15SmallVectorImplISt10unique_ptrINS0_18MCParsedAsmOperandESt14default_deleteIS3_EEEEbb+0x353): error: undefined reference to 'llvm::checkRegister(llvm::MCRegister, llvm::FeatureBitset const&)'
lib/libLLVMXtensaAsmParser.a(XtensaAsmParser.cpp.o):XtensaAsmParser.cpp:function XtensaAsmParser::ParseInstructionWithSR(llvm::ParseInstructionInfo&, llvm::StringRef, llvm::SMLoc, llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand> > >&):(.text._ZN15XtensaAsmParser22ParseInstructionWithSRERN4llvm20ParseInstructionInfoENS0_9StringRefENS0_5SMLocERNS0_15SmallVectorImplISt10unique_ptrINS0_18MCParsedAsmOperandESt14default_deleteIS7_EEEE+0x230): error: undefined reference to 'llvm::checkRegister(llvm::MCRegister, llvm::FeatureBitset const&)'
collect2: error: ld returned 1 exit status
```

Regression range:
0f9e91346698..cdd321462aec

**Comment by sylvestre** [comment]
I guess it is caused by #121118 
cc @andreisfr
can you fix it quickly ?

**Comment by sylvestre** [comment]
full log: https://llvm-jenkins.debian.net/job/llvm-toolchain-oracular-binaries/architecture=amd64,distribution=oracular,label=amd64/181/
