### ISSUE TITLE
constinit should not tie to constant evaluation

### ISSUE THREAD

**Issue by zhihaoy** [llvm/llvm-project#54109]
`constinit` ensures static initialization (the compliment of dynamic initialization, according to [[dcl.constinit]/2](http://eel.is/c++draft/dcl.constinit#2)) rather than requiring constant-initialization. According to [[basic.start.static]/3.2](http://eel.is/c++draft/basic.start.static#3.2), an implementation is permitted to perform more static initializations, and that's what Clang is doing. But this behavior is not reflected in `constinit`. The following code doesn't compile:

```cpp
struct entity {
  static void call(entity *, int);
};

typedef void call_fn(void *, int);

template <class T> struct vtable {
  call_fn *call;
};

template <class T> inline constinit vtable<T> vtable_for{(call_fn *)T::call};

struct wrapper {
  vtable<entity> *vt = &vtable_for<entity>;
  void *data;
};
```

```
b.cc:11:48: error: variable does not have a constant initializer
template <class T> inline constinit vtable<T>  vtable_for{(call_fn *)T::call};
                                               ^         ~~~~~~~~~~~~~~~~~~~~
b.cc:14:25: note: in instantiation of variable template specialization 'vtable_for<entity>' requested here
  vtable<entity> *vt = &vtable_for<entity>;
                        ^
b.cc:11:27: note: required by 'constinit' specifier here
template <class T> inline constinit vtable<T>  vtable_for{(call_fn *)T::call};
                          ^~~~~~~~~
b.cc:11:59: note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
template <class T> inline constinit vtable<T>  vtable_for{(call_fn *)T::call};
                                                          ^
1 error generated.
```

The code compiles fine in GCC 10.2 and MSVC 19.29, C++20 modes.

**Comment by zygoloid** [comment]
[basic.start.static]/3 permits an implementation to perform dynamic initialization as if it were static initialization, but the variable still formally has dynamic initialization, so it can't be declared `constinit`.

I do not believe there was any design intent for the behavior of `constinit` to be non-portable or to depend on what a given implementation happens to be able to emit as constant initialization.
