### ISSUE TITLE
ppc64le offload build broken by 8437b7f5584765ad4f7885500647657714930fbb

### ISSUE THREAD

**Issue by tstellar** [llvm/llvm-project#136596]
@jhuber6 This commit 8437b7f5584765ad4f7885500647657714930fbb ( https://github.com/llvm/llvm-project/pull/131205) broke the build on ppc64le.  You can reproduce by configuring with:
```
cmake -G Ninja -B build -S llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=Native -DLLVM_ENABLE_PROJECTS=clang -DLLVM_ENABLE_RUNTIMES="offload;openmp;compiler-rt" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
```

And running:

```
ninja -C build runtimes
```
See attached build logs for details.  Note we aren't seeing the same failures on configurations where llvm is built with `-DPPC_LINUX_DEFAULT_IEEELONGDOUBLE:BOOL=ON`.

**Comment by tstellar** [comment]
[build.log.txt](https://github.com/user-attachments/files/19838776/build.log.txt)

**Comment by jhuber6** [comment]
Can you link the PR more easily? I'm going to assume that there's some missing `ifdef` for this weird PPC float.

**Comment by jhuber6** [comment]
This log is confusing it me, one of the errors says this, but it was fixed ages ago. Is this a really old build?
```
/root/llvm-project/llvm/cmake/modules/../../../libc/src/string/memory_utils/inline_memset.h:34:2: error: "Unsupported architecture"
   34 | #error "Unsupported architecture"
```

**Comment by jhuber6** [comment]
My best guess is that we don't handle PPC's `doubledouble` format for `long double`.

**Comment by tstellar** [comment]
Here is a more recent build log (link is only good for 2 weeks): https://download.copr.fedorainfracloud.org/results/@fedora-llvm-team/llvm-snapshots-big-merge-20250421/centos-stream-9-ppc64le/08948252-llvm/builder-live.log.gz

**Comment by jhuber6** [comment]
@tstellar Did this fix the issue?

**Comment by tstellar** [comment]
I tested the PR before it was merged and it fixed the issue for me.
