### ISSUE TITLE
clang-15 crashes on __builtin_va_arg

### ISSUE THREAD

**Issue by wierton** [llvm/llvm-project#62711]
The bug triggering testcase:
$ cat small.c
```c
#include <stdarg.h>
#include <stdlib.h>

void vat(va_list param, ...) {
  va_list local;

  __builtin_va_start(local, param);

  if (__builtin_va_arg(global, int) << 1) abort();
}
```

When compile it with Clang 15, Clang 15 crashes:
```console
$ clang-15 small.c
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /usr/lib/llvm-15/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name small.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/home/wierton/tmp/hunter -resource-dir /usr/lib/llvm-15/lib/clang/15.0.7 -internal-isystem /usr/lib/llvm-15/lib/clang/15.0.7/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/home/wierton/tmp/hunter -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/small-835e14.o -x c ./small.c
1.      ./small.c:9:41: current parser token ')'
2.      ./small.c:4:30: parsing function body 'vat'
3.      ./small.c:4:30: in compound statement ('{}')
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/small-29a2d3.c
clang: note: diagnostic msg: /tmp/small-29a2d3.sh
clang: note: diagnostic msg:

********************
```

My Clang version is:
```console
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by DimitryAndric** [comment]
Reproduces with trunk, and this has regressed with b1444edbf41c1fe9f7e676df6e873e9c9318283e ("[AST] Build recovery expression by default for all language") by @hokein @sam-mccall . 

Before b1444edbf41c1fe9f7e676df6e873e9c9318283e, it shows an error an a fixit hint:

```
pr62711.c:9:24: error: use of undeclared identifier 'global'; did you mean 'local'?
  if (__builtin_va_arg(global, int) << 1) abort();
                       ^~~~~~
                       local
pr62711.c:5:11: note: 'local' declared here
  va_list local;
          ^
1 error generated.
```

but afterwards, something goes wrong while creating the fixit message, apparently.
