### PR TITLE
[APFloat] Add exp functions for single and double using exp/expf implementations from LLVM libc.

### PR DESCRIPTION
**Pull request by lntue**
This reapplies #143959 with some changes:
- Only support default rounding modes for now.  Other rounding modes will wait for proper static rounding implementations in LLVM libc.
- Add both single and double precision exp.

### CODE REVIEW

File: llvm/lib/Support/APFloat.cpp [hunk 1]
```diff
@@ -6071,6 +6078,24 @@ APFloat::Storage &APFloat::Storage::operator=(APFloat::Storage &&RHS) {
   return *this;
 }
 
+// TODO: Support other rounding modes when LLVM libc math implement static
+// roundings.
+APFloat exp(const APFloat &X, RoundingMode rounding_mode) {
+  if (rounding_mode == APFloatBase::rmNearestTiesToEven) {
```
Comment (nikic) [inline llvm/lib/Support/APFloat.cpp]: I think it would make more sense to omit the argument entirely for now? We can add it once the support exists.

**Review by nickdesaulniers — APPROVED** [review]

File: llvm/unittests/ADT/APFloatTest.cpp [hunk 2]
```diff
@@ -10206,4 +10206,57 @@ TEST(APFloatTest, isValidArbitraryFPFormat) {
...
+  // exp(float max)
+  EXPECT_EQ(std::numeric_limits<float>::infinity(),
+            llvm::exp(APFloat::getLargest(APFloat::IEEEsingle(), false))
+                .convertToFloat());
+  // exp(min_denormal)
+  EXPECT_EQ(1.0f, llvm::exp(APFloat::getSmallest(APFloat::IEEEsingle(), false))
+                      .convertToFloat());
+  // exp(-1)
+  EXPECT_EQ(0x1.78b564p-2f, llvm::exp(APFloat(-1.0f)).convertToFloat());
+}
```
Comment (jcranmer-intel) [inline llvm/unittests/ADT/APFloatTest.cpp:10258]: Can you add a test for `llvm::exp(APFloat(-90.0f))`? And another for `llvm::exp(APFloat(-710.0))`?

(Both of those values are chosen to give a correctly-rounded result that's a denormal number for float and double, respectively, which should catch someone compiling with denormal flushing on.)

Comment (lntue) [reply llvm/unittests/ADT/APFloatTest.cpp:10258]: Done.

File: llvm/lib/Support/APFloat.cpp [hunk 3]
```diff
@@ -29,6 +29,13 @@
 #include <cstring>
 #include <limits.h>
 
+// Shared headers from LLVM libc
+// Make sure to add ${LLVM_SOURCE_DIR}/../libc to include directories.
+#define LIBC_NAMESPACE __llvm_libc_apfloat
+#define LIBC_MATH (LIBC_MATH_NO_ERRNO | LIBC_MATH_NO_EXCEPT)
```
Comment (AaronBallman) [inline llvm/lib/Support/APFloat.cpp:41]: This macro seems to be unused

File: llvm/lib/Target/AMDGPU/AMDGPULibCalls.cpp [hunk 4]
```diff
@@ -1868,7 +1868,7 @@ bool AMDGPULibCalls::evaluateScalarMathFunc(const FuncInfo &FInfo,
     return true;
 
   case AMDGPULibFunc::EI_EXP:
-    Res0 = APFloat{exp(opr0)};
+    Res0 = APFloat{std::exp(opr0)};
```
Comment (AaronBallman) [inline llvm/lib/Target/AMDGPU/AMDGPULibCalls.cpp:1871]: Two questions, neither of which impact this PR:

1) This is using host calls instead of calculating at runtime, is that actually correct?
2) Should all of these calls be switched to the `std::` form?

Comment (jcranmer-intel) [reply llvm/lib/Target/AMDGPU/AMDGPULibCalls.cpp:1871]: No, it's not correct; fixing that is a longer-term goal of which this PR is but the first step.

Comment (AaronBallman) [reply llvm/lib/Target/AMDGPU/AMDGPULibCalls.cpp:1871]: Okay, so we're making this change to preserve the status quo, but we'll eventually come back here to stop calling the `std::` variants?

File: llvm/lib/Support/APFloat.cpp (hunk 3 above)
Comment (lntue) [reply llvm/lib/Support/APFloat.cpp:41]: These are used inside the LLVM libc's implementation.  I'll add comments about their usage here.

**Comment by lntue** [comment]
ping: @arsenm @jcranmer-intel @AaronBallman

**Review by arsenm — APPROVED** [review]

**Review by jcranmer-intel — APPROVED** [review]

**Comment by ilovepi** [comment]
We're seeing some CI failures after this patch: http://cr-buildbucket.appspot.com/build/8681968716526848977.

```
/b/s/w/ir/x/w/llvm-llvm-project/llvm/../libc/src/__support/math/issignaling.h:18:27: error: expected unqualified-id
   18 | LIBC_INLINE constexpr int issignaling(double x) {
      |                           ^
/b/s/w/ir/x/w/cipd/linux/usr/include/math.h:292:7: note: expanded from macro 'issignaling'
  292 |      (sizeof (x) == sizeof (float)     
```

**Comment by lntue** [comment]
> We're seeing some CI failures after this patch: http://cr-buildbucket.appspot.com/build/8681968716526848977.
> 
> ```
> /b/s/w/ir/x/w/llvm-llvm-project/llvm/../libc/src/__support/math/issignaling.h:18:27: error: expected unqualified-id
>    18 | LIBC_INLINE constexpr int issignaling(double x) {
>       |                           ^
> /b/s/w/ir/x/w/cipd/linux/usr/include/math.h:292:7: note: expanded from macro 'issignaling'
>   292 |      (sizeof (x) == sizeof (float)     
> ```

Can you check https://github.com/llvm/llvm-project/pull/197328 ?  Thanks,

**Comment by dyung** [comment]
@lntue, your change is still failing to build on several build bots even after your recent fix in #197328. Can you take a look and revert if you need time to fix it so that we can get the bots green again?

https://lab.llvm.org/buildbot/#/builders/174/builds/35753
https://lab.llvm.org/buildbot/#/builders/202/builds/6733
https://lab.llvm.org/buildbot/#/builders/181/builds/43300

**Comment by lntue** [comment]
> @lntue, your change is still failing to build on several build bots even after your recent fix in #197328. Can you take a look and revert if you need time to fix it so that we can get the bots green again?
> 
> https://lab.llvm.org/buildbot/#/builders/174/builds/35753 https://lab.llvm.org/buildbot/#/builders/202/builds/6733 https://lab.llvm.org/buildbot/#/builders/181/builds/43300

Sorry for the noise, https://github.com/llvm/llvm-project/pull/197355 should fix the issues for gcc-pre-11

**Comment by joker-eph** [comment]
It's not fixed: 
```

/vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.src/llvm/../libc/src/__support/FPUtil/rounding_mode.h: In function ‘constexpr bool __llvm_libc_apfloat::fputil::fenv_is_round_down()’:
/vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.src/llvm/../libc/src/__support/FPUtil/rounding_mode.h:95:39: error: call to non-constexpr function ‘bool __llvm_libc_apfloat::fputil::generic::fenv_is_round_down()’
     return generic::fenv_is_round_down();
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

https://lab.llvm.org/buildbot/#/builders/116/builds/28500

**Comment by AdamMagierFOSS** [comment]
FWIW in our tests with this commit (from before the revert was merged) we found UBSan warnings when testing `llvm/unittests/ADT/APFloatTest.cpp` when CMake configures the compiler build with `-DLLVM_USE_SANITIZER='Undefined'`:

```
[==========] Running 16 tests from 15 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from APFloatTest
[ RUN      ] APFloatTest.getSmallestNormalized
[       OK ] APFloatTest.getSmallestNormalized (0 ms)
[ RUN      ] APFloatTest.exp
/path/to/llvm-project/llvm/../libc/src/__support/math/exp.h:414:49: runtime error: left shift of negative value -2
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /path/to/llvm-project/llvm/../libc/src/__support/math/exp.h:414:49
```

**Comment by echristo** [comment]
@lntue - so glad to see this going in! That said, having llvm depend on llvm-libc seems to be a bit of an unfortunate dependency. Can we rework part of this to either invert some of the dependency or a shared header that lives in llvm? Thoughts?

**Comment by lntue** [comment]
> @lntue - so glad to see this going in! That said, having llvm depend on llvm-libc seems to be a bit of an unfortunate dependency. Can we rework part of this to either invert some of the dependency or a shared header that lives in llvm? Thoughts?

@echristo So all the implementations of these in LLVM libc are free-standing header-only (https://github.com/llvm/llvm-project/issues/147386).  And for this PR, LLVM will just directly include the headers and build its own copy of math functions.  There is no direct dependency on the build systems or the objects / libraries.  And building this part inside LLVM does not require users to build anything in LLVM libc.

I don't see bringing the entire libm part out will get any benefits.  Currently, the libm parts are tested intensively in the llvm-libc projects, bringing them out to a separate projects will incur a big cost of duplication testing, without much gain.  We are adding more coverage for the shared headers (https://github.com/llvm/llvm-project/blob/main/.github/workflows/libc-shared-tests.yml) to make sure that it should cover most targets supported by LLVM.

**Comment by joker-eph** [comment]
Is there a precedent for including libc files from LLVM? If not that seems like the kind of thing that should go through an RFC on Discourse to get community visibility and buy-in. Even if it is "header only" that may not be "trivial" for everyone.

**Comment by nico** [comment]
There was an RFC for this a while ago: https://discourse.llvm.org/t/rfc-make-clang-builtin-math-functions-constexpr-with-llvm-libc-to-support-c-23-constexpr-math-functions/86450

**Comment by lntue** [comment]
> Is there a precedent for including libc files from LLVM? If not that seems like the kind of thing that should go through an RFC on Discourse to get community visibility and buy-in. Even if it is "header only" that may not be "trivial" for everyone.
> 

Additionally, libc++ is currently using libc files directly https://discourse.llvm.org/t/rfc-project-hand-in-hand-llvm-libc-libc-code-sharing/77701

**Comment by AaronBallman** [comment]
> There was an RFC for this a while ago: https://discourse.llvm.org/t/rfc-make-clang-builtin-math-functions-constexpr-with-llvm-libc-to-support-c-23-constexpr-math-functions/86450

It's also been discussed at LLVM Developer meetings: https://youtu.be/VAEO86YtTHA and had roundtable discussions, so there's been quite a bit of community discussion around the design for a few years now. That said, as we do the implementation work, we may run into pain points which warrant reopening the design discussion. (I don't see evidence we've hit anything more than the usual hiccups with new work, just a reminder that this was discussed quite a bit but isn't so firmly set in stone that we can't change direction if there's good reason to do so.)
