### ISSUE TITLE
Compilation error for incomplete vector type with clang-15

### ISSUE THREAD

**Issue by hudihuda** [llvm/llvm-project#57700]
The following code compiles fine with gcc-10.2, clang-14 (stdlibc++ and libc++) and with clang-15 stdlibc++. clang-15 with libc++ throws an error: arithmetic on a pointer to an incomplete type 'B'. All tests with --std=c++20.

```C++
#include <iostream>
#include <vector>

struct B;

struct A {
	A(std::vector<B> b) : m_(b){}
	std::vector<B> m_;
};

struct B {
	std::vector<A> m_;
};

int main() {
    std::cout << "main..." << std::endl;
}


```

**Comment by zygoloid** [comment]
[vector.overview]p4:

> An incomplete type T may be used when instantiating vector if the allocator meets the [allocator completeness requirements](http://eel.is/c++draft/allocator.requirements.completeness)[.](http://eel.is/c++draft/containers#vector.overview-4.sentence-1) T shall be complete before any member of the resulting specialization of vector is referenced[.](http://eel.is/c++draft/containers#vector.overview-4.sentence-2)

You're trying to reference the move constructor of `vector<B>` before `B` is defined, so you're violating this rule, and libc++ is permitted to reject such usage.

**Comment by zygoloid** [comment]
Probably what changed between libc++14 and libc++15 is that the `vector<B>` move constructor became `constexpr`, so it's now getting instantiated earlier.
