### PR TITLE
[Flang][runtime] Fix compilation errors introduced with PR #96652

### PR DESCRIPTION
**Pull request by mjklemm**

### CODE REVIEW

**Comment by mjklemm** [comment]
This is meant to fix the compilation error introduce with PR #96652

**Review by agozillon — APPROVED** [review]
LGTM! :-)
