### ISSUE TITLE
regression compiling cmake on macOS due to __hash_memory link errors

### ISSUE THREAD

**Issue by seanm** [llvm/llvm-project#155531]
I have bisected a link error I'm getting to https://github.com/llvm/llvm-project/commit/17d05695388128353662fbb80bbb7a13d172b41d.

One commit before that, all is well. Starting with that commit, I get this link error:

```
Undefined symbols for architecture arm64:
  "std::__1::__hash_memory(void const*, unsigned long)", referenced from:
      unsigned long std::__1::__do_string_hash[abi:se210000]<char const*>(char const*, char const*) in libCMakeLib.a[16](cmBinUtilsLinuxELFLinker.cxx.o)
```

This occurs using my own build of Clang (on arm64 macOS 26 beta, and x86_64 macOS 13) then using that to build CMake (and other projects too).

This is similar to https://github.com/llvm/llvm-project/issues/133304 which was closed as a duplicate of https://github.com/llvm/llvm-project/issues/79933 but that was close as "not planned" because basically "linux needs to add availability markups to libc++" but my issue is *on macOS*, where such availability markups do exist IIUC.  So I presume this is different.

@philnik777 @ldionne maybe you have some insight here? Thanks.

**Comment by seanm** [comment]
> How are you building Clang?

```
mkdir build
cd build
CC=/usr/bin/cc CXX=/usr/bin/c++ /Applications/CMake.app/Contents/bin/cmake -G Ninja -Wno-dev -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS='-w' -DCMAKE_CXX_FLAGS='-w' -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra' -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;libunwind;compiler-rt' -DLLVM_CREATE_XCODE_TOOLCHAIN=ON -DLLVM_BUILD_TOOLS=ON -DCLANG_INCLUDE_DOCS=OFF -DCLANG_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_ENABLE_LIBXML2=OFF -DCMAKE_INSTALL_PREFIX=/Users/sean/external/llvm-install ../llvm
ninja install
```

The `/usr/bin/cc` is from Xcode.

>Which libc++ headers do you use?

I don't know. How do I determine that? I didn't do anything to specify any explicitly.

>Do you possibly have libc++ headers from homebrew?

The macOS 13 Mac has brew, but the macOS 26 Mac does not (though it has MacPorts).

---------

@Voldemat thanks for figuring out a minimal case. I repro with that:

```
% xcrun /Users/sean/external/llvm-install/bin/clang++ test.cxx
ld: Undefined symbols:
  std::__1::__hash_memory(void const*, unsigned long), referenced from:
      unsigned long std::__1::__do_string_hash[abi:se220000]<char const*>(char const*, char const*) in test-c5ddd5.o
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by seanm** [comment]
@ldionne thanks for your reply. Could you elaborate though?

>

https://clang.llvm.org/get_started.html

**Comment by seanm** [comment]
@ldionne thanks for your reply, could you elaborate though?

>The problem is that you are using the LLVM 21 headers provided by your build from sources, but you're linking against the system-provided libc++.1.dylib

OK, but how am I doing ether of those? The clang invocation is just:

`xcrun /Users/sean/external/llvm-install/bin/clang++ test.cxx`

Is it the presence of `xcrun` that is making me use the system-provided `libc++.1.dylib`?

What is making me use the headers from my own build?

What incantation do I need to make the clang I've built work?

Thanks.

**Comment by ldionne** [comment]
> [@ldionne](https://github.com/ldionne) thanks for your reply, could you elaborate though?
> 
> > The problem is that you are using the LLVM 21 headers provided by your build from sources, but you're linking against the system-provided libc++.1.dylib
> 
> OK, but how am I doing ether of those? The clang invocation is just:

That's the behavior that Clang has out of the box, basically. You're not doing anything wrong, IMO this is a bug in Clang.

> 
> `xcrun /Users/sean/external/llvm-install/bin/clang++ test.cxx`
> 
> Is it the presence of `xcrun` that is making me use the system-provided `libc++.1.dylib`?

No. `xcrun` sets the `SDKROOT` environment variable, and then Clang picks that up and uses it as a sysroot (roughly equivalent to passing `-isysroot <SDKROOT>`.

> 
> What is making me use the headers from my own build?

By default, Clang will check (in order):
1a. The `include/c++/v1` relative to Clang's executable
2a. The `include/c++/v1` relative to the sysroot (which for you is `SDKROOT` since you use `xcrun`)

The exact logic is here: https://github.com/llvm/llvm-project/blob/main/clang/lib/Driver/ToolChains/Darwin.cpp#L2748-L2760

Now, in your case, since Clang finds `include/c++/v1` at `<clang-executable-folder>/../include/c++/v1`, it stops at (1a) and uses that, which corresponds to your just-built libc++ headers.

The problem is that it doesn't do the same thing when figuring out which library to link against. For linking, it simply uses the one from the sysroot, without checking if you might have a just-built libc++ available relative to the Clang executable. In other words, you probably have both:
1b. `<clang-executable-folder>/../lib/libc++.1.dylib`
2b. `SDKROOT/usr/lib/libc++.1.dylib`

But unlike for the header search path logic, here it goes straight to (2b) and ignores (1b).

That way, you end up mixing (1a) with (2b), when what you want is (1a) with (2a).

> 
> What incantation do I need to make the clang I've built work?

It sucks, but I think that adding `-L <clang-executable-folder>/../lib` should fix your issue. That being said, you'll also need to make sure that the executables you produce are able to find `<clang-executable-folder>/../lib/libc++.1.dylib` at runtime, which might require setting up some rpaths or playing with `DYLD_LIBRARY_PATH`.

**Comment by Voldemat** [comment]
Is it possible to add some default compile options to clang when compiling? I pocked around in cmake files but didn`t found anything like that, I think having cmake variable that embeds set of default options inside compiler would be extremely useful in such cases.

**Comment by seanm** [comment]
>It sucks, but I think that adding -L <clang-executable-folder>/../lib should fix your issue. That being said, you'll also need to make sure that...

It seems rather fraught...

I just tried something else: I removed `libcxx;libcxxabi` from `LLVM_ENABLE_RUNTIMES` and this appears to get me a working compiler!

**Comment by hoyhoy** [comment]
My runtime looks correct...

```
$ otool -l /opt/llvm21.1.0/lib/clang/21/lib/darwin/libclang_rt.asan_osx_dynamic.dylib | grep libc++
         name @rpath/libc++abi.1.dylib (offset 24)
         name @rpath/libc++.1.dylib (offset 24)

$ otool -l /opt/llvm21.1.0/lib/clang/21/lib/darwin/libclang_rt.asan_osx_dynamic.dylib  | grep -A3 LC_RPATH | grep -v cmdsize | grep -v Load
          cmd LC_RPATH
         path /opt/llvm21.1.0/lib (offset 12)
          cmd LC_RPATH
         path /opt/llvm21.1.0/lib/darwin (offset 12)
```

**Comment by hoyhoy** [comment]
I ended up just reverting the libcxx ABI changes.  This has been working for me.

https://gist.github.com/hoyhoy/d1381ed27b951fc8bdfc9fbfb6089fed

**Comment by cjones051073** [comment]
> I'm not aware of anything that allows doing that. IMO we should just fix the compiler so it does the right thing out of the box.

"The right thing" on macOS is not linking against its own libc++. Linking against the system provided libc++ is the only thing to do if you want interoperability of binaries produced with clang-21 with binaries produced with other compilers. Mixing binaries in the same runtime that have been linked against different libc++ implementations is just a route to pain.

**Comment by chandlerc** [comment]
> > > I'm not aware of anything that allows doing that. IMO we should just fix the compiler so it does the right thing out of the box.
> > 
> > 
> > "The right thing" on macOS is not linking against its own libc++. Linking against the system provided libc++ is the only thing to do if you want interoperability of binaries produced with clang-21 with binaries produced with other compilers. Mixing binaries in the same runtime that have been linked against different libc++ implementations is just a route to pain.
> 
> Linking random libraries together is never "the right thing". If you build your own libc++, use the one you built and not an unrelated one. That will only ever result in hard to debug ODR violations (see this very issue). If you want ABI compatibility, use the system libc++ and not one you built.

Because macOS has many OS system libraries with C++ code on the API boundary, my understanding is that it really is problematic to link the just-built libc++ -- you need to use the same one as the system libraries. So my expectation is that the compiler fix here is "don't use just-built headers on macOS without an explicit flag".

FWIW, I'd be happy to be wrong, just my understanding.

**Comment by philnik777** [comment]
> 
> Don't get me wrong - I agree that in theory what you are saying is of course the correct thing to do, to use the libc++ runtime built with the clang you are using with the c++ headers for that clang. The point I am trying to make is in real life that is impractical on macOS as it would render any binaries created by that inoperable with any of the system libraries on binaries created with other compilers.
> 
> In MacPorts, we offer our own builds of clang largely to allow, on systems where the Xcode provided SDK versions are too old and don't offer more modern features, access to newer compiler features. Most of the time, these new features only require the c++ headers, they are inline only, so doing precisely what LLVM/clang has (is) doing, using the new c++ headers but linking against the system libc++ is in practical terms what we want. Yes, we are aware that this is not perfect, and sometimes, on (much) older systems we run into problems with the system libc++ lacking certain things, but the vast majority of the time this isn't an issue. The issue here is this is the first time we have seen issues like this hit the most recent OS (I am on macOS15) and in a commonly used feature. So it basically renders the compiler in its current form useless to us.
> 
> Sure, we could just remove libcxx from the enabled runtimes for clang when we build it. But then we don't get the new headers as well and the new clang just uses the system SDK versions. So we loose all the benefits of why we do this, to pick up new features available in those new headers.

How much newer are the headers you actually get? the system SDK should provide fairly recent ones.

> I guess I need to see how this issues evolves. If its decided that LLVM will switch to no longer linking against the system libc++ on macOS, and instead use the newly created on, as formally correct as that might be, it will fundamentally alter (degrade) MacPorts relationship with new compilers and we will have to see how we handle that.
> 
> If you stick with linking against the system libc++, then this means clang-21(and newer) will only be usable on some future) macOS system where the new libc++ ABI changes hit the system version.

As far as I'm aware the system libraries don't have C++ APIs, do they? Assuming that case, to avoid name clashes, the right thing to do is to change the inline namespace of libc++ and ship your own dylib, not hope that things happen to work out.
You can also set `-DLIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS=On` when building libc++ to get the appropriate annotations to make your scenario work. This is just as unsupported as anything else you're doing, but that would most likely solve your issue.

(Just as a note, I feel like we're kinda moving off-topic. Maybe we should move this discussion elsewhere.)

**Comment by cjones051073** [comment]
> > Don't get me wrong - I agree that in theory what you are saying is of course the correct thing to do, to use the libc++ runtime built with the clang you are using with the c++ headers for that clang. The point I am trying to make is in real life that is impractical on macOS as it would render any binaries created by that inoperable with any of the system libraries on binaries created with other compilers.
> > In MacPorts, we offer our own builds of clang largely to allow, on systems where the Xcode provided SDK versions are too old and don't offer more modern features, access to newer compiler features. Most of the time, these new features only require the c++ headers, they are inline only, so doing precisely what LLVM/clang has (is) doing, using the new c++ headers but linking against the system libc++ is in practical terms what we want. Yes, we are aware that this is not perfect, and sometimes, on (much) older systems we run into problems with the system libc++ lacking certain things, but the vast majority of the time this isn't an issue. The issue here is this is the first time we have seen issues like this hit the most recent OS (I am on macOS15) and in a commonly used feature. So it basically renders the compiler in its current form useless to us.
> > Sure, we could just remove libcxx from the enabled runtimes for clang when we build it. But then we don't get the new headers as well and the new clang just uses the system SDK versions. So we loose all the benefits of why we do this, to pick up new features available in those new headers.
> 
> How much newer are the headers you actually get? the system SDK should provide fairly recent ones.

Depends. On newer system not so much but then we tend to use the Xcode provided clang there most of the time.

However, we support older macOS systems, going back far further than upstream LLVM supports, and here it really helps for instance if a package requires a newer c++ standard than the system Xcode provided clang supports. This is a very regular use case.

> 
> > I guess I need to see how this issues evolves. If its decided that LLVM will switch to no longer linking against the system libc++ on macOS, and instead use the newly created on, as formally correct as that might be, it will fundamentally alter (degrade) MacPorts relationship with new compilers and we will have to see how we handle that.
> > If you stick with linking against the system libc++, then this means clang-21(and newer) will only be usable on some future) macOS system where the new libc++ ABI changes hit the system version.
> 
> As far as I'm aware the system libraries don't have C++ APIs, do they? Assuming that case, to avoid name clashes, the right thing to do is to change the inline namespace of libc++ and ship your own dylib, not hope that things happen to work out. You can also set `-DLIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS=On` when building libc++ to get the appropriate annotations to make your scenario work. This is just as unsupported as anything else you're doing, but that would most likely solve your issue.

Yeah, this falls under the "I will need to think how best to handle this" as there are a bunch of other requirements we have I haven't really gone into that might also be broken by all this...

> (Just as a note, I feel like we're kinda moving off-topic. Maybe we should move this discussion elsewhere.)

probably..

**Comment by hoyhoy** [comment]
Hmm, `LIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS` is set in `libcxx/cmake/caches/Apple.cmake`, but apparently that doesn't get sourced if you build llvm on macOS....

The only way I could get a working compiler was reverting 17d05695 and 9fdb4f35.

I never set `LIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS` on llvm 17, 18, 19, or 20, and everything worked for me.

**Comment by hoyhoy** [comment]
Yeah, setting `LIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS=ON` works.  I reverted my reverts and everything is compiling...

**Comment by hoyhoy** [comment]
Also, if we absolutely must set `LIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS` to make LLVM work on macOS, why isn't it set by default?

**Comment by cjones051073** [comment]
> I built llvm 21.1.1 with `LIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS=ON`, but I still get this...
> 
> ```
> ld64.lld: error: undefined symbol: std::__1::__hash_memory(void const*, unsigned long)
> >>> referenced by .conan2/p/b/proto856b5ac6948fd/b/src/src/google/protobuf/compiler/command_line_interface.cc
> >>>               libprotocd.a(command_line_interface.cc.o):(symbol unsigned long std::__1::__do_string_hash[abi:ne210101]<char const*>(char const*, char const*)+0x24)
> >>> referenced by .conan2/p/b/proto856b5ac6948fd/b/src/src/google/protobuf/compiler/cpp/file.cc
> >>>               libprotocd.a(file.cc.o):(symbol std::__1::hash<google::protobuf::Descriptor const*>::operator()[abi:ne210101](google::protobuf::Descriptor const*) const+0xe0)
> >>> referenced by .conan2/p/b/proto856b5ac6948fd/b/src/src/google/protobuf/compiler/cpp/file.cc
> >>>               libprotocd.a(file.cc.o):(symbol std::__1::hash<google::protobuf::FileDescriptor const*>::operator()[abi:ne210101](google::protobuf::FileDescriptor const*) const+0xe0)
> >>> referenced 2 more times
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> It must only work if you rebuild the runtime separately... MacPorts ended up using my patch that reverted the recent libcxx changes.

No, we are no longer using that patch. We just set `LIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS=ON` now.

**Comment by hoyhoy** [comment]
I tried `-L` at first, but that didn't work for me.  I have a cfg file for clang.  I turned it on there, but that didn't work at runtime with ASAN enabled.

> I ended up solving the particular issue for my llvm-dependent codebase with:
> 
>   if (APPLE AND LLVM_LIBRARY_DIR)
>     # Homebrew deploys libc++ along with the llvm package. We must point to it
>     # otherwise clang will use the header files of the package and link to
>     # system libc++. See llvm/llvm-project#155531 and Homebrew/homebrew-core#235411
>     target_link_directories(<target> PUBLIC ${LLVM_LIBRARY_DIR}/c++)
>   endif()
> This change adds a `-L` to the package provided libc++...

**Comment by hoyhoy** [comment]
I ended up refactoring my llvm build script to do a two-stage build on macOS 15.7 on x86_64h.  Everything is working now.

https://gist.github.com/hoyhoy/492cf3077239baececb6b838bf620d39

This also solved my lipo issues discussed here... 

https://github.com/llvm/llvm-project/issues/84649

**Comment by maxence-glt** [comment]
21.1.8 has the same issue

```cpp
❱ make run
clang++ -O0 -g main.cpp

Undefined symbols for architecture arm64:
  "std::__1::__hash_memory(void const*, unsigned long)", referenced from:
      ltmp21 in main-57097c.o
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [run] Error 1

❱ llvm-config --version
21.1.8

❱ cat main.cpp
#include <iostream>
#include <unordered_map>

int main() {
    std::unordered_map<std::string, int> m;
    m["test"] = 3;

    return 0;
}
```

**Comment by laverdet** [comment]
I just added a shim to my project. The intent is to compile with latest clang & header-only libc++ features but produce a distributable binary that doesn't need a custom stdlib.

```cc
#include <__functional/hash.h>
namespace std::inline __1 {
auto __hash_memory([[_Clang::__noescape__]] const void *ptr, size_t size) noexcept -> size_t {
  return __murmur2_or_cityhash<size_t>()(ptr, size);
}
} // namespace std::inline __1
```
