### PR TITLE
[libc][math] Refactor log10, log1p, log2 implementation to header-only in src/__support/math folder.

### PR DESCRIPTION
**Pull request by nico**
Part of #147386

in preparation for:
https://discourse.llvm.org/t/rfc-make-clang-builtin-math-functions-constexpr-with-llvm-libc-to-support-c-23-constexpr-math-functions/86450

### CODE REVIEW

File: libc/src/__support/math/CMakeLists.txt [hunk 1]
```diff
@@ -1053,6 +1053,56 @@ add_header_library(
...
+    libc.src.__support.FPUtil.double_double
+    libc.src.__support.FPUtil.dyadic_float
+    libc.src.__support.FPUtil.fenv_impl
+    libc.src.__support.FPUtil.fp_bits
+    libc.src.__support.FPUtil.multiply_add
+    libc.src.__support.FPUtil.polyeval
+    libc.src.__support.integer_literals
+    libc.src.__support.macros.optimization
+    libc.src.__support.math.common_constants
+    libc.src.__support.math.log_range_reduction
```
Comment (bassiounix) [inline libc/src/__support/math/CMakeLists.txt]:
```suggestion
    .common_constants
    .log_range_reduction
    libc.src.__support.FPUtil.double_double
    libc.src.__support.FPUtil.dyadic_float
    libc.src.__support.FPUtil.fenv_impl
    libc.src.__support.FPUtil.fp_bits
    libc.src.__support.FPUtil.multiply_add
    libc.src.__support.FPUtil.polyeval
    libc.src.__support.integer_literals
    libc.src.__support.macros.optimization
```

File: libc/src/__support/math/CMakeLists.txt [hunk 2]
```diff
@@ -1053,6 +1053,56 @@ add_header_library(
...
+  DEPENDS
+    libc.src.__support.FPUtil.double_double
+    libc.src.__support.FPUtil.dyadic_float
+    libc.src.__support.FPUtil.fenv_impl
+    libc.src.__support.FPUtil.fp_bits
+    libc.src.__support.FPUtil.multiply_add
+    libc.src.__support.FPUtil.polyeval
+    libc.src.__support.integer_literals
+    libc.src.__support.macros.optimization
+    libc.src.__support.math.common_constants
```
Comment (bassiounix) [inline libc/src/__support/math/CMakeLists.txt]:
```suggestion
    .common_constants
    libc.src.__support.FPUtil.double_double
    libc.src.__support.FPUtil.dyadic_float
    libc.src.__support.FPUtil.fenv_impl
    libc.src.__support.FPUtil.fp_bits
    libc.src.__support.FPUtil.multiply_add
    libc.src.__support.FPUtil.polyeval
    libc.src.__support.integer_literals
    libc.src.__support.macros.optimization
```

File: libc/src/__support/math/log10.h [hunk 3]
```diff
@@ -0,0 +1,917 @@
...
+//     l = hex(value)[2:]
+//     n = 8
+//     x = [l[i:i + n] for i in range(0, len(l), n)]
+//     return "0x" + "'".join(x) + "_u128"
+// (s, m, e) = RealField(128)(2).log10().sign_exponent_mantissa();
+// print(format_hex(m));
+constexpr Float128 LOG10_2(Sign::POS, /*exponent=*/-129, /*mantissa=*/
+                           0x9a209a84'fbcff798'8f8959ac'0b7c9178_u128);
+
+alignas(16) constexpr LogRR LOG10_TABLE = {
```
Comment (bassiounix) [inline libc/src/__support/math/log10.h]:
```suggestion
alignas(16) LIBC_INLINE_VAR constexpr LogRR LOG10_TABLE = {
```

File: libc/src/__support/math/log10.h [hunk 4]
```diff
@@ -0,0 +1,917 @@
...
+        {Sign::POS, -151, 0xd768fb85'48d78dd0'b76d969d'42ce9734_u128},
+        {Sign::POS, -151, 0xdae26af5'800f7def'08e39b87'02d0373a_u128},
+        {Sign::POS, -151, 0xde5bda65'eede65ed'6d0063a9'23dd0cc6_u128},
+    }};
+
+// > P = fpminimax(log10(1 + x)/x, 3, [|128...|], [-0x1.0002143p-29 , 0x1p-29]);
+// > P;
+// > dirtyinfnorm(log10(1 + x)/x - P, [-0x1.0002143p-29 , 0x1p-29]);
+// 0x1.64fb8...p-123
+constexpr Float128 BIG_COEFFS[4]{
```
Comment (bassiounix) [inline libc/src/__support/math/log10.h]:
```suggestion
LIBC_INLINE_VAR constexpr Float128 BIG_COEFFS[4]{
```

File: libc/src/__support/math/log10.h [hunk 5]
```diff
@@ -0,0 +1,917 @@
...
+    {Sign::NEG, -131, 0xde5bd8a9'373f89a7'6903c4ce'1582517d_u128},
+    {Sign::POS, -130, 0x943d3b1b'7a1af679'b8a21791'624e2e8a_u128},
+    {Sign::NEG, -130, 0xde5bd8a9'37287195'355baaaf'abc25990_u128},
+    {Sign::POS, -129, 0xde5bd8a9'37287195'355baaaf'ad33dbd9_u128},
+};
+
+// Reuse the output of the fast pass range reduction.
+// -2^-8 <= m_x < 2^-7
+double log10_accurate(int e_x, int index, double m_x) {
```
Comment (bassiounix) [inline libc/src/__support/math/log10.h]:
```suggestion
LIBC_INLINE static constexpr double log10_accurate(int e_x, int index, double m_x) {
```

If you had problems with GCC remove `constexpr` qualifier.

File: libc/src/__support/math/log10.h [hunk 6]
```diff
@@ -0,0 +1,917 @@
...
+#else
+  uint64_t c_m = x_m & 0x3FFF'E000'0000'0000ULL;
+  double c = FPBits_t(c_m).get_val();
+  double u = fputil::multiply_add(r, m - c, CD[index]); // exact
+#endif // LIBC_TARGET_CPU_HAS_FMA_DOUBLE
+
+  // Error of u_sq = ulp(u^2);
+  double u_sq = u * u;
+  // Degree-7 minimax polynomial
+  double p0 = fputil::multiply_add(u, LOG_COEFFS[1], LOG_COEFFS[0]);
```
Comment (bassiounix) [inline libc/src/__support/math/log10.h]: Did you compile with GCC12.2?
I'm certain that this should raise compilation errors due to the current nature of `multiply_add`.

File: libc/src/__support/math/log1p.h [hunk 7]
```diff
@@ -0,0 +1,1068 @@
...
+namespace log1p_internal {
+// 128-bit precision dyadic floating point numbers.
+using Float128 = typename fputil::DyadicFloat<128>;
+
+using LIBC_NAMESPACE::operator""_u128;
+
+using namespace common_constants_internal;
+
+// R1[i] = 2^-8 * nearestint( 2^8 / (1 + i * 2^-7) )
+constexpr double R1[129] = {
```
Comment (bassiounix) [inline libc/src/__support/math/log1p.h]:
```suggestion
LIBC_INLINE_VAR constexpr double R1[129] = {
```

File: libc/src/__support/math/log1p.h [hunk 8]
```diff
@@ -0,0 +1,1068 @@
...
+    0x1.0ap-1, 0x1.08p-1, 0x1.08p-1, 0x1.06p-1, 0x1.06p-1, 0x1.04p-1, 0x1.04p-1,
+    0x1.02p-1, 0x1.02p-1, 0x1p-1,
+};
+
+// Extra constants for exact range reduction when FMA instructions are not
+// available:
+// r * c - 1 for r = 2^-8 * nearestint( 2^8 / (1 + i * 2^-7))
+//           and c = 1 + i * 2^-7
+//           with i = 0..128.
+[[maybe_unused]] constexpr double RCM1[129] = {
```
Comment (bassiounix) [inline libc/src/__support/math/log1p.h]:
```suggestion
[[maybe_unused]] LIBC_INLINE_VAR constexpr double RCM1[129] = {
```

File: libc/src/__support/math/log1p.h [hunk 9]
```diff
@@ -0,0 +1,1068 @@
...
+    {0x1.202380cda46bep-45, 0x1.5ee82aa2418p-1},
+    {0x1.202380cda46bep-45, 0x1.5ee82aa2418p-1},
+    {0.0, 0.0},
+};
+
+// Degree-7 minimax polynomial log(1 + v) ~ v - v^2 / 2 + ...
+// generated by Sollya with:
+// > P = fpminimax(log(1 + x)/x, 6, [|1, 1, D...|],
+//                 [-0x1.69000000000edp-8, 0x1.7f00000000081p-8]);
+constexpr double P_COEFFS[6] = {-0x1p-1,
```
Comment (bassiounix) [inline libc/src/__support/math/log1p.h]:
```suggestion
LIBC_INLINE_VAR constexpr double P_COEFFS[6] = {-0x1p-1,
```

File: libc/src/__support/math/log1p.h [hunk 10]
```diff
@@ -0,0 +1,1068 @@
...
+constexpr Float128 LOG_2(Sign::POS, /*exponent=*/-128, /*mantissa=*/
+                         0xb17217f7'd1cf79ab'c9e3b398'03f2f6af_u128);
+
+// -log(r1) with 128-bit precision generated by SageMath with:
+//
+// for i in range(129):
+//   r = 2^-8 * round( 2^8 / (1 + i*2^(-7)) );
+//   s, m, e = RealField(128)(r).log().sign_mantissa_exponent();
+//   print("{Sign::POS,", e, ", format_hex(m), "},");
+constexpr Float128 LOG_R1[129] = {
```
Comment (bassiounix) [inline libc/src/__support/math/log1p.h]:
```suggestion
LIBC_INLINE_VAR constexpr Float128 LOG_R1[129] = {
```

File: libc/src/__support/math/log1p.h [hunk 11]
```diff
@@ -0,0 +1,1068 @@
...
+    {Sign::POS, -128, 0xaf741551'20c9011c'066d235e'e63073dd_u128},
+    {Sign::POS, -128, 0xaf741551'20c9011c'066d235e'e63073dd_u128},
+    {Sign::POS, 0, 0_u128},
+};
+
+// Logarithm range reduction - Step 2:
+//   s(k) = 2^-18 round( 2^18 / (1 + k*2^-14) ) - 1 for k = -91 .. 96
+// Output range:
+//   [-0x1.1037c00000040271p-15 , 0x1.108480000008096cp-15]
+constexpr double S2[198] = {
```
Comment (bassiounix) [inline libc/src/__support/math/log1p.h]:
```suggestion
LIBC_INLINE_VAR constexpr double S2[198] = {
```

File: libc/src/__support/math/log1p.h [hunk 12]
```diff
@@ -0,0 +1,1068 @@
...
+};
+
+// -log(r) for the second step, generated by SageMath with:
+//
+// for i in range(-91, 97):
+//   r = 2^-18 * round( 2^18 / (1 + i*2^(-14)) );
+//   s, m, e = RealField(128)(r).log().sign_mantissa_exponent();
+//   print("{Sign::POS," if (s == -1) else "{Sign::NEG,", e, ",
+//         format_hex(m), "},");
+constexpr Float128 LOG_R2[198] = {
```
Comment (bassiounix) [inline libc/src/__support/math/log1p.h]:
```suggestion
LIBC_INLINE_VAR constexpr Float128 LOG_R2[198] = {
```

File: libc/src/__support/math/log1p.h [hunk 13]
```diff
@@ -0,0 +1,1068 @@
...
+};
+
+// -log(r) for the third step, generated by SageMath with:
+//
+// for i in range(-69, 70):
+//   r = 2^-21 * round( 2^21 / (1 + i*2^(-21)) );
+//   s, m, e = RealField(128)(r).log().sign_mantissa_exponent();
+//   print("{Sign::POS," if (s == -1) else "{Sign::NEG,", e, ",
+//         format_hex(m), "},");
+constexpr Float128 LOG_R3[139] = {
```
Comment (bassiounix) [inline libc/src/__support/math/log1p.h]:
```suggestion
LIBC_INLINE_VAR constexpr Float128 LOG_R3[139] = {
```

File: libc/src/__support/math/log1p.h [hunk 14]
```diff
@@ -0,0 +1,1068 @@
...
+    {Sign::POS, -142, 0x8a0094c8'd5e0d9e1'c5a59fd3'6bd44397_u128},
+};
+
+// Minimax polynomial generated by Sollya with:
+// > P = fpminimax((log(1 + x) - x)/x^2, 3, [|1, 128...|],
+//                 [-0x1.01928p-22 , 0x1p-22]);
+// > P;
+// > dirtyinfnorm(log(1 + x)/x - 1 - x*P, [-0x1.01928p-22 , 0x1p-22]);
+// 0x1.ce1e...p-116
+constexpr Float128 BIG_COEFFS[4]{
```
Comment (bassiounix) [inline libc/src/__support/math/log1p.h]:
```suggestion
LIBC_INLINE_VAR constexpr Float128 BIG_COEFFS[4]{
```

File: libc/src/__support/math/log2.h [hunk 15]
```diff
@@ -0,0 +1,978 @@
...
+#endif // LIBC_TARGET_CPU_HAS_FMA_DOUBLE
+
+  // Exact sum:
+  //   r1.hi + r1.lo = e_x * log(2)_hi - log(r)_hi + u
+  r1 = fputil::exact_add(LOG_R1[index].hi, u);
+
+  // Error of u_sq = ulp(u^2);
+  double u_sq = u * u;
+  // Degree-7 minimax polynomial
+  double p0 = fputil::multiply_add(u, LOG_COEFFS[1], LOG_COEFFS[0]);
```
Comment (bassiounix) [inline libc/src/__support/math/log2.h]: Did you compile with GCC12.2?
I'm certain that this should raise compilation errors due to the current nature of `multiply_add`.

File: libc/src/__support/math/log2.h [hunk 16]
```diff
@@ -0,0 +1,978 @@
...
+namespace log2_internal {
+// 128-bit precision dyadic floating point numbers.
+using Float128 = typename fputil::DyadicFloat<128>;
+
+using LIBC_NAMESPACE::operator""_u128;
+
+using namespace common_constants_internal;
+using namespace math::log_range_reduction_internal;
+
+constexpr fputil::DoubleDouble LOG2_E = {0x1.777d0ffda0d24p-56,
```
Comment (bassiounix) [inline libc/src/__support/math/log2.h]:
```suggestion
LIBC_INLINE_VAR constexpr fputil::DoubleDouble LOG2_E = {0x1.777d0ffda0d24p-56,
```

File: libc/src/__support/math/log2.h [hunk 17]
```diff
@@ -0,0 +1,978 @@
...
+                                         0x1.71547652b82fep0};
+
+alignas(16) const fputil::DoubleDouble LOG_R1[128] = {
```
Comment (bassiounix) [inline libc/src/__support/math/log2.h]:
```suggestion
alignas(16) LIBC_INLINE_VAR constexpr fputil::DoubleDouble LOG_R1[128] = {
```

File: libc/src/__support/math/log2.h [hunk 18]
```diff
@@ -0,0 +1,978 @@
...
+        {Sign::POS, -149, 0xb2e4eaaa'acbebbbe'5aca1bc7'77a54d5e_u128},
+        {Sign::POS, -149, 0xb5c793a2'979323ee'd5094eb9'9a35d1f0_u128},
+        {Sign::POS, -149, 0xb8aa3c9a'b0921c55'357b5aa4'ac49738d_u128},
+    }};
+
+// > P = fpminimax(log2(1 + x)/x, 3, [|128...|], [-0x1.0002143p-29 , 0x1p-29]);
+// > P;
+// > dirtyinfnorm(log2(1 + x)/x - P, [-0x1.0002143p-29 , 0x1p-29]);
+// 0x1.27ad5...p-121
+constexpr Float128 BIG_COEFFS[4]{
```
Comment (bassiounix) [inline libc/src/__support/math/log2.h]:
```suggestion
LIBC_INLINE_VAR constexpr Float128 BIG_COEFFS[4]{
```

**Review by bassiounix — CHANGES_REQUESTED** [review]
Thank you for the refactor. Overall LGTM with some small changes.
Also please confirm that this change compiles with GCC12.2 locally.
If you had any compilation errors because of `constexpr` qualifier, you can safely remove it.

File: libc/src/__support/math/log10.h (hunk 6 above)
Comment (nico) [reply libc/src/__support/math/log10.h]: No, I'm on macOS and I'm building with system clang.

Does CI not cover gcc 12.2? (If not, why not? Missing capacity?

**Comment by bassiounix** [comment]
> As asked above, any reason why that isn't covered by CI?

I requested the addition of those to the CI, we only have gcc build bots for main not the precommit CI

> Is the "build with gcc12.2 before sending patches" requirement documented somewhere?

I actually don't know, but what I know from libc maintainers that libc has to compile with both clang and gcc.

> I appreciate the time you're taking to educate me here.

it's nothing really, I'm happy to help :)

> ps: Oh, do you want me to change anything about the bazel files?

I don't think the failures are because of your code, there's a problem with the main bazel build files. we can decide what to do about those once you finish your changes.

> It feels like nobody's really building libm with gcc on a mac. Is linux required to be able to make libm patches?

It's not that linux is required but we need to make sure that all of the supported targets of libc compile and pass the requirements, including linux.
If you want you can try to setup a VM to use GCC or even qemu would be enough, even docker is a fine option or trying to use online machine to try and compile your code.

In any case, you can safely now remove the `constexpr` qualifier because I know for a fact it won't compile.

Also resolve the conflicts and I think you'd be good to go!

**Comment by AnonMiraj** [comment]
> > Is the "build with gcc12.2 before sending patches" requirement documented somewhere?
> 
> I actually don't know, but what I know from libc maintainers that libc has to compile with both clang and gcc.

https://github.com/llvm/llvm-project/blob/4885d1fcf6d8d2a86d0579439cf0a96122106ad1/libc/src/math/docs/add_math_function.md?plain=1#L175

File: libc/src/__support/math/log10.h [hunk 19]
```diff
@@ -0,0 +1,917 @@
...
+namespace log10_internal {
+// 128-bit precision dyadic floating point numbers.
+using Float128 = typename fputil::DyadicFloat<128>;
+
+using LIBC_NAMESPACE::operator""_u128;
+
+using namespace common_constants_internal;
+using namespace math::log_range_reduction_internal;
+
+constexpr fputil::DoubleDouble LOG10_E = {0x1.95355baaafad3p-57,
```
[the remark this answers is not in the document]
Comment (bassiounix) [reply libc/src/__support/math/log10.h]: Could you please add this?

File: libc/src/__support/math/log1p.h [hunk 20]
```diff
@@ -0,0 +1,1068 @@
...
+  // Range reduction:
+  // Find k such that |x_hi - k * 2^-7| <= 2^-8.
+  int idx = static_cast<int>((xhi_frac + (1ULL << (FRACTION_LEN - 8))) >>
+                             (FRACTION_LEN - 7));
+  int x_e = xhi_bits.get_exponent() + (idx >> 7);
+  double e_x = static_cast<double>(x_e);
+
+  // hi is exact
+  // ulp(hi) = ulp(LOG_2_HI) = ulp(LOG_R1_DD[idx].hi) = 2^-43
+  double hi = fputil::multiply_add(e_x, LOG_2_HI, LOG_R1_DD[idx].hi);
```
[the remark this answers is not in the document]
Comment (bassiounix) [reply libc/src/__support/math/log1p.h]: I am still skeptical of keeping this function `constexpr`, I'd prefer to remove the qualifier now until we fix the internal code with `constexpr`, which is outside of this refactor scope.

**Review by bassiounix — CHANGES_REQUESTED** [review]
LGTM overall with some nits.

**Comment by nico** [comment]
Both done, thanks!
