### ISSUE TITLE
Shared library builds but doesn't work on Mac OS X 10.6

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9357]
|  |  |
| --- | --- |
| Bugzilla Link | [8985](https://llvm.org/bz8985) |
| Version | 2.8 |
| OS | MacOS X |
| Attachments | [Makefile.rules patch for Mac OS X 10.6](https://user-images.githubusercontent.com/60944935/143742557-74f6aafe-f11f-45b6-b219-726bcad354a3.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Using ./configure  --enable-shared compiles cleanly but as soon as one tries to load the library--for example, in Ruby using FFI--the following error is generated.

dyld: loaded: /Users/<user>/llvm/2.8/lib/libLLVM-2.8.dylib
dyld: lazy symbol binding failed: Symbol not
found:__ZN4llvm2cl6Option11addArgumentEv
  Referenced from: /Users/<user>/llvm/2.8/lib/libLLVM-2.8.dylib
  Expected in: flat namespace

dyld: Symbol not found: __ZN4llvm2cl6Option11addArgumentEv
  Referenced from: /Users/<user>/llvm/2.8/lib/libLLVM-2.8.dylib
  Expected in: flat namespace

Trace/BPT trap

Applying the attached patch fixes the problem.

The modified options use the default two-level namespace on OS X and change name resolution to run time lookup. The library compiles cleanly and loads properly with those options.

Using those options doesn't seem to have any ill effect but maybe there's a reason why the former options were used, although many dynamic libraries for Mac OS X are compiled with the latter--the former actually seems to be a legacy from pre-10.3 days.

**Comment by Endilll** [comment]
Autoconf support was deprecated and removed in 2016.
Feel free to reopen if you encounter similar issue with CMake.
