### ISSUE TITLE
Regression in `Bindings/OCaml/core.ml`

### ISSUE THREAD

**Issue by tuliom** [llvm/llvm-project#86944]
The LLVM test `Bindings/OCaml/core.ml` started to fail after commit caa225825075237cd6b15757476dd1999bec290b.

```
+ /b/1/clang-x86_64-debian-fast/llvm.obj/bin/FileCheck /b/1/clang-x86_64-debian-fast/llvm.src/llvm/test/Bindings/OCaml/core.ml
/b/1/clang-x86_64-debian-fast/llvm.src/llvm/test/Bindings/OCaml/core.ml:255:11: error: CHECK: expected string not found in input
 * CHECK: @const_nuw_neg = global i64 sub nuw
          ^
<stdin>:30:36: note: scanning from here
```

The complete log is available at: [FAIL__LLVM__core_ml.txt](https://github.com/llvm/llvm-project/files/14789479/FAIL__LLVM__core_ml.txt)

Source: https://lab.llvm.org/buildbot/#/builders/109/builds/85934

**Comment by dtcxzyw** [comment]
Thank you! I will fix it later :)
