### ISSUE TITLE
[MLIR][TableGen] Attribute constraints regression: predicates can no longer reference $_op

### ISSUE THREAD

**Issue by shkoo** [llvm/llvm-project#69789]
It looks like attribute constraints can no longer reference $_op as the documentation (`docs/DefiningDialects/Operations.md`) says they should be able to.  mlir-tblgent substitutes "$_op" with a reference to a non-existent "op" variable, giving a compilation error.

This seems to be a regression in 5e118f933b6590cecd7f1afb30845a1594bc4a5d.   This functionality is partially tested by `mlir/mlir/test/mlir-tblgen/constraint-unique.td`, but unfortunately that test doesn't verify that the generated code actually compiles. :(

The `constraint-unique.td` lit test contains this:
```tblgen
def AnAttrPred : CPred<"attrPred($_self, $_op)">;
```

which generates this code:
```c++
static ::mlir::LogicalResult __mlir_ods_local_attr_constraint_constraint2Dunique0(
    ::mlir::Attribute attr, ::llvm::StringRef attrName, llvm::function_ref<::mlir::InFlightDiagnostic()> getDiag) {
  if (attr && !((attrPred(attr, *op))))
    return getDiag() << "attribute '" << attrName
        << "' failed to satisfy constraint: an attribute";
  return ::mlir::success();
}
static ::mlir::LogicalResult __mlir_ods_local_attr_constraint_constraint2Dunique0(
    ::mlir::Operation *op, ::mlir::Attribute attr, ::llvm::StringRef attrName) {
  return __mlir_ods_local_attr_constraint_constraint2Dunique0(attr, attrName, [op]() {
    return op->emitOpError();
  });
}
```

Notice that the first of those two generated functions references "*op", but there is no "op" passed to that function so this gets a compilation error.
