### PR TITLE
[lldb][NFC] Fix a build failure with MSVC

### PR DESCRIPTION
**Pull request by igorkudrin**
This fixes a build error with msvc for code introduced in #106442:

```
...\lldb\source\Expression\DiagnosticManager.cpp(37): error C2668: 'llvm::ErrorInfo<lldb_private::ExpressionError,lldb_private::ExpressionErrorBase>::ErrorInfo': ambiguous call to overloaded function
...\llvm\include\llvm/Support/Error.h(357): note: could be 'llvm::ErrorInfo<lldb_private::ExpressionError,lldb_private::ExpressionErrorBase>::ErrorInfo(std::error_code)', which inherits 'lldb_private::CloneableECError::CloneableECError(std::error_code)' via base class 'lldb_private::ExpressionErrorBase'
...\llvm\include\llvm/Support/Error.h(357): note: or       'llvm::ErrorInfo<lldb_private::ExpressionError,lldb_private::ExpressionErrorBase>::ErrorInfo(std::error_code,std::string)', which inherits 'lldb_private::ExpressionErrorBase::ExpressionErrorBase(std::error_code,std::string)' via base class 'lldb_private::ExpressionErrorBase'
...\lldb\source\Expression\DiagnosticManager.cpp(37): note: while trying to match the argument list '(std::error_code)'
```

### CODE REVIEW

**Review by labath — APPROVED** [review]
Looks good, I guess. Is that constructor even necessary, given that it just forwards the argument to the base class, and we already have the forwarding `using` declaration?

**Comment by igorkudrin** [comment]
> Looks good, I guess. Is that constructor even necessary, given that it just forwards the argument to the base class, and we already have the forwarding `using` declaration?

The constructor looks redundant at the moment, perhaps it is just a legacy from the early stages of patch #106442. Maybe some other constructors can also be reduced, for example, `Win32Error::Win32Error()`. However, I may not fully understand the intentions of the author of the original patch, so I'd prefer @adrian-prantl to do the cleanup if necessary. My patch is only intended to fix the immediate problem.

**Comment by adrian-prantl** [comment]
> > Looks good, I guess. Is that constructor even necessary, given that it just forwards the argument to the base class, and we already have the forwarding `using` declaration?
> 
> The constructor looks redundant at the moment, perhaps it is just a legacy from the early stages of patch #106442. Maybe some other constructors can also be reduced, for example, `Win32Error::Win32Error()`. However, I may not fully understand the intentions of the author of the original patch, so I'd prefer @adrian-prantl to do the cleanup if necessary. My patch is only intended to fix the immediate problem.

This constructor is more a leftover after a bunch of refactoring, your change LGTM!
