### ISSUE TITLE
Stack overflow in clang-tidy

### ISSUE THREAD

**Issue by abrachet** [llvm/llvm-project#55851]
```c
#import <Foundation/Foundation.h>

static NSDictionary<NSNumber*, NSNumber*>* A() {
  return @{};
}

static NSNumber *B(NSDictionary* d) {
  NSNumber* n = d[@""];
  NSNumber* n2 = A()[n];
  if (n2) {
  } else {
    if (n != nil) {}
  }
  return nil;
}

int main() {
  B(@{});
}
```
Run `clang-tidy repro.mm -- -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk` 
The following reproducer will cause a stack overflow after infinite recursion. I have bisected to https://reviews.llvm.org/D124758.

I've attached the pre processed source as well
[repro.mii.txt](https://github.com/llvm/llvm-project/files/8830405/repro.mii.txt)

See also https://github.com/flutter/flutter/issues/105155

@martong, could you take a look please? This is currently blocking us.

**Comment by martong** [comment]
Ok, thanks for the report, I am looking into it.

**Comment by martong** [comment]
I've been trying to reproduce with `clang++ --analyze repro.mii.mm -fblocks`.
But received the following errors.
```
/Users/abrachet/scratch/flutter_repro/repro.mm:8:18: error: array subscript is not an integer
  NSNumber* n = d[@""];
                 ^~~~
/Users/abrachet/scratch/flutter_repro/repro.mm:9:21: error: array subscript is not an integer
  NSNumber* n2 = A()[n];
                    ^~
2 errors generated.
```
I wonder which flags are missing.

If you could help me reducing the file to an absolute minimal reproducer with the proper compiler flags, that would be of great help. Usually, we use [creduce](https://embed.cs.utah.edu/creduce/) for such reductions.

Other than that, there is a patch (not yet landed), which might solve this issue: https://reviews.llvm.org/D126560 Could you please check if that patch applied on llvm/main solves the issue?

**Comment by abrachet** [comment]
That patch indeed fixes it, although I should say that the diff did not apply cleanly, the following two lines seemed to not be in the diff on phabricator https://github.com/llvm/llvm-project/blob/main/clang/lib/StaticAnalyzer/Core/ConstraintManager.cpp#L49-L50. I just removed them and it worked. Thanks a lot

Which is good because I couldn't figure out which flags were missing and I don't think creduce works on Objective-C++ :)

**Comment by martong** [comment]
Thanks. Next week Tuesday, I am going to commit the referenced patch.
