### PR TITLE
[Clang] Fixed a crash when instantiating an invalid out-of-line static data member definition in a local class

### LINKED ISSUE #195416: [clang] Assertion `!isa<TagDecl>(this) || !cast<TagDecl>(this)->isCompleteDefinition()' failed.
Reproducer:
https://godbolt.org/z/1oWWeWeqh
```cpp
constexpr bool foo() {
  struct U {
  struct S {};
  static constexpr S S::bar{42};
  }
}
```

Backtrace:
```console
clang++: /root/llvm-project/llvm/tools/clang/lib/AST/DeclBase.cpp:180: void clang::Decl::setInvalidDecl(bool): Assertion `!isa<TagDecl>(this) || !cast<TagDecl>(this)->isCompleteDefinition()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:4:28: current parser token '{'
2.	<source>:1:22: parsing function body 'foo'
3.	<source>:1:22: in compound statement ('{}')
4.	<source>:2:3: parsing struct/union/class body 'U'
 #0 0x0000000004549938 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4549938)
 #1 0x0000000004546764 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4546764)
 #2 0x0000000004546d84 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4546d84)
 #3 0x0000000004482cb8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x00007867aea42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007867aea969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x00007867aea42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x00007867aea287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x00007867aea2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #9 0x00007867aea39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x00000000080745f5 clang::Decl::setInvalidDecl(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x80745f5)
#11 0x0000000007239701 clang::Sema::ActOnVariableDeclarator(clang::Scope*, clang::Declarator&, clang::DeclContext*, clang::TypeSourceInfo*, clang::LookupResult&, llvm::MutableArrayRef<clang::TemplateParameterList*>, bool&, llvm::ArrayRef<clang::BindingDecl*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7239701)
#12 0x000000000725a3b7 clang::Sema::HandleDeclarator(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x725a3b7)
#13 0x00000000072ffdff clang::Sema::ActOnCXXMemberDeclarator(clang::Scope*, clang::AccessSpecifier, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>, clang::Expr*, clang::VirtSpecifiers const&, clang::InClassInitStyle) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x72ffdff)
#14 0x0000000006ec07ae clang::Parser::ParseCXXClassMemberDeclaration(clang::AccessSpecifier, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::ParsingDeclRAIIObject*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ec07ae)
#15 0x0000000006ec1eaf clang::Parser::ParseCXXClassMemberDeclarationWithPragmas(clang::AccessSpecifier&, clang::ParsedAttributes&, clang::TypeSpecifierType, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ec1eaf)
#16 0x0000000006ec3b8f clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributes&, unsigned int, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ec3b8f)
#17 0x0000000006ec652b clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ec652b)
#18 0x0000000006e99e1c clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::LateParsedAttrList*, clang::ImplicitTypenameContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e99e1c)
#19 0x0000000006ea06b7 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ea06b7)
#20 0x0000000006ea0bfc clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ea0bfc)
#21 0x0000000006f53630 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::LabelDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f53630)
#22 0x0000000006f53eb9 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::LabelDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f53eb9)
#23 0x0000000006f5c82e clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f5c82e)
#24 0x0000000006f5d04a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f5d04a)
#25 0x0000000006e61733 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e61733)
#26 0x0000000006e9819d clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e9819d)
#27 0x0000000006e54cbb clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e54cbb)
#28 0x0000000006e554bf clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e554bf)
#29 0x0000000006e5cf41 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e5cf41)
#30 0x0000000006e5de75 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e5de75)
#31 0x0000000006e5e260 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e5e260)
#32 0x0000000006e3ed03 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e3ed03)
#33 0x000000000505d368 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x505d368)
#34 0x000000000537e465 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x537e465)
#35 0x00000000052fd058 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52fd058)
#36 0x000000000547ab1d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x547ab1d)
#37 0x0000000000decdab cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdecdab)
#38 0x0000000000de370a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#39 0x0000000000de388d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#40 0x00000000050c75b9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#41 0x00000000044830f4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44830f4)
#42 0x00000000050c7be6 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#43 0x00000000050861e2 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x50861e2)
#44 0x000000000508718e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x508718e)
#45 0x000000000508ee35 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x508ee35)
#46 0x0000000000de9134 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde9134)
#47 0x0000000000ca16ba main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xca16ba)
#48 0x00007867aea29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#49 0x00007867aea29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#50 0x0000000000de31a5 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde31a5)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by TPPPP72**
Add check before the function that cause assertion.
Fix #176152, Fix #195416

### CODE REVIEW

**Comment by TPPPP72** [comment]
#195416 is a regression issue caused by #176152.

Original fix PR to #176152 has been reverted and @ojhunt has added a test to #195416.
So I just add a test to #176152.

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 1]
```diff
@@ -1799,6 +1799,14 @@ Decl *TemplateDeclInstantiator::VisitVarDecl(VarDecl *D,
...
     SemaRef.deduceOpenCLAddressSpace(Var);
 
+  if (D->getQualifierLoc()) {
+    if (D->getLexicalDeclContext()->isDependentContext() &&
+        DC->isFunctionOrMethod()) {
+      Var->setInvalidDecl();
+      return nullptr;
+    }
+  }
+
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]: Why do we have to put it in the instantiator? We don't need an instantiated Var before we can tell if its valid.

File: clang/test/SemaTemplate/gh176152.cpp [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+template <class T> int f(T) {
+  struct A {
+    static int B; // expected-error {{static data member 'B' not allowed in local struct 'A'}}
+  };
+  int A::B; // expected-note {{previous definition is here}}
+  int A::B = 1; // expected-error {{redefinition of 'B'}}
+  return 0;
+}
+
+int x = f(0);
```
Comment (zyn0217) [inline clang/test/SemaTemplate/gh176152.cpp]: That is, we should diagnose early without instantiating f.

Comment (TPPPP72) [reply clang/test/SemaTemplate/gh176152.cpp]: Please refer back to #182707. This topic has been discussed previously. In short, this bug can only be reproduced through instantiation.

Comment (zyn0217) [reply clang/test/SemaTemplate/gh176152.cpp]: Yes so why should instantiate `A::B`? I wonder if we should bail out early elsewhere if we encounter any invalid decls.

Comment (TPPPP72) [reply clang/test/SemaTemplate/gh176152.cpp]: I feel I need to clarify that this crash occurred because during the template declaration phase, `A::B` was not marked as an invalid declaration (nor should it be, since non-instantiated templates shouldn't undergo semantic analysis). During the instantiation phase, because B's context is related to A. B, viewed in isolation, is also a valid declaration (you can't say that int `A::B`, viewed alone, is an invalid declaration). Therefore, the scheme of marking it as invalid is inherently flawed.

Comment (zyn0217) [reply clang/test/SemaTemplate/gh176152.cpp]: I don't think I understand what you mean, we already diagnose `A::B` in that dependent context https://godbolt.org/z/dY8rKWvbG

So why do you think `A::B` is still valid?

Comment (zyn0217) [reply clang/test/SemaTemplate/gh176152.cpp]: If name lookup finds anything invalid, the declaration itself is also invalid. See this example: https://godbolt.org/z/cM5Y55s7o

`g` involves `f` which is invalid, and we mark g as invalid as well as building it with a RecoveryExpr.

Comment (TPPPP72) [reply clang/test/SemaTemplate/gh176152.cpp]: In fact, this is not just a feeling, but a proven fact.

In `VisitVarDecl`, I added these:
```cpp
if (D->getIdentifier()) {
  llvm::errs() << "Checking VarDecl: " << D->getNameAsString() << "\n";
  llvm::errs() << "  D->isInvalidDecl(): " << D->isInvalidDecl() << "\n";
  llvm::errs() << "  Var->isInvalidDecl(): " << Var->isInvalidDecl() << "\n";
  llvm::errs() << "  Var Context Kind: " << Var->getDeclContext()->getDeclKindName() << "\n";
  if (auto *FD = dyn_cast<FunctionDecl>(Var->getDeclContext())) {
      llvm::errs() << "  Var Context Name: " << FD->getNameAsString() << "\n";
  }
}
```

```
Checking VarDecl: B
  D->isInvalidDecl(): 0
  Var->isInvalidDecl(): 0
  Var Context Kind: Function
  Var Context Name: f
```

I'm not saying the entire node is valid, but rather that it's valid specifically for B. Whether B's state is valid can only be determined by parsing the instantiation of A.

Comment (zyn0217) [reply clang/test/SemaTemplate/gh176152.cpp]: Did you read my example? I meant, the status quo of whatever D in the instantiator became could be incorrect, and what we need to do is to avoid meaningless instantiation early.

In this case when `A::B` is declared, a name lookup should have happened and that name lookup should find the invalid Decl. And We need to check if we missed a check somewhere that the decl is overlooked and get slipped into the instantiator, and if that's the case, we prevent it.

**Comment by ojhunt** [comment]
@TPPPP72 the regression was a failure yes, but did you make sure it wasn't your original change exposing a different underlying problem? e.g. a path that isn't mishandling an invalid decl. I know there are many ways in which we end up with invalid declarations not being marked as invalid, while maintaining correct behavior because even if we don't mark the relevant decls as invalid we've generated an error, which kills the build.

**Comment by TPPPP72** [comment]
> @TPPPP72 the regression was a failure yes, but did you make sure it wasn't your original change exposing a different underlying problem? e.g. a path that isn't mishandling an invalid decl. I know there are many ways in which we end up with invalid declarations not being marked as invalid, while maintaining correct behavior because even if we don't mark the relevant decls as invalid we've generated an error, which kills the build.

I think this is a timing issue: when parsing function `f`, `A` only reports an error but doesn't mark it as invalid. So, in this edge case, the erroneous `Decl` flows into `SubstQualifier` in a valid state, triggering an assertion. `A` is only marked as invalid after the entire function parsing is complete.

**Comment by TPPPP72** [comment]
> I think this is a timing issue: when parsing function `f`, `A` only reports an error but doesn't mark it as invalid. So, in this edge case, the erroneous `Decl` flows into `SubstQualifier` in a valid state, triggering an assertion. `A` is only marked as invalid after the entire function parsing is complete.

Therefore, I believe that in this situation, when parsing `B`, `A` is valid. However, `B` directly triggers the assertion, without giving `A` a chance to be re-marked as invalid.

**Comment by zyn0217** [comment]
> I think this is a timing issue: when parsing function f, A only reports an error but doesn't mark it as invalid. 

This is not a timing issue, but where the problem happens. You should invalidate the decl as soon as it gets diagnosed, rather than deferring them to the instantiation.

**Comment by TPPPP72** [comment]
> > I think this is a timing issue: when parsing function f, A only reports an error but doesn't mark it as invalid.
> 
> This is not a timing issue, but where the problem happens. You should invalidate the decl as soon as it gets diagnosed, rather than deferring them to the instantiation.

I don't think avoiding instantiation is feasible, as clang currently doesn't process `VarDecl`.

[https://godbolt.org/z/e5WWMoqEh](https://godbolt.org/z/e5WWMoqEh)
Not instantiating the template doesn't report a `VarDecl` error, and node `b` is valid. If we directly mark the entire `CXXRecordDecl` as invalid, I believe the reverted PR has already proven it's not feasible.

**Comment by zyn0217** [comment]
> > > I think this is a timing issue: when parsing function f, A only reports an error but doesn't mark it as invalid.
> > 
> > 
> > This is not a timing issue, but where the problem happens. You should invalidate the decl as soon as it gets diagnosed, rather than deferring them to the instantiation.
> 
> I don't think avoiding instantiation is feasible, as clang currently doesn't process `VarDecl`.
> 
> https://godbolt.org/z/e5WWMoqEh Not instantiating the template doesn't report a `VarDecl` error, and node `b` is valid. If we directly mark the entire `CXXRecordDecl` as invalid, I believe the reverted PR has already proven it's not feasible.

I don't understand what 'doesn't process VarDecl' means? It seems to me that we do build a VarDecl for `int A::B`:

```
      |-DeclStmt 0x491bc1e0 <line:5:3, col:11>
      | `-VarDecl 0x491bc130 parent 0x491bbe80 prev 0x491bc040 <col:3, col:10> col:10 B 'int'
      |   `-NestedNameSpecifier TypeSpec 'A'
```

Also, why do you think a reverted PR means being infeasible? AFAIK the regression it brought is just another case where we shouldn't call SetInvalid on an incomplete type, and we can simply guard that call from that case.

Regardless, unless @ojhunt's concerns can be addressed, I do think the change in this PR looks more arbitrary than the reverted one.

**Comment by zyn0217** [comment]
@TPPPP72 I took a stab at it and I think we could resolve it in this way:

```diff
diff --git a/clang/lib/Sema/SemaDecl.cpp b/clang/lib/Sema/SemaDecl.cpp
index 9f8fc5a187b0..bd7d3130e7e8 100644
--- a/clang/lib/Sema/SemaDecl.cpp
+++ b/clang/lib/Sema/SemaDecl.cpp
@@ -4897,6 +4897,8 @@ void Sema::MergeVarDecl(VarDecl *New, LookupResult &Previous) {
       if (Def && checkVarDeclRedefinition(Def, New))
         return;
     }
+    if (Old->isInvalidDecl())
+      New->setInvalidDecl();
   } else {
     // C++ may not have a tentative definition rule, but it has a different
     // rule about what constitutes a definition in the first place. See
@@ -7950,7 +7952,7 @@ NamedDecl *Sema::ActOnVariableDeclarator(

     if (CurContext->isRecord()) {
       if (SC == SC_Static) {
        if (const CXXRecordDecl *RD = dyn_cast<CXXRecordDecl>(DC)) {
           // Walk up the enclosing DeclContexts to check for any that are
           // incompatible with static data members.
           const DeclContext *FunctionOrMethod = nullptr;
@@ -7973,7 +7975,6 @@ NamedDecl *Sema::ActOnVariableDeclarator(
                  diag::err_static_data_member_not_allowed_in_local_class)
                 << Name << RD->getDeclName() << RD->getTagKind();
+             Invalid = true;
           } else if (AnonStruct) {
             // C++ [class.static.data]p4: Unnamed classes and classes contained
             // directly or indirectly within unnamed classes shall not contain
```

Can you test it? thanks!

**Comment by TPPPP72** [comment]
> Can you test it? thanks!

Already tested, this is correct.

**Comment by ojhunt** [comment]
@TPPPP72 sorry, so this is what I meant previously: the other assertion could have been the result of an existing error: other code failing to invalidate the decl when it should have, and then other code never having to have considered the potential that it was operating on an already invalid decl. You pointed to the decl saying it was not invalid as evidence of it not being invalid without considering that the same error you originally fixed could have been happening there as well: an invalid decl (or anything else) not being recorded as invalid.

I apologize for not being as clear as I should have been.

**Comment by TPPPP72** [comment]
@ojhunt I didn't quite understand it at first, but it became much clearer after seeing @zyn0217 's code. I should have realized earlier that the problem might lie in the merge declaration.

**Review by ojhunt — CHANGES_REQUESTED** [review]
This should also include a test that ensures we diagnose without instantiating.

**Comment by TPPPP72** [comment]
Ping

**Review by ojhunt — APPROVED** [review]
@zyn0217 this looks good to me at this point, do you also want to do a run through?

**Comment by zyn0217** [comment]
> this looks good to me at this point, do you also want to do a run through?

LGTM too
Thanks!
