### PR TITLE
[mlir][OpenMP] set correct insert point after creating a barrier

### LINKED ISSUE #138436: [Flang][OpenMP] compilation failed with "Basic Block in function '_QQmain' does not have terminator!"
Reproducible on Godbolt:
https://godbolt.org/z/zMjo7ajYv
```f90
!$omp parallel
!$omp cancel parallel
!$omp barrier
!$omp end parallel
end
```

### PR DESCRIPTION
**Pull request by tblah**
Fixes #138436

### CODE REVIEW

**Review by bhandarkar-pranav — APPROVED** [review]

**Comment by tblah** [comment]
The CI failure is the buildkite bug with precompiled headers discussed in https://github.com/llvm/llvm-project/pull/141927 and so is not related to this PR.
