### ISSUE TITLE
[flang][openmp] SIMD LINEAR plus COMMON leads to "error: symbol must have a type"

### ISSUE THREAD

**Issue by sscalpone** [llvm/llvm-project#202329]
May have been introduced with #189170.

May be related to older issue #61651.

```fortran
  subroutine sub(x)
    real :: x(:)
    integer :: b
    common/c/b
    !$omp simd linear(/c/)
      do i = 1, 10
        x(i) = x(i) * 2
      end do
    !$omp end simd
  end subroutine
```

```
% flang -c -fopenmp cb.f90
error: loc("/home/sscalpone/work/pgi/tests/nag/run/omp40/cb.f90":4:12): symbol must have a type
LLVM ERROR: aborting
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
...
```

**Comment by luporl** [comment]
@adit4443ya, can you take a look at this issue?

With #189170 reverted a semantic error is shown, instead of a crash:
```
error: Semantic errors in ftest.f90
ftest.f90:5:22: error: 'b' is a common block name and must not appear in an LINEAR clause
    !$omp simd linear(/c/)
                       ^
```

It seems to me this is the correct behavior, since in the example above the common block name was used, instead of one of its members.

**Comment by adit4443ya** [comment]
@luporl @sscalpone I opened up PR for this issue , kindly have a review.
