### PR TITLE
[LLVM][Support] Fixed the compile error caused by #73603

### PR DESCRIPTION
**Pull request by shiltian**
This patch fixed the following compile error caused by #73603.

```
llvm/lib/Support/raw_ostream.cpp: In static member function ‘static llvm::Expected<llvm::ListeningSocket> llvm::ListeningSocket::createUnix(llvm::StringRef, int)’:
llvm/lib/Support/raw_ostream.cpp:1040:10: error: could not convert ‘ListenSocket’ from ‘llvm::ListeningSocket’ to ‘llvm::Expected<llvm::ListeningSocket>’
   return ListenSocket;
          ^~~~~~~~~~~~
```

### CODE REVIEW

**Review by Bigcheese — APPROVED** [review]
LGTM, thanks!
