### PR TITLE
[Clang] No longer reject call expression whose type is a not-yet-deduced auto type.

### LINKED ISSUE #207565: [clang][rejects-valid][21 regression] calling a constant template parameter pack with placeholder type rejected when expanded with a generic lambda's pack
Starts to occur in clang 21.1.0, works in cland 20.1.0, only confirmed in godbolt.
The type of the lambda's pack does not seem to be significant, my original case had a lambda with an explicit template parameter list but I reduced it to a valid C++17 program.

https://godbolt.org/z/vhPvoaMPa
```cpp
template<auto... Cs>
struct S
{
  static constexpr auto cl = [](auto... args)
    { return (..., (Cs(), args)); };
};

template struct S<>;
```
```
<source>:5:21: error: called object type 'auto' is not a function or function pointer
    5 |     { return (..., (Cs(), args)); };
      |                     ^~
<source>:5:5: note: while substituting into a lambda expression here
    5 |     { return (..., (Cs(), args)); };
      |     ^
<source>:8:17: note: in instantiation of template class 'S<>' requested here
    8 | template struct S<>;
      |                 ^
```
Also occurs in a function:
https://godbolt.org/z/YETaWc1M9
```cpp
template<auto... Cs>
void f()
{
  auto cl = [](auto... args)
    { return (..., (Cs(), args)); };
}

template void f<>();
```
Does not require a fold expression, pack expansions also emit the same behavior:
https://godbolt.org/z/cb751h6vn
```cpp
template<auto... Cs>
struct S
{
  static constexpr auto cl = [](auto... args)
    { int arr[] = {(Cs(), args, 42)...}; };
};

template struct S<>;
```

Cases with more sane instantiations, also rejected: https://godbolt.org/z/fzheqY7Tv

### PR DESCRIPTION
**Pull request by cor3ntin**
This fixes a regression introduced in #139246

Fixes #207565

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -6828,7 +6828,7 @@ static bool MayBeFunctionType(const ASTContext &Context, const Expr *E) {
       T == Context.BuiltinFnTy || T == Context.OverloadTy ||
       T->isFunctionType() || T->isFunctionReferenceType() ||
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaExpr.cpp:6829]: `isFunctionReferenceType()` makes me wonder if we're not handling a reference to a function pointer type correctly...

**Review by AaronBallman — APPROVED** [review]
LGTM!

File: clang/lib/Sema/SemaExpr.cpp [hunk 2]
```diff
@@ -6828,7 +6828,7 @@ static bool MayBeFunctionType(const ASTContext &Context, const Expr *E) {
...
       T->isMemberFunctionPointerType() || T->isFunctionPointerType() ||
-      T->isBlockPointerType() || T->isRecordType())
+      T->isBlockPointerType() || T->isRecordType() || T->isUndeducedType())
```
Comment (mizvekov) [inline clang/lib/Sema/SemaExpr.cpp:6831]: This is suspect, undeduced types leaking out like this is a sign of a bug, that we never tried to deduce this type. Otherwise this should have been deduced-as-dependent, and fallen into the dependent category.

File: clang/test/SemaTemplate/fun-template-def.cpp [hunk 3]
```diff
@@ -109,6 +109,19 @@ auto k = c_<1>; // expected-note {{in instantiation of variable}}
 
 }
 
+namespace GH207565 {
+    template <auto... Cs> struct S {
+    static constexpr auto cl  = [](auto... args) { return (..., (Cs(), args)); };
```
Comment (Waffl3x) [inline clang/test/SemaTemplate/fun-template-def.cpp:114]: I would have liked for this to also be diagnosed, but only EDG diagnoses it so it's probably unreasonable to expect that.

File: clang/lib/Sema/SemaExpr.cpp (hunk 2 above)
Comment (Waffl3x) [reply clang/lib/Sema/SemaExpr.cpp:6831]: tl;dr undeduced types aren't leaking out, it's just a quirk of how SubstNonTypeTemplateParmPackExpr is built.

I got curious and investigated this, it looks like SubstNonTypeTemplateParmPackExpr is just always built with the declared type of the constant template parameter.
https://github.com/llvm/llvm-project/blob/2078da43e25a4623cab2d0d60decddf709aaea28/clang/lib/Sema/SemaTemplateInstantiate.cpp#L2235-L2247
And while slightly different now...
https://github.com/llvm/llvm-project/blob/2a8e0e1abbdc558f3a4b43d5a9432c07b5d01387/clang/lib/Sema/SemaTemplateInstantiate.cpp#L2189-L2215
...it doesn't seem to change the outcome.
So it's relying on a quirk of SubstNonTypeTemplateParmPackExpr that won't reasonably change.
https://clang.llvm.org/doxygen/classclang_1_1SubstNonTypeTemplateParmPackExpr.html
> When a pack expansion in the source code contains multiple parameter packs and those parameter packs correspond to different levels of template parameter lists, this node is used to represent a non-type template parameter pack from an outer level,...

https://clang.llvm.org/doxygen/ExprCXX_8cpp_source.html#l01773
```
  setDependence(ExprDependence::TypeValueInstantiation |
                ExprDependence::UnexpandedPack);
```
With that said, it looks like "E->[containsUnexpandedParameterPack](https://clang.llvm.org/doxygen/classclang_1_1Expr.html#a45c0f5a000bc434250cb5338a536e187)()" conveys the intent more accurately, and effectively relies on the same quirk. On the other hand, if TemplateInstantiator::TransformTemplateParmRefExpr gets a QoI change to store the deduced type when every element is the same, using containsUnexpandedParameterPack will suppress valid diagnostics.

**Comment by cor3ntin** [comment]
If people have ideas how to improve that, we can always do so in follow up work :)

**Comment by mizvekov** [comment]
> If people have ideas how to improve that, we can always do so in follow up work :)

Might have been a good idea to wait before merging, since there is unaddressed feedback and we barely had any time to look over this.
