### ISSUE TITLE
LLVM fails to build with MinGW (gcc 4.8.1) - error: unknown type name 'off_t'

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#18905]
|  |  |
| --- | --- |
| Bugzilla Link | [18531](https://llvm.org/bz18531) |
| Version | trunk |
| OS | Windows XP |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
While building LLVM with MinGW I get the following error.

llvm[2]: ======= Finished Linking Release Executable yaml2obj (without symbols)
make[2]: Leaving directory `/d/federico/LLVM/trunk/build/tools/yaml2obj'
make[2]: Entering directory `/d/federico/LLVM/trunk/build/tools/llvm-c-test'
llvm[2]: Compiling calc.c for Release build
llvm[2]: Compiling disassemble.c for Release build
llvm[2]: Compiling helpers.c for Release build
llvm[2]: Compiling include-all.c for Release build
In file included from d:/federico/LLVM/trunk/llvm/tools/llvm-c-test/include-all.
c:33:0:
d:/federico/LLVM/trunk/llvm/include/llvm-c/lto.h:195:54: error: unknown type nam
e 'off_t'
                                     size_t map_size, off_t offset);
                                                      ^
/bin/rm: cannot lstat `/d/federico/LLVM/trunk/build/tools/llvm-c-test/Release/in
clude-all.d.tmp': No such file or directory
make[2]: *** [/d/federico/LLVM/trunk/build/tools/llvm-c-test/Release/include-all
.o] Error 1
make[2]: Leaving directory `/d/federico/LLVM/trunk/build/tools/llvm-c-test'
make[1]: *** [llvm-c-test/.makeall] Error 2
make[1]: Leaving directory `/d/federico/LLVM/trunk/build/tools'
make: *** [all] Error 1

The problem appeared after moving to the latest version of MinGW that has GCC 4.8.1. The preliminary configuration script has run with no issues (from the build directory ../llvm/configure).

**Comment by arsenm** [comment]
Old build issue
