### PR TITLE
[libc] Build with -Wshadow

### PR DESCRIPTION
**Pull request by nico**
This relands https://github.com/llvm/llvm-project/pull/196519. It now only enables the warning for
clang 22 and newer, since older versions had false positives.

### CODE REVIEW

**Comment by simpal01** [comment]
Hi,

We (https://github.com/arm/arm-toolchain) started seeing a new build failure after the recent `[libc] Build with -Wshadow` change in PR https://github.com/llvm/llvm-project/pull/197516 

The error we see is:
```
    In file included from libc/src/stdio/vsprintf.cpp:17:
    In file included from libc/src/stdio/printf_core/printf_main.h:15:
    In file included from libc/src/stdio/printf_core/converter.h:21:
    In file included from libc/src/stdio/printf_core/converter_atlas.h:35:
    libc/src/stdio/printf_core/float_hex_converter.h:36:9: error:
      declaration shadows a type alias in namespace '...::printf_core'
      [-Werror,-Wshadow]
        using StorageType = LDBits::StorageType;
              ^
    libc/src/stdio/printf_core/float_dec_converter_limited.h:65:7: note:
      previous declaration is here
    using StorageType = fputil::FPBits<long double>::StorageType;
```
  With -Wshadow enabled, this now fails because both
  `float_dec_converter_limited.h` and `float_hex_converter.h` define `StorageType` which Clang now diagnoses as shadowing and fails.

**Comment by simpal01** [comment]
Ping

**Comment by michaelrj-google** [comment]
Hi @simpal01, I'm looking into a fix for that shadowing issue. Could you confirm that you're only seeing shadowing errors in those printf pieces?

**Comment by michaelrj-google** [comment]
Managed to reproduce the issue locally, I've created https://github.com/llvm/llvm-project/pull/197985 which should fix it.

**Comment by nico** [comment]
> Managed to reproduce the issue locally, I've created https://github.com/llvm/llvm-project/pull/197985 which should fix it.

Thank you!

> Hi,
> 
> We (https://github.com/arm/arm-toolchain) started seeing a new build failure…

If this is a configuration that you care about, would it be possible that you try to get it added to libc's pre-commit testing? Thanks!

**Comment by simpal01** [comment]
> Hi @simpal01, I'm looking into a fix for that shadowing issue. Could you confirm that you're only seeing shadowing errors in those printf pieces?

Yes, your patch fixed the build. Thanks.

**Comment by simpal01** [comment]
> > Managed to reproduce the issue locally, I've created #197985 which should fix it.
> 
> Thank you!
> 
> > Hi,
> > We (https://github.com/arm/arm-toolchain) started seeing a new build failure…
> 
> If this is a configuration that you care about, would it be possible that you try to get it added to libc's pre-commit testing? Thanks!

Yes, we are working on upstreaming a few arm bare-metal configurations for libc testing. Thanks.
