### ISSUE TITLE
Clang++ errors when using `va_start` in a lambda with variadic arguments

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#19991]
|  |  |
| --- | --- |
| Bugzilla Link | [19617](https://llvm.org/bz19617) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Program that causes the issue described in this ticket](https://user-images.githubusercontent.com/60944935/143749415-fdfa5c4f-390c-44b0-82c6-8df7cf768e16.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@DougGregor,@vadz |

## Extended Description 

# Overview

Clang will error out if `va_start` is used from a lambda with C-style variadic arguments, unless the parent function also has variadic arguments.

# Steps to reproduce

Compile attached file.

# Expected result

Program should (probably?) compile and return 88 on execution.

# Actual result

Clang errors out:
```
    test.cpp:8:3: error: 'va_start' used in function with fixed args
                va_start(ap, a);
```
# Additional information

I'm not a language lawyer, so I'm not sure if lambdas with variadic arguments are allowed. However, I'm pretty confident that either lambdas with variadic arguments should always cause an error (including when the parent function also has variadic parameters), or that they should work on their own.

g++ 4.8.1 seems to accept lambdas with variadic arguments (or at least accepts the attached program).

**Comment by frederick-vs-ja** [comment]
Fixed in Clang 5 (Xcode 9.3/Apple Clang 9.1?) ([Godbolt link](https://godbolt.org/z/1fWrKdoWa)).

**Comment by llvmbot** [comment]
@llvm/issue-subscribers-clang-frontend

Author: None (llvmbot)

<details>
|  |  |
| --- | --- |
| Bugzilla Link | [19617](https://llvm.org/bz19617) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [Program that causes the issue described in this ticket](https://user-images.githubusercontent.com/60944935/143749415-fdfa5c4f-390c-44b0-82c6-8df7cf768e16.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@DougGregor,@vadz |

## Extended Description 


# Overview

Clang will error out if `va_start` is used from a lambda with C-style variadic arguments, unless the parent function also has variadic arguments.

# Steps to reproduce

Compile attached file.

# Expected result

Program should (probably?) compile and return 88 on execution.

# Actual result

Clang errors out:
```
    test.cpp:8:3: error: 'va_start' used in function with fixed args
                va_start(ap, a);
```
# Additional information

I'm not a language lawyer, so I'm not sure if lambdas with variadic arguments are allowed. However, I'm pretty confident that either lambdas with variadic arguments should always cause an error (including when the parent function also has variadic parameters), or that they should work on their own.

g++ 4.8.1 seems to accept lambdas with variadic arguments (or at least accepts the attached program).
</details>
