### PR TITLE
[ConstantFolding] Add support for llvm.atan in constant folding.

### LINKED ISSUE #143360: Missing constant folding for atan with -ffast-math on llvm 20.1.0
Hi, 
Compiling this simple test, which is taken from gcc's regression, works on llvm 18.1.7, but gets a link error on llvm 20.1.0 (undefined reference to 'link_error')

Compiled using `clang test.c -O2 -ffast-math -lm`
On llvm 20 & 18, without the `-ffast-math` flag, compilation passes.
(my default march is `rv32imc`, but I tried if with a couple different march's(32/64, with/out `f`, with/out `d`) with the same result)
```
extern void link_error(void);

extern double atan(double);

int main()
{
  if (atan(1.0) < 0.78 || atan(1.0) > 0.79)
    link_error(); /* expected to be optimized out */

  return 0;
}
```

Is this expected?

EDIT: upon more tries, it seems not to be RISCV specific issue, as I also tried it with `-target x86_64-linux-gnu` and got the same result. Leaving the [RISCV] for now, because I'm not sure what label I should use (maybe clang:codegen?)

### PR DESCRIPTION
**Pull request by topperc**
Fixes #143360

### CODE REVIEW

**Review by nikic — APPROVED** [review]

**Comment by lei137** [comment]
@nikic The testcase is failing for https://lab.llvm.org/buildbot/#/builders/64/builds/4143

The affected test is:
```
define double @test_atan_neg0() {
; CHECK-LABEL: define double @test_atan_neg0() {
; CHECK-NEXT:    ret double -0.000000e+00
;
  %res = call double @llvm.atan.f64(double -0.0)
  ret double %res
}
```

This bot is generating:
```
define double @test_atan_neg0() {
  ret double 0.000000e+00
}
```

instead of `-0.000000e+00`.  Not sure if the neg is a must for neg0 here.

**Comment by jcranmer-intel** [comment]
`atan(-0.0)` is `-0.0` per IEEE 754, so it's a problem if it's being folded to `+0.0`.

**Comment by topperc** [comment]
> `atan(-0.0)` is `-0.0` per IEEE 754, so it's a problem if it's being folded to `+0.0`.

I think the constant folding just calls the native libm function linked with the compiler.

**Comment by jcranmer-intel** [comment]
> I think the constant folding just calls the native libm function linked with the compiler.

Which we really shouldn't be doing, I know @andykaylor has filed an issue on that in the past. The sooner we can get llvm-libc hand-in-hand with APFloat integration, the better.

**Comment by andykaylor** [comment]
> > I think the constant folding just calls the native libm function linked with the compiler.
> 
> Which we really shouldn't be doing, I know @andykaylor has filed an issue on that in the past. The sooner we can get llvm-libc hand-in-hand with APFloat integration, the better.

The issue I had (and I seem to be in the minority in caring about this) is that when we constant fold a transcendental function by calling the libm function, we run the risk of getting a different answer than we would have gotten if the call had been evaluated at runtime if the user binary is linked with a different math library than the compiler. That's a problem of bitwise reproducibility of results.

If the math library linked with the compiler is simply returning an incorrect result (as seems to be the case here) that's a much bigger problem, but it's a problem for the library.

**Comment by lei137** [comment]
I would like to xfail this tc for now so we can bring the aix bot back to green.
https://github.com/llvm/llvm-project/pull/143723

**Comment by lei137** [comment]
PR to add special handling for -/+0.0: https://github.com/llvm/llvm-project/pull/143962
