### PR TITLE
[Flang] Update the fix of PR 80738 to cover generic interface inside modules

### PR DESCRIPTION
**Pull request by DanielCChen**
The following test cases crashes. The problem is that the fix for PR https://github.com/llvm/llvm-project/pull/80738 is not quite complete. It should `GetUltimate()` of the `interface_` before check if it is generic.

```
  MODULE M

    CONTAINS

    FUNCTION Int(Arg)
    INTEGER :: Int, Arg
      Int = Arg
    END FUNCTION

    FUNCTION Int8(Arg)
    INTEGER(8) :: Int8, Arg
      Int8 = 8_8
    END FUNCTION

  END MODULE

  MODULE M1
  USE M

    INTERFACE Int8
      MODULE PROCEDURE  Int
      MODULE PROCEDURE  Int8
    END INTERFACE

  END MODULE

  PROGRAM PtrAssignGen
  USE M
  USE M1
  IMPLICIT NONE

  INTERFACE Int
    MODULE PROCEDURE  Int
    MODULE PROCEDURE  Int8
  END INTERFACE

  PROCEDURE(Int8),   POINTER :: PtrInt8

  PtrInt8 => Int8
  IF ( PtrInt8(100_8) .NE. 8_8 ) ERROR STOP 12

  END
  ```

### CODE REVIEW

**Review by jeanPerier — APPROVED** [review]
LGTM

**Comment by psteinfeld** [comment]
This change is causing some of our tests to fail.  Here's an example.  I have two files that are compiled separately.  Here's the first file:
```
module fmod
contains
  subroutine inner(n)
    print *, n
  end subroutine
end module
module fmod1
  use fmod,proc1=>inner
  procedure(proc1),pointer :: p1
end module
```
I then compile this file with `flang-new -c first.f90`.  Here's the second file:
```
Program test
  Use fmod1
  p1 => proc1
  Call p1(343)
End Program
```
I then compile this file with `flang-new main.f90 first.o`.  I expect this to not produce errors.  But I get the following output:
```
error: Semantic errors in main.f90
./main.f90:3:3: error: 'inner' is not a procedure
    p1 => proc1
    ^^^^^^^^^^^
./main.f90:3:3: error: In assignment to object pointer 'p1', the target 'inner' is a procedure designator
    p1 => proc1
    ^^^^^^^^^^^
./fmod1.mod:4:27: Declaration of 'p1'
  procedure(inner),pointer::p1
                            ^^
./main.f90:4:3: error: 'inner' is not a procedure
    Call p1(343)
    ^^^^^^^^^^^^
./fmod1.mod:4:11: error: 'inner' must be an abstract interface or a procedure with an explicit interface
  procedure(inner),pointer::p1
            ^^^^^
```
Weirdly, if I concatenate these two files, everything works.

I'm planning to revert this change.  Stay tuned for that.

**Comment by DanielCChen** [comment]
@psteinfeld Thanks for the notification. I will take a another look of the fix and your test case.

**Comment by DanielCChen** [comment]
https://github.com/llvm/llvm-project/pull/81544 is created to handle both the original case in this PR and the regressions.
