### ISSUE TITLE
Cannot compile with gcc < 8.1

### ISSUE THREAD

**Issue by aaronkintel** [llvm/llvm-project#57057]
The [release notes](https://github.com/llvm/llvm-project/blob/main/llvm/docs/ReleaseNotes.rst#update-on-required-toolchains-to-build-llvm) indicate that gcc >= 7.1 is sufficient to compile LLVM, but I get the following error when I try with 7.2.0:

```console
<pre>llvm-project/llvm/include/llvm/ADT/StringRef.h:85:65: error: call to non-constexpr function 'static std::size_t std::char_traits<char>::length(const char_type*)'
         : Data(Str), Length(Str ? std::char_traits<char>::length(Str) : 0) {}
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
```

Constexpr `char_traits<>::length` was [not implemented until gcc 8.1](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017).

**Comment by efriedma-quic** [comment]
See b4e9977fc18405d4a11cbaf1975bcadbf75920b8 .  CC @d0k

**Comment by d0k** [comment]
Do we need to bring the fallback to __builtin_strlen back?

**Comment by efriedma-quic** [comment]
Ping?  Looks like this is still broken.

Falling back to __builtin_strlen would work.
