### ISSUE TITLE
flang: fails to build with `fatal error: 'flang/Optimizer/Dialect/CUF/Attributes/CUFEnumAttr.h.inc' file not found`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#92635]
On debian linux:

```
FAILED: tools/flang/lib/Optimizer/Dialect/CUF/CMakeFiles/obj.CUFDialect.dir/CUFDialect.cpp.o 
/opt/sccache//sccache /build/source/build-llvm/./bin/clang++ -DFLANG_INCLUDE_TESTS=1 -DFLANG_LITTLE_ENDIAN=1 -DFLANG_VENDOR="\"Debian \"" -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/flang/lib/Optimizer/Dialect/CUF -I/build/source/flang/lib/Optimizer/Dialect/CUF -I/build/source/flang/include -Itools/flang/include -Iinclude -I/build/source/llvm/include -isystem /build/source/llvm/../mlir/include -isystem tools/mlir/include -isystem tools/clang/include -isystem /build/source/llvm/../clang/include -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/source/build-llvm/tools/clang/stage2-bins=../../../../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -Wno-deprecated-copy -Wno-string-conversion -Wno-ctad-maybe-unsupported -Wno-unused-command-line-argument -Wstring-conversion           -Wcovered-switch-default -Wno-nested-anon-types -O2 -DNDEBUG -g1  -fno-exceptions -funwind-tables -std=c++17 -MD -MT tools/flang/lib/Optimizer/Dialect/CUF/CMakeFiles/obj.CUFDialect.dir/CUFDialect.cpp.o -MF tools/flang/lib/Optimizer/Dialect/CUF/CMakeFiles/obj.CUFDialect.dir/CUFDialect.cpp.o.d -o tools/flang/lib/Optimizer/Dialect/CUF/CMakeFiles/obj.CUFDialect.dir/CUFDialect.cpp.o -c /build/source/flang/lib/Optimizer/Dialect/CUF/CUFDialect.cpp
In file included from /build/source/flang/lib/Optimizer/Dialect/CUF/CUFDialect.cpp:14:
In file included from /build/source/flang/include/flang/Optimizer/Dialect/CUF/CUFOps.h:12:
/build/source/flang/include/flang/Optimizer/Dialect/CUF/Attributes/CUFAttr.h:23:10: fatal error: 'flang/Optimizer/Dialect/CUF/Attributes/CUFEnumAttr.h.inc' file not found
   23 | #include "flang/Optimizer/Dialect/CUF/Attributes/CUFEnumAttr.h.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by sylvestre** [comment]
caused by https://github.com/llvm/llvm-project/pull/92317 it seems
cc @clementval

**Comment by sylvestre** [comment]
full log:
https://llvm-jenkins.debian.net/job/llvm-toolchain-bullseye-binaries/architecture=amd64,distribution=bullseye,label=amd64/1239/consoleFull

**Comment by clementval** [comment]
Sorry for the inconvenience. This e90126e0dd6f058e1602bb6c769dfa4c52d7ad47 should fix your issue.

**Comment by mjklemm** [comment]
I'm still getting an error even with #e90126e in the tree:

```
In file included from /net/home/micha/projects/llvm/llvm-project/flang/lib/Optimizer/Dialect/CUF/Attributes/CUFAttr.cpp:14:
/net/home/micha/projects/llvm/llvm-project/flang/include/flang/Optimizer/Dialect/CUF/CUFDialect.h:24:10: fatal error: flang/Optimizer/Dialect/CUF/CUFDialect.h.inc: No such file or directory
   24 | #include "flang/Optimizer/Dialect/CUF/CUFDialect.h.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[162.350s  61% 1x 4514/7315] Linking CXX shared library lib/libMLIRGPUPipelines.so.19.0git
ninja: build stopped: subcommand failed.
nice ninja  645.48s user 118.48s system 470% cpu 2:42.37 total
```

**Comment by mjklemm** [comment]
Seems to be working now.  Closing.

**Comment by DavidTruby** [comment]
I don't think this is fixed, I still see the error. I'm guessing you just got lucky with the build order @mjklemm. I will be posting a fix shortly
