### PR TITLE
[libc++] Short-cut constraints of single-argument `any` constructor

### LINKED ISSUE #176877: PR #174619 breaks valid code: `no member named 'value' in 'std::is_copy_constructible<Foo>'`
The following code (https://gcc.godbolt.org/z/YEsedh1Pn) is broken by https://github.com/llvm/llvm-project/pull/174619:

```
#include <any>

struct Foo {
  Foo(std::any v);
};

template <typename T, bool = std::is_copy_constructible<T>::value>
void f(T) {}

void q(Foo x) { f(x); }
```

The code compiles fine with libc++ prior to that change and with libstdc++. The issue was reported last week at https://github.com/llvm/llvm-project/pull/174619#issuecomment-3753720486

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
When a default template argument of a function template uses `std::is_copy_constructible<T>::value` and `T` is convertible from and to `any`, the changes in 21dc73f6a46cd786394f10f5aef46ec4a2d26175 would introduce constraint meta-recursion when compiling with Clang.

This patch short-cuts constraints of the related constructor to avoid computing `is_copy_constructible<T>` when `decay_t<T>` is `any`, which gets rid of constraint meta-recursion in the overload resolution of copy construction of `T`.

Fixes #176877.

### CODE REVIEW

**Review by alexfh — APPROVED** [review]
Thank you for the fix! I verified that it resolves the original issue for us.

**Review by philnik777 — APPROVED** [review]
Sorry, I completely missed the other messages. LGTM!
