### ISSUE TITLE
[clang][rejects-valid][21 regression] calling a constant template parameter pack with placeholder type rejected when expanded with a generic lambda's pack

### ISSUE THREAD

**Issue by Waffl3x** [llvm/llvm-project#207565]
Starts to occur in clang 21.1.0, works in cland 20.1.0, only confirmed in godbolt.
The type of the lambda's pack does not seem to be significant, my original case had a lambda with an explicit template parameter list but I reduced it to a valid C++17 program.

https://godbolt.org/z/vhPvoaMPa
```cpp
template<auto... Cs>
struct S
{
  static constexpr auto cl = [](auto... args)
    { return (..., (Cs(), args)); };
};

template struct S<>;
```
```
<source>:5:21: error: called object type 'auto' is not a function or function pointer
    5 |     { return (..., (Cs(), args)); };
      |                     ^~
<source>:5:5: note: while substituting into a lambda expression here
    5 |     { return (..., (Cs(), args)); };
      |     ^
<source>:8:17: note: in instantiation of template class 'S<>' requested here
    8 | template struct S<>;
      |                 ^
```
Also occurs in a function:
https://godbolt.org/z/YETaWc1M9
```cpp
template<auto... Cs>
void f()
{
  auto cl = [](auto... args)
    { return (..., (Cs(), args)); };
}

template void f<>();
```
Does not require a fold expression, pack expansions also emit the same behavior:
https://godbolt.org/z/cb751h6vn
```cpp
template<auto... Cs>
struct S
{
  static constexpr auto cl = [](auto... args)
    { int arr[] = {(Cs(), args, 42)...}; };
};

template struct S<>;
```

Cases with more sane instantiations, also rejected: https://godbolt.org/z/fzheqY7Tv

**Comment by shafik** [comment]
Looks like gcc is the only that accepts this: https://godbolt.org/z/1j6djvv9e

CC @cor3ntin

**Comment by Waffl3x** [comment]
I was advised to use /Zc:lambda- by Cameron DaCamara, an MSVC front-end engineer.
https://learn.microsoft.com/en-us/cpp/build/reference/zc-lambda
> The bug with MSVC only exists with /Zc:lambda. If you add /Zc:lambda- to any repro, it will compile.

https://godbolt.org/z/WoaT5en7b
Also, EDG is only grumpy with the empty pack case, which I find odd.
