### PR TITLE
[Clang] Enable -fextend-variable-liveness at -Og

### PR DESCRIPTION
**Pull request by SLTozer**
This patch follows two other ongoing reviews, https://github.com/llvm/llvm-project/pull/110000 and https://github.com/llvm/llvm-project/pull/110102, which add a new feature to Clang - `-fextend-variable-liveness`, which generates fake uses for user variables (and the `this` pointer) to prevent them from being optimized out, providing a better debug experience at the cost of less efficient generated code. This is useful for debugging code without the need to disable optimizations outright, which is particularly important when debugging applications where some level of optimization is necessary, e.g. game code.

Following the inclusion of the flag, this patch enables it by default when `-Og` is set. Currently, `-Og` is equivalent to `-O1` - it is effectively just an alias. By enabling `-fextend-variable-liveness`, this patch changes the code generated by Clang with `-Og` to have reduced optimization and greater debuggability than `-O1`, differentiating the two according to their respective purposes. This idea was discussed previously on [Discourse](https://discourse.llvm.org/t/rfc-redefine-og-o1-and-add-a-new-level-of-og/72850), where there was general agreement with the principle of this change.

### CODE REVIEW

File: clang/lib/Frontend/CompilerInvocation.cpp [hunk 1]
```diff
@@ -1834,6 +1834,14 @@ bool CompilerInvocation::ParseCodeGenArgs(CodeGenOptions &Opts, ArgList &Args,
     Opts.setInlining(CodeGenOptions::NormalInlining);
   }
 
+  // If we have specified -Og and have not set any explicit -fextend-lifetimes
+  // value, then default to -fextend-lifetimes=all.
```
Comment (jmorse) [inline clang/lib/Frontend/CompilerInvocation.cpp:1838]: This is going to create confusion by speculating the existence of an `={all,params,this}`  fextend-lifetimes when it doesn't exist yet, and might not.

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -441,6 +441,10 @@ Modified Compiler Flags
   ``memset`` and similar functions for which it is a documented undefined
   behavior. It is implied by ``-Wnontrivial-memaccess``
 
+- The ``-Og`` optimization flag now sets ``-fextend-lifetimes``, a new compiler
+  flag, resulting in slightly reduced optimization compared to ``-O1`` in
```
Comment (jmorse) [inline clang/docs/ReleaseNotes.rst:445]: Can we just say "trading optimization for improved..." to indicate that this is a conscious decision the developer might make?

File: clang/test/CodeGen/fake-use-opt-flags.cpp [hunk 3]
```diff
@@ -0,0 +1,30 @@
+/// Check that we generate fake uses only when -fextend-lifetimes is set and we
+/// are not setting optnone, or when we have optimizations set to -Og and we have
+/// not passed -fno-extend-lifetimes.
+// RUN: %clang_cc1 -emit-llvm -disable-llvm-passes -O0 -fextend-lifetimes %s -o - | FileCheck %s
```
Comment (jmorse) [inline clang/test/CodeGen/fake-use-opt-flags.cpp:4]: Intention of this RUN line is that no fake uses are generated, but there are no test-lines for ensuring that -> add an implicit-fake-not? And the other check-only FileCheck commands.

**Review by jmorse — COMMENTED** [review]
Some minor test comments, otherwise looking good,

File: clang/lib/Frontend/CompilerInvocation.cpp (hunk 1 above)
Comment (SLTozer) [reply clang/lib/Frontend/CompilerInvocation.cpp:1838]: Ah, I implemented the `=` option on a local-only branch, and accidentally left this comment in. My mistake, though I may yet decide to merge the feature into the earlier PRs.

File: clang/test/CodeGen/fake-use-opt-flags.cpp (hunk 3 above)
Comment (SLTozer) [reply clang/test/CodeGen/fake-use-opt-flags.cpp:4]: Normally I would use implicit-check-not, but in this case we're `CHECK-NEXT`ing from the start of the function to the very end, which equally guarantees that no fake uses have been generated.

File: clang/lib/Frontend/CompilerInvocation.cpp [hunk 4]
```diff
@@ -1834,6 +1834,14 @@ bool CompilerInvocation::ParseCodeGenArgs(CodeGenOptions &Opts, ArgList &Args,
     Opts.setInlining(CodeGenOptions::NormalInlining);
   }
 
+  // If we have specified -Og and have not explicitly set -fno-extend-lifetimes,
+  // then default to -fextend-lifetimes.
+  if (Arg *A = Args.getLastArg(options::OPT_O_Group);
+      A && A->containsValue("g")) {
```
Comment (MaskRay) [inline clang/lib/Frontend/CompilerInvocation.cpp:1840]: `A->getValue() == "g"`

Perhaps move the code around ToolChains/Clang.cpp:9198 and let the driver pass -fextend-lifetimes to frontend.

File: clang/test/CodeGen/fake-use-opt-flags.cpp (hunk 3 above)
Comment (MaskRay) [reply clang/test/CodeGen/fake-use-opt-flags.cpp:4]: We just need two RUN lines, one with -fextended-lifetimes and one without. -O group is completely orthogonal and does not need to be tested

File: clang/lib/Frontend/CompilerInvocation.cpp (hunk 4 above)
Comment (SLTozer) [reply clang/lib/Frontend/CompilerInvocation.cpp:1840]: Is there an advantage to having it passed through the driver? I ask mainly because I see `-fextend-lifetimes` as being a feature of `-Og` optimization, and if you invoke `clang -cc1 -Og` directly then you'd expect/hope that the optimization behaviour would be the same as `clang -Og` - I'm not too familiar with expected Clang behaviour though, so if this is quite normal for driver/frontend behaviour then I'm fine to switch it.

Comment (rnk) [reply clang/lib/Frontend/CompilerInvocation.cpp:1840]: I agree, the driver's job is usually to unpack high level flags into semi-orthogonal cc1 flags. So, for example, in clang-cl, /O1 becomes a collection of things like `-Os -ffunction-sections -fdata-sections` and maybe something else I've forgotten. `clang++ -fexceptions` becomes `-fexceptions -fcxx-exceptions` in most contexts, separating destructor cleanups from try/throw language support.

cc1 flags kind of represent features that are useful to toggle on and off for testing and test case reduction, since they're one of the things we reduce in the [clang crash reducer script](https://github.com/llvm/llvm-project/blob/main/clang/utils/creduce-clang-crash.py).

Comment (SLTozer) [reply clang/lib/Frontend/CompilerInvocation.cpp]: I've moved this behaviour to the driver now. Also regarding the first request to use `A->getValue() == "g"` - if just `-O` is passed then `A->getValue()` will crash, as there are no values. An alternative would be to change the check to `A->getNumValues() && A->getValue() == "g"`, but I think `containsValue` is more concise.

**Comment by SLTozer** [comment]
I've updated this patch, and made it dependent on a [previous PR](https://github.com/llvm/llvm-project/pull/110000) - the logic for enabling the flag is coupled with code from the earlier PR, and also we now slightly extend the test added in that PR instead of creating a new one.

File: clang/docs/ReleaseNotes.rst [hunk 5]
```diff
@@ -412,6 +412,20 @@ New Compiler Flags
   only for thread-local variables, and none (which corresponds to the
   existing ``-fno-c++-static-destructors`` flag) skips all static
   destructors registration.
+- The ``-fextend-variable-liveness`` flag has been added to allow for improved
+  debugging of optimized code. Using ``-fextend-variable-liveness`` will cause
+  Clang to generate code that tries to preserve the liveness of source variables
+  through optimizations, meaning that variables will typically be visible in a
+  debugger more often. The flag has two levels: ``-fextend-variable-liveness``,
+  or ``-fextend-variable-liveness=all``, extendes the liveness of all user
```
Comment (jmorse) [inline clang/docs/ReleaseNotes.rst:420]:
```suggestion
  or ``-fextend-variable-liveness=all``, extends the liveness of all user
```

File: clang/docs/ReleaseNotes.rst [hunk 6]
```diff
@@ -412,6 +412,20 @@ New Compiler Flags
...
+  variables and the ``this`` pointer. Alternatively ``-fextend-this-ptr``, or
+  ``-fextend-variable-liveness=this``, has the same behaviour but applies only
+  to the ``this`` variable in C++ class member functions, meaning its effect is
+  a strict subset of ``-fextend-variable-liveness``. Note that this flag
+  modifies the results of optimizations that Clang performs, which will result
+  in reduced performance in generated code; however, this feature will not
+  extend the liveness of some variables in cases where doing so would likely
+  have a severe impact on generated code performance.
```
Comment (jmorse) [inline clang/docs/ReleaseNotes.rst:428]: IMO, just drop the late sentence for brevity -- it's up to the user to work out whether the trade-off is worth it.

File: clang/include/clang/Driver/Options.td [hunk 7]
```diff
@@ -4298,6 +4298,26 @@ def stack_usage_file : Separate<["-"], "stack-usage-file">,
...
   HelpText<"Filename (or -) to write stack usage output to">,
   MarshallingInfoString<CodeGenOpts<"StackUsageOutput">>;
+def fextend_variable_liveness_EQ : Joined<["-"], "fextend-variable-liveness=">,
+  Group<f_Group>, Visibility<[ClangOption, CC1Option]>,
+  HelpText<"Extend the liveness of user variables through optimizations to "
+           "prevent stale or optimized-out variable values when debugging. Can "
+           "be applied to all user variables, or just to the C++ 'this' ptr. "
+           "May choose not to extend the liveness of some variables, such as "
+           "non-scalars larger than 4 unsigned ints, or variables in any "
+           "inlined functions.">,
```
Comment (jmorse) [inline clang/include/clang/Driver/Options.td:4308]: Are there other compiler flags which have such long help-text? IIRC this is a super-short summary that appears on the command line with --help, and thus conciseness is key. Developers looking for more information will go to the full docs.

**Review by jmorse — COMMENTED** [review]
This looks good, but I'd like to reword some of it

File: clang/docs/ReleaseNotes.rst (hunk 6 above)
Comment (SLTozer) [reply clang/docs/ReleaseNotes.rst:428]: The intention here is just to specify to the user that some variables won't have their liveness extended, so that they're not caught off-guard if they notice some variables getting excluded.

**Comment by SLTozer** [comment]
With the prior patches having landed, this is now in a state where it could land; I've rebased it onto main, meaning all of the code diff in this PR is now relevant.

**Review by rnk — APPROVED** [review]
Is this ready to go? I can't recall if we ultimately accepted the RFC.

**Review by MaskRay — APPROVED** [review]

**Comment by gulfemsavrun** [comment]
We started seeing the following failure, and I bisected it to this commit.
```
[1343/43547](319) CXX host_x64/obj/third_party/protobuf/src/google/protobuf/libprotobuf_lite.generated_message_tctable_lite.cc.o
FAILED: [code=1] host_x64/obj/third_party/protobuf/src/google/protobuf/libprotobuf_lite.generated_message_tctable_lite.cc.o 
../../build/rbe/reclient_cxx.sh --working-subdir=out/not-default --exec_strategy=remote_local_fallback --preserve_unchanged_output_mtime --  ../../prebuilt/third_party/clang/linux-x64/bin/clang++ -MD -MF host_x64/obj/third_party/protobuf/src/google/protobuf/libprotobuf_lite.generated_message_tctable_lite.cc.o.d -DTOOLCHAIN_VERSION=xBAWf3R2sN1ViZaJjFVJTCaaAZEuAtpSDTaGs7iC35IC -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -DGOOGLE_PROTOBUF_NO_RTTI -DHAVE_PTHREAD -I../.. -Ihost_x64/gen -I../../third_party/protobuf/src -I../../third_party/protobuf/third_party/utf8_range -I../../third_party/abseil-cpp -fcolor-diagnostics -fcrash-diagnostics-dir=clang-crashreports -fcrash-diagnostics=all -ffp-contract=off --sysroot=../../prebuilt/third_party/sysroot/linux --target=x86_64-unknown-linux-gnu -ffile-compilation-dir=. -no-canonical-prefixes -fomit-frame-pointer -fdata-sections -ffunction-sections -Og -Xclang -debug-info-kind=constructor -g3 -grecord-gcc-switches -gdwarf-5 -gz=zstd -Wall -Wextra -Wconversion -Wextra-semi -Wimplicit-fallthrough -Wnewline-eof -Wstrict-prototypes -Wwrite-strings -Wno-sign-conversion -Wno-unused-parameter -Wnonportable-system-include-path -Wno-missing-field-initializers -Wno-extra-qualification -Wno-cast-function-type-strict -Wno-cast-function-type-mismatch -Wno-unknown-warning-option -Wno-missing-template-arg-list-after-template-kw -Wno-deprecated-pragma -Wno-nontrivial-memaccess -fvisibility=hidden -Werror -Wa,--fatal-warnings --sysroot=../../prebuilt/third_party/sysroot/linux --target=x86_64-unknown-linux-gnu -Wno-deprecated-pragma -Wno-enum-enum-conversion -Wno-extra-semi -Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-invalid-noreturn -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-function -Wno-unused-private-field -Wno-deprecated-declarations -Wno-deprecated-this-capture -Wno-unnecessary-virtual-specifier -Wno-c++98-compat-extra-semi -Wno-shorten-64-to-32 -Wno-sign-compare -Wno-missing-field-initializers -Wno-conversion -Wno-unknown-warning-option -Wno-implicit-int-float-conversion -Wno-array-parameter -Wno-deprecated-builtins -fvisibility-inlines-hidden -stdlib=libc++ -stdlib=libc++ -std=c++20 -Wno-deprecated-this-capture -fno-exceptions -fno-rtti -ftemplate-backtrace-limit=0 -stdlib=libc++ -c ../../third_party/protobuf/src/google/protobuf/generated_message_tctable_lite.cc -o host_x64/obj/third_party/protobuf/src/google/protobuf/libprotobuf_lite.generated_message_tctable_lite.cc.o
../../third_party/protobuf/src/google/protobuf/generated_message_tctable_lite.cc:68:28: error: cannot compile this tail call skipping over cleanups yet
   68 |   PROTOBUF_MUSTTAIL return GenericFallbackImpl<MessageLite, std::string>(
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   69 |       PROTOBUF_TC_PARAM_PASS);
      |       ~~~~~~~~~~~~~~~~~~~~~~~
```

I'm uploading a reproducer.
[clang-crashreports.zip](https://github.com/user-attachments/files/19859700/clang-crashreports.zip)

Any ideas why we might be hitting this issue? This happens during a built with `-Og`, and issue does not remove if I remove `-Og` flag.

**Comment by SLTozer** [comment]
> Any ideas why we might be hitting this issue? This happens during a built with `-Og`, and issue does not remove if I remove `-Og` flag.

At a glance that looks like it could be related, we generate (no-op) cleanup as part of -fextend-variable-liveness. I'll look into this, but could you clarify what you mean - did you mean that the error occurs with `-Og` and does _not_ occur when you remove `-Og`?

**Comment by SLTozer** [comment]
> We started seeing the following failure, and I bisected it to this commit.

I've created a fix for this issue here: https://github.com/llvm/llvm-project/pull/136867

**Comment by gulfemsavrun** [comment]
> > Any ideas why we might be hitting this issue? This happens during a built with `-Og`, and issue does not remove if I remove `-Og` flag.
> 
> At a glance that looks like it could be related, we generate (no-op) cleanups as part of -fextend-variable-liveness. I'll look into this, but could you clarify what you mean - did you mean that the error occurs with `-Og` and does _not_ occur when you remove `-Og`?

Yes, it does not reproduce if I remove `-Og`.

**Comment by mikaelholmen** [comment]
I did some downstream testing with "-Og" since this patch and noticed that e.g.
```
llc -mtriple=avr bbi-106478.ll
```
crashes with
```
SoftenFloatOperand Op #1: t2: ch = fake_use t0, ConstantFP:f64<0.000000e+00>

LLVM ERROR: Do not know how to soften this operator's operand!
```
and
```
llc -mtriple=systemz bbi-106478.ll
```
fails with
```
llc: ../lib/Target/SystemZ/SystemZLongBranch.cpp:226: unsigned int getInstSizeInBytes(const MachineInstr &, const SystemZInstrInfo *): Assertion `(Size || MI.isDebugOrPseudoInstr() || MI.isPosition() || MI.isKill() || MI.isImplicitDef() || MI.getOpcode() == TargetOpcode::MEMBARRIER || MI.getOpcode() == TargetOpcode::INIT_UNDEF || MI.isInlineAsm() || MI.getOpcode() == SystemZ::STACKMAP || MI.getOpcode() == SystemZ::PATCHPOINT || MI.getOpcode() == SystemZ::EH_SjLj_Setup) && "Missing size value for instruction."' failed.
```
for bbi-106478.ll just being
```
define double @idd() {
entry:
  notail call void (...) @llvm.fake.use(double 0.000000e+00)
  ret double 0.000000e+00
}
```
(and if removing the llvm.fake.use call they don't crash)
so I guess there is some testing and fixes around llvm.fake.use left to do.

**Comment by SLTozer** [comment]
> I did some downstream testing with "-Og" since this patch and noticed that e.g.

Thanks for catching these - in terms of legalizer support it looks like everything relevant is implemented except for `SoftenFloatOperand`, so that should be a straightforward fix. The target-specific error is also trivial (`FAKE_USE` has a size of 0), but it would be preferable if every target didn't need to account for it - previously there was a discussion of whether `FAKE_USE` should have `isPosition`, and this probably settles that since it would allow them to be treated correctly by-default.

I'll revert this for now (after verifying), since it may take a little time to confirm that changing `isPosition()` doesn't introduce any new bugs; I'll try to expand the fake use tests to cover more targets at the same time.

**Comment by mikaelholmen** [comment]
> > I did some downstream testing with "-Og" since this patch and noticed that e.g.
> 
> Thanks for catching these - in terms of legalizer support it looks like everything relevant is implemented except for `SoftenFloatOperand`, so that should be a straightforward fix. The target-specific error is also trivial (`FAKE_USE` has a size of 0), but it would be preferable if every target didn't need to account for it - previously there was a discussion of whether `FAKE_USE` should have `isPosition`, and this probably settles that since it would allow them to be treated correctly by-default.
> 
> I'll revert this for now (after verifying), since it may take a little time to confirm that changing `isPosition()` doesn't introduce any new bugs; I'll try to expand the fake use tests to cover more targets at the same time.

Thanks!

**Comment by MaskRay** [comment]
Since the option has been renamed to `-fextend-variable-liveness`, I think you want to edit this title and the description to reflect the naming change as well. I wanted to check the status the effort and I tried `git log --grep fextend-lifetimes` but found nothing, then I realized that the option has been renamed :)

**Comment by efriedma-quic** [comment]
There's a corresponding intrinsic llvm.fake.use (FAKE_USE in MIR), which isn't used by anything else.  Possibly there's a bug in the implementation of that intrinsic.
