### PR TITLE
[llvm-objcopy][COFF] Update .symidx values after stripping

### PR DESCRIPTION
**Pull request by e-kud**
After deleting debug sections, symbol indices are shifted but sections consisting of .symidx directives are completely ignored. Update symbol indices as well.

### CODE REVIEW

**Comment by e-kud** [comment]
It is still not a universal solution, as actually `.symidx` could be used in any section but WinCFGuard sections consist only of them.

**Review by jh7370 — COMMENTED** [review]
It's been a while since I've looked at the details of the COFF Object class, so this probably won't be all that straightforward, but rather than have lots of finalize* methods that specifically target different features that need updating, I wonder if it would be possible to have a finalize virtual method on the section class? The default would do nothing, but certain Section subclasses could then define a different behaviour, specific to the section kind, which takes care of updating references etc.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 1]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
   return Error::success();
 }
 
+Error COFFWriter::finalizeCFGuardContents() {
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp:97]: Fixed.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 2]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
...
+        Sym.Sym.StorageClass != IMAGE_SYM_CLASS_STATIC)
+      return createStringError(object_error::invalid_symbol_index,
+                               "symbol '%s' has unexpected section format",
+                               Sym.Name.str().c_str());
+
+    ArrayRef<uint8_t> RawIds = Sec->getContents();
+    // Nothing to do and also CheckSum will be -1 instead of 0 if we recalculate
+    // it on empty input.
+    if (RawIds.size() == 0)
+      return Error::success();
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp]: Yes, you are completely right! Fixed.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 3]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
...
+
+    // Create updated content
+    ArrayRef<uint32_t> Ids(reinterpret_cast<const uint32_t *>(RawIds.data()),
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp]: Fixed.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 4]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
...
+                               "symbol '%s' is missing its section",
+                               Sym.Name.str().c_str());
+
+    if (Sym.Sym.NumberOfAuxSymbols != 1 ||
+        Sym.Sym.StorageClass != IMAGE_SYM_CLASS_STATIC)
+      return createStringError(object_error::invalid_symbol_index,
+                               "symbol '%s' has unexpected section format",
+                               Sym.Name.str().c_str());
+
+    ArrayRef<uint8_t> RawIds = Sec->getContents();
```
[the remark this answers is not in the document]
Comment (mstorsjo) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp:132]: That's not what I meant with offset. The string-or-offset aspect of the name is not an issue here.

What I meant was, we have this:
```
struct coff_symbol {
  union { ... } Name;

  support::ulittle32_t Value;
  SectionNumberType SectionNumber;
```

A symbol in a COFF object points at a section number, and `Value` is an offset into that section. E.g. when you have one large `.text` section and a function is at a specific offset within that section.

For section definition symbols, with `coff_aux_section_definition`, it is of course most common that they have a zero offset and point to the start of the section. (I'm not sure if it makes sense to have a section definition symbol pointing at an offset within the section.) But it would be good to verify this, because if the symbol has got a nonzero `Value` here, it really means that it points at an offset into the section.

Now if the linker doesn't really use the symbol at all, but just inspects the whole contents of the section, it probably doesn't matter either way. But in the current form, where we primarily iterate over symbols and use that to look up a section, it gives an impression that almost any symbol would be ok.

Anyway, if you add a `Value != 0` to the check where you currently check `Sym.Sym.NumberOfAuxSymbols != 1 || Sym.Sym.StorageClass != IMAGE_SYM_CLASS_STATIC`, then it's probably fine.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 5]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
...
+    ArrayRef<uint8_t> NewRawIds(reinterpret_cast<uint8_t *>(NewIds.data()),
+                                RawIds.size());
+    // Update check sum
+    JamCRC JC(/*Init=*/0);
+    JC.update(NewRawIds);
+    coff_aux_section_definition *SD =
+        reinterpret_cast<coff_aux_section_definition *>(Sym.AuxData[0].Opaque);
+    SD->CheckSum = JC.getCRC();
+    // Set new content
+    Sec->setOwnedContents(NewRawIds);
```
[the remark this answers is not in the document]
Comment (mstorsjo) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp]: Thanks; explicitly pointing that out that we create a new vector here makes it clearer.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 6]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
...
+  if (!NeedUpdate)
+    return Error::success();
+
+  for (auto &Sym : Obj.getMutableSymbols()) {
+    if (Sym.Name != ".gljmp$y" && Sym.Name != ".giats$y" &&
+        Sym.Name != ".gfids$y")
+      continue;
+
+    auto Sec = find_if(Obj.getMutableSections(),
+                       [&Sym](Section &S) { return S.Name == Sym.Name; });
```
[the remark this answers is not in the document]
Comment (mstorsjo) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp:118]: Making a mapping from section to symbol would be good here, yes.

However - do note that an object file can have multiple symbols with the same name. Only extern symbols are unique - non-extern symbols can be have collisions. So looking up a symbol based on a section name doesn't generally work.

As an example:
```c
void func1(void) {}
void func2(void) {}
```

```console
$ clang -target x86_64-windows-msvc -c test.c -ffunction-sections
$ obj2yaml test.o
  - Name:            .text
    Value:           0
    SectionNumber:   4
    SimpleType:      IMAGE_SYM_TYPE_NULL
    ComplexType:     IMAGE_SYM_DTYPE_NULL
    StorageClass:    IMAGE_SYM_CLASS_STATIC
    SectionDefinition:
      Length:          1
      NumberOfRelocations: 0
      NumberOfLinenumbers: 0
      CheckSum:        40735498
      Number:          4
      Selection:       IMAGE_COMDAT_SELECT_NODUPLICATES
  - Name:            func1
    Value:           0
    SectionNumber:   4
    SimpleType:      IMAGE_SYM_TYPE_NULL
    ComplexType:     IMAGE_SYM_DTYPE_FUNCTION
    StorageClass:    IMAGE_SYM_CLASS_EXTERNAL
  - Name:            .text
    Value:           0
    SectionNumber:   5
    SimpleType:      IMAGE_SYM_TYPE_NULL
    ComplexType:     IMAGE_SYM_DTYPE_NULL
    StorageClass:    IMAGE_SYM_CLASS_STATIC
    SectionDefinition:
      Length:          1
      NumberOfRelocations: 0
      NumberOfLinenumbers: 0
      CheckSum:        40735498
      Number:          5
      Selection:       IMAGE_COMDAT_SELECT_NODUPLICATES
  - Name:            func2
    Value:           0
    SectionNumber:   5
    SimpleType:      IMAGE_SYM_TYPE_NULL
    ComplexType:     IMAGE_SYM_DTYPE_FUNCTION
    StorageClass:    IMAGE_SYM_CLASS_EXTERNAL
```

It's unlikely that you'd have multiple duplicate symbols/sections for these CFG sections - but it sets a bad precedent if we have code in objcopy that does incorrect assumptions on how you can look things up.

The only right way to map a section to its section definition is by looking at the `SectionNumber` field - looking for a symbol with the right StorageClass and number of aux symbols.

So for that, perhaps it's simplest to either iterate over all symbols, pick up all section definitions (ones with num aux == 1 and IMAGE_SYM_CLASS_STATIC I guess), put that in a map with SectionNumber->Symbol, and look up in that when operating on/iterating over sections?

**Comment by e-kud** [comment]
> > It is still not a universal solution, as actually .symidx could be used in any section but WinCFGuard sections consist only of them.
> 
> Going through places where we use emitCOFFSymbolIndex() in LLVM, there's also `.gehcont$y` (for `/guard:ehcont`), `.impcall` (AArch64 import call optimization), and `.hybmp$x` (Arm64EC).

This is true. `ehcontguard` has the same structure as cfguards,  `.hybmp$x` has a structure of `<id, id, kind>`. `.impcall` is something the most hard to support. It has a format of `<size, sec number, [<0x13, sym offset, sym id>]>`. For the last, notice, it is not only about symbol index but also about section numbers. They are changing as well. This is completely ignored now

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp]: Implemented as a mapping of symbols with the specified names, section definition and zero offset from section id to its section definition.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 7]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
...
+
+    if (Sec == Obj.getMutableSections().end() ||
+        Sec->UniqueId != Sym.TargetSectionId)
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp]: Currently we match symbols using `Sec.UniqueId` in a map formed from `Sym.TargetSectionId`. Should be resolved.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 8]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
...
+    // it on empty input.
+    if (RawIds.size() == 0)
+      return Error::success();
+
+    // Create updated content
+    ArrayRef<uint32_t> Ids(reinterpret_cast<const uint32_t *>(RawIds.data()),
+                           RawIds.size() / 4);
+    std::vector<uint32_t> NewIds;
+    for (auto Id : Ids)
+      NewIds.push_back(SymIdMap[Id]);
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp]: Added a check and a test for it.

File: llvm/lib/ObjCopy/COFF/COFFObject.cpp [hunk 9]
```diff
@@ -16,8 +16,11 @@ namespace coff {
 using namespace object;
 
 void Object::addSymbols(ArrayRef<Symbol> NewSymbols) {
+  size_t RawIndex = 0;
```
Comment (e-kud) [inline llvm/lib/ObjCopy/COFF/COFFObject.cpp:19]: @mstorsjo I've noticed that this approach is error-prone as if `addSymbols` invoked twice, symbols will have duplicated `OriginalRawIndex` (It doesn't happen now). Looks like we should have this variable as a class member.

**Comment by e-kud** [comment]
Supported `.gehcont$y` change as it is similar to cfguards. I'll try to reduce tests size a little bit later.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 10]
```diff
@@ -93,59 +94,75 @@ Error COFFWriter::finalizeSymbolContents() {
...
+  auto IsSymIdxSection = [](StringRef Name) {
+    return Name == ".gljmp$y" || Name == ".giats$y" || Name == ".gfids$y" ||
+           Name == ".gehcont$y";
+  };
+
   DenseMap<size_t, size_t> SymIdMap;
+  SmallDenseMap<ssize_t, coff_aux_section_definition *, 4> SecIdMap;
   bool NeedUpdate = false;
-  for (Symbol &Sym : Obj.getMutableSymbols()) {
+  for (auto &Sym : Obj.getMutableSymbols()) {
```
[the remark this answers is not in the document]
Comment (mstorsjo) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp:113]: This case seems to be able to make do with `Obj.getSymbols()` as well, as it doesn't mutate the symbols.

**Review by mstorsjo — COMMENTED** [review]
Thanks, the implementation looks mostly straightforward at this point now. A couple issues/questions remain though, plus @jh7370's comments.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 11]
```diff
@@ -93,59 +94,75 @@ Error COFFWriter::finalizeSymbolContents() {
...
-                           RawIds.size() / 4);
-    std::vector<uint32_t> NewIds;
-    for (auto Id : Ids)
-      NewIds.push_back(SymIdMap[Id]);
+    ArrayRef<support::ulittle32_t> Ids(
+        reinterpret_cast<const support::ulittle32_t *>(RawIds.data()),
+        RawIds.size() / 4);
+    std::vector<support::ulittle32_t> NewIds;
+    for (auto Id : Ids) {
+      if (!SymIdMap.contains(Id))
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp]: Moved to the iterators.

File: llvm/test/tools/llvm-objcopy/COFF/strip-update-ehcont.test [hunk 12]
```diff
@@ -0,0 +1,201 @@
+# RUN: yaml2obj %s -o %t.in.o
+
+# RUN: llvm-readobj -r -s  -x '.gehcont$y' %t.in.o | FileCheck %s --check-prefix=ORIG
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-update-ehcont.test]: `-x '.gehcont$y'` is to see that contents really changed after stripping.

**Review by mstorsjo — COMMENTED** [review]
LGTM from me, but leaving it up to @jh7370 to approve once he's ok with the details he has commented on.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 13]
```diff
@@ -92,6 +93,63 @@ Error COFFWriter::finalizeSymbolContents() {
   return Error::success();
 }
 
+Error COFFWriter::finalizeCFGuardContents() {
+  DenseMap<size_t, size_t> SymIdMap;
+  bool NeedUpdate = false;
+  for (Symbol &Sym : Obj.getMutableSymbols()) {
```
[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/lib/ObjCopy/COFF/COFFWriter.cpp:112]: > Yes, fixed.

This doesn't look fixed to me. You're still calling `getMutableSymbols` and not `getSymbols` here. Also, please use `const &` where possible, not just `&`.

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test [hunk 14]
```diff
@@ -0,0 +1,75 @@
+# Bail out if a section consisting of symidx has unexpected format for patching
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test:1]: Nit: llvm-objcopy tests (along with most new LLVM binutils testing) uses double comment markers (i.e. `##` here) for comments, to help distinguish them from `RUN` and `CHECK` lines etc.

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test [hunk 15]
```diff
@@ -0,0 +1,75 @@
...
+# its content and updating a check sum. Basically, the expected format is a
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test:2]:
```suggestion
# its content and updating a checksum. Basically, the expected format is a
```

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test [hunk 16]
```diff
@@ -0,0 +1,75 @@
...
+# definitive symbol with a zero offset that is linked with section.
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test:3]: "with section" sounds like it's missing a "the" or "a" depending on context that I'm not confident about.

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test [hunk 17]
```diff
@@ -0,0 +1,75 @@
...
+# In the case, the symbol .gfids$y is not present at all.
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test:4]:
```suggestion
# In this case, the symbol .gfids$y is not present at all.
```

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-2.test [hunk 18]
```diff
@@ -0,0 +1,95 @@
+# Bail out if a section consisting of symidx has unexpected format for patching
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-2.test:1]: Don't split strongly-related test cases up into different files. You can use yaml2obj `--docnum` to have multiple YAML docs in the same file, and/or (potentially - not sure if the feature is supported for COFF) `-D` to parameterise them.

File: llvm/test/tools/llvm-objcopy/COFF/strip-update-winguards.test [hunk 19]
```diff
@@ -1,8 +1,12 @@
+# .gfids$y, .giats$y and .gljmp$y cf-guard sections consist of .symidx
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/COFF/strip-update-winguards.test:1]: Is there a reason this and `strip-update-ehcont` couldn't be folded together into a single test case that shows that all these sections get updated?

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 20]
```diff
@@ -92,6 +94,76 @@ Error COFFWriter::finalizeSymbolContents() {
...
+    return Name == ".gljmp$y" || Name == ".giats$y" || Name == ".gfids$y" ||
+           Name == ".gehcont$y";
+  };
+
+  DenseMap<size_t, size_t> SymIdMap;
+  SmallDenseMap<ssize_t, coff_aux_section_definition *, 4> SecIdMap;
+  for (Symbol &Sym : Obj.getMutableSymbols()) {
+    SymIdMap[Sym.OriginalRawIndex] = Sym.RawIndex;
+
+    // We collect only definition symbols of the sections to update checksum.
```
Comment (jh7370) [inline llvm/lib/ObjCopy/COFF/COFFWriter.cpp:115]: Is "checksum" here a specific named thing in the spec? If not, please use "the checksum". If it is a named thing, use the same capitalization as the spec uses (also applies to the next comment below).

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 21]
```diff
@@ -92,6 +94,76 @@ Error COFFWriter::finalizeSymbolContents() {
...
+          reinterpret_cast<coff_aux_section_definition *>(
+              Sym.AuxData[0].Opaque);
+  }
+
+  for (Section &Sec : Obj.getMutableSections()) {
+    if (!IsSymIdxSection(Sec.Name))
+      continue;
+
+    ArrayRef<uint8_t> RawIds = Sec.getContents();
+    // Nothing to do and also CheckSum will be -1 instead of 0 if we recalculate
```
Comment (jh7370) [inline llvm/lib/ObjCopy/COFF/COFFWriter.cpp:129]: Same comment as above.

File: llvm/lib/ObjCopy/COFF/COFFWriter.cpp [hunk 22]
```diff
@@ -92,6 +94,76 @@ Error COFFWriter::finalizeSymbolContents() {
...
+      if (SymIdIt == SymIdMap.end())
+        return createStringError(object_error::invalid_symbol_index,
+                                 "section '%s' contains a .symidx (%d) that is "
+                                 "incorrect or was stripped",
+                                 Sec.Name.str().c_str(), Id.value());
+      NewIds.push_back(support::ulittle32_t(SymIdIt->getSecond()));
+    }
+    ArrayRef<uint8_t> NewRawIds(reinterpret_cast<uint8_t *>(NewIds.data()),
+                                RawIds.size());
+    // Update check sum.
```
Comment (jh7370) [inline llvm/lib/ObjCopy/COFF/COFFWriter.cpp:157]:
```suggestion
    // Update checksum.
```

File: llvm/test/tools/llvm-objcopy/COFF/strip-update-ehcont.test (hunk 12 above)
[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/test/tools/llvm-objcopy/COFF/strip-update-ehcont.test]: Yes, I think it's redundant, given this is using YAML.

**Review by jh7370 — COMMENTED** [review]
One more minor round of comments. Please note that I am not going to be at work much of next week and will likely not have time to review further. I am happy for @mstorsjo to approve in my absence once my comments have been addressed.

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test (hunk 14 above)
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test]: Used `##` for the comments.

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test (hunk 16 above)
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test]: Added `the` as definitive symbols should be linked to a unique sections IIUC.

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test (hunk 17 above)
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-1.test]: Fixed.

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-2.test (hunk 18 above)
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section-2.test]: Merged all error tests into one, as they all describe an invalid section obtained by compiler or stripping. Tests for errors include/exclude the whole blocks of fields. I've decided not to use `-D` for it.

File: llvm/test/tools/llvm-objcopy/COFF/strip-update-winguards.test (hunk 19 above)
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-update-winguards.test]: Folded them together.

**Review by mstorsjo — APPROVED** [review]
LGTM

**Review by MaskRay — APPROVED** [review]

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section.test [hunk 23]
```diff
@@ -0,0 +1,225 @@
...
+## Essentially, the expected format is a definitive symbol with a zero offset
+## linked to the section. Valid data consists of a sequence of symbol indices
+## that remain in the symbol table even after stripping.
+
+## In this case, the symbol .gfids$y is not present at all.
+
+# RUN: yaml2obj %s --docnum=1 -o %t1.in.o
+# RUN: not llvm-objcopy --strip-debug %t1.in.o %t1.out.o 2>&1 | FileCheck %s --check-prefix=ERROR-NOSYM
+
+# ERROR-NOSYM: section '.gfids$y' does not have the corresponding symbol or the symbol has unexpected format
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section.test]: Added.

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section.test [hunk 24]
```diff
@@ -0,0 +1,225 @@
...
+
+--- !COFF
+header:
+  Machine:         IMAGE_FILE_MACHINE_AMD64
+  Characteristics: [  ]
+sections:
+  - Name:            .text
+    Characteristics: [ IMAGE_SCN_CNT_CODE, IMAGE_SCN_MEM_EXECUTE, IMAGE_SCN_MEM_READ ]
+    Alignment:       4
+    SectionData:     488D0500000000488D0D00000000488D0500000000488D0500000000
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section.test]: Reduced tests more

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section.test [hunk 25]
```diff
@@ -0,0 +1,225 @@
+## Bail out if a section consisting of symidx is invalid.
+## It includes both: an unexpected format for patching section data and
+## updating the checksum, as well as data validity.
+## Essentially, the expected format is a definitive symbol with a zero offset
+## linked to the section. Valid data consists of a sequence of symbol indices
+## that remain in the symbol table even after stripping.
+
+## In this case, the symbol .gfids$y is not present at all.
+
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section.test]: Done

File: llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section.test [hunk 26]
```diff
@@ -0,0 +1,225 @@
+## Bail out if a section consisting of symidx is invalid.
+## It includes both: an unexpected format for patching section data and
+## updating the checksum, as well as data validity.
```
[the remark this answers is not in the document]
Comment (e-kud) [reply llvm/test/tools/llvm-objcopy/COFF/strip-invalid-symidx-section.test]: Removed.

**Review by jh7370 — APPROVED** [review]
LGTM.

**Comment by mstorsjo** [comment]
I'd like to have this fix in 21.x; https://github.com/llvm/llvm-project/commit/be5c96bfac328fed548c532bbe1710fe23460a85 caused the issue of strip corrupting object files built with CFGuard, in cases where it didn't use to before - see https://github.com/curl/curl-for-win/commit/a5e6d0dcffa55a3da4ddd346c7ca77f05e455ece for discussion/debugging around that. With this patch, that issue is fixed.

So I'll propose backporting it.
