### ISSUE TITLE
[CodeGen] Building error introduced by commit c53cbce

### ISSUE THREAD

**Issue by maurossi** [llvm/llvm-project#56754]
In commit c53cbce `[CodeGen] Define ABI breaking class members correctly`
some identifiers declared inside  `#ifndef NDEBUG/#endif `bracing were not
correctly changed to `#if LLVM_ENABLE_ABI_BREAKING_CHECKS/#endif` bracing,
causing the building error:

```console
external/llvm-project/llvm/lib/CodeGen/MachineScheduler.cpp:754:29: error: use of undeclared identifier 'MISchedCutoff'
  if (NumInstrsScheduled == MISchedCutoff && MISchedCutoff != ~0U) {
                            ^
external/llvm-project/llvm/lib/CodeGen/MachineScheduler.cpp:754:46: error: use of undeclared identifier 'MISchedCutoff'
  if (NumInstrsScheduled == MISchedCutoff && MISchedCutoff != ~0U) {
                                             ^
2 errors generated.
```

The following diff is required to be able to build libLLVMCodeGen

```diff
diff --git a/llvm/lib/CodeGen/MachineScheduler.cpp b/llvm/lib/CodeGen/MachineScheduler.cpp
index 96131dc2983e..c25a8a9ab1bc 100644
--- a/llvm/lib/CodeGen/MachineScheduler.cpp
+++ b/llvm/lib/CodeGen/MachineScheduler.cpp
@@ -102,7 +102,7 @@ const bool PrintDAGs = false;
 
 } // end namespace llvm
 
-#ifndef NDEBUG
+#if LLVM_ENABLE_ABI_BREAKING_CHECKS
 /// In some situations a few uninteresting nodes depend on nearly all other
 /// nodes in the graph, provide a cutoff to hide them.
 static cl::opt<unsigned> ViewMISchedCutoff("view-misched-cutoff", cl::Hidden,
@@ -115,7 +115,7 @@ static cl::opt<std::string> SchedOnlyFunc("misched-only-func", cl::Hidden,
   cl::desc("Only schedule this function"));
 static cl::opt<unsigned> SchedOnlyBlock("misched-only-block", cl::Hidden,
                                         cl::desc("Only schedule this MBB#"));
-#endif // NDEBUG
+#endif
 
 /// Avoid quadratic complexity in unusually large basic blocks by limiting the
 /// size of the ready lists.
```

**Comment by maurossi** [comment]
Please @EugeneZelenko could you please add this issue to [LLVM 15.0.0 Release](https://github.com/llvm/llvm-project/milestone/11) Milestone ?

I thought I could add the issue to Milestone after having opened it, but I am not able to

Thank you

**Comment by EugeneZelenko** [comment]
@maurossi: Done.

**Comment by RKSimon** [comment]
This was fixed in trunk by https://reviews.llvm.org/D130425+ adc387460d85a371d111bcd3e08fdc8d4f26ddd5
