### PR TITLE
[ARM,AArch64] Fix ABI bugs with over-sized bitfields

### PR DESCRIPTION
**Pull request by ostannard**
This fixes two bugs in the ABI for over-sized bitfields for ARM and AArch64:

The container type picked for an over-sized bitfield already contributes to the alignment of the structure, but it should also contribute to the "unadjusted alignment" which is used by the ARM and AArch64 PCS.

AAPCS64 defines the bitfield layout algorithm for over-sized bitfields as picking a container which is the fundamental integer data type with the largest size less than or equal to the bit-field width. Since AAPCS64 has a 128-bit integer fundamental data type, we need to consider Int128 as a container type for AArch64.

### CODE REVIEW

**Comment by ostannard** [comment]
Ping

File: clang/test/CodeGen/aapcs64-align.cpp [hunk 1]
```diff
@@ -161,5 +168,62 @@ int test_bitint8(){
...
+// CHECK: declare void @f7(i32 noundef, i64)
+void f7(int a, OverSizedBitfield b);
+void g7() {
+  OverSizedBitfield s = {42};
+  f7(1, s);
+}
+
+// There are no 128-bit fundamental data types defined by AAPCS32, so this gets
+// a 64-bit container plus 64 bits of padding, giving it a size of 16 bytes and
+// alignment of 8 bytes.
```
Comment (john-brawn-arm) [inline clang/test/CodeGen/aapcs64-align.cpp:191]: It looks like you've copy-pasted this comment and it's not correct here (we expect a 128-bit container).

**Review by john-brawn-arm — APPROVED** [review]
LGTM.

**Comment by fmayer** [comment]
This changed the size of the following struct:

```
#include <stdint.h>

struct A {
     bool value : 64 = false;
        uint64_t : 448;
};

static_assert(sizeof(A) == 64);
```

Used to be 64 but became 80. I bisected to this change.

```
$ llvm-project/build/bin/clang++ -target aarch64 -c foo.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
foo.c:4:22: warning: default member initializer for bit-field is a C++20 extension [-Wc++20-extensions]
    4 |      bool value : 64 = false;
      |                      ^
foo.c:8:15: error: static assertion failed due to requirement 'sizeof(A) == 64'
    8 | static_assert(sizeof(A) == 64);
      |               ^~~~~~~~~~~~~~~
foo.c:8:25: note: expression evaluates to '80 == 64'
    8 | static_assert(sizeof(A) == 64);
      |               ~~~~~~~~~~^~~~~
1 warning and 1 error generated.
```


```
% clang++-19 -target aarch64 -c foo.c
clang++-19: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
foo.c:4:22: warning: default member initializer for bit-field is a C++20 extension [-Wc++20-extensions]
    4 |      bool value : 64 = false;
      |                      ^
1 warning generated.
```

**Comment by ostannard** [comment]
That looks like the expected consequence of this change:
* Previously, the anonymous bitfield was erroneously given a 64-bit container, so it occupied 7 copies of the container type, starting at byte 8 of the struct and ending at 64.
* Now, it is given a 128-bit container, as required by AAPCS64, so it needs 4 copies of the container type, starting at byte 16 and ending at 80.

GCC also gives this struct a size of 80 bytes.

**Comment by fmayer** [comment]
Could we make sure this gets called out in the Release Notes? Even if it's a fix, this is a change of ABI which could break stuff.

**Comment by ostannard** [comment]
I'd assumed that this was a sufficiently uncommon edge-case that it wasn't worth a release note, but I'll keep that in mind in future and add release notes for things like this.
