### ISSUE TITLE
[libc++][test] `-Wunused-variable` warning in thread.semaphore/lost_wakeup.timed.pass.cpp

### ISSUE THREAD

**Issue by StephanTLavavej** [llvm/llvm-project#178855]
Introduced by #172214, FYI @huixie90.

https://github.com/llvm/llvm-project/blob/369e78774aef4f576a4fce37b55b8179170ce3f8/libcxx/test/std/thread/thread.semaphore/lost_wakeup.timed.pass.cpp#L28

emits:

```
D:\GitHub\STL\llvm-project\libcxx\test\std\thread\thread.semaphore\lost_wakeup.timed.pass.cpp(28,23): error: unused variable 'b' [-Werror,-Wunused-variable]
   28 | static std::barrier<> b(num_acquirer + 1);
      |                       ^
```

This is a problem for microsoft/STL's use of the libc++ test suite because we build the tests with warnings-as-errors to be good kitties.

**Comment by rturrado** [comment]
That variable `b` is not used, is it? I can create a PR removing that line.

**Comment by huixie90** [comment]
Yeah sorry. I will remove the unused variables
