### PR TITLE
[libc++] Fixes valarray proxy type compound assignment operations.

### LINKED ISSUE #21320: Cannot multiply a valarray and a single element slice_array
```
#include <valarray>

int main(int argc, char *argv[]) {
       std::valarray<double> a(4, 10);
       std::valarray<double> b(4, 20);
       a *= b[std::slice(1,1,1)];
       return 0;
}

fails to compile, with error:
test.cpp:6:4: error: no viable overloaded '*='
       a *= b[std::slice(1,1,1)];
       ~ ^  ~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/valarray:871:15: note: candidate function not viable: no known conversion from 'slice_array<value_type>' to 'const value_type'
     (aka 'const double') for 1st argument
   valarray& operator*= (const value_type& __x);
             ^
/usr/include/c++/v1/valarray:885:9: note: candidate template ignored: disabled by 'enable_if' [with _Expr = std::__1::slice_array<double>]
       __is_val_expr<_Expr>::value,
       ^

Compiles with gcc 4.8 and 4.9
```

### PR DESCRIPTION
**Pull request by mordante**
The valarray<>::operator[](...) const functions return proxy objects. The valarray<>::operator[](...) functions return valarray objects.

However the standard allows functions returning valarray objects to return custom proxy objects instead. Libc++ returns __val_expr proxies. Functions taking a valarray object must work with the custom proxies too. Therefore several operations have a custom proxy overload instead of valarray overloads.

Libc++ doesn't specify a valarray overload. This is an issue with the standard proxy types; these can implicitly be converted to a valarray.

The solution is to allow the standard proxies to behave as-if they are custom proxies.

This patch fixes the valarray compound assignments. Other operations, like the binary non-member functions are not fixed. These will be done in a followup patch.

Fixes: https://github.com/llvm/llvm-project/issues/21320

### CODE REVIEW

File: libcxx/include/valarray [hunk 1]
```diff
@@ -819,6 +819,19 @@ public:
   _LIBCPP_HIDE_FROM_ABI valarray& operator<<=(const value_type& __x);
   _LIBCPP_HIDE_FROM_ABI valarray& operator>>=(const value_type& __x);
 
+  // The valarray overloads are needed for the types with an implicit
+  // conversion to valarray. For example slice_array.
+  _LIBCPP_HIDE_FROM_ABI valarray& operator*=(const valarray& __v) { return operator*= <valarray>(__v); }
```
Comment (mordante) [inline libcxx/include/valarray:824]: @ldionne There are a lot more functions to convert and a lot more tests to write. I like to discuss this approach before doing that work. It's the intention to do everything in one patch.

Comment (ldionne) [reply libcxx/include/valarray:824]: Instead, I think we should make things like `gslice_array` & friends be `__val_expr`s and give them the necessary indexing operators (via a private name). That would allow for a much more efficient implementation of e.g. `valarray::operator*=` than if we need to create a temporary `valarray` first.

**Review by ldionne — CHANGES_REQUESTED** [review]

File: libcxx/include/valarray [hunk 2]
```diff
@@ -916,6 +947,21 @@ template <class _Tp, size_t _Size>
...
+
+template <class _Expr, __enable_if_t<__is_val_expr<_Expr>::value, int> = 0>
+_LIBCPP_HIDE_FROM_ABI typename _Expr::value_type __get(const _Expr& __v, size_t __i, false_type) {
+  return __v[__i];
+}
+
+template <class _Expr, __enable_if_t<__is_val_expr<_Expr>::value, int> = 0>
+_LIBCPP_HIDE_FROM_ABI typename _Expr::value_type __get(const _Expr& __v, size_t __i) {
+  return std::__get(__v, __i, __index_use_member_get<_Expr>()) ;
+}
```
Comment (ldionne) [inline libcxx/include/valarray:963]: Simplification suggestion:

```suggestion
template <class _Expr, __enable_if_t<__is_val_expr<_Expr>::value && __index_use_member_get<_Expr>(), int> = 0>
_LIBCPP_HIDE_FROM_ABI typename _Expr::value_type __get(const _Expr& __v, size_t __i) {
  return __v.__get(__i);
}

template <class _Expr, __enable_if_t<__is_val_expr<_Expr>::value && !__index_use_member_get<_Expr>(), int> = 0>
_LIBCPP_HIDE_FROM_ABI typename _Expr::value_type __get(const _Expr& __v, size_t __i) {
  return __v[__i];
}
```

File: libcxx/test/std/numerics/numarray/template.valarray/valarray.cassign/and_valarray.pass.cpp [hunk 3]
```diff
@@ -12,29 +12,71 @@
...
+// [valarray.syn]/3
+//   Any function returning a valarray<T> is permitted to return an object of
+//   another type, provided all the const member functions of valarray<T> are
+//   also applicable to this type.
+//
+// Libc++ uses this and returns __val_expr<_Expr> for several operations.
+//
+// The const overloads of
+//   valarray::operator[](...) const
+// return propxy objects. These proxies are implicitly convertable to
```
Comment (ldionne) [inline libcxx/test/std/numerics/numarray/template.valarray/valarray.cassign/and_valarray.pass.cpp:24]:
```suggestion
// return propxy objects. These proxies are implicitly convertible to
```

**Review by ldionne — COMMENTED** [review]
I think this is the right approach!

File: libcxx/test/libcxx/numerics/numarray/class.gslice.array/assert.get.pass.cpp [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
+// See https://llvm.org/LICENSE.txt for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+// REQUIRES: has-unix-headers
+// UNSUPPORTED: c++03
+// UNSUPPORTED: libcpp-hardening-mode=none
+// XFAIL: availability-verbose_abort-missing
```
Comment (mordante) [inline libcxx/test/libcxx/numerics/numarray/class.gslice.array/assert.get.pass.cpp:12]: @var-const after rebasing this test started to unexpectedly pass today on [Apple back-deployment with hardening enabled](https://buildkite.com/llvm-project/libcxx-ci/builds/33077#_) is that an issue in this test or an issue in main?

**Review by ldionne — APPROVED** [review]
Thanks for fixing this bug!

File: libcxx/test/libcxx/numerics/numarray/class.gslice.array/assert.get.pass.cpp (hunk 4 above)
Comment (var-const) [reply libcxx/test/libcxx/numerics/numarray/class.gslice.array/assert.get.pass.cpp:12]: @mordante This should now be 
```cpp
// XFAIL: libcpp-hardening-mode=debug && availability-verbose_abort-missing
```
We no longer check the error message in hardening modes below debug (debug still calls verbose abort but production modes just trap), so the availability of verbose abort is no longer important for these tests other than in the debug mode.

Comment (var-const) [reply libcxx/test/libcxx/numerics/numarray/class.gslice.array/assert.get.pass.cpp:12]: (I plan to soon add a lit feature that would combine all the requirements related to `check_assertion.h` together which should hopefully make this a bit nicer)
