### PR TITLE
[orc-rt] Add missing `#include <optional>`

### PR DESCRIPTION
**Pull request by kawashima-fj**
`std::optional` in `NativeDylibManager.h`, which was introduced in #201519, causes a compilation error.

```
llvm-project/orc-rt/include/orc-rt/NativeDylibManager.h:74:57: error: no member named 'optional' in namespace 'std'
   74 |       move_only_function<void(Expected<std::vector<std::optional<void *>>>)>;
      |                                                         ^~~~~~~~         
```

I don't know why other users don't encounter this error.

### CODE REVIEW

**Review by lhames — APPROVED** [review]

**Comment by lhames** [comment]
Thanks for the fix @kawashima-fj!

> I don't know why other users don't encounter this error.

It just depends on the SDK: Whatever I'm building on must be pulling std::optional in transitively.
