### PR TITLE
[clang] Fix couroutine error for operator new.

### PR DESCRIPTION
**Pull request by alinas**
Fix error occuring with couroutines:
"error: too many arguments to function call, expected 3, have 4" for operator new.

Introduced by cd67cfecb1a1.

AI assisted explanation of the issue:
Prior to cd67cfecb1a1, Sema::FindAllocationFunctions took OperatorNew by reference and would unconditionally reset it to nullptr at the beginning of its search. The commit changed FindAllocationFunctions to return a std::optional<ResolvedAllocation>.

In clang/lib/Sema/SemaCoroutine.cpp, the result is handled like this:

   1     IAP = ImplicitAllocationParameters(
   2         alignedAllocationModeFromBool(ShouldUseAlignedAlloc));
   3
   4     auto FoundAllocations = S.FindAllocationFunctions(...);
   5     if (FoundAllocations) {
   6       IAP = FoundAllocations->IAP;
   7       OperatorNew = FoundAllocations->OperatorNew;
   8     }

  If the coroutine promise defines an unaligned operator new(size_t, void*, size_t), the first lookup succeeds but is considered unaligned
  (IAP.PassAlignment resolves to No). Because aligned allocation is enabled by default, the coroutine builder attempts a second lookup without placement
  arguments:

   1     if (!OperatorNew || (S.getLangOpts().CoroAlignedAllocation &&
   2                          !isAlignedAllocation(IAP.PassAlignment)))
   3       LookupAllocationFunction(/*NewScope*/ AllocationFunctionScope::Class,
   4                                /*WithoutPlacementArgs*/ true);

  When this second lookup runs, it resets IAP.PassAlignment to Yes at the start of the lambda. However, if this second lookup fails to find an aligned
  operator new, FindAllocationFunctions returns std::nullopt.

  Because FoundAllocations is empty, OperatorNew is never reset to nullptr, and IAP is never reset to No. They leak state:
   - OperatorNew retains the result from the first successful lookup (which takes 3 parameters).
   - IAP.PassAlignment retains the initialized Yes from the second failed lookup.

### CODE REVIEW

**Review by boomanaiden154 — COMMENTED** [review]
A regression test would probably be good?

File: clang/lib/Sema/SemaCoroutine.cpp [hunk 1]
```diff
@@ -1488,6 +1488,8 @@ bool CoroutineStmtBuilder::makeNewAndDeleteExpr() {
     if (FoundAllocations) {
       IAP = FoundAllocations->IAP;
       OperatorNew = FoundAllocations->OperatorNew;
+    } else {
+      OperatorNew = nullptr;
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaCoroutine.cpp:1492]: I wonder if we can refactor LookupAllocationFunction so that it doesn't mutate state and/or add a comment.
at the very least I think LookupAllocationFunction should capture `OperatorNew` explicitly.

**Review by cor3ntin — COMMENTED** [review]
This change needs a release note.
Please add an entry to `clang/docs/ReleaseNotes.md` in the section the most adapted to the change, and referencing any Github issue this change fixes. Thanks!

**Comment by alinas** [comment]
I'm unsure if this specific change is the (only) one that needs the release notes added, vs the revision that did the changes which introduced the error.

Pinging @ojhunt as the author of the original change to follow up here. My goal is to resolve and get to green again, but I don't have enough clang or coroutine familiarity.

File: clang/lib/Sema/SemaCoroutine.cpp (hunk 1 above)
Comment (ojhunt) [reply clang/lib/Sema/SemaCoroutine.cpp:1492]: The simplification that caused this attempted to do just that - it's just going to require many passes to get to that point. Out parameters are the worst.

File: clang/lib/Sema/SemaCoroutine.cpp
Comment (ojhunt) [inline clang/lib/Sema/SemaCoroutine.cpp:1479]: It feels like a better fix would be:
```cpp
ImplicitAllocationParameters RetryIAP = ImplicitAllocationParameters(...);
S.FindAllocationFunctions(..., RetryIAP, ...);
...
```

Rather than replacing the IAP early before the second lookup.

Comment (ojhunt) [reply clang/lib/Sema/SemaCoroutine.cpp:1479]: *But to be clear, I haven't yet had time to look directly into this. I'm also unsure how we end up in a state where we're having to reset `OperatorNew` which is why I'm not 100% sure the above is correct (I believe it should be null already if we hit this path: the first lookup failed, which should mean it remains a nullptr, then the second fails so we shouldn't hit the path the writes a new value into it.

**Review by ojhunt — COMMENTED** [review]
I haven't had enough time to really think about this, but I do feel like the pre-resolution overwrite of IAP is incorrect, regardless of anything else.

I'll try to look at this more thoroughly in a few hours

**Comment by ojhunt** [comment]
@alinas could you point to the failing bot? (not a "ugh I don't trust you" just irked because I'd swear this passed pre-commit tests)

**Comment by ojhunt** [comment]
@alinas  would you be ok with merging this now to unblock the bots while I verify a full fix and work out if I can find other failure cases.

**Comment by boomanaiden154** [comment]
> could you point to the failing bot? (not a "ugh I don't trust you" just irked because I'd swear this passed pre-commit tests)

This was failing on some internal CI smoke tests from what I understand, not on any upstream (premerge or buildbot) infrastructure.

**Comment by alinas** [comment]
Confirming there was no public bot failing, this was found through internal testing. Hopefully the regressions test added in this PR will help in further iterations.

Thank you for merging!

**Comment by ojhunt** [comment]
Is it appropriate to auto-revert on downstream failures? I don't believe we've taken that approach previously, and I'm not sure I would feel comfortable doing that even it is allowed.

I'd just like to have @AaronBallman clarify what is expected in this scenario.

**Comment by boomanaiden154** [comment]
> Is it appropriate to auto-revert on downstream failures? I don't believe we've taken that approach previously, and I'm not sure I would feel comfortable doing that even it is allowed.

At least in LLVM, auto-revert on downstream failures where the failure is obviously wrong and a minimal reproducer is provided is generally how it's done.

**Comment by AaronBallman** [comment]
> Is it appropriate to auto-revert on downstream failures? I don't believe we've taken that approach previously, and I'm not sure I would feel comfortable doing that even it is allowed.
> 
> I'd just like to have @AaronBallman clarify what is expected in this scenario.

It can be appropriate to auto-revert on downstream failures, but isn't always. If there's a reproducer that shows the changes were incorrect in upstream, it's fine to do a timely revert. However, 1) the revert has to be timely but without jumping the gun; there may be additional failures to be found and we want to avoid revert/reland dances as much as we can, 2) the changes have to be incorrect; there needs to be a real analysis of the failure to determine the test was correct and the changes were wrong, not just "behavior changed downstream, revert upstream", and 3) the failure needs to have a reproducer at the time of the revert which shows the failure can be reproduced upstream (and we'd love for a minimal reproducer as soon as possible).

Outside of that kind of situation, it's more negotiable. e.g., we've had folks who can't share the reproducer immediately because it's customer code, but can share the crash log showing a failing assert added in the PR, with a promise that the public reproducer will be coming in a few hours, and ask if it's okay to revert. Or sometimes downstream testing finds an issue four days after the changes land and so there's questions as to whether a revert is better than fixing forward, so ask if it's okay to revert. That kind of thing.

**Comment by ojhunt** [comment]
In this particular case the switch to revert seemed unreasonably fast -- my general approach is to bring in the work around or reversion downstream to unblock our downstream bots while the appropriate solution is discussed here. 

There have been plenty of times where changes here have broken our downstream forks, and the cost of a downstream work around while a thorough discussion of the actual issue and appropriate fix in upstream has resulted in less work for everyone involved and less revert dancing.

My _personal_ view is that it is unreasonable for a downstream fork to force an immediate reversion of a change that does not break the main repository, and that's what I'm going to stick with.

But to be clear: I think that "downstream breakage that is unambiguously an error should trigger a revert" (as was the case here) is an equally reasonable position for someone to take.

**Comment by lexi-nadia** [comment]
I switched to a revert because, in my experience, I've found that, when there's an unambiguous error in a change, returning to a known-good state tends to be the most effective and expedient way to address the errors.

But my own perspective is biased by at least two things. First, this is the standard practice at the organization where I work, so it's at least partly "what I'm used to" rather than "unambiguous best practice". Second, we are the downstream customer who saw the error, and so it feels like a pressing problem for us in a way that it might not be in reality.

Basically, it hadn't even occurred to me that a revert would be perceived as anything other than the expected and appropriate action! :)

From the discussion on this thread, it sounds like that isn't actually the unambiguous standard practice for LLVM, and I made a bad assumption. Sorry about that!

**Comment by ojhunt** [comment]
> I switched to a revert because, in my experience, I've found that, when there's an unambiguous error in a change, returning to a known-good state tends to be the most effective and expedient way to address the errors.
> 
> But my own perspective is biased by at least two things. First, this is the standard practice at the organization where I work, so it's at least partly "what I'm used to" rather than "unambiguous best practice". Second, we are the downstream customer who saw the error, and so it feels like a pressing problem for us in a way that it might not be in reality.
> 
> Basically, it hadn't even occurred to me that a revert would be perceived as anything other than the expected and appropriate action! :)
> 
> From the discussion on this thread, it sounds like that isn't actually the unambiguous standard practice for LLVM, and I made a bad assumption. Sorry about that!

I do think that that is a perfectly reasonable view point -- my PoV is simply "downstream problems are our problem due to not having pushed sufficient tests, etc upstream". For our downstream forks we do reasonably fast reverts for unambiguously borked PRs in our trees, but it seems less common for us to push for upstream reverts - although I'm unsure how strongly other folk here have the same opinion as me.

For this case I was mostly wanting to verify the null reset was a correct fix vs simply papering over one part of a problem.
