### ISSUE TITLE
Mesa build error with clang 3.6.2 undefined reference to `llvm::sys::getProcessTriple()'

### ISSUE THREAD

**Issue by vinsonlee** [llvm/llvm-project#25118]
|  |  |
| --- | --- |
| Bugzilla Link | [24744](https://llvm.org/bz24744) |
| Version | 3.6 |
| OS | Linux |

## Extended Description 
Mesa fails to build with clang 3.6.2.

This build error occurs with clang 3.6.2 on Fedora 24 Rawhide and Ubuntu 15.10 Wily.

src/gallium/auxiliary/gallivm/lp_bld_debug.cpp:141: undefined reference to `llvm::sys::getProcessTriple()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Mesa builds successfully with clang 3.6.0 on Ubuntu 15.04 Vivid.

**Comment by arsenm** [comment]
Old build issue
