### ISSUE TITLE
clang 15.0.0: Template type deduction fails in C++20 mode

### ISSUE THREAD

**Issue by pkl97** [llvm/llvm-project#57797]
The following code fails to compile with clang 15.0.0 in C++20 mode:
```c++
#include <list>
#include <memory>
#include <string>

template<typename T, typename S>
std::list<T> mapType(const std::list<S>& /*p_values*/, const std::function<T (const S&)>& /*p_map*/)
{
    return std::list<T>();
}

int main()
{
    std::list<std::string> sourceList;
    std::list<std::shared_ptr<std::string>> targetList=mapType<std::shared_ptr<std::string>,std::string>(sourceList,&std::make_shared<std::string,const std::string&>);
    return 0;
}
```
This error occurs:
```console
[user@host]$ clang++ -std=c++20 -Wall -Wextra main.cpp
main.cpp:14:56: error: no matching function for call to 'mapType'
    std::list<std::shared_ptr<std::string>> targetList=mapType<std::shared_ptr<std::string>,std::string>(sourceList,&std::make_shared<std::string,const std::string&>);
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:6:14: note: candidate function template not viable: no overload of 'make_shared' matching 'const std::function<shared_ptr<string> (const string &)>' for 2nd argument
std::list<T> mapType(const std::list<S>& p_values, const std::function<T (const S&)>& p_map)
             ^
2 warnings and 1 error generated.
```

However the code compiles fine with clang 15.0.0 in C++17 mode (`-std=c++17`), clang 11.0.1 in C++20 mode and with Visual Studio 2019 19.11.18 (cl 19.29) also in C++20 mode. Could this be a bug in the compiler frontend or am I missing something?

**Comment by adi-g15** [comment]
I believe the problem might be with your build of clang (or maybe my build is old). I tried both (C++17, C++20) standards with clang 15.0.0 (release build), and clang 14.0.6 shipped with arch linux.

It compiles without any error, except a `error: no template named 'function' in namespace 'std'`, for which I added `#include <functional>` at top.

My build command for llvm clang:

```sh
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DLLVM_USE_LINKER=lld -DLLVM_ENABLE_PROJECTS="clang;mlir" -DLLVM_TARGETS_TO_BUILD="X86" ../llvm
```

**Comment by pkl97** [comment]
Hi @adi-g15

Sorry, I inadvertently left out an important piece. My compiler defaults to using libc++ as Standard Library, so the complete command to reproduce the issue is "clang++ -std=c++20 -stdlib=libc++ -Wall -Wextra main.cpp".

When using libstdc++ instead of libc++ then it works fine after adding the "functional" include as you pointed out.

**Comment by adi-g15** [comment]
> Hi @adi-g15
> 
> Sorry, I inadvertently left out an important piece. My compiler defaults to using libc++ as Standard Library, so the complete command to reproduce the issue is "clang++ -std=c++20 -stdlib=libc++ -Wall -Wextra main.cpp".

Oh thanks @pkl97 , **I can now reproduce the bug** :+1: (with the very recent commit: 7772624f3bac5499b36da8a20d5d73fcbc6f8683).

Command used to build clang:
```sh
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DLLVM_USE_LINKER=lld -DLLVM_ENABLE_PROJECTS="clang;mlir" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" -DLLVM_TARGETS_TO_BUILD="X86" ../llvm
```

Command used to run the given c++ code snippet:
```sh
clang++ -std=c++20 -stdlib=libc++ -Wall -Wextra main.cpp
```

**Comment by adi-g15** [comment]
Based on my observations, **this might not be an issue with clang, rather it is a bug in the code (undefined behaviour)**, and these are the reasons it fails to compile:

1. The given code snippet above fails to compile **since this is an error** with `libc++ 16.0.0` when compiled with `-std=c++20`, so substitution failure occurs and as per [SFINAE](https://devdocs.io/cpp/language/sfinae), compiler discards the specialization:

```cpp
const std::function< std::shared_ptr<string> (const string&) >& f1 = &std::make_shared<string, const string&>;
const auto& f2 = &std::make_shared<string, const string&>;
```

> It is the same with above code, that older versions or when using libstdc++ or when using C++17, it also compiles fine, only fails with `clang++` + `libstdc++` + `c++20`.

2. The previous snippet fails because it is **undefined behaviour** to take address of `std::make_shared` in C++20 (thanks to xiaoso for telling me this on discord, [message link](https://discord.com/channels/636084430946959380/636732894974312448/1020959197816434829)), see https://en.cppreference.com/w/cpp/language/extending_std#Addressing_restriction.
 
   Till C++17 it is not undefined behaviour, but now it is, so some like gcc and libstdc++ work, while libc++ doesn't, it's upto the compiler, and since it is undefined behaviour, so this might actually just be a bug in the code itself, not in clang.

@pkl97 this was the first time I tried to debug an issue in llvm repo, so might be wrong on these points somewhere, do let me know if you think so :sweat_smile:

**Comment by pkl97** [comment]
Hi @adi-g15 

Thanks a lot for the clarification! The C++20 Standard (16.4.5.2.1, paragraph 6) states:

> Let F denote a standard library function (16.4.6.4), a standard library static member function, or an
instantiation of a standard library function template. Unless F is designated an addressable function, the
behavior of a C++ program is unspecified (possibly ill-formed) if it explicitly or implicitly attempts to form a
pointer to F.

So we will update the code in question and close this ticket.
