### ISSUE TITLE
Bogus new error on Wparentheses

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#129429]
For this C++ code:

extern void g( int);

void f( int a, int b, int c)
{
	if (a <= b <= c)
	{
		g( a);
	}
}

given to a couple of recent builds of clang, does this:

Alphasrc $ /home/dcb40b/llvm/results.20250221/bin/clang++ -c -g -O2 -Wall mar2b.cc
mar2b.cc:6:13: warning: comparisons like 'X<=Y<=Z' don't have their mathematical meaning [-Wparentheses]
    6 |         if (a <= b <= c)
      |                    ^
1 warning generated.
Alphasrc $ /home/dcb40b/llvm/results.20250223/bin/clang++ -c -g -O2 -Wall mar2b.cc
mar2b.cc:6:13: error: comparisons like 'X<=Y<=Z' don't have their mathematical meaning [-Wparentheses]
    6 |         if (a <= b <= c)
      |                    ^
1 error generated.
Alphasrc $ 

I think it is an error to error on this code and a warning is fine.

**Comment by dcb314** [comment]
git hashes are 

af64f0a6c2e26b3fd1979c1fa380136e5528c9b3 and 72791fef6d6c84b72cb961b288b25283bea97310

This is 201 commits.

**Comment by zwuis** [comment]
Introduced by #128145.
