### ISSUE TITLE
Failing clang-cl OpenSSL build with error about stdatomic with latest MSVC 17.1.0

### ISSUE THREAD

**Issue by emmenlau** [llvm/llvm-project#53917]
I'm compiling current OpenSSL 1.1.1m with clang-cl 13.0.1 release from github. This used to work, but started failing last week when I updated MSVC from 2022 v17.0.x to v17.1.0. Now I get the following error:
```
clang-cl.exe  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /O2 -march=native /U__PRFCHW__ -utf-8 -FS /I "." /I "include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_MONT5" -D"OPENSSL_BN_ASM_GF2m" -D"SHA1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"KECCAK1600_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"AESNI_ASM" -D"VPAES_ASM" -D"GHASH_ASM" -D"ECP_NISTZ256_ASM" -D"X25519_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\"C:\\data\\usr-dst-C7Ha32c193131104c1301\\Tools\"" -D"ENGINESDIR=\"C:\\data\\usr-dst-C7Ha32c193131104c1301\\Tools\\lib\\engines-1_1\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  -c /Focrypto\asn1\a_sign.obj "crypto\asn1\a_sign.c"
In file included from crypto\asn1\a_sign.c:22:
In file included from include\crypto/evp.h:11:
In file included from include\internal/refcount.h:21:
In file included from C:\BDA\ci\LLVM-13.0.1\lib\clang\13.0.1\include\stdatomic.h:17:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\stdatomic.h(15,2): error: <stdatomic.h> is not yet supported when compiling as C, but this is planned for a future release.
#error <stdatomic.h> is not yet supported when compiling as C, but this is planned for a future release.
 ^
```

This used to work fine with MSVC 2022 v17.0.x. It also works when I manually define `__STDC_NO_ATOMICS__=1`.

**Comment by triplef** [comment]
I believe this was worked around in https://github.com/llvm/llvm-project/commit/1ad7de9e92bc2977698e5f6d6493202b50c912d5.

**Comment by emmenlau** [comment]
> I believe this was worked around in [1ad7de9](https://github.com/llvm/llvm-project/commit/1ad7de9e92bc2977698e5f6d6493202b50c912d5).

Yes, this looks like it should work. Closing as fixed. I will reopen if the problem persits.
