### PR TITLE
Reland: [clang] preserve class type sugar when taking pointer to member

### PR DESCRIPTION
**Pull request by mizvekov**
Original PR: #130537
Originally reverted due to revert of dependent commit. Relanding with no changes.

This changes the MemberPointerType representation to use a NestedNameSpecifier instead of a Type to represent the base class.

Since the qualifiers are always parsed as nested names, there was an impedance mismatch when converting these back and forth into types, and this led to issues in preserving sugar.

The nested names are indeed a better match for these, as the differences which a QualType can represent cannot be expressed syntatically, and they represent the use case more exactly, being either dependent or referring to a CXXRecord, unqualified.

This patch also makes the MemberPointerType able to represent sugar for a {up/downcast}cast conversion of the base class, although for now the underlying type is canonical, as preserving the sugar up to that point requires further work.

As usual, includes a few drive-by fixes in order to make use of the improvements.

### CODE REVIEW

**Review by Michael137 — COMMENTED** [review]
LLDB changes LGTM

**Comment by mstorsjo** [comment]
This change broke building Qt (tested with 6.8), ending up with errors like this:

```
qtbase/src/corelib/kernel/qcoreapplication.cpp:2946:78: error: 'this' cannot be used in a static member function declaration
 2946 |             : slotObject(std::move(slotObject)), context(context ? context : this)
      |                                                                              ^
qtbase/src/corelib/kernel/qobjectdefs_impl.h:405:23: note: in instantiation of template class 'QtPrivate::CallableHelper<void (PermissionReceiver::*)(const QPermission &)>' requested here
  405 |     struct Callable : CallableHelper<Func, Args...>::Type
      |                       ^
qtbase/src/corelib/kernel/qobjectdefs.h:437:38: note: in instantiation of template class 'QtPrivate::Callable<void (PermissionReceiver::*)(const QPermission &)>' requested here
  437 |                  typename QtPrivate::Callable<Func>::ReturnType *ret)
      |                                      ^
qtbase/src/corelib/kernel/qcoreapplication.cpp:2980:13: note: while substituting deduced template arguments into function template 'invokeMethod' [with Func = void (PermissionReceiver::*)(const QPermission &)]
 2980 |             QMetaObject::invokeMethod(receiver,
      |             ^
```

This issue also persists on the latest git main as of right now.

I've reduced the issue down to the following small reproducer:
```c++
template <typename Func> struct CallableHelper {
  static auto Resolve() -> Func;
};
struct QIODevice {
  void d_func() { d_ptr; }
  int d_ptr;
};
struct Callable : CallableHelper<void (QIODevice::*)()> {};
```
Reproducible with e.g. `clang -target x86_64-linux-gnu -c repro.cpp` (presumably the same way for any target).

**Comment by mizvekov** [comment]
Thanks, for the report, will be fixed by https://github.com/llvm/llvm-project/pull/132551

**Comment by mstorsjo** [comment]
> Thanks, for the report, will be fixed by #132551

Thanks for the quick fix, I can confirm that Qt builds fine for me again!

**Comment by rupprecht** [comment]
Still seeing a crash even with the latest fix applied
```
assertion failed at clang/include/clang/AST/Type.h:945 in const ExtQualsTypeCommonBase *clang::QualType::getCommonPtr() const: !isNull() && "Cannot retrieve a NULL type pointer"
*** Check failure stack trace: ***
    @     0x55e0dffed1f5  DeduceTemplateArgumentsByTypeMatch()
    @     0x55e0dffecc3e  DeduceTemplateArgumentsByTypeMatch()
    @     0x55e0dfff79f1  DeduceTemplateArguments()
    @     0x55e0dffe3ce9  DeduceTemplateArguments()
    @     0x55e0dffe47c0  clang::Sema::DeduceTemplateArguments()
    @     0x55e0e008943b  clang::Sema::InstantiateClassTemplateSpecialization()
    @     0x55e0e018b8a3  llvm::function_ref<>::callback_fn<>()
    @     0x55e0e0b04caf  clang::StackExhaustionHandler::runWithSufficientStackSpace()
    @     0x55e0e01741a8  clang::Sema::RequireCompleteTypeImpl()
    @     0x55e0e01739b5  clang::Sema::RequireCompleteType()
    @     0x55e0df8e6914  clang::Sema::RequireCompleteDeclContext()
    @     0x55e0dfd44fa9  clang::Sema::LookupParsedName()
    @     0x55e0dfb3b113  clang::Sema::BuildQualifiedDeclarationNameExpr()
    @     0x55e0e00d83e8  clang::TreeTransform<>::TransformDependentScopeDeclRefExpr()
    @     0x55e0e00d2529  clang::TreeTransform<>::TransformCallExpr()
    @     0x55e0e00ef218  clang::TreeTransform<>::TransformReturnStmt()
    @     0x55e0e00d9018  clang::TreeTransform<>::TransformCompoundStmt()
    @     0x55e0e008aa0a  clang::Sema::SubstStmt()
    @     0x55e0e011f3ce  clang::Sema::InstantiateFunctionDefinition()
    @     0x55e0e0b04caf  clang::StackExhaustionHandler::runWithSufficientStackSpace()
    @     0x55e0dffed9d6  clang::Sema::DeduceReturnType()
    @     0x55e0dfb2bac5  clang::Sema::DiagnoseUseOfDecl()
    @     0x55e0dfeb8361  FinishOverloadedCallExpr()
    @     0x55e0dfeb8274  clang::Sema::BuildOverloadedCallExpr()
    @     0x55e0dfb322ba  clang::Sema::BuildCallExpr()
    @     0x55e0dfb492b8  clang::Sema::ActOnCallExpr()
    @     0x55e0e00d2704  clang::TreeTransform<>::TransformCallExpr()
    @     0x55e0e008d052  clang::TreeTransform<>::TransformExprs()
    @     0x55e0e00d258c  clang::TreeTransform<>::TransformCallExpr()
    @     0x55e0e008d052  clang::TreeTransform<>::TransformExprs()
    @     0x55e0e00d258c  clang::TreeTransform<>::TransformCallExpr()
    @     0x55e0e00ef218  clang::TreeTransform<>::TransformReturnStmt()
    @     0x55e0e00d9018  clang::TreeTransform<>::TransformCompoundStmt()
    @     0x55e0e008aa0a  clang::Sema::SubstStmt()
    @     0x55e0e011f3ce  clang::Sema::InstantiateFunctionDefinition()
    @     0x55e0e01227ba  clang::Sema::PerformPendingInstantiations()
    @     0x55e0df88aaac  clang::Sema::ActOnEndOfTranslationUnitFragment()
    @     0x55e0df88b22b  clang::Sema::ActOnEndOfTranslationUnit()
    @     0x55e0df5a1e5a  clang::Parser::ParseTopLevelDecl()
    @     0x55e0df59e05e  clang::ParseAST()
...
```
In the meantime, I'll try reducing this

**Comment by mizvekov** [comment]
Thanks, that would be appreciated.

**Comment by mizvekov** [comment]
Thanks, this will be fixed here: https://github.com/llvm/llvm-project/pull/133113

**Comment by nico** [comment]
> Thanks, this will be fixed here: #133113

That also fixes an `Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.` we started seeing after this here landed (repro: https://issues.chromium.org/issues/406497227#comment3)

It'd be good if we could either land that soon or revert this here until the follow-up is ready, to keep HEAD green. (#133113 looks kind of involved, so maybe reverting first is safer? You'll need:

```
% git revert 960615954e4cb3150ae4a479fa7f9d0d17035eea
% git revert 5999be0f4770e9dd0f88ee9051a37119c8f5a1e4
% git revert 45270853192db53022ccadf4767999af4fe4e332
% git revert 14f7bd63b95d0f61a6f47119ac66398ca230559a
```

to also revert the existing 3 follow-ups, else you'll get conflicts.)

**Comment by mizvekov** [comment]
@nico thanks, that's landed. Let me know if it's all green now, otherwise we proceed with the revert.

**Comment by nico** [comment]
Looks like that helped, thanks!

**Comment by earnol** [comment]
Could you please look into https://github.com/llvm/llvm-project/issues/133144? It looks like to be caused by your change.

**Comment by alexfh** [comment]
I've found a new crash that's not fixed by https://github.com/llvm/llvm-project/pull/133343. Reducing...

**Comment by mizvekov** [comment]
@alexfh should be fixed by https://github.com/llvm/llvm-project/pull/133613

**Comment by alexfh** [comment]
> @alexfh should be fixed by #133613

Thank you! The crash is resolved. Do you still need a reduced test case?

**Comment by mizvekov** [comment]
> > @alexfh should be fixed by #133613
> 
> 
> 
> Thank you! The crash is resolved. Do you still need a reduced test case?

No worries, the tests included in PR already reproduce it.

**Comment by aeubanks** [comment]
@mizvekov we're seeing pcm non-determinism after this reland, does anything jump out at you?

**Comment by eaeltsin** [comment]
We are now seeing non-determinism in `.pcm` files that root-causes to this commit.

@mizvekov - might it be something obvious, like pointer-keyed containers or similar?

**Comment by mizvekov** [comment]
> We are now seeing non-determinism in `.pcm` files that root-causes to this commit.
> 
> @mizvekov - might it be something obvious, like pointer-keyed containers or similar?

I don't see anything obvious. The only parts of the patch which touch anything similar to pointer-keyed containers are the type properties cache changes, like the linkage computation.

**Comment by mizvekov** [comment]
@eaeltsin speculative fix here, but can you try with this patch? https://github.com/llvm/llvm-project/pull/135434

**Comment by eaeltsin** [comment]
Memory Sanitizer complains about initialized value [here](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Serialization/ASTReader.h#L2438)

Will try the patch now.

**Comment by eaeltsin** [comment]
@mizvekov - no, the patch doesn't help, or I did something wrong.

**Comment by mizvekov** [comment]
Okay, if the problem is an uninitialized source location somewhere, then that patch doesn't help at all.

**Comment by mizvekov** [comment]
Do you have a backtrace of that uninitialized read?

**Comment by eaeltsin** [comment]
Well, to be honest, I'm not completely sure these are the same problems, these are just sanitizer finding for the same compilation.

Here is the [MSan finding](https://gist.github.com/eaeltsin/834192fe5d8bbbc061e1488f113e34e1). Please note my source is somewhat behind the head, so locations might be off a bit

**Comment by mizvekov** [comment]
Thanks for that stack trace, could be unrelated to this, but that still helped find a bug: https://github.com/llvm/llvm-project/pull/135450

**Comment by eaeltsin** [comment]
Patched #135450 but still see the same MSan finding on my compilation - uninitialized value while checking location validity in `TranslateSourceLocation` called from `VisitSubstNonTypeTemplateParmExpr`.

Sorry but I'm not yet sure how to strip the reproducer from internal code so cannot provide it :|

**Comment by eaeltsin** [comment]
Using library with assertions, I'm seeing out-of-bounds source location read called from `ASTStmtReader::VisitSubstNonTypeTemplateParmExpr` - [trace](https://gist.github.com/eaeltsin/845fb9cc6f65f47ed03a64aca5aff923)

**Comment by eaeltsin** [comment]
Didn't fire so far.

Though this is non-deterministic, I might be (un)lucky.

**Comment by eaeltsin** [comment]
Comparing bcanalyzer --dump outputs for non-deterministic pcms, I see a lot of op values that differ by 1.

I wonder if this might be something like the mismatch of Read Write UnsignedOrNone vs unsigned ...

**Comment by mizvekov** [comment]
Could it be you are hitting an overflow/wrap around perhaps?

Some of these nodes store the unsignedOrNone representation in a bitfield, but that's still 15 bits.

**Comment by mizvekov** [comment]
In one of these changes we did bump one of these bit fields down to 15 bits, starting from 16.

**Comment by eaeltsin** [comment]
No, the problem seems to be in serialization/deserialization, there must be some mismatch between `ASTStmtWriter::VisitSubstNonTypeTemplateParmExpr` and `ASTStmtReader::VisitSubstNonTypeTemplateParmExpr`.

More precisely, I'm seeing that `ASTStmtWriter::VisitSubstNonTypeTemplateParmExpr` outputs a record of 5 elements, while `ASTStmtReader::VisitSubstNonTypeTemplateParmExpr` gets a record of 4 elements as input, and thus triggers assertion when reading the source location.

**Comment by emaxx-google** [comment]
Hello, the minimized reproducer for the determinism issue is there: https://pastebin.com/6aL6rmBe . To build it, unpack it into separate files (via `split-file`), then run `CLANG=path/to/clang make`. The nondeterminism can be checked by looping `make clean` + `make` + `md5sum problem.pcm` - typically a different hash pops up after a few dozens of iterations.

**Comment by gulfemsavrun** [comment]
We started seeing the following issue, and bisected to this commit.
```
test.cpp:8:12: error: no matching function for call to 'GetFieldChecked'
    8 |     return GetFieldChecked(b, &std::remove_reference<decltype(b)>::type::has_total);
      |            ^~~~~~~~~~~~~~~
test.cpp:6:5: note: candidate template ignored: deduced conflicting types for parameter 'Table' ('Bar' vs. 'const Bar')
    6 | int GetFieldChecked(const Table&, bool (Table::*)() const);
      |     ^
1 error generate
```

Here's a small test case:
```
#include <type_traits>
struct Bar {
  bool has_total() const;
};
template <typename Table>
int GetFieldChecked(const Table&, bool (Table::*)() const);
int foo(const Bar& b) { 
    return GetFieldChecked(b, &std::remove_reference<decltype(b)>::type::has_total);
}
```

If we just compile it via `clang++ -c test.cpp` with this commit, we ran into this issue and it is blocking us to roll Clang in our project.

**Comment by HighCommander4** [comment]
> Any update about the issue that I reported above?

You may want to open a new issue to track that, so it can get annotated with the appropriate labels (e.g. `rejects-valid`) and get more attention by showing up on issues lists / dashboards that people may be watching.

**Comment by mizvekov** [comment]
@gulfemsavrun thanks for reporting the issue.

This should be fixed soon by https://github.com/llvm/llvm-project/pull/142081

**Comment by igorkudrin** [comment]
Hi @mizvekov, there is a crash in Clang caused by this PR, could you take a look?
