### ISSUE TITLE
Call to consteval function in member initializer cause compilation error

### ISSUE THREAD

**Issue by finomen** [llvm/llvm-project#118000]
If consteval function called in method initializer and this class used in both consteval and not consteval functions, compilation fails with 
```
<source>:4:17: error: cannot take address of consteval function 'baz' outside of an immediate invocation
    int mSize = baz();
```

```c++
consteval int baz() { return 0;}

struct S {
    int mSize = baz();
};

consteval void bar() {
    S s;
}

void foo() {
    S s;
}
```

This bug is present in 16.x.x and >=18.0.0. (https://godbolt.org/z/o6EnWvvW7)

Issue was introduced in https://github.com/llvm/llvm-project/commit/ca619613801233ef2def8c3cc7d311d5ed0033cb
After it was fixed in https://github.com/llvm/llvm-project/commit/467688527017efb611b09c0cbf92f2d3ecdd1724
And happens again after https://github.com/llvm/llvm-project/commit/baf6bd303bd58a521809d456dd9b179636982fc5

**Comment by tbaederr** [comment]
CC @cor3ntin
