### PR TITLE
[debugserver] Fix debugserver build on < macOS 10.15

### LINKED ISSUE #156144: error: use of undeclared identifier 'VM_MEMORY_SANITIZER'
Build failure of flang 21.1.0 on macOS 10.14:

```
/opt/local/var/macports/build/lldb-21-46f2584b/work/llvm-project-21.1.0.src/lldb/tools/debugserver/source/MacOSX/MachVMRegion.cpp:212:26: error: use of undeclared identifier 'VM_MEMORY_SANITIZER'
  212 |       m_data.user_tag == VM_MEMORY_SANITIZER) {
      |                          ^
1 error generated.
```

Full log: https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/240590/steps/install-port/logs/stdio

Maybe these lines are needed in that file too:

https://github.com/llvm/llvm-project/blob/35a3ae3137800c14f63fb76c3dd4d429546269f6/compiler-rt/lib/sanitizer_common/sanitizer_mac.cpp#L112-L115

### PR DESCRIPTION
**Pull request by JDevlieghere**
The VM_MEMORY_SANITIZER constant was added in macOs 10.15 and friends. Support using the constant on older OSes.

Fixes #156144

### CODE REVIEW

**Review by felipepiovezan — APPROVED** [review]
Thanks for catching this!
