### ISSUE TITLE
clang-scan-deps fails to find stddef.h

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#60669]
Given the following translation unit

```cpp
#include <stddef.h>
```

Running

```shell
clang-scan-deps -format=p1689 -- -std=c++20 a.cpp -o /dev/null > /dev/null
```

fails with 

```console
Error while scanning dependencies for a.cpp:
a.cpp:1:10: fatal error: 'stddef.h' file not found
```

With a build at git revision 89197b59f597995ecb6b6dc2e262a1ecddeee901

Note that other includes work, so long as they do not transitively include `stddef.h` (and maybe other headers?). For instance, I can `#include <version>` just fine.

**Comment by davidstone** [comment]
Looks like this was introduced in 591fdcde921334b2d502779006d7c168307a2106 @ChuanqiXu9

**Comment by ChuanqiXu9** [comment]
I failed to reproduce this. And the command line should be  `clang-scan-deps -format=p1689 -- <compiler-executable> -std=c++20 a.cpp -o /dev/null > /dev/null`. I haven't added the docs since the clang-scan-deps is not stable. You can try again with 212d905

**Comment by ChuanqiXu9** [comment]
Oh, I reproduced this after I changed the work dir.
