### ISSUE TITLE
Using clang as CPP makes unexpected indentation changes

### ISSUE THREAD

**Issue by trini** [llvm/llvm-project#78778]
For background, over in [U-Boot](https://docs.u-boot.org/) we use the same "Kconfig" language as the Linux kernel, and so have a config file for a build that is defined with `CONFIG_FOO=y` and `# CONFIG_BAR is not set`. What we're doing now is allowing for a config file to `#include` another valid config file fragment, and using `$(CC) -E` to handle the include directive.

When using GCC, this works as expected and nothing about the files is changed. However, with clang-16 `# CONFIG_FOO is not set` becomes ` # CONFIG_FOO is not set`, which is invalid for the Kconfig language. I can pass in `-traditional-cpp` as another flag and in _some_ cases this will keep the expected behavior, but in others, it does not.

I've put an example of what I'm doing at: https://gist.github.com/trini/a9fec05a1010611f287661e58b17cbd0 which shows the trivial case. Using the [starfive_visionfive2_defconfig](https://source.denx.de/u-boot/u-boot/-/raw/master/configs/starfive_visionfive2_defconfig) file as non-trivial testcase shows that even with `-traditional-cpp` we still get some whitespace changes.

**Comment by shafik** [comment]
CC @cor3ntin @tahonermann

**Comment by tahonermann** [comment]
Hi @trini. I was able to reproduce the reported issue.

I spent a few minutes looking at this, but was unable to quickly identify where the leading space character is coming from. Any chance that you are able to investigate further? Alternatively, you might consider use of a `sed` script or similar to discard unwanted whitespace.

**Comment by trini** [comment]
Sorry @tahonermann but I have no idea where to start on the llvm side of the issue. I can work around the issue, yes, but I do worry about other cases where cpp is (ab)used and white space matters.

**Comment by trini** [comment]
Having just hit a much larger example of the problem, I'm just checking in to see if looking further in to this is on anyones radar, it sounds like it's unfortunately not clear where the problem might be and so possibly a difficult fix? Thanks.

**Comment by AaronBallman** [comment]
The leading whitespace is added by this block: https://github.com/llvm/llvm-project/blob/7677453886a665b37f22c77434b36a680aba6ebb/clang/lib/Frontend/PrintPreprocessedOutput.cpp#L709

It looks like that hack may need to be improved.

**Comment by tahonermann** [comment]
That hack goes back to at least 2006. Git history stops at https://github.com/llvm/llvm-project/commit/22eb972f387744658b8292afb84ca2c27b434816.

**Comment by trini** [comment]
Yeah, I'm not saying this is a recent regression in llvm, to be clear. A long-standing but just now problematic for someone situation is reasonable.

**Comment by tahonermann** [comment]
For ease of reference, here is the hack Aaron linked to:
```
clang/lib/Frontend/PrintPreprocessedOutput.cpp:
 703       // This hack prevents stuff like:
 704       // #define HASH #
 705       // HASH define foo bar
 706       // From having the # character end up at column 1, which makes it so it
 707       // is not handled as a #define next time through the preprocessor if in
 708       // -fpreprocessed mode.
 709       if (ColNo <= 1 && Tok.is(tok::hash))
 710         *OS << ' ';
```

I played around a bit and discovered the following interesting things.

1. Clang doesn't support a `-fpreprocessed` option as either a driver or a `-cc1` option.
2. Gcc does support a `-fpreprocessed` option and its behavior is sensitive to the hack.
3. Clang expands macros when compiling `.i` files or when invoked with `-x cpp-output`; gcc does not.

The following demonstrates how gcc's behavior changes with the hack in place. Note that `-fpreprocessed` is implied when compiling a `.i`, `.ii`, or `.mi` file and `-x` isn't used.
```
$ cat t.i
# define X foo
int i = X;
 # define Y bar
int j = Y;

$ gcc -c t.i
t.i:2:9: error: ‘X’ undeclared here (not in a function)
    2 | int i = X;
      |         ^
t.i:3:2: error: stray ‘#’ in program
    3 |  # define Y bar
      |  ^
t.i:3:4: error: unknown type name ‘define’
    3 |  # define Y bar
      |    ^~~~~~
t.i:3:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘bar’
    3 |  # define Y bar
      |             ^~~
```

The first define directive is ignored and `X` is not expanded. The second define directive is not ignored, but is not treated as a directive either.

In contrast, Clang processes both define directives as directives and performs macro expansion.
```
$ clang -c t.i
t.i:2:9: error: use of undeclared identifier 'foo'
    2 | int i = X;
      |         ^
t.i:1:12: note: expanded from macro 'X'
    1 | # define X foo
      |            ^
t.i:4:9: error: use of undeclared identifier 'bar'
    4 | int j = Y;
      |         ^
t.i:3:13: note: expanded from macro 'Y'
    3 |  # define Y bar
      |             ^
2 errors generated.
```

My conclusions:

1. This hack appears to date back to a time when someone (presumably Chris Lattner) was using Clang to generate preprocessed output that was then consumed by gcc. Perhaps this was part of very early Clang development when the preprocessor was being developed and fed to gcc to validate compilation.
2. The hack is probably no longer needed.
3. Clang should probably emulate gcc's `-fpreprocessed` behavior by ignoring preprocessor directives and suppressing macro expansion when processing files named `.i`, `.ii`, or `.mi` or when invoked with `-x cpp-output` or similar.

**Comment by tahonermann** [comment]
I locally removed the hack and ran the Clang testsuite. The following tests failed:

- `clang/test/Preprocessor/hash_space.c`
- `clang/test/Preprocessor/print-assembler.s`

The `hash_space.c` test exists specifically to test this hack, so removal is appropriate.

The `print-assembler.s` test is more interesting. It was introduced by commit https://github.com/llvm/llvm-project/commit/400a64e81b5a297f88a789573c89fe08c60bf914. This needs more investigation.

**Comment by ziyao233** [comment]
Someone has hit the issue again when building U-Boot with Clang 19[1]. Is there any possibility to get it resolved?

[1]: https://lore.kernel.org/u-boot/20250427145011.17331-2-ziyao@disroot.org/

**Comment by nathanielhourt** [comment]
> The print-assembler.s test is more interesting. It was introduced by commit 400a64e. This needs more investigation.

It would seem to me that the presence or absence of the leading space is insignificant to the functionality being tested there. Is it possible that the test was written as such simply because that's what passed with the existing implementation?

If the checks were rewritten to `// CHECK-NEXT: {{^ ?}}# asdf` then the test would become agnostic to the addition of the leading space to the original code.

**Comment by zygoloid** [comment]
> 2. The hack is probably no longer needed.
> 3. Clang should probably emulate gcc's `-fpreprocessed` behavior by ignoring preprocessor directives and suppressing macro expansion when processing files named `.i`, `.ii`, or `.mi` or when invoked with `-x cpp-output` or similar.

Unfortunately, I don't think that works. The problem is pragmas. Specifically, some pragmas take effect when the parser reaches them (and potentially have some Sema effect too). Such pragmas typically get transformed into tokens in the output of preprocessing. For example, `#pragma omp blah` or `#pragma clang diagnostics ignored("-Wfoo")`. Those pragmas need to be included in the `-E` output, and Clang writes them back out as `#pragma ...`.

In order for the compilation flow of first preprocessing and then compiling to work (eg, as some distributed compilation systems do), we need to execute *some* `#pragma`s in the preprocessed output. But we can also have a token sequence that resembles a pragma in the preprocessed output that was produced by macro expansion. And we can't produce the same output for both cases, otherwise we will miscompile one or the other. So for example:
```c++
#pragma message "Hello"
#define FOO #pragma message "World"
FOO
```
... is preprocessed by both GCC and Clang to
```c++
#pragma message "Hello"

 #pragma message "World"
```
... with a leading space before the line 3 pragma to disable the directive when in processing-preprocessed-source mode.

So, GCC also does the space-insertion thing. But it appears to use a [very strange rule](https://godbolt.org/z/WYhWrGzer). As far as I can tell, it inserts a space at the start of a line if it would otherwise start with a `#` produced by macro expansion, *or* if the line contained an unrecognized directive and the *previous* line started with a macro-expanded `#`. That doesn't make much sense to me; maybe it's a bug. GCC also seems to have changed behavior in version 13 onwards, and now silently eats recognized pragmas in `-x assembler-with-cpp` mode, even if they ought to have an effect later in processing.

I think probably the right thing for us to do here is to only produce a space at the start of a line if the line would otherwise start with a `#`, and that `#` was *not* at the start of the line in the original source. (Be careful of lines line `EMPTY#foo` preprocessing into `#foo`.)

Eg:
```diff
-      if (ColNo <= 1 && Tok.is(tok::hash))
+      if (ColNo <= 1 && Tok.is(tok::hash) && !Tok.isAtStartOfLine())
```
though someone will need to write some tests and make sure this does the right thing in corner cases.

**Comment by trini** [comment]
Since it seemed like @zygoloid had a plan to address this, I'm wondering if it's on anyones TODO list? We've been able to work around this issue for some time, but it would be nice to not have to at some point in the future if possible. Thanks!
