### ISSUE TITLE
MLIR fails to build with `MPI.cpp.o: multiple definition of 'mlir::`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#81875]
```
/usr/bin/ld.gold: error: tools/mlir/lib/Dialect/MPI/IR/CMakeFiles/obj.MLIRMPIDialect.dir/MPI.cpp.o: multiple definition of 'mlir::mpi::detail::CommRankOpGenericAdaptorBase::CommRankOpGenericAdaptorBase(mlir::DictionaryAttr, mlir::EmptyProperties const&, mlir::RegionRange)'
/usr/bin/ld.gold: tools/mlir/lib/Dialect/MPI/IR/CMakeFiles/obj.MLIRMPIDialect.dir/MPIOps.cpp.o: previous definition here
/usr/bin/ld.gold: error: tools/mlir/lib/Dialect/MPI/IR/CMakeFiles/obj.MLIRMPIDialect.dir/MPI.cpp.o: multiple definition of 'mlir::mpi::detail::CommRankOpGenericAdaptorBase::CommRankOpGenericAdaptorBase(mlir::mpi::CommRankOp)'
/usr/bin/ld.gold: tools/mlir/lib/Dialect/MPI/IR/CMakeFiles/obj.MLIRMPIDialect.dir/MPIOps.cpp.o: previous definition here
/usr/bin/ld.gold: error: tools/mlir/lib/Dialect/MPI/IR/CMakeFiles/obj.MLIRMPIDialect.dir/MPI.cpp.o: multiple definition of 'mlir::mpi::detail::CommRankOpGenericAdaptorBase::getODSOperandIndexAndLength(unsigned int, unsigned int)'
```
regression range:
562790f371f2..356400049064

**Comment by sylvestre** [comment]
seems that it was caused by #68892
cc @AntonLydike

**Comment by sylvestre** [comment]
Full log:
https://llvm-jenkins.debian.net/job/llvm-toolchain-lunar-binaries/architecture=arm64,distribution=lunar,label=arm64/584/consoleFull

**Comment by joker-eph** [comment]
Patch was reverted
