### PR TITLE
[libc++] Remove explicit mentions of __need_FOO macros

### PR DESCRIPTION
**Pull request by ldionne**
This change has a long history. It was first attempted naively in https://reviews.llvm.org/D131425, which didn't work because we broke the ability for code to include e.g. <stdio.h> multiple times and get different definitions based on the pre-defined macros.

However, in #86843 we managed to simplify <stddef.h> by including the underlying system header outside of any include guards, which worked.

This patch applies the same simplification we did to <stddef.h> to the other headers that currently mention __need_FOO macros explicitly.

### CODE REVIEW

**Review by philnik777 — APPROVED** [review]

File: libcxx/test/libcxx/clang_modules_include.gen.py [hunk 1]
```diff
@@ -49,6 +49,9 @@
 // TODO: Investigate why this doesn't work on Picolibc once the locale base API is refactored
 // UNSUPPORTED: LIBCXX-PICOLIBC-FIXME
 
+// TODO: Fix seemingly circular inclusion or <wchar.h> on AIX
+// UNSUPPORTED: LIBCXX-AIX-FIXME
```
Comment (ldionne) [inline libcxx/test/libcxx/clang_modules_include.gen.py:53]: @daltenty This appears to start failing on AIX after this patch, see e.g. https://buildkite.com/llvm-project/libcxx-ci/builds/39304#0193b131-ead6-42af-b231-48d8de48b2a6. I don't understand why it fails though, since we have proper include guards in `wchar.h` around the functions that are seemingly re-defined. Since I don't have access to an AIX box matching the CI to reproduce, it would be helpful if someone on the AIX side could take a look.

**Comment by petrhosek** [comment]
We started seeing a different failure on our downstream builders after this change:
```
FAILED: libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o 
/b/s/w/ir/x/w/llvm_build/./bin/clang++ --target=aarch64-unknown-linux-gnu --sysroot=/b/s/w/ir/x/w/cipd/linux -DLIBCXX_BUILDING_LIBCXXABI -DLIBC_NAMESPACE=__llvm_libc_common_utils -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_LINK_PTHREAD_LIB -D_LIBCPP_LINK_RT_LIB -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src -I/b/s/w/ir/x/w/llvm_build/include/aarch64-unknown-linux-gnu/c++/v1 -I/b/s/w/ir/x/w/llvm_build/include/c++/v1 -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/include -I/b/s/w/ir/x/w/llvm-llvm-project/runtimes/cmake/Modules/../../../libc --target=aarch64-unknown-linux-gnu -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins=../../../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes -O2 -g -DNDEBUG -std=c++2b -UNDEBUG -faligned-allocation -nostdinc++ -fvisibility-inlines-hidden -fvisibility=hidden -fsized-deallocation -Wall -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wzero-length-array -Wdeprecated-redundant-constexpr-static-def -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-error -MD -MT libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o -MF libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o.d -o libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o -c /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/charconv.cpp
In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/charconv.cpp:12:
In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/include/from_chars_floating_point.h:25:
In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/include/to_chars_floating_point.h:20:
In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/__algorithm/find.h:33:
In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/cwchar:114:
In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/cwctype:57:
In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/wctype.h:65:
In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/wctype.h:33:
In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/wchar.h:121:
In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/__mbstate_t.h:47:
In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/wchar.h:36:
In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/stdio.h:109:
In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/stdio.h:74:
In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/libio.h:31:
/b/s/w/ir/x/w/cipd/linux/usr/include/_G_config.h:24:3: error: unknown type name '__mbstate_t'
   24 |   __mbstate_t __state;
      |   ^
/b/s/w/ir/x/w/cipd/linux/usr/include/_G_config.h:29:3: error: unknown type name '__mbstate_t'
   29 |   __mbstate_t __state;
      |   ^
2 errors generated.
```
This is while building libc++ for Linux against Debian 8 "jessie" sysroot.

**Comment by glandium** [comment]
> We started seeing a different failure on our downstream builders after this change:
> 
> ```
> FAILED: libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o 
> /b/s/w/ir/x/w/llvm_build/./bin/clang++ --target=aarch64-unknown-linux-gnu --sysroot=/b/s/w/ir/x/w/cipd/linux -DLIBCXX_BUILDING_LIBCXXABI -DLIBC_NAMESPACE=__llvm_libc_common_utils -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_LINK_PTHREAD_LIB -D_LIBCPP_LINK_RT_LIB -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src -I/b/s/w/ir/x/w/llvm_build/include/aarch64-unknown-linux-gnu/c++/v1 -I/b/s/w/ir/x/w/llvm_build/include/c++/v1 -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/include -I/b/s/w/ir/x/w/llvm-llvm-project/runtimes/cmake/Modules/../../../libc --target=aarch64-unknown-linux-gnu -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins=../../../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes -O2 -g -DNDEBUG -std=c++2b -UNDEBUG -faligned-allocation -nostdinc++ -fvisibility-inlines-hidden -fvisibility=hidden -fsized-deallocation -Wall -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wzero-length-array -Wdeprecated-redundant-constexpr-static-def -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-error -MD -MT libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o -MF libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o.d -o libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o -c /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/charconv.cpp
> In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/charconv.cpp:12:
> In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/include/from_chars_floating_point.h:25:
> In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/include/to_chars_floating_point.h:20:
> In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/__algorithm/find.h:33:
> In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/cwchar:114:
> In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/cwctype:57:
> In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/wctype.h:65:
> In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/wctype.h:33:
> In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/wchar.h:121:
> In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/__mbstate_t.h:47:
> In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/wchar.h:36:
> In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/stdio.h:109:
> In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/stdio.h:74:
> In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/libio.h:31:
> /b/s/w/ir/x/w/cipd/linux/usr/include/_G_config.h:24:3: error: unknown type name '__mbstate_t'
>    24 |   __mbstate_t __state;
>       |   ^
> /b/s/w/ir/x/w/cipd/linux/usr/include/_G_config.h:29:3: error: unknown type name '__mbstate_t'
>    29 |   __mbstate_t __state;
>       |   ^
> 2 errors generated.
> ```
> 
> This is while building libc++ for aarch64 Linux against Debian 8 "jessie" sysroot.

Same here, while building libcxx-fuzzing for x86-64 linux against Debian jessie sysroot.

**Comment by ldionne** [comment]
This would seem to point to a missing include in the system headers that is being exposed by this patch, but it's really hard to tell without having a local repro. I tried installing Debian Jessie in a Docker image but I can't get anything to work in it, `apt-get update` won't even work.

**Comment by petrhosek** [comment]
> This would seem to point to a missing include in the system headers that is being exposed by this patch, but it's really hard to tell without having a local repro. I tried installing Debian Jessie in a Docker image but I can't get anything to work in it, `apt-get update` won't even work.

If you want to reproduce this locally, you can download our sysroot from https://chrome-infra-packages.appspot.com/p/fuchsia/third_party/sysroot/linux/+/dCkoVcYlgGIP_pmR61ZMIrSDgdrV81BtxcPeTRuyqlUC and use it with `CMAKE_SYSROOT`.

We still use Debian 8 "jessie" as our sysroot because it corresponds to Ubuntu 14.04 which is still used by a number of projects (including Android) and that way we can guarantee that binaries produced by our toolchain will run there, but we don't actually do any builds on Debian 8 "jessie" or ubuntu 14.04.

**Comment by ldionne** [comment]
I am trying to run in a ubuntu Docker image with your sysroot and hitting some failures:

```
$ cmake -S runtimes/ -B build -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_C_COMPILER=clang-19 -DCMAKE_SYSROOT=/tmp/sysroot-linux -GNinja
-- Performing standalone runtimes build.
CMake Deprecation Warning at /tmp/llvm-project/cmake/Modules/CMakePolicy.cmake:6 (cmake_policy):
  The OLD behavior for policy CMP0116 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:18 (include)


-- The C compiler identification is Clang 19.1.6
-- The CXX compiler identification is Clang 19.1.6
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /usr/bin/clang-19
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/clang-19
-- Check for working C compiler: /usr/bin/clang-19 - broken
CMake Error at /usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/usr/bin/clang-19"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/tmp/llvm-project/build/CMakeFiles/CMakeScratch/TryCompile-vkoXgV'

    Run Build Command(s): /usr/bin/ninja -v cmTC_94ff8
    [1/2] /usr/bin/clang-19 --sysroot=/tmp/sysroot-linux    -MD -MT CMakeFiles/cmTC_94ff8.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_94ff8.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_94ff8.dir/testCCompiler.c.o -c /tmp/llvm-project/build/CMakeFiles/CMakeScratch/TryCompile-vkoXgV/testCCompiler.c
    [2/2] : && /usr/bin/clang-19 --sysroot=/tmp/sysroot-linux   CMakeFiles/cmTC_94ff8.dir/testCCompiler.c.o -o cmTC_94ff8   && :
    FAILED: cmTC_94ff8
    : && /usr/bin/clang-19 --sysroot=/tmp/sysroot-linux   CMakeFiles/cmTC_94ff8.dir/testCCompiler.c.o -o cmTC_94ff8   && :
    /usr/bin/ld: cannot find crtbeginS.o: No such file or directory
    /usr/bin/ld: cannot find -lgcc: No such file or directory
    /usr/bin/ld: cannot find -lgcc_s: No such file or directory
    clang-19: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:23 (project)


-- Configuring incomplete, errors occurred!
```

If you want me to investigate, I'm happy to do that but I'll need a clear reproducer.

**Comment by glandium** [comment]
Can you try with this sysroot: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/b2JMQqG2TSWBboQasE6Lag/runs/0/artifacts/public%2Fbuild%2Fsysroot-x86_64-linux-gnu.tar.zst

**Comment by petrhosek** [comment]
> If you want me to investigate, I'm happy to do that but I'll need a clear reproducer.

Our sysroot doesn't contain libgcc since we always use compiler-rt and libunwind, so you need `-DCMAKE_{SHARED,MODULE,EXE}_LINKER_FLAGS="--rtlib=compiler-rt --unwindlib=libunwind"`.

**Comment by ldionne** [comment]
Now I get:

```
CMake Error at /usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/usr/bin/clang-19"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/tmp/llvm-project/build/CMakeFiles/CMakeScratch/TryCompile-byXI6P'

    Run Build Command(s): /usr/bin/ninja -v cmTC_b2c1b
    [1/2] /usr/bin/clang-19 --sysroot=/tmp/sysroot-linux    -MD -MT CMakeFiles/cmTC_b2c1b.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_b2c1b.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_b2c1b.dir/testCCompiler.c.o -c /tmp/llvm-project/build/CMakeFiles/CMakeScratch/TryCompile-byXI6P/testCCompiler.c
    [2/2] : && /usr/bin/clang-19 --sysroot=/tmp/sysroot-linux  --rtlib=compiler-rt --unwindlib=libunwind CMakeFiles/cmTC_b2c1b.dir/testCCompiler.c.o -o cmTC_b2c1b   && :
    FAILED: cmTC_b2c1b
    : && /usr/bin/clang-19 --sysroot=/tmp/sysroot-linux  --rtlib=compiler-rt --unwindlib=libunwind CMakeFiles/cmTC_b2c1b.dir/testCCompiler.c.o -o cmTC_b2c1b   && :
    /usr/bin/ld: cannot find -lunwind: No such file or directory
    clang-19: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
  ```
  
Sorry, but I can't play whack-a-mole like that. Can you please provide a working reproducer (e.g. a script that sets up the necessary Docker image + CMake invocation), a pre-commit CI bot that catches it, or perform the analysis of why this is now failing yourself? Otherwise, that isn't really workable -- this patch is correct according to our CI, and that's how we determine what's supported. I don't want to be pedantic and use that criterion to dismiss arbitrary breakage, but we do need to draw a line about where contributor responsibility ends and consumers' responsibility begins, otherwise folks can offload arbitrary troubleshooting to us.

**Comment by glandium** [comment]
Please try the sysroot from https://github.com/llvm/llvm-project/pull/119025#issuecomment-2552356809

**Comment by petrhosek** [comment]
I tested the following instructions locally and confirmed that it reproduces the failure:

```
docker run --rm -it ubuntu:24.04
$ apt-get update
$ apt install lsb-release wget software-properties-common gnupg git cmake ninja-build zstd
$ wget https://apt.llvm.org/llvm.sh
$ chmod +x llvm.sh
$ ./llvm.sh 19 all
$ wget https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/b2JMQqG2TSWBboQasE6Lag/runs/0/artifacts/public%2Fbuild%2Fsysroot-x86_64-linux-gnu.tar.zst
$ tar -xf public%2Fbuild%2Fsysroot-x86_64-linux-gnu.tar.zst
$ git clone https://github.com/llvm/llvm-project
$ cd llvm-project
$ cmake -S runtimes/ -B build -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_C_COMPILER=clang-19 -DCMAKE_SYSROOT=/sysroot-x86_64-linux-gnu -GNinja
$ ninja -C build
```

**Comment by ldionne** [comment]
Thanks for the steps, I followed exactly that but I still get:

```
CMake Error at /usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/usr/bin/clang-19"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/llvm-project/build/CMakeFiles/CMakeScratch/TryCompile-w2zQf9'

    Run Build Command(s): /usr/bin/ninja -v cmTC_5116d
    [1/2] /usr/bin/clang-19 --sysroot=/sysroot-x86_64-linux-gnu    -MD -MT CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o -c /llvm-project/build/CMakeFiles/CMakeScratch/TryCompile-w2zQf9/testCCompiler.c
    [2/2] : && /usr/bin/clang-19 --sysroot=/sysroot-x86_64-linux-gnu   CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o -o cmTC_5116d   && :
    FAILED: cmTC_5116d
    : && /usr/bin/clang-19 --sysroot=/sysroot-x86_64-linux-gnu   CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o -o cmTC_5116d   && :
    /usr/bin/ld: cannot find Scrt1.o: No such file or directory
    /usr/bin/ld: cannot find crti.o: No such file or directory
    /usr/bin/ld: cannot find crtbeginS.o: No such file or directory
    /usr/bin/ld: cannot find -lgcc: No such file or directory
    /usr/bin/ld: cannot find -lgcc_s: No such file or directory
    /usr/bin/ld: cannot find -lc: No such file or directory
    /usr/bin/ld: cannot find -lgcc: No such file or directory
    /usr/bin/ld: cannot find -lgcc_s: No such file or directory
    /usr/bin/ld: cannot find crtendS.o: No such file or directory
    /usr/bin/ld: cannot find crtn.o: No such file or directory
    clang-19: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
```

**Comment by petrhosek** [comment]
> Thanks for the steps, I followed exactly that but I still get:
> 
> ```
> CMake Error at /usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:67 (message):
>   The C compiler
> 
>     "/usr/bin/clang-19"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: '/llvm-project/build/CMakeFiles/CMakeScratch/TryCompile-w2zQf9'
> 
>     Run Build Command(s): /usr/bin/ninja -v cmTC_5116d
>     [1/2] /usr/bin/clang-19 --sysroot=/sysroot-x86_64-linux-gnu    -MD -MT CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o -c /llvm-project/build/CMakeFiles/CMakeScratch/TryCompile-w2zQf9/testCCompiler.c
>     [2/2] : && /usr/bin/clang-19 --sysroot=/sysroot-x86_64-linux-gnu   CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o -o cmTC_5116d   && :
>     FAILED: cmTC_5116d
>     : && /usr/bin/clang-19 --sysroot=/sysroot-x86_64-linux-gnu   CMakeFiles/cmTC_5116d.dir/testCCompiler.c.o -o cmTC_5116d   && :
>     /usr/bin/ld: cannot find Scrt1.o: No such file or directory
>     /usr/bin/ld: cannot find crti.o: No such file or directory
>     /usr/bin/ld: cannot find crtbeginS.o: No such file or directory
>     /usr/bin/ld: cannot find -lgcc: No such file or directory
>     /usr/bin/ld: cannot find -lgcc_s: No such file or directory
>     /usr/bin/ld: cannot find -lc: No such file or directory
>     /usr/bin/ld: cannot find -lgcc: No such file or directory
>     /usr/bin/ld: cannot find -lgcc_s: No such file or directory
>     /usr/bin/ld: cannot find crtendS.o: No such file or directory
>     /usr/bin/ld: cannot find crtn.o: No such file or directory
>     clang-19: error: linker command failed with exit code 1 (use -v to see invocation)
>     ninja: build stopped: subcommand failed.
> ```

Are you using an Arm machine by any chance? What's the output of `uname -a` (inside the container)?

**Comment by zeroomega** [comment]
Not sure if it is helpful for understanding the underlying issue. I reproduced the issue locally and used -dD and -E to see the pre-processed file. And noticed a difference in handling the headers


Before this patch:

system wchar.h ->(include) libcxx/stdio.h ->(include) system stdio.h ->(end of included file) libcxx/stdio.h ->(include) system wchar.h -> define mbstate_t type -> ... -> (include) system _G_config.h -> define __need_mbstate_t -> (include) system wchar.h (but skipped due to header macro) -> used __need_mbstate_t

After this patch:

system wchar.h ->(include) libcxx/stdio.h ->(include) system stdio.h  -> (end of included file) libcxx/stdio.h -> (include) system stdio.h -> (end of included file) libcxx/stdio.h ->(include) system stdio.h -> ... -> system _G_config.h ->  define __need_mbstate_t  -> system wchar.h (but skipped due to header macro) -> use before define error 

It appears to me after this patch, during the processing of `wchar.h`, before the definition of the `mbstate_t` types,  libcxx stdio.h header caused the `_G_config.h` to be included and processed. Despite the `_G_config.h`includes the `wchar.h`, the wchar's include macro was already defined at this point so it has no effect. Before this patch, the `wchar.h` will finish processing before `_G_config.h` was included. In a local experiment, I reverted your change to the `stdio.h` but keep the rest of the patch unchanged, the build passed. Also in my local reproduction, the i386-linux and x64-linux runtimes are also affected by this build failure, not just arm64.

**Comment by ldionne** [comment]
Isn't that a circular dependency in the system headers?

After the patch, it looks like we have

```
system wchar.h ->... -> (include) system stdio.h -> ... -> system _G_config.h -> define __need_mbstate_t -> system wchar.h
```

How does including just the system's `wchar.h` header differ from that? Does that also fail (I can't imagine)?

**Comment by petrhosek** [comment]
The behavior of system `wchar.h` differs based on which `__need_FOO` macros; this is the case for other system headers as well, not just `wchar.h`, so the fact that it's being included multiple times is likely working as intended in this case.

@ldionne Would it be possible to revert this change? I plan to continue looking into this issue to see if there's another way to achieve the same result without breaking the compatibility with older sysroots, but I'd like to avoid leaving our downstream builders completely broken for the next two weeks since that will mean will loose test coverage during that time.

**Comment by kongy** [comment]
> > We started seeing a different failure on our downstream builders after this change:
> > ```
> > FAILED: libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o 
> > /b/s/w/ir/x/w/llvm_build/./bin/clang++ --target=aarch64-unknown-linux-gnu --sysroot=/b/s/w/ir/x/w/cipd/linux -DLIBCXX_BUILDING_LIBCXXABI -DLIBC_NAMESPACE=__llvm_libc_common_utils -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_LINK_PTHREAD_LIB -D_LIBCPP_LINK_RT_LIB -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src -I/b/s/w/ir/x/w/llvm_build/include/aarch64-unknown-linux-gnu/c++/v1 -I/b/s/w/ir/x/w/llvm_build/include/c++/v1 -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/include -I/b/s/w/ir/x/w/llvm-llvm-project/runtimes/cmake/Modules/../../../libc --target=aarch64-unknown-linux-gnu -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins=../../../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes -O2 -g -DNDEBUG -std=c++2b -UNDEBUG -faligned-allocation -nostdinc++ -fvisibility-inlines-hidden -fvisibility=hidden -fsized-deallocation -Wall -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wzero-length-array -Wdeprecated-redundant-constexpr-static-def -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-error -MD -MT libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o -MF libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o.d -o libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o -c /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/charconv.cpp
> > In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/charconv.cpp:12:
> > In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/include/from_chars_floating_point.h:25:
> > In file included from /b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/include/to_chars_floating_point.h:20:
> > In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/__algorithm/find.h:33:
> > In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/cwchar:114:
> > In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/cwctype:57:
> > In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/wctype.h:65:
> > In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/wctype.h:33:
> > In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/wchar.h:121:
> > In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/__mbstate_t.h:47:
> > In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/wchar.h:36:
> > In file included from /b/s/w/ir/x/w/llvm_build/include/c++/v1/stdio.h:109:
> > In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/stdio.h:74:
> > In file included from /b/s/w/ir/x/w/cipd/linux/usr/include/libio.h:31:
> > /b/s/w/ir/x/w/cipd/linux/usr/include/_G_config.h:24:3: error: unknown type name '__mbstate_t'
> >    24 |   __mbstate_t __state;
> >       |   ^
> > /b/s/w/ir/x/w/cipd/linux/usr/include/_G_config.h:29:3: error: unknown type name '__mbstate_t'
> >    29 |   __mbstate_t __state;
> >       |   ^
> > 2 errors generated.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is while building libc++ for aarch64 Linux against Debian 8 "jessie" sysroot.
> 
> Same here, while building libcxx-fuzzing for x86-64 linux against Debian jessie sysroot.

This change also broke Android's ToT integration in the same way.

**Comment by petrhosek** [comment]
The breakage should be addressed by #120946, at least on our side the builders are back to green. Let me know if you still see the issue.
