### ISSUE TITLE
[Flang][OpenMP] critical region with "omp_" leading name regression.

### ISSUE THREAD

**Issue by scamp-nvidia** [llvm/llvm-project#205855]
Consider the following code: 

```fortran
module repro_mod
  implicit none
  type :: t
  contains
    procedure :: sub
  end type t
contains
  logical function skip_unit(u)
    integer, intent(in) :: u
    logical :: opened
    inquire(unit=u, opened=opened)
    skip_unit = .not. opened
  end function skip_unit
  subroutine sub(this, text, us)
    class(t), intent(in) :: this
    character(len=*), intent(in) :: text
    integer, intent(in) :: us(:)
    integer :: i
    do i = 1, size(us)
      if (skip_unit(us(i))) cycle
      !$omp critical(omp_c)
      write(us(i), '(a)') text
      flush(us(i))
      !$omp end critical(omp_c)
    end do
  end subroutine sub
end module repro_mod
```

Compiling this code emits the following error message: 

```
scamp$ flang test.F90 -fopenmp -c
error: Semantic errors in test.F90
test.F90:21:22: error: Internal: no symbol found for 'omp_c'
        !$omp critical(omp_c)
                       ^^^^^
test.F90:21:22: error: CRITICAL argument should be a name
        !$omp critical(omp_c)
                       ^^^^^
test.F90:21:22: error: 'OMP_C' is not a valid locator
        !$omp critical(omp_c)
                       ^^^^^
test.F90:24:26: error: Internal: no symbol found for 'omp_c'
        !$omp end critical(omp_c)
                           ^^^^^
test.F90:24:26: error: CRITICAL argument should be a name
        !$omp end critical(omp_c)
                           ^^^^^
test.F90:24:26: error: 'OMP_C' is not a valid locator
        !$omp end critical(omp_c)
                           ^^^^^
```

If I change the "omp_c" name to "c" - then it compiles as previously expected. From regression testing we know that it passed before c656cb11639b5e6bd43fc691b3dab91a5d42ce37 and failed after a1cdfebb72880cb1b5039611cafee7ca3af7a368. In that range, I immediately look suspiciously at 

14840af5d694f40dbc8b1733330da2db4000335c
[flang][OpenMP] Check that IF clause applies to at most one leaf 

846793e2a57a39c90a4e57a61ea940127bbabf1a
[flang][OpenMP][NFC] Hoist variant match-info construction into Semantics 

1cf4a0cb7909cb7b9e0bf15757fc77dc9b02c796
[flang][OpenMP] Lower task reduction modifier

e68e8d35c91b4fd3ba0ae3ef12d79b41d92580b2
[flang][OpenMP] Parsing and semantics of locators as part of OmpObject 

This fell out from testing a large, important application in our stack. Pinging the authors of the suspicious commits: @kparzysz @Saieiei @abidh

**Comment by Saieiei** [comment]
Thanks for the ping and the bisect range.

I had a quick look, and I don't think #205124 / `1cf4a0c` is involved here. That change only touches task-reduction-modifier lowering / MLIR-to-LLVMIR translation, and does not touch the parser, semantics, name resolution, `OmpObject`, locator handling, or `critical(name)` handling. The diagnostics here are emitted before lowering runs.

The behavior seems to match `e68e8d3` / #203910 more closely. In that change, `OmpObject` parsing tries the locator path first, and names starting with `OMP_` / `OMPX_` are treated as reserved locator identifiers. That would explain why `critical(omp_c)` is parsed differently and fails with the locator-related diagnostic, while `critical(c)` still works.

So I think the fix is likely in the reserved-locator / `OmpObject` parsing path, probably making sure ordinary names are not swallowed as reserved locators in contexts like `critical(name)`. Happy to help test a patch or add a regression test if useful.

**Comment by kparzysz** [comment]
`omp_c` is a reserved name (since it starts with the `omp_` prefix).  The locator PR added handling of reserved names, but missed this case.

[6.0:149:11-13]
> OpenMP reserves names that begin with the omp_, ompt_ and ompd_ prefixes for names defined in this specification so OpenMP programs must not declare names that begin with them.

**Comment by scamp-nvidia** [comment]
Hi - am I reading your response/pull request correctly that you're going to emit a better error message, but not revert back to the original behavior? Is this just for openmp version 6 support, or all openmp versions? Because I looked at what GNU, NVHPC, and IFX all do currently with regards to this and they compile it. 

```
[scamp]$ module purge ; module load gcc/16.1.0
[scamp]$ gfortran test.F90 -fopenmp -c
[scamp]$ module purge ; module load intel/latest
[scamp]$ ifx --version
ifx (IFX) 2025.3.2 20260112
Copyright (C) 1985-2026 Intel Corporation. All rights reserved.
[scamp]$ ifx test.F90 -fopenmp -c
[scamp]$ module purge ; module load nvhpc/26.5
[scamp]$ nvfortran test.F90 -fopenmp -c
[scamp]$
```

We took this example from a large European chemistry code, so this change is going to have a big impact - I think they only release once or twice a year and getting code changes in is a slow process. If we don't support this, their builds may start failing with Flang and Flang-based compilers for some time before they can catch up their code base. 

I'm not pushing back on the correctness of it - if OpenMP version 6 says this isn't allowed, then that's okay. But just trying to look at the whole picture and understand.

**Comment by sscalpone** [comment]
Thanks @kparzysz for explaining that OpenMP reserves identifiers with the `omp_` prefix starting with v5.2.

I expected to see an error from this example:
```
% cat mp2.f90
 logical :: omp_available
 end
% flang -c mp2.f90 -fopenmp -fopenmp-version=60
%
```
Is the prohibition general or only in specific contexts?

My recommendation is to flag the reserved identifiers with a warning (so the user can promote it to an error).  Flang's OpenMP implementation uses the OpenMP version to adjust the compiler's behavior, which would be another avenue for enforcing the OpenMP 5.2+ rule.  (I prefer the warning.)
