### PR TITLE
[llvm] Fixed ItaniumDemangle.h compiled by MSVC

### PR DESCRIPTION
**Pull request by slydiman**
If the includes tree is big enough, `llvm::itanium_demangle::PointerType` may conflict with `llvm::PointerType` from other headers. This patch fixes the following [error](https://lab.llvm.org/buildbot/#/builders/141/builds/8206):
```
C:\lldb-aarch64-windows\llvm-project\llvm\include\llvm/Demangle/ItaniumDemangle.h(617,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
  617 |   friend class PointerType;
      |                ^
      |                ::llvm::
C:\lldb-aarch64-windows\llvm-project\llvm\include\llvm/Demangle/ItaniumDemangle.h(667,24): error: 'Protocol' is a private member of 'llvm::itanium_demangle::ObjCProtoName'
  667 |       OB += objcProto->Protocol;
      |                        ^
C:\lldb-aarch64-windows\llvm-project\llvm\include\llvm/Demangle/ItaniumDemangle.h(615,20): note: implicitly declared private here
  615 |   std::string_view Protocol;
```
Few buildbots broken by #131836 must be green after this patch.

### CODE REVIEW

**Comment by Michael137** [comment]
I already fixed this in a separate commit by just not using the `friend class` idiom: https://github.com/llvm/llvm-project/commit/bd96fa778809d70e688d27cae2f7667b2aed69c0

**Comment by Michael137** [comment]
Apologies for the disruption with the buildbots

**Comment by slydiman** [comment]
> The bots are now red for other reasons

https://github.com/llvm/llvm-project/pull/131836#issuecomment-2831613099
