### ISSUE TITLE
Failure in using clang under nvcc

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#57763]
I start to see the following failure in my nightly builds since 20220908,
```console
$ nvcc --allow-unsupported-compiler -ccbin=/soft/compilers/llvm/main-20220908/bin/clang++ -gencode=arch=compute_80,code=sm_80 ./CMakeFiles/3.23.2/CompilerIdCUDA/CMakeCUDACompilerId.cu
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_pair.h(442): error: argument list for class template "std::pair" is missing

/usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_pair.h(442): error: expected a ")"

/usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_pair.h(442): error: template parameter "_T1" may not be redeclared in this scope

/usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_pair.h(442): error: expected a ";"

4 errors detected in the compilation of "./CMakeFiles/3.23.2/CompilerIdCUDA/CMakeCUDACompilerId.cu".
```
[reproducer.zip](https://github.com/llvm/llvm-project/files/9577758/reproducer.zip)

250cde6ea92d5372572a6cf5ad845f926660f0f2 already bad
ea953b9d9a65c202985a79f1f95da115829baef6 from 20220907 was OK.
Should be caused by a commit between.

I tried `-E` to see the code after preprocessing. The number of lines increase by 36%.

I'm wondering if clang can recover the previous behavior.

**Comment by ye-luo** [comment]
the first bad commit.
```
commit e321c8dd2cea8365045ed44ae1c3c00c6a977d2e
Author: Fangrui Song <i@maskray.me>
Date:   Wed Sep 7 14:17:52 2022 -0700

    C++/ObjC++: switch to gnu++17 as the default standard
    
    Clang's default C++ standard is now `gnu++17` instead of `gnu++14`:
    https://discourse.llvm.org/t/c-objc-switch-to-gnu-17-as-the-default-dialect/64360
    
    * CUDA/HIP are unchanged: C++14 from D103221.
    * Sony PS4/PS5 are unchanged: https://discourse.llvm.org/t/c-objc-switch-to-gnu-17-as-the-default-dialect/64360/6
    * lit feature `default-std-cxx` is added to keep CLANG_DEFAULT_STD_CXX=xxx tests working.
      Whether the cmake variable should be retained is disccused in D133375.
    
    Depends on D131464
    
    Close https://github.com/llvm/llvm-project/issues/56946
    
    Reviewed By: #clang-language-wg, aaron.ballman
    
    Differential Revision: https://reviews.llvm.org/D131465
```

**Comment by tbaederr** [comment]
/cc @MaskRay 

So does using `-std=gnu++14` work around this problem? libstdc++ 7 seems pretty old, I'm not sure if we can reasonably expect it to compile fine when using clang and c++17.

**Comment by jwakely** [comment]
The libstdc++ code is perfectly valid C++17:

```c++
#if __cpp_deduction_guides >= 201606
  template<typename _T1, typename _T2> pair(_T1, _T2) -> pair<_T1, _T2>;
#endif
```

Those lines are unchanged in GCC 12, so not a problem due to libstdc++ from GCC 7 being old.

**Comment by jwakely** [comment]
Probably an nvcc bug actually, their parser seems to get confused.

**Comment by jwakely** [comment]
So cicc needs to be updated for the new default in Clang? Or something else?

**Comment by ye-luo** [comment]
It is a many body problem. One way out was to figure out why the added lines from switching to gnu++17 (32k vs 24k gnu++14) were causing problems. g++(12) also default to c++17 and has no issue with nvcc.
