### PR TITLE
[C++20] [Modules] Fix may-be incorrect ADL for module local entities

### LINKED ISSUE #123815: [c++][Modules] Member variable of non-exported type has inaccessible hidden friend with defaulted comparison
The following valid translation units

```c++
export module a;

namespace n {
}
```

```c++
export module b;

import a;

namespace n {

struct monostate {
	friend bool operator==(monostate, monostate) = default;
};

export struct wrapper {
	friend bool operator==(wrapper const &, wrapper const &) = default;

	monostate m_value;
};

} // namespace n
```

```c++
import b;

static_assert(n::wrapper() == n::wrapper());
```

are rejected by clang with

```console
In file included from /app/c.cpp:1:
b.cpp:12:67: error: invalid operands to binary expression ('const monostate' and 'const monostate')
   12 |         friend bool operator==(wrapper const &, wrapper const &) = default;
      |                                                                          ^
c.cpp:3:28: note: in defaulted equality comparison operator for 'wrapper' first required here
    3 | static_assert(n::wrapper() == n::wrapper());
      |                            ^
c.cpp:3:28: error: static assertion expression is not an integral constant expression
    3 | static_assert(n::wrapper() == n::wrapper());
      |               ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
2 errors generated.
```

See it live: https://godbolt.org/z/19dG3G7Pb

Introduced by c5e4afe6733c58e24023ede04275bbed3bde8240 @ChuanqiXu9

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
Close https://github.com/llvm/llvm-project/issues/123815

See the comments for details. We can't get primary context arbitrarily since the redecl may have different context and information.

There is a TODO for modules specific case, I'd like to make it after this PR.

### CODE REVIEW

**Comment by ChuanqiXu9** [comment]
@nikic given the lookup process is on the hot path, it'll be appreciated if you can test the compilation time impact on this.

**Comment by ChuanqiXu9** [comment]
> @nikic given the lookup process is on the hot path, it'll be appreciated if you can test the compilation time impact on this for non module users.

**Comment by nikic** [comment]
I'm not seeing any impact: https://llvm-compile-time-tracker.com/compare.php?from=ff0f1dd341cb2fdc1281a14413b3aa93bf9a20c7&to=4bfdd091675b9957686ac81457629e124950dc25&stat=instructions:u

**Comment by ChuanqiXu9** [comment]
> I'm not seeing any impact: https://llvm-compile-time-tracker.com/compare.php?from=ff0f1dd341cb2fdc1281a14413b3aa93bf9a20c7&to=4bfdd091675b9957686ac81457629e124950dc25&stat=instructions:u

Thank you!

**Comment by ChuanqiXu9** [comment]
I'd like to land this given the scale of the patch and I want to fix it before 20.x and I may not be available in the next few days.
