### PR TITLE
[flang-rt] Avoid duplicate definition of `std::__libcpp_verbose_abort`

### PR DESCRIPTION
**Pull request by mmuetzel**
If a project depends on the Flang runtime and on libc++, linking fails because `std::__libcpp_verbose_abort` is defined in both libraries.

Avoid that duplicate definition by defining `_LIBCPP_VERBOSE_ABORT` before including any C++ headers and by renaming that symbol in the Flang runtime to `flang_rt_verbose_abort`.

The function that is modified was originally introduced in D158957 to solve an undefined symbol error when linking pure-Fortran projects with the Flang runtime.
Providing a definition for that symbol in the Flang runtime might work correctly for ELF or Mach-O if that symbol has weak linkage in libc++. But at least for COFF, this now causes multiple-definition errors for projects that are linking to the Flang runtime and to libc++.

The linker errors before this change for Windows/MinGW using Clang+Flang+lld look like this:
```
ld.lld: error: duplicate symbol: std::__1::__libcpp_verbose_abort(char const*, ...)
>>> defined at libflang_rt.runtime.a(io-api-minimal.cpp.obj)
>>> defined at libc++.dll.a(libc++.dll)
```

### CODE REVIEW

File: flang-rt/cmake/modules/AddFlangRT.cmake
Comment (mstorsjo) [inline flang-rt/cmake/modules/AddFlangRT.cmake]: This isn't very pretty, but I guess it is a kinda reasonable way around this problem.

I have a faint memory that you mentioned that there was some precedent from elsewhere about doing the same; is that the case and can you provide that reference?

**Review by mstorsjo — COMMENTED** [review]
This looks mostly reasonable to me, but I don't think I'm authoritative to approve things here.

CC @clementval @Meinersbur if they happen to know a suitable reviewer for it.

**Review by Meinersbur — COMMENTED** [review]
#77883 did remove the documentation for `_LIBCPP_VERBOSE_ABORT` and https://discourse.llvm.org/t/rfc-hardening-in-libc/73925/ implies that it is going to be removed. Would that solve our problem or does in mean evantually we have to find a different solution?

**Review by Meinersbur — APPROVED** [review]
LGTM, thanks for all the work
