### ISSUE TITLE
Clang accepts copy constructor when the copy constructor is declared incorrectly

### ISSUE THREAD

**Issue by hughbe** [llvm/llvm-project#31422]
|  |  |
| --- | --- |
| Bugzilla Link | [32074](https://llvm.org/bz32074) |
| Version | unspecified |
| OS | Windows NT |
| CC | @hyp,@DougGregor,@zygoloid,@rnk |

## Extended Description 
The following code compiles fine with Clang (3.9.1). GCC (7, snapshot) and MSVC (Visual Studio 2015 Update 3) correctly identify this as a badly formed copy constructor and don't compile this. Obviously fixing this would be a breaking change. However, it's successful compilation causes portability issues: https://github.com/apple/swift/pull/7762

```cpp
template <bool refcountIsInline>
class RefCountBitsT {
    RefCountBitsT(RefCountBitsT<true> newbits) { }
};

class SideTableRefCountBits : public RefCountBitsT<false> {
    SideTableRefCountBits(RefCountBitsT<true> newbits)
        : RefCountBitsT<false>(newbits) {}
};
```
GCC emits:
```
source_file.cpp: In instantiation of ‘class RefCountBitsT<true>’:
source_file.cpp:3:48:   required from here
source_file.cpp:3:5: error: invalid constructor; you probably meant ‘RefCountBitsT<true> (const RefCountBitsT<true>&)’
     RefCountBitsT(RefCountBitsT<true> newbits) { }
     ^
source_file.cpp: In constructor ‘SideTableRefCountBits::SideTableRefCountBits(RefCountBitsT<true>)’:
source_file.cpp:3:5: error: ‘RefCountBitsT<refcountIsInline>::RefCountBitsT(RefCountBitsT<true>) [with bool refcountIsInline = false]’ is private
source_file.cpp:8:39: error: within this context
         : RefCountBitsT<false>(newbits) {}
                                       ^
source_file.cpp:8:39: error: call of overloaded ‘RefCountBitsT(RefCountBitsT<true>&)’ is ambiguous
source_file.cpp:3:5: note: candidate: RefCountBitsT<refcountIsInline>::RefCountBitsT(RefCountBitsT<true>) [with bool refcountIsInline = true]
     RefCountBitsT(RefCountBitsT<true> newbits) { }
     ^
source_file.cpp:2:7: note: candidate: constexpr RefCountBitsT<true>::RefCountBitsT(const RefCountBitsT<true>&)
 class RefCountBitsT {
       ^
source_file.cpp:3:5: note:   initializing argument 1 of ‘RefCountBitsT<refcountIsInline>::RefCountBitsT(RefCountBitsT<true>) [with bool refcountIsInline = false]’
     RefCountBitsT(RefCountBitsT<true> newbits) { }
```

MSVC emits:
```
source_file.cpp(3): error C2652: 'RefCountBitsT<true>': illegal copy constructor: first parameter must not be a 'RefCountBitsT<true>'
source_file.cpp(7): note: see reference to class template instantiation 'RefCountBitsT<true>' being compiled
source_file.cpp(3): error C2333: 'RefCountBitsT<true>::RefCountBitsT': error in function declaration; skipping function body
source_file.cpp(7): error C2664: 'RefCountBitsT<false>::RefCountBitsT(RefCountBitsT<false> &&)': cannot convert argument 1 from 'RefCountBitsT<true>' to 'RefCountBitsT<true>'
source_file.cpp(7): note: Cannot copy construct class 'RefCountBitsT<true>' due to ambiguous copy constructors or no available copy constructor
```

**Comment by shafik** [comment]
clang no longer accepts: https://godbolt.org/z/MeMfqcz89
