### ISSUE TITLE
While building project with fshort-wchar facing compilation error : "segmented_iterator.h:72:46: error: template argument ‘(sizeof (_Tp) * 0)’ involves template parameter(s) "

### ISSUE THREAD

**Issue by spectrum248** [llvm/llvm-project#72836]
In my C++ project using cmake i need to compile my project with -fshort-wchar force project to use wchar 2 bytes in place of 4 bytes. For that As per steps mention in this issue thread : https://discourse.llvm.org/t/fshort-wchar-and-std-wstring/68668/3 
i tried to build LLVM Project locally but failed to build generating below compilation.

Environment:
- Ubuntu 22.04
- GCC 11.04.0 x86_64 -linux-gnu
-  Tried to build with code branches llvmorg-14.0.6, llvmorg-17.0.4, llvmorg-16.0.6 
 
Tried by using same steps mention in issue thread: 

1. 
```c++
$ git -C temp/libcxx3/src clone https://github.com/llvm/llvm-project.git
$ git -C temp/libcxx3/src/llvm-project checkout llvmorg-17.0.4
``` 

2. 
 ```c++

$ cmake -S temp/libcxx3/src/llvm-project/runtimes -B temp/libcxx3/obj -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DCMAKE_CXX_FLAGS="-fshort-wchar -fvisibility=hidden" -DCMAKE_INSTALL_PREFIX=temp/libcxx3/out -DLIBCXX_ENABLE_SHARED=OFF -DLIBCXX_ABI_NAMESPACE=__short_wchar -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=ON
``` 
Configuration logs:
[cmake command log.txt](https://github.com/llvm/llvm-project/files/13408192/cmake.command.log.txt)

3. 
```c++
$ cmake --build temp/libcxx3/obj -t cxx -t cxxabi -t unwind
``` 
During building above command receiving issue while compiling cxa_default_handlers.cpp file:
```c++
[ 92%] Built target generate-cxxabi-headers
[ 92%] Building CXX object libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_aux_runtime.cpp.o
[ 92%] Building CXX object libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_default_handlers.cpp.o
In file included from /home/shrihari/temp/libcxx3/obj/include/c++/v1/__algorithm/for_each_segment.h:13,
                 from /home/shrihari/temp/libcxx3/obj/include/c++/v1/__algorithm/copy.h:13,
                 from /home/shrihari/temp/libcxx3/obj/include/c++/v1/__memory/uninitialized_algorithms.h:13,
                 from /home/shrihari/temp/libcxx3/obj/include/c++/v1/__memory/ranges_uninitialized_algorithms.h:22,
                 from /home/shrihari/temp/libcxx3/obj/include/c++/v1/memory:896,
                 from /home/shrihari/temp/libcxx3/src/llvm-project/libcxxabi/src/cxa_default_handlers.cpp:13:
/home/shrihari/temp/libcxx3/obj/include/c++/v1/__iterator/segmented_iterator.h:72:46: error: template argument ‘(sizeof (_Tp) * 0)’ involves template parameter(s)
   72 | struct __has_specialization<_Tp, sizeof(_Tp) * 0> : true_type {};
      |                                  ~~~~~~~~~~~~^~~
gmake[3]: *** [libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/build.make:90: libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_default_handlers.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:967: libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1242: libcxx/src/CMakeFiles/cxx.dir/rule] Error 2
gmake: *** [Makefile:520: cxx] Error 2
``` 

Build command logs:
[cmake build command logs.txt](https://github.com/llvm/llvm-project/files/13408241/cmake.build.command.logs.txt)

**Comment by philnik777** [comment]
I don't know exactly what the error is about. I've never seen that before.
A few observations:
- LLVM 14 didn't have this code, so there it should be a different error, if any at all
- LLVM 17 requires at least GCC 12, maybe even 13
- I don't see how `-fshort-wchar` would have any impact on this. Could you check whether you get the same error without `-fshort-wchar`?

**Comment by spectrum248** [comment]
> LLVM 14 didn't have this code, so there it should be a different error, if any at all 

With LLVM 14 and 15 branch able to compile and install with no errors generated. Thanks for help @philnik777  :+1:

> I don't see how `-fshort-wchar `would have any impact on this. Could you check whether you get the same error without -fshort-wchar?

No impact observe of `-fshort-wchar` on compilation issue 
- As with and without flag we receive same error mention with LLVM 16 and 17.

**Comment by philnik777** [comment]
Ok, so it seems like it's a tooling issue and not an argument issue. Could you try to use a more up-to-date GCC or Clang?
