### ISSUE TITLE
Compile error related to constexpr variable template in a template class

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#39542]
|  |  |
| --- | --- |
| Bugzilla Link | [40195](https://llvm.org/bz40195) |
| Version | 7.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
The following C++17 program does not compile:

template<typename>
struct A {
    template<typename>
    inline static constexpr int X = 1;
    inline static constexpr int Y = X<void>;
};
constexpr int Y = A<void>::Y;

clang++ -std=c++17 main.cpp
main.cpp:7:19: error: constexpr variable 'Y' must be initialized by a constant expression
constexpr int Y = A<void>::Y;
                  ^~~~~~~~~~
1 error generated.

This error is produced with any Clang version starting with 5.0.0 (where sufficient C++17 support appeared). It compiles with GCC (7.1 and newer).

**Comment by yuanfang-chen** [comment]
Fixed as of llvm14. https://godbolt.org/z/36GPq1erY

**Comment by llvmbot** [comment]
@llvm/issue-subscribers-clang-frontend
