### ISSUE TITLE
/build/source/clang/lib/Sema/SemaDecl.cpp:9737:39: error: 'class clang::FunctionDecl' has no member named 'isFromGlobalModule'; did you mean 'isFromExplicitGlobalModule'?

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#109758]
on linux

```

FAILED: tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaDecl.cpp.o 
/opt/sccache//sccache /usr/bin/g++-13 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/source/build-llvm/tools/clang/lib/Sema -I/build/source/clang/lib/Sema -I/build/source/clang/include -I/build/source/build-llvm/tools/clang/include -I/build/source/build-llvm/include -I/build/source/llvm/include -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=3 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fdebug-prefix-map=/build/source/build-llvm=../ -fdebug-prefix-map=/build/source/= -no-canonical-prefixes -ffile-prefix-map=/build/source/build-llvm=../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -MD -MT tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaDecl.cpp.o -MF tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaDecl.cpp.o.d -o tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaDecl.cpp.o -c /build/source/clang/lib/Sema/SemaDecl.cpp
/build/source/clang/lib/Sema/SemaDecl.cpp: In member function 'clang::NamedDecl* clang::Sema::ActOnFunctionDeclarator(clang::Scope*, clang::Declarator&, clang::DeclContext*, clang::TypeSourceInfo*, clang::LookupResult&, clang::MultiTemplateParamsArg, bool&)':
/build/source/clang/lib/Sema/SemaDecl.cpp:9737:39: error: 'class clang::FunctionDecl' has no member named 'isFromGlobalModule'; did you mean 'isFromExplicitGlobalModule'?
 9737 |                                NewFD->isFromGlobalModule() ||
      |                                       ^~~~~~~~~~~~~~~~~~
      |                                       isFromExplicitGlobalModule
At global scope:
```

Seems to be caused by https://github.com/llvm/llvm-project/pull/109077/files

**Comment by sylvestre** [comment]
fixed now
