### ISSUE TITLE
[CUDA] std::clamp doesn't compile with latest clang and gcc

### ISSUE THREAD

**Issue by pateldeev** [llvm/llvm-project#95183]
Using `std::clamp` fails to compile with clang 18.1.7 and gcc 14.1 libstd. It works with gcc 13.2.

Error message is 
```
external/local_config_clang/crosstool/extra_tools/lib/gcc/x86_64-linux-gnu/14.1.0/../../../../include/c++/14.1.0/bits/stl_algo.h:3625:7: error: reference to __host__ function '__glibcxx_assert_fail' in __host__ __device__ function
 3625 |       __glibcxx_assert(!(__hi < __lo));
      |       ^
external/local_config_clang/crosstool/extra_tools/lib/gcc/x86_64-linux-gnu/14.1.0/../../../../include/x86_64-linux-gnu/c++/14.1.0/bits/c++config.h:612:7: note: expanded from macro '__glibcxx_assert'
  612 |         std::__glibcxx_assert_fail();                                   \
      |              ^
quantize.cu.cc:12:13: note: called by 'quantize_z'
   12 |       std::clamp(z, kMinZ, kMaxZ);
      |            ^
```

**Comment by pinskia** [comment]
Same bug as before:
https://github.com/llvm/llvm-project/issues/49727

**Comment by pinskia** [comment]
But it looks like there is some fundamental issue with how cuda handles this.

**Comment by pinskia** [comment]
https://github.com/pytorch/pytorch/issues/127666

**Comment by AngryLoki** [comment]
The same error occurs now with `std::array`, as libstdc++-15 adds `__glibcxx_requires_subscript` there too.
https://github.com/gcc-mirror/gcc/blob/2f2e51b6596c3796b907c6289d3e631508d8774e/libstdc%2B%2B-v3/include/std/array#L207-L222

This breaks libraries like `composable-kernel` - https://bugs.gentoo.org/955623. Note: works with stdlibc++-14 and libc++.

Looks like it is possible to undo `__glibcxx_requires_subscript` both for `std::clamp` and `std::array` by adding this:
```
#if !defined(__HIPCC_RTC__) && defined(__cplusplus) && defined(__clang__) && defined(__HIP__) \
&& defined(__HIP_PLATFORM_AMD__) && defined(__GLIBCXX__) \
&& defined(_GLIBCXX_RELEASE) && (_GLIBCXX_RELEASE == 15)
#include <debug/assertions.h>
#define __glibcxx_requires_subscript (void)
#endif
```
to https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/__clang_hip_runtime_wrapper.h at least before `#include <complex>` (which transitively includes `<array>`). Are there any better solutions?

**Comment by zhaorv** [comment]
There is ongoing discussion to fix this in libstdc++: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115740

**Comment by AngryLoki** [comment]
Looks like the issue was addressed in https://github.com/llvm/llvm-project/pull/136133 by @jmmartinez

**Comment by jmmartinez** [comment]
The issue should have been solved by the patch mentioned above.

@pateldeev Could you try with a nightly version of clang to confirm the issue has been solved for you?

Also, a workaround this issue could be to define the macro `_GLIBCXX_ASSERTIONS` to `0` on the command line.

**Comment by jmmartinez** [comment]
Since the issue seems to be solved in the latest LLVM version by https://github.com/llvm/llvm-project/pull/136133 I've closed it.
