### ISSUE TITLE
KwinFT C++20 ranges MR 168 doesn't compile with Clang

### ISSUE THREAD

**Issue by ms178** [llvm/llvm-project#57650]
The KwinFT project came up with https://gitlab.com/kwinft/kwinft/-/merge_requests/168 which makes use of C++20 ranges features. This MR compiles fine with GCC 12.2 but I ran into a compilation issue with Clang 16 (df868edee561eb973edd85ec9df41c67aa0bff6b) - and the KwinFT devs told me that it is a compiler bug, therefore filing this issue.

```console
/home/marcus/Downloads/KDE/kwinft-git/src/kwin/win/stacking.h:155:12: error: no matching function for call to 'ensure_stacking_order_in_list'
    return ensure_stacking_order_in_list(*space->stacking_order, list);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by gulafaran** [comment]
well to be fair that specific error you got is not related, but this example
https://godbolt.org/z/d6eodcT6o compiles on gcc but not clang.

**Comment by royjacobson** [comment]
Clang does not support libstdc++'s ranges yet because of #44178. It seems very likely that this is a duplicate of that bug.

**Comment by royjacobson** [comment]
Works after https://reviews.llvm.org/D126907, so this was a duplicate.

**Comment by ms178** [comment]
@royjacobson While it compiles fine now with a new Clang-16 snaptshot, KwinFT segfaults with it. I don't know if that is an Clang or application issue though, just wanted to mention it here as well. I've made a stack trace and also reported it with the KwinFT-devs: https://files.gitter.im/5eba51c2d73408ce4fe37145/VEIK/segfault_KDE.txt
