### ISSUE TITLE
Trunk no longer builds with clang-10

### ISSUE THREAD

**Issue by HighCommander4** [llvm/llvm-project#220387]
Trying to build llvm-project trunk with clang-10 as the host compiler fails with the following error:

```console
[338/5789] Building CXX object lib/Analysis/CMakeFiles/LLVMAnalysis.dir/BasicAliasAnalysis.cpp.o
FAILED: lib/Analysis/CMakeFiles/LLVMAnalysis.dir/BasicAliasAnalysis.cpp.o 
/usr/bin/clang++-10 -D_GLIBCXX_USE_CXX11_ABI=1 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/__w/clangd/clangd/clangd_snapshot_20260726/lib/Analysis -I/__w/clangd/clangd/llvm-project/llvm/lib/Analysis -I/__w/clangd/clangd/clangd_snapshot_20260726/include -I/__w/clangd/clangd/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-comment -Wstring-conversion -Wno-pass-failed -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -gline-tables-only -DNDEBUG -include /__w/clangd/clangd/.github/workflows/lib_compat.h -fno-exceptions -funwind-tables -fno-rtti -std=c++17 -MD -MT lib/Analysis/CMakeFiles/LLVMAnalysis.dir/BasicAliasAnalysis.cpp.o -MF lib/Analysis/CMakeFiles/LLVMAnalysis.dir/BasicAliasAnalysis.cpp.o.d -o lib/Analysis/CMakeFiles/LLVMAnalysis.dir/BasicAliasAnalysis.cpp.o -c /__w/clangd/clangd/llvm-project/llvm/lib/Analysis/BasicAliasAnalysis.cpp
In file included from /__w/clangd/clangd/llvm-project/llvm/lib/Analysis/BasicAliasAnalysis.cpp:34:
In file included from /__w/clangd/clangd/llvm-project/llvm/include/llvm/IR/CycleInfo.h:18:
/__w/clangd/clangd/llvm-project/llvm/include/llvm/ADT/GenericCycleInfo.h:231:33: error: member reference base type 'ArrayRef' is not a structure or union
    return ArrayRef(BlockLayout).slice(Cyc.EntryBegin, Cyc.EntrySize);
           ~~~~~~~~~~~~~~~~~~~~~^~~~~~
1 error generated.
```

(Originally encountered in https://github.com/clangd/clangd/issues/2697.)

This is a regression from https://github.com/llvm/llvm-project/commit/285a3cb74ef4, which introduced a use of CTAD in a dependent context which triggers a bug in clang-10.

The bug in question was fixed in clang-12 by https://github.com/llvm/llvm-project/commit/d1751d14a6b2.

---

Note, I do realize that clang-10 is quite old, and I'd be fine with closing this as "wontfix because we no longer support clang-10 as a host compiler". But in that case I'd suggest documenting clang >= 12 as the minimum required host compiler at https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library, and having CMake enforce it.

**Comment by HighCommander4** [comment]
In case we do want to accept fixes to issues like this, I posted a PR: https://github.com/llvm/llvm-project/pull/220449
