### PR TITLE
[Offload] Fix missing dependencies in Offload API generation

### LINKED ISSUE #142756: offload `fatal error: 'OffloadAPI.h' file not found`  - on linux
```
FAILED: offload/liboffload/CMakeFiles/LLVMOffload.dir/src/OffloadImpl.cpp.o
/build/source/build-llvm/./bin/clang++ --target=x86_64-pc-linux-gnu -DDEBUG_PREFIX=\"Liboffload\" -DTARGET_NAME=\"Liboffload\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/source/llvm/include -I/build/source/build-llvm/include -I/build/source/build-llvm/runtimes/runtimes-bins/offload/liboffload/API -I/build/source/build-llvm/runtimes/runtimes-bins/offload/liboffload/../include -I/build/source/offload/liboffload/include -I/build/source/offload/liboffload/../include -I/build/source/offload/liboffload/../plugins-nextgen/common/include -I/build/source/build-llvm/runtimes/runtimes-bins/offload/liboffload/../plugins-nextgen/common/include -I/build/source/offload/plugins-nextgen/common/include -I/build/source/build-llvm/runtimes/runtimes-bins/offload/plugins-nextgen/common/include -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=3 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fdebug-prefix-map=/build/source/build-llvm/runtimes/runtimes-bins=../../../ -fdebug-prefix-map=/build/source/= -no-canonical-prefixes -ffile-prefix-map=/build/source/build-llvm/runtimes/runtimes-bins=../../../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -O3 -DNDEBUG -std=c++17 -fPIC  -fno-exceptions -funwind-tables -fno-exceptions -Werror=global-constructors -MD -MT offload/liboffload/CMakeFiles/LLVMOffload.dir/src/OffloadImpl.cpp.o -MF offload/liboffload/CMakeFiles/LLVMOffload.dir/src/OffloadImpl.cpp.o.d -o offload/liboffload/CMakeFiles/LLVMOffload.dir/src/OffloadImpl.cpp.o -c /build/source/offload/liboffload/src/OffloadImpl.cpp
In file included from /build/source/offload/liboffload/src/OffloadImpl.cpp:14:
/build/source/offload/liboffload/include/OffloadImpl.hpp:11:10: fatal error: 'OffloadAPI.h' file not found
   11 | #include <OffloadAPI.h>
      |          ^~~~~~~~~~~~~~
1 error generated.
```
probably caused by #141982

### PR DESCRIPTION
**Pull request by callumfare**
Thanks to @RossBrunton for spotting this.

We attempt to clang-format the generated Offload header files, but if clang-format isn't available we just copy the generated files instead. That fallback path was missing the correct dependencies.

Fixes #142756

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]
Didn't my original patch have that? Guess I didn't notice it missing.

**Comment by kparzysz** [comment]
The generation fails if the "generated" and "include" subdirectories are missing.

runtimes/runtimes-bins/offload/plugins-nextgen/common/include
runtimes/runtimes-bins/offload/liboffload/API/generated

**Comment by callumfare** [comment]
@kparzysz I don't see any failures when building with a completely clean build directory. Could you share the build log where you're getting those failures?

**Comment by kparzysz** [comment]
Here's the error
```
[ 62%] Building include/OffloadErrcodes.inc...
[ 62%] Linking CXX static library /work/kparzysz/git/llvm.org/b/x86/lib/amdgcn-amd-amdhsa/libompdevice.a
[ 62%] Built target RTScudoCUnitTest.x86_64
[ 62%] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_alloc.cpp.o/work/kparzysz/git/llvm.org/b/x86/bin/offload-tblgen: error opening /work/kparzysz/git/llvm.org/b/x86/runtimes/runtimes-bins/offload/plugins-nextgen/common/include/OffloadErrcodes.inc: No such file or directory
make[5]: *** [offload/plugins-nextgen/common/CMakeFiles/PluginErrcodes.dir/build.make:121: offload/plugins-nextgen/common/include/OffloadErrcodes.inc] Error 1
make[5]: Leaving directory '/work2/kparzysz/git/llvm.org/b/x86/runtimes/runtimes-bins'
make[4]: *** [CMakeFiles/Makefile2:26763: offload/plugins-nextgen/common/CMakeFiles/PluginErrcodes.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
```

My cmake command was
```
cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_LIT_ARGS='-sv -j64' -DCMAKE_INSTALL_PREFIX=/work/kparzysz/c/org -DCMAKE_BUILD_TYPE=Release -DCLANG_DEFAULT_LINKER=lld -DLLVM_BUILD_TESTS=ON -DLLVM_INCLUDE_TESTS=ON -DCLANG_INCLUDE_TESTS=ON -DLLVM_TARGETS_TO_BUILD=all -DLLVM_ENABLE_RUNTIMES='openmp;offload;compiler-rt;libcxx;libcxxabi;libunwind' -DLLVM_ENABLE_PROJECTS='bolt;clang;clang-tools-extra;flang;lld;lldb;mlir;polly;pstl' -DBUILD_SHARED_LIBS=ON -DLIBOMPTARGET_PLUGINS_TO_BUILD='amdgpu;host' -DCLANG_DEFAULT_PIE_ON_LINUX=OFF -DLIBOMP_OMPT_SUPPORT=OFF -DLLVM_OMIT_DAGISEL_COMMENTS=OFF ../../llvm
```

**Comment by kparzysz** [comment]
Manually creating the two directories fixes the problem: make all install completes successfully.

**Comment by callumfare** [comment]
Thanks, it could be a difference between Ninja and Makefile, I'll investigate

**Comment by kparzysz** [comment]
This happens when I start with an empty directory as the build tree.  Once it's populated with make files and subdirectories (with these two created by hand), everything works in all subsequent builds.

**Comment by callumfare** [comment]
@kparzysz I was able to reproduce this failure, it should be fixed by this PR https://github.com/llvm/llvm-project/pull/142817
