### PR TITLE
[clang] Skip dllexport of inherited constructors with unsatisfied constraints

### LINKED ISSUE #185924: [clang] dllexport causing instantiation attempt for constructor that doesn't fullfill requires clause
Building with clang 23 main on Windows there is a build failure in the [Ladybird project](https://github.com/LadybirdBrowser/ladybird). This works with earlier clang versions and with clang 23 prior to 6811a83c81500ee373adfc0d9978ff9625a4cf1c (#182706)
<details>
<summary>Compile failure output</summary>

```
In file included from E:\lib\ladybird\Libraries\LibWeb\CSS\EasingFunction.cpp:7:
In file included from E:\lib\ladybird\Libraries\LibWeb\CSS\EasingFunction.h:9:
In file included from E:\lib\ladybird\Libraries\LibWeb/CSS/StyleValues/StyleValue.h:13:
In file included from E:\lib\ladybird\AK/NonnullOwnPtr.h:10:
In file included from E:\lib\ladybird\AK/Format.h:11:
In file included from E:\lib\ladybird\AK/Error.h:11:
E:\lib\ladybird\AK/Variant.h(274,11): error: no matching constructor for initialization of 'AK::Variant<Web::CSS::EasingStyleValue::Linear, Web::CSS::EasingStyleValue::CubicBezier, Web::CSS::EasingStyleValue::Steps>'
  274 |         : Variant(Empty())
      |           ^       ~~~~~~~
E:\lib\ladybird\Libraries\LibWeb/CSS/StyleValues/EasingStyleValue.h(85,20): note: in instantiation of member function 'AK::Variant<Web::CSS::EasingStyleValue::Linear, Web::CSS::EasingStyleValue::CubicBezier, Web::CSS::EasingStyleValue::Steps>::Variant' requested here
   85 |     struct WEB_API Function : public Variant<Linear, CubicBezier, Steps> {
      |                    ^
E:\lib\ladybird\AK/Variant.h(278,36): note: candidate constructor not viable: no known conversion from 'Empty' to 'const Variant<Web::CSS::EasingStyleValue::Linear, Web::CSS::EasingStyleValue::CubicBezier, Web::CSS::EasingStyleValue::Steps>' for 1st argument
  278 |     AK_MAKE_CONDITIONALLY_COPYABLE(Variant, <Ts>&&...);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
E:\lib\ladybird\AK/Noncopyable.h(56,5): note: expanded from macro 'AK_MAKE_CONDITIONALLY_COPYABLE'
   56 |     c(c const&) = default;                             \
      |     ^ ~~~~~~~~
E:\lib\ladybird\AK/Variant.h(279,35): note: candidate constructor not viable: no known conversion from 'Empty' to 'Variant<Web::CSS::EasingStyleValue::Linear, Web::CSS::EasingStyleValue::CubicBezier, Web::CSS::EasingStyleValue::Steps>' for 1st argument
  279 |     AK_MAKE_CONDITIONALLY_MOVABLE(Variant, <Ts>&&...);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
E:\lib\ladybird\AK/Noncopyable.h(41,5): note: expanded from macro 'AK_MAKE_CONDITIONALLY_MOVABLE'
   41 |     c(c&&) = default;                       \
      |     ^ ~~~
E:\lib\ladybird\AK/Variant.h(282,19): note: candidate constructor not viable: no known conversion from 'Empty' to 'const Variant<Web::CSS::EasingStyleValue::Linear, Web::CSS::EasingStyleValue::CubicBezier, Web::CSS::EasingStyleValue::Steps>' for 1st argument
  282 |     ALWAYS_INLINE Variant(Variant const& old)
      |                   ^       ~~~~~~~~~~~~~~~~~~
E:\lib\ladybird\AK/Variant.h(294,19): note: candidate constructor not viable: no known conversion from 'Empty' to 'Variant<Web::CSS::EasingStyleValue::Linear, Web::CSS::EasingStyleValue::CubicBezier, Web::CSS::EasingStyleValue::Steps>' for 1st argument
  294 |     ALWAYS_INLINE Variant(Variant&& old)
      |                   ^       ~~~~~~~~~~~~~
E:\lib\ladybird\AK/Variant.h(238,5): note: candidate template ignored: could not match 'Variant<NewTs...>' against 'Empty'
  238 |     Variant(Variant<NewTs...>&& old)
      |     ^
E:\lib\ladybird\AK/Variant.h(245,5): note: candidate template ignored: could not match 'Variant<NewTs...>' against 'Empty'
  245 |     Variant(Variant<NewTs...> const& old)
      |     ^
E:\lib\ladybird\AK/Variant.h(257,5): note: candidate template ignored: constraints not satisfied [with T = Empty]
  257 |     Variant(T&& t)
      |     ^
E:\lib\ladybird\AK/Variant.h(256,13): note: because 'IsConstructible<Web::CSS::EasingStyleValue::Linear, Empty>' evaluated to false
  256 |         && (IsConstructible<Ts, T> || ...))
      |             ^
E:\lib\ladybird\AK/Variant.h(256,13): note: and 'IsConstructible<Web::CSS::EasingStyleValue::CubicBezier, Empty>' evaluated to false
E:\lib\ladybird\AK/Variant.h(256,13): note: and 'IsConstructible<Web::CSS::EasingStyleValue::Steps, Empty>' evaluated to false
E:\lib\ladybird\AK/Variant.h(278,36): note: candidate constructor not viable: constraints not satisfied
  278 |     AK_MAKE_CONDITIONALLY_COPYABLE(Variant, <Ts>&&...);
      |                                    ^
E:\lib\ladybird\AK/Variant.h(278,5): note: because '!AK::Detail::IsCopyConstructible<Web::CSS::EasingStyleValue::Linear> && AK::Detail::IsCopyConstructible<Web::CSS::EasingStyleValue::CubicBezier> && AK::Detail::IsCopyConstructible<Web::CSS::EasingStyleValue::Steps>' evaluated to false
  278 |     AK_MAKE_CONDITIONALLY_COPYABLE(Variant, <Ts>&&...);
      |     ^
E:\lib\ladybird\AK/Noncopyable.h(55,5): note: expanded from macro 'AK_MAKE_CONDITIONALLY_COPYABLE'
   55 |     AK_MAKE_CONDITIONALLY_NONCOPYABLE(c, __VA_ARGS__); \
      |     ^
E:\lib\ladybird\AK/Noncopyable.h(47,14): note: expanded from macro 'AK_MAKE_CONDITIONALLY_NONCOPYABLE'
   47 |     requires(!(AK::Detail::IsCopyConstructible __VA_ARGS__))                                                \
      |              ^
E:\lib\ladybird\AK/Variant.h(279,35): note: candidate constructor not viable: constraints not satisfied
  279 |     AK_MAKE_CONDITIONALLY_MOVABLE(Variant, <Ts>&&...);
      |                                   ^
E:\lib\ladybird\AK/Variant.h(279,5): note: because '!AK::Detail::IsMoveConstructible<Web::CSS::EasingStyleValue::Linear> && AK::Detail::IsMoveConstructible<Web::CSS::EasingStyleValue::CubicBezier> && AK::Detail::IsMoveConstructible<Web::CSS::EasingStyleValue::Steps>' evaluated to false
  279 |     AK_MAKE_CONDITIONALLY_MOVABLE(Variant, <Ts>&&...);
      |     ^
E:\lib\ladybird\AK/Noncopyable.h(40,5): note: expanded from macro 'AK_MAKE_CONDITIONALLY_MOVABLE'
   40 |     AK_MAKE_CONDITIONALLY_NONMOVABLE(c, T); \
      |     ^
E:\lib\ladybird\AK/Noncopyable.h(32,14): note: expanded from macro 'AK_MAKE_CONDITIONALLY_NONMOVABLE'
   32 |     requires(!(AK::Detail::IsMoveConstructible __VA_ARGS__))                                                \
      |              ^
E:\lib\ladybird\AK/Variant.h(269,5): note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  269 |     Variant()
      |     ^
E:\lib\ladybird\AK/Variant.h(272,5): note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  272 |     Variant()
      |     ^
E:\lib\ladybird\AK/Variant.h(484,14): note: candidate constructor not viable: requires 2 arguments, but 1 was provided
  484 |     explicit Variant(IndexType index, Detail::VariantConstructTag)
      |              ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
</details>

What appears to happen is that for some reason the Variant constructor for a variant with an empty member attempts to be instantiated for a class that inherits from variant, even though this variant doesn't have this member. 
The relevant constructor in [Variant.h](https://github.com/LadybirdBrowser/ladybird/blob/master/AK/Variant.h)

```
    Variant()
    requires(!can_contain<Empty>())
    = delete;
    Variant()
    requires(can_contain<Empty>())
        : Variant(Empty())
    {
    }
```

And here is one of the structs that inherit from it: [EasingStyleValue.h](https://github.com/LadybirdBrowser/ladybird/blob/502f2618aa476d37e7949eb93bfab0fd758b040e/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.h#L85)

```cpp
    struct WEB_API Function : public Variant<Linear, CubicBezier, Steps> {
        using Variant::Variant;

        void serialize(StringBuilder&, SerializationMode) const;
    };
```

As written above I bisected this to #182706. Is this expected behavior for msvc? This code doesn't compile with msvc for other reasons so checking that would need a reduced reproducible. 
CC: @chinmaydd 

I upload a reproducer made with -gen-reproducer. Compressed to a zip file as the upload failed for the cpp file. 

[reproducer.zip](https://github.com/user-attachments/files/25914153/reproducer.zip)

### PR DESCRIPTION
**Pull request by chinmaydd**
When a class is marked `__declspec(dllexport)`, Clang eagerly creates inherited constructors via `findInheritingConstructor` and propagates the dllexport attribute to all members. This bypasses overload resolution, which would normally filter out constructors whose requires clause is not satisfied. As a result, Clang attempted to instantiate constructor bodies that should never be available, causing spurious compilation errors.

Add constraint satisfaction checks in `checkClassLevelDLLAttribute` to match MSVC behavior:

1. Before eagerly creating inherited constructors, verify that the base constructor's `requires` clause is satisfied. Skip creation otherwise.

2. Before applying dllexport to non-inherited methods of class template specializations, verify constraint satisfaction. This handles the case where `dllexport` propagates to a base template specialization whose own members have unsatisfied constraints.

Inherited constructors skip the second check since their constraints were already verified at creation time.

Fixes #185924

Followup to https://github.com/llvm/llvm-project/pull/182706

Assisted by: Cursor // Claude Opus 4.6

### CODE REVIEW

File: clang/test/SemaCXX/dllexport-constrained-inherited-ctor.cpp [hunk 1]
```diff
@@ -0,0 +1,35 @@
+// RUN: %clang_cc1 -triple x86_64-windows-msvc -fsyntax-only -fms-extensions -verify -std=c++20 %s
```
[the remark this answers is not in the document]
Comment (efriedma-quic) [reply clang/test/SemaCXX/dllexport-constrained-inherited-ctor.cpp]: Tests like this aren't that common because we usually don't need to test whether a template is instantiated, but I'm sure there are a few.

I think this is the best way to ensure test coverage.

**Review by efriedma-quic — APPROVED** [review]
LGTM
