### PR TITLE
[flang] fix Werror=dangling-reference

### PR DESCRIPTION
**Pull request by sebpop**
when compiling with g++ 13.3.0 flang build on arm64-linux ubuntu 24.04 machine fails with:

llvm-project/flang/lib/Semantics/expression.cpp:424:17: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
424 |   const Symbol &coarraySymbol{ref.GetBase().GetLastSymbol()};
    |                 ^~~~~~~~~~~~~
llvm-project/flang/lib/Semantics/expression.cpp:424:58: note: the temporary was destroyed at the end of the full expression ‘Fortran::evaluate::CoarrayRef::GetBase() const().Fortran::evaluate::NamedEntity::GetLastSymbol()’
424 |   const Symbol &coarraySymbol{ref.GetBase().GetLastSymbol()};
    |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

Keep the base in a temporary variable to make sure it is not deleted.

### CODE REVIEW

**Review by klausler — APPROVED** [review]
Please use braced initialization; otherwise LGTM, and thanks.

**Comment by sebpop** [comment]
Abandoning this patch as the code has changed and flang finishes build without errors on my system.
