### ISSUE TITLE
openmp: recent link issue `ompt_callback.cpp:function ompt_init(): error: undefined reference to 'dlsym'`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#58721]
On Linux on Debian Bullseye:
```console
[5831/9215] : && /build/source/build-llvm/./bin/clang++ -fPIC -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/source/build-llvm/tools/clang/stage2-bins=build-llvm/tools/clang/stage2-bins -ffile-prefix-map=/build/source/= -no-canonical-prefixes -Wall -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-enum-constexpr-conversion -Wno-extra -Wno-pedantic -std=c++17 -O2 -DNDEBUG -g1  -Wl,-z,relro -Wl,--build-id -Wl,-z,defs -Wl,-z,nodelete -fuse-ld=gold   -Wl,--gc-sections -shared -Wl,-soname,libomptarget.so.16 -o lib/libomptarget.so.16 projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/api.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/device.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/interface.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/interop.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/omptarget.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/ompt_callback.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/rtl.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/LegacyAPI.cpp.o  -Wl,-rpath,"\$ORIGIN:/build/source/build-llvm/tools/clang/stage2-bins/projects/openmp/libomptarget/src/..:/build/source/build-llvm/tools/clang/stage2-bins/lib:"  -Wl,--version-script=/build/source/openmp/libomptarget/src/exports  lib/libLLVM-16.so.1 && :
FAILED: lib/libomptarget.so.16 
: && /build/source/build-llvm/./bin/clang++ -fPIC -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/source/build-llvm/tools/clang/stage2-bins=build-llvm/tools/clang/stage2-bins -ffile-prefix-map=/build/source/= -no-canonical-prefixes -Wall -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-enum-constexpr-conversion -Wno-extra -Wno-pedantic -std=c++17 -O2 -DNDEBUG -g1  -Wl,-z,relro -Wl,--build-id -Wl,-z,defs -Wl,-z,nodelete -fuse-ld=gold   -Wl,--gc-sections -shared -Wl,-soname,libomptarget.so.16 -o lib/libomptarget.so.16 projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/api.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/device.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/interface.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/interop.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/omptarget.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/ompt_callback.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/rtl.cpp.o projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/LegacyAPI.cpp.o  -Wl,-rpath,"\$ORIGIN:/build/source/build-llvm/tools/clang/stage2-bins/projects/openmp/libomptarget/src/..:/build/source/build-llvm/tools/clang/stage2-bins/lib:"  -Wl,--version-script=/build/source/openmp/libomptarget/src/exports  lib/libLLVM-16.so.1 && :
projects/openmp/libomptarget/src/CMakeFiles/omptarget.dir/ompt_callback.cpp.o:ompt_callback.cpp:function ompt_init(): error: undefined reference to 'dlsym'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

@kiranchandramohan seems that you recently landed a bunch of OpenMP changes.

**Comment by ms178** [comment]
I can confirm build issues with OpenMP on current LLVM-git main; I got a slightly different output, but with the same file:

```
[1156/1993] Building CXX object openmp/libomptarget/src/CMakeFiles/omptarget.dir/ompt_callback.cpp.o
FAILED: openmp/libomptarget/src/CMakeFiles/omptarget.dir/ompt_callback.cpp.o 
/tmp/makepkg/llvm-git/src/llvm-project/build/./bin/clang++ --target=x86_64-pc-linux-gnu -DOMPT_SUPPORT=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/makepkg/llvm-git/src/llvm-project/llvm/include -I/tmp/makepkg/llvm-git/src/llvm-project/build/include -I/tmp/makepkg/llvm-git/src/llvm-project/openmp/libomptarget/include -O3 -D_FORTIFY_SOURCE=0 -march=native -mtune=native -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -fno-math-errno -fno-trapping-math -falign-functions=32 -funroll-loops -fno-semantic-interposition -fcf-protection=none -mharden-sls=none -fomit-frame-pointer -mprefer-vector-width=256 -flto -flto=auto -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-enum-constexpr-conversion -Wno-extra -Wno-pedantic -std=c++17 -O3 -DNDEBUG -fPIC  -fno-exceptions -std=gnu++17 -MD -MT openmp/libomptarget/src/CMakeFiles/omptarget.dir/ompt_callback.cpp.o -MF openmp/libomptarget/src/CMakeFiles/omptarget.dir/ompt_callback.cpp.o.d -o openmp/libomptarget/src/CMakeFiles/omptarget.dir/ompt_callback.cpp.o -c /tmp/makepkg/llvm-git/src/llvm-project/openmp/libomptarget/src/ompt_callback.cpp
/tmp/makepkg/llvm-git/src/llvm-project/openmp/libomptarget/src/ompt_callback.cpp:19:10: fatal error: 'omp-tools.h' file not found
#include "omp-tools.h"
         ^~~~~~~~~~~~~
1 error generated.
```

**Comment by dhruvachak** [comment]
This is caused by D123572. I just reverted it while I try to reproduce the problem. Did not see that problem on Ubuntu.

**Comment by jhuber6** [comment]
> This is caused by D123572. I just reverted it while I try to reproduce the problem. Did not see that problem on Ubuntu.

Seems that patch uses `dlsym` directly while the rest of OpenMP moved to the LLVM libraries. It's possible it relied on a transitive reference that was removed when that change was made.

**Comment by dhruvachak** [comment]
Thanks, Joseph. I will look into the dlsym issue.

About the other issue, @ms178 were you doing a clean build/install? If you already had build and install directories, can you remove both of them and try the build from scratch to see if omp-tools.h can be found now?

**Comment by dhruvachak** [comment]
With this patch, libomptarget now looks for omp-tools.h as well, not just libomp.

**Comment by ms178** [comment]
@dhruvachak Yes, that was a clean build without CCache. I'll give current head a try and will report back.

**Comment by ms178** [comment]
@dhruvachak The build succeeded successfully now, thanks.

**Comment by dhruvachak** [comment]
@ms178 Can you please provide your cmake options? I would like to reproduce the omp-tools.h not found problem.

**Comment by ms178** [comment]
@dhruvachak Just take a look at the [PKGBUILD](https://github.com/ms178/archpkgbuilds/blob/main/toolchain-experimental/llvm-git/PKGBUILD_MOLD) in my repo, I also specify some linker flags there. I've also used the Mold linker in that particular instance.

I use these flags in makepkg.conf (where global CFLAGS are defined on Arch-based distros):
```
export CC=clang
export CXX=clang++
export CC_LD=mold
export CXX_LD=mold
export AR=llvm-ar
export NM=llvm-nm
export STRIP=llvm-strip
export OBJCOPY=llvm-objcopy
export OBJDUMP=llvm-objdump
export READELF=llvm-readelf
export RANLIB=llvm-ranlib
export HOSTCC=clang
export HOSTCXX=clang++
export HOSTAR=llvm-ar
export CFLAGS="-O3 -march=native -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -fno-math-errno -fno-trapping-math -falign-functions=32 -funroll-loops -fno-semantic-interposition -fcf-protection=none -mharden-sls=none -fomit-frame-pointer -mprefer-vector-width=256 -flto"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zmax-page-size=0x200000"
CCLDFLAGS="$LDFLAGS"
CXXLDFLAGS="$LDFLAGS"
export ASFLAGS="-D__AVX__=1 -D__AVX2__=1 -msse2avx -D__FMA__=1"
```

**Comment by dhruvachak** [comment]
Thanks @ms178 Your cmake options helped find the problem. Ths host OMPT variable LIBOMP_OMPT_SUPPORT was not handled properly. 

I fixed both the problems in this issue and updated D123572. If you get a chance, please try it out and report if there are still problems.

**Comment by ms178** [comment]
@dhruvachak Great that I could be of help, I can test this post-merge.

**Comment by shiltian** [comment]
I suppose [5b67bce787e4](https://reviews.llvm.org/rG5b67bce787e4eeee1222c78bee7c0e9bc5563a3a) fixed the issue.
