### ISSUE TITLE
Compilation fails on trunk with "incomplete definition of type"

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#56878]
Hi, I have a (minified) code using boost::beast which compiles fine using latest Clang 14.0.6 but does not compile with 15.0.0-rc1 or trunk: https://godbolt.org/z/WjbGacE7o.

Full error:
```
In file included from <source>:4:
In file included from /opt/compiler-explorer/libs/boost_1_79_0/boost/beast/core.hpp:24:
In file included from /opt/compiler-explorer/libs/boost_1_79_0/boost/beast/core/buffers_suffix.hpp:144:
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/core/impl/buffers_suffix.hpp:147:47: error: incomplete definition of type 'boost::asio::is_const_buffer_sequence<boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::basic_fields<std::allocator<char>>::writer::field_range, boost::beast::http::chunk_crlf>>>'
        net::is_const_buffer_sequence<Buffers>::value ||
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/core/detail/variant.hpp:201:22: note: in instantiation of member function 'boost::beast::buffers_suffix<boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::basic_fields<std::allocator<char>>::writer::field_range, boost::beast::http::chunk_crlf>>>::buffers_suffix' requested here
        ::new(&buf_) mp11::mp_at_c<variant, I - 1>(
                     ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/http/impl/serializer.hpp:114:21: note: in instantiation of function template specialization 'boost::beast::detail::variant<boost::beast::buffers_suffix<boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::basic_fields<std::allocator<char>>::writer::field_range, boost::beast::http::chunk_crlf>>>, boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::basic_fields<std::allocator<char>>::writer::field_range, boost::beast::http::chunk_crlf>>, boost::asio::const_buffer>>, boost::beast::buffers_suffix<boost::asio::const_buffer>, boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::basic_fields<std::allocator<char>>::writer::field_range, boost::beast::http::chunk_crlf>>, boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf>>, boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf>>, boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::chunk_crlf>>, boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::basic_fields<std::allocator<char>>::writer::field_range, boost::beast::http::chunk_crlf>>, boost::beast::http::detail::chunk_size, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::beast::http::chunk_crlf, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::chunk_crlf>>, boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::chunk_crlf>>>::emplace<1UL, boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::basic_fields<std::allocator<char>>::writer::field_range, boost::beast::http::chunk_crlf>>>' requested here
        v_.template emplace<1>(fwr_->get());
                    ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/http/impl/write.hpp:96:17: note: in instantiation of function template specialization 'boost::beast::http::serializer<true, boost::beast::http::basic_string_body<char>>::next<boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<boost::beast::http::detail::write_msg_op<(lambda at <source>:18:9), boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>, boost::beast::basic_stream<boost::asio::ip::tcp>, boost::beast::http::detail::serializer_is_done, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>, boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>::lambda &>' requested here
            sr_.next(ec, f);
                ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/http/impl/write.hpp:86:9: note: in instantiation of member function 'boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<boost::beast::http::detail::write_msg_op<(lambda at <source>:18:9), boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>, boost::beast::basic_stream<boost::asio::ip::tcp>, boost::beast::http::detail::serializer_is_done, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>, boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>::operator()' requested here
        (*this)();
        ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/http/impl/write.hpp:312:9: note: in instantiation of function template specialization 'boost::beast::http::detail::write_some_op<boost::beast::http::detail::write_op<boost::beast::http::detail::write_msg_op<(lambda at <source>:18:9), boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>, boost::beast::basic_stream<boost::asio::ip::tcp>, boost::beast::http::detail::serializer_is_done, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>, boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>::write_some_op<boost::beast::http::detail::write_op<boost::beast::http::detail::write_msg_op<(lambda at <source>:18:9), boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>, boost::beast::basic_stream<boost::asio::ip::tcp>, boost::beast::http::detail::serializer_is_done, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>>' requested here
        write_some_op<
        ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/asio/async_result.hpp:482:5: note: (skipping 8 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    BOOST_ASIO_MOVE_CAST(Initiation)(initiation)(
    ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/asio/detail/config.hpp:135:37: note: expanded from macro 'BOOST_ASIO_MOVE_CAST'
# define BOOST_ASIO_MOVE_CAST(type) static_cast<type&&>
                                    ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/http/impl/write.hpp:270:9: note: in instantiation of member function 'boost::beast::http::detail::write_msg_op<(lambda at <source>:18:9), boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>::operator()' requested here
        (*this)();
        ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/http/impl/write.hpp:406:9: note: in instantiation of function template specialization 'boost::beast::http::detail::write_msg_op<(lambda at <source>:18:9), boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>::write_msg_op<(lambda at <source>:18:9), const boost::beast::http::message<true, boost::beast::http::basic_string_body<char>> &>' requested here
        write_msg_op<
        ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/asio/async_result.hpp:482:5: note: in instantiation of function template specialization 'boost::beast::http::detail::run_write_msg_op::operator()<(lambda at <source>:18:9), boost::beast::basic_stream<boost::asio::ip::tcp>, true, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char>>>' requested here
    BOOST_ASIO_MOVE_CAST(Initiation)(initiation)(
    ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/asio/detail/config.hpp:135:37: note: expanded from macro 'BOOST_ASIO_MOVE_CAST'
# define BOOST_ASIO_MOVE_CAST(type) static_cast<type&&>
                                    ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/asio/async_result.hpp:862:21: note: in instantiation of function template specialization 'boost::asio::detail::completion_handler_async_result<(lambda at <source>:18:9), void (boost::system::error_code, unsigned long)>::initiate<boost::beast::http::detail::run_write_msg_op, (lambda at <source>:18:9), boost::beast::basic_stream<boost::asio::ip::tcp> *, const boost::beast::http::message<true, boost::beast::http::basic_string_body<char>> *, std::integral_constant<bool, true>>' requested here
    Signatures...>::initiate(BOOST_ASIO_MOVE_CAST(Initiation)(initiation),
                    ^
/opt/compiler-explorer/libs/boost_1_79_0/boost/beast/http/impl/write.hpp:878:17: note: in instantiation of function template specialization 'boost::asio::async_initiate<(lambda at <source>:18:9), void (boost::system::error_code, unsigned long), boost::beast::http::detail::run_write_msg_op, boost::beast::basic_stream<boost::asio::ip::tcp> *, const boost::beast::http::message<true, boost::beast::http::basic_string_body<char>> *, std::integral_constant<bool, true>>' requested here
    return net::async_initiate<
                ^
1 error generated.
```

Maybe it is a problem with Boost, not with Clang. I can't really understand but it did compile with previous versions.

**Comment by vient** [comment]
I tried to make smaller reproducer and noted that the problem goes away if you add an instantiation of the type which is said to be incomplete, or copy this static_assert into your code.
    
So like this
```cpp
using Type = boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffer, boost::asio::const_buffer, boost::asio::const_buffer, boost::beast::http::basic_fields<std::allocator<char>>::writer::field_range, boost::beast::http::chunk_crlf>>;
boost::asio::is_const_buffer_sequence<Type> unused;
```
or like this
```cpp
static_assert(boost::beast::net::is_const_buffer_sequence<Type>::value);
```

**Comment by vient** [comment]
Weirdly, if I try to naively creduce the reproducer matching following criteria:
* clang 15.0.0-rc1 gives `error: incomplete definition of type 'boost::asio::...`
* clang 14 does not give it

then I get rather small test files, several KB, that stop getting the error from clang 15 if first formatted with clang-format-14.

**Comment by vient** [comment]
Looks like it is no longer reproducible on main branch, at least CE shows so.

**Comment by vient** [comment]
Bisected the fix: https://github.com/llvm/llvm-project/commit/df48e3fbcc8be1f4c04bd97517d12e662f54de75

So waiting for https://github.com/llvm/llvm-project/issues/56928 then.
