### PR TITLE
[lldb] fix failing tests due to CI diagnostics rendering

### PR DESCRIPTION
**Pull request by charles-zablit**
This patch fixes issues introduced by https://github.com/llvm/llvm-project/pull/171491 when running tests in CI.

The shell tests expect certain characters when matching diagnostics. With https://github.com/llvm/llvm-project/pull/171491, those characters can either be Unicode specific characters or their ASCII equivalent. The tests were always expecting the ASCII version. This patch fixes this by using a regex to match one or the other.

### CODE REVIEW

**Review by adrian-prantl — APPROVED** [review]

**Comment by charles-zablit** [comment]
> Nothing changed [lab.llvm.org/buildbot#/builders/197/builds/11757](https://lab.llvm.org/buildbot/#/builders/197/builds/11757) [lab.llvm.org/buildbot#/builders/211/builds/4494](https://lab.llvm.org/buildbot/#/builders/211/builds/4494)

I reverted the changes.

> Windows will not print unicode chars to stdout without a special system settings.

I don't think that's what's happening in the CI, because the logs do say:
```
# | <stdin>:19:19: note: possible intended match here
# |                   ╰─ error: use of undeclared identifier 'a'
```

I am not hitting this issue when testing on macOS, I will try to rerun the full test suite on Windows.
