### ISSUE TITLE
`clang-cmake-x86_64-avx512-linux` tests fail in CI

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#76018]
https://lab.llvm.org/buildbot/#/builders/258/builds/11355

Excerpt:
`FAIL: MemProfiler-x86_64-linux-dynamic::memprof_profile_dump.cpp`
```
RUN: at line 1: /localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/./bin/clang  --driver-mode=g++ -fmemory-profile -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only  -m64  -shared-libsan /localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/llvm/compiler-rt/test/memprof/TestCases/memprof_profile_dump.cpp -o /localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/runtimes/runtimes-bins/compiler-rt/test/memprof/X86_64LinuxDynamicConfig/TestCases/Output/memprof_profile_dump.cpp.tmp
+ /localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/./bin/clang --driver-mode=g++ -fmemory-profile -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -m64 -shared-libsan /localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/llvm/compiler-rt/test/memprof/TestCases/memprof_profile_dump.cpp -o /localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/runtimes/runtimes-bins/compiler-rt/test/memprof/X86_64LinuxDynamicConfig/TestCases/Output/memprof_profile_dump.cpp.tmp
In file included from /localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/llvm/compiler-rt/test/memprof/TestCases/memprof_profile_dump.cpp:7:
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:27:6: error: variable has incomplete type 'void'
   27 | void SANITIZER_CDECL __memprof_record_access_range(void const volatile *addr,
      |      ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:27:21: error: expected ';' after top level declarator
   27 | void SANITIZER_CDECL __memprof_record_access_range(void const volatile *addr,
      |                     ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:35:6: error: variable has incomplete type 'void'
   35 | void SANITIZER_CDECL __memprof_record_access(void const volatile *addr);
      |      ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:35:21: error: expected ';' after top level declarator
   35 | void SANITIZER_CDECL __memprof_record_access(void const volatile *addr);
      |                     ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:42:6: error: variable has incomplete type 'void'
   42 | void SANITIZER_CDECL __memprof_on_error(void);
      |      ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:42:21: error: expected ';' after top level declarator
   42 | void SANITIZER_CDECL __memprof_on_error(void);
      |                     ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:46:6: error: variable has incomplete type 'void'
   46 | void SANITIZER_CDECL __memprof_print_accumulated_stats(void);
      |      ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:46:21: error: expected ';' after top level declarator
   46 | void SANITIZER_CDECL __memprof_print_accumulated_stats(void);
      |                     ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:55:13: error: redefinition of 'SANITIZER_CDECL'
   55 | const char *SANITIZER_CDECL __memprof_default_options(void);
      |             ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:46:6: note: previous definition is here
   46 | void SANITIZER_CDECL __memprof_print_accumulated_stats(void);
      |      ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:55:28: error: expected ';' after top level declarator
   55 | const char *SANITIZER_CDECL __memprof_default_options(void);
      |                            ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:60:5: error: redefinition of 'SANITIZER_CDECL'
   60 | int SANITIZER_CDECL __memprof_profile_dump(void);
      |     ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:55:13: note: previous definition is here
   55 | const char *SANITIZER_CDECL __memprof_default_options(void);
      |             ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:60:20: error: expected ';' after top level declarator
   60 | int SANITIZER_CDECL __memprof_profile_dump(void);
      |                    ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:66:6: error: variable has incomplete type 'void'
   66 | void SANITIZER_CDECL __memprof_profile_reset(void);
      |      ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/stage1/lib/clang/18/include/sanitizer/memprof_interface.h:66:21: error: expected ';' after top level declarator
   66 | void SANITIZER_CDECL __memprof_profile_reset(void);
      |                     ^
/localdisk2/buildbot/llvm-worker/clang-cmake-x86_64-avx512-linux/llvm/compiler-rt/test/memprof/TestCases/memprof_profile_dump.cpp:14:3: error: use of undeclared identifier '__memprof_profile_dump'
   14 |   __memprof_profile_dump();
      |   ^
15 errors generated.
```

The first failing build was https://lab.llvm.org/buildbot/#/builders/258/builds/8852 but the commit related to that is not the cause. @JOE1994 already followed up on that out shortly after this started.

Looking in-between that ID and the last good commit this was obviously caused by b799080f19c2c1a23d096289e6e03cdbd8b44895 committed by @strega-nil.

**Comment by firewave** [comment]
Considering that the actual commit did not trigger a failing build I wonder if there is some gap in the determination logic of the builds to be triggered.

**Comment by strega-nil** [comment]
I believe that we agreed that this was an issue with that specific builder, not the change I made; likely, something wrong with the include paths somehow, which end up including the incorrect `<sanitizer/common_interface_defs.h>`.

**Comment by Enna1** [comment]
Fixed with https://github.com/llvm/llvm-project/commit/ac6f9a785c8adb39bbd9f4aeb20e73b46855ea5b
