### PR TITLE
Fix bazel dep caused by f5b73760

### PR DESCRIPTION
**Pull request by lialan**

### CODE REVIEW

**Comment by lialan** [comment]
Downstream seeing:
```
ERROR: /github/home/.cache/bazel/_bazel_root/4584916dfcfb338dd37ec7118133b12a/external/llvm-project/mlir/BUILD.bazel:13070:11: Compiling mlir/lib/Dialect/MemRef/IR/MemRefDialect.cpp [for tool] failed: (Exit 1): clang failed: error executing CppCompile command (from target @@llvm-project//mlir:MemRefDialect) /usr/lib/llvm-14/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 ... (remaining 136 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/llvm-project/mlir/lib/Dialect/MemRef/IR/MemRefDialect.cpp:13:10: error: module llvm-project//mlir:MemRefDialect does not depend on a module exporting 'mlir/Dialect/UB/IR/UBOps.h'
#include "mlir/Dialect/UB/IR/UBOps.h"
         ^
1 error generated.
```
