### ISSUE TITLE
Error when compiling with GCC 7

### ISSUE THREAD

**Issue by Diana-Dubov** [llvm/llvm-project#63843]
According to llvm documentation it shall [support GCC 7] (https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library).
[This commit: [ADT] Add deduction guide for iterator_range](https://reviews.llvm.org/D152891) breaks it.
Getting this error when compiling with GCC7.4:

```external/llvm-project/llvm/include/llvm/ADT/iterator_range.h:33:26: error: no matching function for call to 'mlir::ValueTypeIterator<llvm::detail::indexed_accessor_range_base<mlir::ResultRange, mlir::detail::OpResultImpl*, mlir::OpResult, mlir::OpResult, mlir::OpResult>::iterator>::ValueTypeIterator(llvm::detail::indexed_accessor_range_base<mlir::TypeRange, llvm::PointerUnion<const mlir::Value*, const mlir::Type*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Type, mlir::Type, mlir::Type>::iterator)'
     std::void_t<decltype(static_cast<To>(
                          ^~~~~~~~~~~~~~~~
         std::declval<std::add_rvalue_reference_t<From>>()))>> : std::true_type {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from external/llvm-project/mlir/include/mlir/Support/TypeID.h:20:0,
                 from external/llvm-project/mlir/include/mlir/IR/MLIRContext.h:13,
                 from external/llvm-project/mlir/include/mlir/IR/DialectRegistry.h:16,
                 from external/llvm-project/mlir/include/mlir/IR/Dialect.h:16,
                 from external/llvm-project/mlir/include/mlir/IR/OpDefinition.h:22,
                 from external/llvm-project/mlir/include/mlir/IR/Builders.h:12,
                 from external/llvm-project/mlir/include/mlir/IR/PatternMatch.h:12,
                 from external/llvm-project/mlir/lib/IR/PatternMatch.cpp:9:
external/llvm-project/llvm/include/llvm/ADT/STLExtras.h:399:3: note: candidate: llvm::mapped_iterator_base<DerivedT, ItTy, ReferenceTy>::mapped_iterator_base(ItTy) [with DerivedT = mlir::ValueTypeIterator<llvm::detail::indexed_accessor_range_base<mlir::ResultRange, mlir::detail::OpResultImpl*, mlir::OpResult, mlir::OpResult, mlir::OpResult>::iterator>; ItTy = llvm::detail::indexed_accessor_range_base<mlir::ResultRange, mlir::detail::OpResultImpl*, mlir::OpResult, mlir::OpResult, mlir::OpResult>::iterator; ReferenceTy = mlir::Type]
   mapped_iterator_base(ItTy U)
```

It is fixed in GCC8 and later, but the issue at GCC7 exists and breaks the promise to support this version.

Thank you

**Comment by Diana-Dubov** [comment]
@steakhal can you please take a look?

**Comment by joker-eph** [comment]
@Diana-Dubov I left a comment in the revision, this is the most usual way to signal that something is broken.

**Comment by steakhal** [comment]
I'll look at this on the weekend.

**Comment by steakhal** [comment]
Here is a partial revert "fix" for the build, by removing the SFINAE constraint and putting back the TODO which was originally there.
https://reviews.llvm.org/D155441

**Comment by steakhal** [comment]
Please reply to the patch. I don't usually monitor Github notifications.

> Why not just ifdef it on the version of the compiler?
> I mean, if someone writes a code that doesn't satisfy SFINAE with GCC7, then there will be compiler-error in the CI

Accommodated the patch according to this.

**Comment by MaskRay** [comment]
I suspect that 7.4 may not be good enough,,,, 7.5 should be fine.

FWIW I created [Require GCC>=7.5 as GCC 7.3 cannot build llvm](https://discourse.llvm.org/t/require-gcc-7-5-as-gcc-7-3-cannot-build-llvm/72310).

**Comment by loongknown** [comment]
> Here is a partial revert "fix" for the build, by removing the SFINAE constraint and putting back the TODO which was originally there. https://reviews.llvm.org/D155441


However, the issue still exists in the KylinV10 system.My gcc version is gcc8.3.0.

**Comment by loongknown** [comment]
However, the issue still exists in the KylinV10 system.My gcc version is gcc8.3.0.

**Comment by steakhal** [comment]
> However, the issue still exists in the KylinV10 system.My gcc version is gcc8.3.0.

Do you imply that we should check `#if __GNUC__ == 8` instead?
Could you clarify your expectations @loongknown?

**Comment by joker-eph** [comment]
We have a gcc 7.5 bot here FYI: https://lab.llvm.org/buildbot/#/builders/264

**Comment by steakhal** [comment]
> We have a gcc 7.5 bot here FYI: https://lab.llvm.org/buildbot/#/builders/264

Thanks Mehdi! Then it seems like it should build on that version of gcc (`GNU 7.5.0`). :thinking:

**Comment by loongknown** [comment]
> Could you clarify your expectations

My operating system is KylinV10, and my GCC version is 8.5.0. I hope to successfully compile LLVM.

**Comment by joker-eph** [comment]
Please file another bug with detailed instruction on your environment, the sequence of commands you ran, and join the detailed log that lead to the error.

**Comment by loongknown** [comment]
my gcc version is 8.3.0.The compilation command is as follows:
cmake -G "Unix Makefiles" ../llvm \
      -DLLVM_ENABLE_PROJECTS="mlir" \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_TARGETS_TO_BUILD="X86"
make -j 32
The error message is as follows:

/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/iterator_range.h:33:26: error: no matching function for call to ‘llvm::detail::indexed_accessor_range_base<mlir::ValueRange, llvm::PointerUnion<const mlir::Value*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Value, mlir::Value, mlir::Value>::iterator::iterator(llvm::detail::indexed_accessor_range_base<mlir::ResultRange, mlir::detail::OpResultImpl*, mlir::OpResult, mlir::OpResult, mlir::OpResult>::iterator)’
     std::void_t<decltype(static_cast<To>(
                          ^~~~~~~~~~~~~~~~
         std::declval<std::add_rvalue_reference_t<From>>()))>> : std::true_type {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/dongshuai/test/llvm-project/mlir/include/mlir/Support/TypeID.h:20,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/MLIRContext.h:13,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/DialectRegistry.h:16,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/Dialect.h:16,
                 from /home/dongshuai/test/llvm-project/mlir/lib/IR/Dialect.cpp:9:
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1262:5: note: candidate: ‘llvm::detail::indexed_accessor_range_base<DerivedT, BaseT, T, PointerT, ReferenceT>::iterator::iterator(BaseT, ptrdiff_t) [with DerivedT = mlir::ValueRange; BaseT = llvm::PointerUnion<const mlir::Value*, mlir::OpOperand*, mlir::detail::OpResultImpl*>; T = mlir::Value; PointerT = mlir::Value; ReferenceT = mlir::Value; ptrdiff_t = long int]’
     iterator(BaseT owner, ptrdiff_t curIndex)
     ^~~~~~~~
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1262:5: note:   candidate expects 2 arguments, 1 provided
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1253:9: note: candidate: ‘constexpr llvm::detail::indexed_accessor_range_base<mlir::ValueRange, llvm::PointerUnion<const mlir::Value*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Value, mlir::Value, mlir::Value>::iterator::iterator(const llvm::detail::indexed_accessor_range_base<mlir::ValueRange, llvm::PointerUnion<const mlir::Value*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Value, mlir::Value, mlir::Value>::iterator&)’
   class iterator : public indexed_accessor_iterator<iterator, BaseT, T,
         ^~~~~~~~
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1253:9: note:   no known conversion for argument 1 from ‘llvm::detail::indexed_accessor_range_base<mlir::ResultRange, mlir::detail::OpResultImpl*, mlir::OpResult, mlir::OpResult, mlir::OpResult>::iterator’ to ‘const llvm::detail::indexed_accessor_range_base<mlir::ValueRange, llvm::PointerUnion<const mlir::Value*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Value, mlir::Value, mlir::Value>::iterator&’
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1253:9: note: candidate: ‘constexpr llvm::detail::indexed_accessor_range_base<mlir::ValueRange, llvm::PointerUnion<const mlir::Value*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Value, mlir::Value, mlir::Value>::iterator::iterator(llvm::detail::indexed_accessor_range_base<mlir::ValueRange, llvm::PointerUnion<const mlir::Value*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Value, mlir::Value, mlir::Value>::iterator&&)’
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1253:9: note:   no known conversion for argument 1 from ‘llvm::detail::indexed_accessor_range_base<mlir::ResultRange, mlir::detail::OpResultImpl*, mlir::OpResult, mlir::OpResult, mlir::OpResult>::iterator’ to ‘llvm::detail::indexed_accessor_range_base<mlir::ValueRange, llvm::PointerUnion<const mlir::Value*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Value, mlir::Value, mlir::Value>::iterator&&’
In file included from /home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/iterator.h:12,
                 from /home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/STLExtras.h:24,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/Support/TypeID.h:20,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/MLIRContext.h:13,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/DialectRegistry.h:16,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/Dialect.h:16,
                 from /home/dongshuai/test/llvm-project/mlir/lib/IR/Dialect.cpp:9:
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/iterator_range.h: In instantiation of ‘struct llvm::explicitly_convertible<const mlir::Type*, llvm::detail::indexed_accessor_range_base<mlir::TypeRange, llvm::PointerUnion<const mlir::Value*, const mlir::Type*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Type, mlir::Type, mlir::Type>::iterator, void>’:
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/iterator_range.h:53:72:   required by substitution of ‘template<class Container, std::enable_if_t<llvm::explicitly_convertible<decltype (llvm::adl_begin(declval<Container&>())), llvm::detail::indexed_accessor_range_base<mlir::TypeRange, llvm::PointerUnion<const mlir::Value*, const mlir::Type*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Type, mlir::Type, mlir::Type>::iterator, void>::value, void>* <anonymous> > llvm::iterator_range<llvm::detail::indexed_accessor_range_base<mlir::TypeRange, llvm::PointerUnion<const mlir::Value*, const mlir::Type*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Type, mlir::Type, mlir::Type>::iterator>::iterator_range(Container&&) [with Container = llvm::ArrayRef<mlir::Type>; std::enable_if_t<llvm::explicitly_convertible<decltype (llvm::adl_begin(declval<Container&>())), llvm::detail::indexed_accessor_range_base<mlir::TypeRange, llvm::PointerUnion<const mlir::Value*, const mlir::Type*, mlir::OpOperand*, mlir::detail::OpResultImpl*>, mlir::Type, mlir::Type, mlir::Type>::iterator, void>::value, void>* <anonymous> = <missing>]’
/home/dongshuai/test/llvm-project/mlir/include/mlir/IR/TypeRange.h:51:40:   required from here

**Comment by joker-eph** [comment]
@loongknown : as instructed above, please open **another** bug. This bug is closed, and you have a slightly different issue.

(also please include the CMake configuration log, and add these logs as textual file attachment instead of plain text in the description).

**Comment by joker-eph** [comment]
@loongknown :
https://github.com/llvm/llvm-project/pull/82643

**Comment by loongknown** [comment]
> @loongknown : #82643

Have you tested on GCC 8.3.0? Even after applying this patch, I'm still getting compilation errors. The error message is as follows:

/home/dongshuai/test/llvm-project/mlir/lib/Transforms/Utils/CFGToSCF.cpp: In function ‘mlir::FailureOr<llvm::SmallVector<mlir::Block*> > transformToStructuredCFBranches(mlir::Block*, mlir::function_ref<mlir::Value(unsigned int)>, mlir::function_ref<mlir::Value(mlir::Type)>, mlir::CFGToSCFInterface&, mlir::DominanceInfo&)’:
/home/dongshuai/test/llvm-project/mlir/lib/Transforms/Utils/CFGToSCF.cpp:1187:61: error: call of overloaded ‘OperandRange(mlir::MutableOperandRange)’ is ambiguous
             getMutableSuccessorOperands(user->getBlock(), 0)));
                                                             ^
In file included from /home/dongshuai/test/llvm-project/mlir/include/mlir/Support/TypeID.h:20,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/MLIRContext.h:13,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/DialectRegistry.h:16,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/Dialect.h:16,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/OpDefinition.h:22,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/Builders.h:12,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/Transforms/CFGToSCF.h:18,
                 from /home/dongshuai/test/llvm-project/mlir/lib/Transforms/Utils/CFGToSCF.cpp:116:
/home/dongshuai/test/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1273:3: note: candidate: ‘llvm::detail::indexed_accessor_range_base<DerivedT, BaseT, T, PointerT, ReferenceT>::indexed_accessor_range_base(const llvm::iterator_range<llvm::detail::indexed_accessor_range_base<DerivedT, BaseT, T, PointerT, ReferenceT>::iterator>&) [with DerivedT = mlir::OperandRange; BaseT = mlir::OpOperand*; T = mlir::Value; PointerT = mlir::Value; ReferenceT = mlir::Value]’
   indexed_accessor_range_base(const iterator_range<iterator> &range)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/TypeRange.h:18,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/OperationSupport.h:23,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/Dialect.h:17,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/OpDefinition.h:22,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/IR/Builders.h:12,
                 from /home/dongshuai/test/llvm-project/mlir/include/mlir/Transforms/CFGToSCF.h:18,
                 from /home/dongshuai/test/llvm-project/mlir/lib/Transforms/Utils/CFGToSCF.cpp:116:
/home/dongshuai/test/llvm-project/mlir/include/mlir/IR/ValueRange.h:44:21: note:   inherited here
   using RangeBaseT::RangeBaseT;
                     ^~~~~~~~~~
/home/dongshuai/test/llvm-project/mlir/include/mlir/IR/ValueRange.h:41:7: note: candidate: ‘constexpr mlir::OperandRange::OperandRange(const mlir::OperandRange&)’
 class OperandRange final : public llvm::detail::indexed_accessor_range_base<
       ^~~~~~~~~~~~
/home/dongshuai/test/llvm-project/mlir/include/mlir/IR/ValueRange.h:41:7: note: candidate: ‘constexpr mlir::OperandRange::OperandRange(mlir::OperandRange&&)’
