### ISSUE TITLE
FreeBSD 13 compilation broken by 0d8cb8b399adcd17e8bf17be7814d030308c8b82

### ISSUE THREAD

**Issue by VoxSciurorum** [llvm/llvm-project#55414]
Since commit 0d8cb8b399adcd17e8bf17be7814d030308c8b82 on main I can't build on FreeBSD 13 due to the following error (irrelevant local disk path replaced by [...]).  The system compiler is clang 13.0.0 and the system C++ headers are from LLVM of unknown (to me) vintage.

```console
In file included from [...]/llvm-project/llvm/lib/DebugInfo/DWARF/DWARFVerifier.cpp:8:
In file included from [...]/llvm-project/llvm/include/llvm/DebugInfo/DWARF/DWARFVerifier.h:12:
In file included from [...]/llvm-project/llvm/include/llvm/ADT/Optional.h:19:
In file included from [...]/llvm-project/llvm/include/llvm/ADT/Hashing.h:51:
In file included from /usr/include/c++/v1/algorithm:653:
In file included from /usr/include/c++/v1/functional:500:
In file included from /usr/include/c++/v1/__functional/function.h:20:
In file included from /usr/include/c++/v1/__memory/shared_ptr.h:22:
/usr/include/c++/v1/__memory/allocator.h:154:28: error: call to implicitly-deleted copy constructor of 'llvm::IntervalMap<unsigned int, unsigned long, 12>'
        ::new ((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                           ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/__memory/allocator_traits.h:290:13: note: in instantiation of function template specialization 'std::allocator<llvm::IntervalMap<unsigned int, unsigned long, 12>>::construct<llvm::IntervalMap<unsigned int, unsigned long, 12>, const llvm::IntervalMap<unsigned int, unsigned long, 12> &>' requested here
        __a.construct(__p, _VSTD::forward<_Args>(__args)...);
            ^
/usr/include/c++/v1/vector:1085:25: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<llvm::IntervalMap<unsigned int, unsigned long, 12>>>::construct<llvm::IntervalMap<unsigned int, unsigned long, 12>, const llvm::IntervalMap<unsigned int, unsigned long, 12> &, void>' requested here
        __alloc_traits::construct(this->__alloc(), _VSTD::__to_address(__pos), __x);
                        ^
/usr/include/c++/v1/vector:1178:9: note: in instantiation of member function 'std::vector<llvm::IntervalMap<unsigned int, unsigned long, 12>>::__construct_at_end' requested here
        __construct_at_end(__n, __x);
        ^
[...]/llvm-project/llvm/lib/DebugInfo/DWARF/DWARFVerifier.cpp:410:48: note: in instantiation of member function 'std::vector<llvm::IntervalMap<unsigned int, unsigned long, 12>>::vector' requested here
  std::vector<IntervalMap<uint32_t, uint64_t>> Sections(
                                               ^
[...]/llvm-project/llvm/include/llvm/ADT/IntervalMap.h:970:14: note: copy constructor of 'IntervalMap<unsigned int, unsigned long, 12>' is implicitly deleted because variant field 'leaf' has a non-trivial copy constructor
    RootLeaf leaf;
             ^
1 error generated.
--- lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFVerifier.cpp.o ---
*** [lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFVerifier.cpp.o] Error code 1
```

**Comment by DimitryAndric** [comment]
See my comment here: https://reviews.llvm.org/rG0d8cb8b399adcd17e8bf17be7814d030308c8b82#1085375

The short story is that FreeBSD has always kept the first libc++ ABI with regards to std::pair constructors, and this sometimes causes problems when building programs that make use of them. I'm not sure why this particular llvm commit now triggers it, though. Apparently nobody called the IntervalMap copy constructor up to now? :)

**Comment by DimitryAndric** [comment]
> Reverting [dc4f9f0](https://github.com/llvm/llvm-project/commit/dc4f9f0368cd56484d5e33364c06739be5ae1f1d) ("[ADT] Just use a union in IntervalMap") also fixes the build.

Hmm, so maybe it's that which causes the constructor to become non-trivial? Not sure how that works.
