### ISSUE TITLE
apt fails to compile with clang trunk/17.0.0

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#63743]
Attached is preprocessed file which fails to compile with clang trunk + libc++, this works ok with libstdc++ and clang also works ok with clang-16, this is on aarch64/x86_64

```
| /mnt/b/yoe/master/build/tmp/work/cortexa72-cortexa53-crypto-yoe-linux/apt/2.6.1-r0/recipe-sysroot/usr/include/c++/v1/__algorithm/sort.h:290:44: error: invalid operands to binary expression ('const APT::C
         ontainer_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>' and 'difference_type' (aka 'long'))  for (_RandomAccessIterator __i = __first + difference_type(1); __i != __last; ++__i) {
                                    ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
```

[test.zip](https://github.com/llvm/llvm-project/files/11984023/test.zip)

**Comment by philnik777** [comment]
Could you provide the non-preprocessed source? 100k lines is a bit much to reduce IMO.

**Comment by ldionne** [comment]
Closing as not reproducible.

**Comment by kraj** [comment]
@ldionne I can still observe this issue with clang 20.1.8 as well. This time I tried to reduce it a bit. Here is a smaller test case
`depcache.cc`

```c++
#include <algorithms.h>
//typedef VersionContainer<std::vector<pkgCache::VerIterator> > VersionVector;
void a() {
  APT::VersionVector b;
  sort(b.begin(), b.end());
}
```

This needs to point to apt source headers for getting `algorithms.h` I am attaching the include.zip here
unzip it and point clang++ to it

```
clang++ -D_WITH_GETLINE=1 -Dapt_pkg_EXPORTS -I./include/ -I./include/apt-pkg depcache.cc -stdlib=libc++
```

[include.zip](https://github.com/user-attachments/files/21324199/include.zip)

Can you re-open the issue also please ?

**Comment by ldionne** [comment]
First, I get:

```
In file included from depcache.cc:1:
In file included from ./include/apt-pkg/algorithms.h:32:
In file included from ./include/apt-pkg/cachefilter.h:9:
In file included from ./include/apt-pkg/pkgcache.h:85:
./include/apt-pkg/string_view.h:75:54: error: use of undeclared identifier 'memrchr'; did you mean 'memchr'?
   75 |         const char *found = static_cast<const char*>(memrchr(data_, c, size_));
      |                                                      ^~~~~~~
      |                                                      memchr
.../usr/include/c++/v1/string.h:98:69: note: 'memchr' declared here
   98 | inline _LIBCPP_HIDE_FROM_ABI _LIBCPP_PREFERRED_OVERLOAD const void* memchr(const void* __s, int __c, size_t __n) {
```

It looks like this code is using a non-portable function `memrchr`. But if I resolve that issue (by using e.g. `memchr` instead just to silent it), then I can reproduce and I get this:

```
$ clang++ -D_WITH_GETLINE=1 -Dapt_pkg_EXPORTS -I./include/ -I./include/apt-pkg depcache.cc -stdlib=libc++
In file included from depcache.cc:1:
In file included from ./include/apt-pkg/algorithms.h:32:
In file included from ./include/apt-pkg/cachefilter.h:9:
In file included from ./include/apt-pkg/pkgcache.h:78:
In file included from ./include/apt-pkg/mmap.h:31:
In file included from <...>/usr/include/c++/v1/string:652:
In file included from <...>/usr/include/c++/v1/string_view:947:
In file included from <...>/usr/include/c++/v1/algorithm:1881:
In file included from <...>/usr/include/c++/v1/__algorithm/nth_element.h:15:
<...>/usr/include/c++/v1/__algorithm/sort.h:280:52: error: invalid operands to binary expression ('const APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>' and 'difference_type' (aka 'long'))
  280 |   const _RandomAccessIterator __leftmost = __first - difference_type(1);
      |                                            ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
<...>/usr/include/c++/v1/__algorithm/sort.h:761:14: note: in instantiation of function template specialization 'std::__insertion_sort_unguarded<std::_ClassicAlgPolicy, std::__less<void, void> &, APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>>' requested here
  761 |         std::__insertion_sort_unguarded<_AlgPolicy, _Compare>(__first, __last, __comp);
      |              ^
<...>/usr/include/c++/v1/__algorithm/sort.h:888:8: note: in instantiation of function template specialization 'std::__introsort<std::_ClassicAlgPolicy, std::__less<void, void> &, APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>, false>' requested here
  888 |   std::__introsort<_AlgPolicy, _Comp&, _RandomAccessIterator, __use_branchless_sort<_Comp, _RandomAccessIterator> >(
      |        ^
<...>/usr/include/c++/v1/__algorithm/sort.h:953:10: note: in instantiation of function template specialization 'std::__sort_dispatch<std::_ClassicAlgPolicy, APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>, std::__less<void, void>>' requested here
  953 |     std::__sort_dispatch<_AlgPolicy>(std::__unwrap_iter(__first), std::__unwrap_iter(__last), __comp);
      |          ^
<...>/usr/include/c++/v1/__algorithm/sort.h:961:8: note: in instantiation of function template specialization 'std::__sort_impl<std::_ClassicAlgPolicy, APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>, std::__less<void, void>>' requested here
  961 |   std::__sort_impl<_ClassicAlgPolicy>(std::move(__first), std::move(__last), __comp);
      |        ^
<...>/usr/include/c++/v1/__algorithm/sort.h:967:8: note: in instantiation of function template specialization 'std::sort<APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>, std::__less<void, void>>' requested here
  967 |   std::sort(__first, __last, __less<>());
      |        ^
depcache.cc:5:3: note: in instantiation of function template specialization 'std::sort<APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>>' requested here
    5 |   sort(b.begin(), b.end());
      |   ^
<...>/usr/include/c++/v1/__ios/fpos.h:60:40: note: candidate template ignored: could not match 'fpos' against 'APT::Container_iterator'
   60 | inline _LIBCPP_HIDE_FROM_ABI streamoff operator-(const fpos<_StateT>& __x, const fpos<_StateT>& __y) {
      |                                        ^
<...>/usr/include/c++/v1/__iterator/reverse_iterator.h:289:1: note: candidate template ignored: could not match 'reverse_iterator' against 'APT::Container_iterator'
  289 | operator-(const reverse_iterator<_Iter1>& __x,
      | ^
<...>/usr/include/c++/v1/__iterator/wrap_iter.h:216:5: note: candidate template ignored: could not match '__wrap_iter' against 'APT::Container_iterator'
  216 |     operator-(const __wrap_iter<_Iter1>& __x,
      |     ^
<...>/usr/include/c++/v1/__iterator/move_iterator.h:303:1: note: candidate template ignored: could not match 'move_iterator' against 'APT::Container_iterator'
  303 | operator-(const move_iterator<_Iter1>& __x, const move_iterator<_Iter2>& __y) -> decltype(__x.base() - __y.base()) {
      | ^
./include/apt-pkg/pkgcache.h:113:38: note: candidate template ignored: could not match 'map_pointer' against 'APT::Container_iterator'
  113 | template<typename T> inline uint32_t operator -(map_pointer<T> u, map_pointer<T> m) { return uint32_t(u) - uint32_t(m); }
      |                                      ^
./include/apt-pkg/cacheset.h:225:23: note: candidate function not viable: no known conversion from 'const APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>' to 'APT::Container_iterator_base<APT::VersionContainerInterface, APT::VersionContainer<std::vector<pkgCache::VerIterator>>, APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>, std::__wrap_iter<pkgCache::VerIterator *>, pkgCache::VerIterator>' for object argument
  225 |         inline iterator_type operator-(typename container_iterator::difference_type const &n) { return iterator_type(_iter - n); }
      |                              ^
./include/apt-pkg/cacheset.h:226:54: note: candidate function not viable: no known conversion from 'const APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>' to 'APT::Container_iterator_base<APT::VersionContainerInterface, APT::VersionContainer<std::vector<pkgCache::VerIterator>>, APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>, std::__wrap_iter<pkgCache::VerIterator *>, pkgCache::VerIterator>' for object argument
  226 |         inline typename container_iterator::difference_type operator-(iterator_type const &b) { return (_iter - b._iter); }
      |                                                             ^
```

**Comment by philnik777** [comment]
That looks to me suspiciously like the iterator isn't implementing the required API. Looks like there is a `const` missing on `operator-`, which the error message says.

**Comment by ldionne** [comment]
I believe your code is incorrect. You're passing `APT::VersionVector::iterator` objects to `std::sort`, which requires random access iterators. However, random access iterators [are required to support](https://en.cppreference.com/w/cpp/named_req/RandomAccessIterator) the expression `it - n` where `n` is a `difference_type` value and `it` is either a `const` or a non-`const` iterator.

In `std::__insertion_sort_unguarded` ([here](https://github.com/llvm/llvm-project/blob/5d3b0578d8d51947a6878d65249174de86105073/libcxx/include/__algorithm/sort.h#L274)), we (rightfully) use `it - n` where `it` is a `const`-qualified object, which seems to throw off your code. Indeed, when I use your reproducer locally and remove `const` on that function declaration, the code passes.

The error message seems to confirm the above: the `operator-` method doesn't have a `const` qualifier on it, but it should:

```
./include/apt-pkg/cacheset.h:225:23: note: candidate function not viable: no known conversion from 'const APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>' to 'APT::Container_iterator_base<APT::VersionContainerInterface, APT::VersionContainer<std::vector<pkgCache::VerIterator>>, APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>, std::__wrap_iter<pkgCache::VerIterator *>, pkgCache::VerIterator>' for object argument
  225 |         inline iterator_type operator-(typename container_iterator::difference_type const &n) { return iterator_type(_iter - n); }
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  NO CONST HERE
```

Edit: @philnik777 and I got into a race condition and arrived at the same conclusion

**Comment by kraj** [comment]
Indeed, its fixed in apt as well https://salsa.debian.org/apt-team/apt/-/commit/b4488583424b33f51cb031562a9e8df820ffda23
I was on an older snapshot, thanks for help and sorry for noise.
