### ISSUE TITLE
lldb 13.0.0: crash in SymbolFileDWARF::GetTypeSystem(DWARFUnit&)

### ISSUE THREAD

**Issue by dmlary** [llvm/llvm-project#53570]
Crash while printing a c++ class private variable.

```txt
(lldb) p m_platform_sp
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: lldb -p 11383
 #0 0x000000000042043c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/llvm-13.0.0/bin/lldb+0x42043c)
 #1 0x000000000041e994 llvm::sys::RunSignalHandlers() (/usr/local/llvm-13.0.0/bin/lldb+0x41e994)
 #2 0x000000000041ed53 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f6cfe42b630 __restore_rt sigaction.c:0:0
 #4 0x00007f6cfa222594 SymbolFileDWARF::GetTypeSystem(DWARFUnit&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12a4594)
 #5 0x00007f6cfa226d82 SymbolFileDWARF::GetDWARFParser(DWARFUnit&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12a8d82)
 #6 0x00007f6cfa254dc2 DWARFASTParserClang::CopyUniqueClassMethodTypes(DWARFDIE const&, DWARFDIE const&, lldb_private::Type*, std::vector<DWARFDIE, std::allocator<DWARFDIE> >&) (.part.672) DWARFASTParserClang.cpp:0:0
 #7 0x00007f6cfa25696e DWARFASTParserClang::ParseSubroutine(DWARFDIE const&, ParsedDWARFTypeAttributes&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12d896e)
 #8 0x00007f6cfa25b384 DWARFASTParserClang::ParseTypeFromDWARF(lldb_private::SymbolContext const&, DWARFDIE const&, bool*) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12dd384)
 #9 0x00007f6cfa22ba33 SymbolFileDWARF::ParseType(lldb_private::SymbolContext const&, DWARFDIE const&, bool*) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12ada33)
#10 0x00007f6cfa22c62e SymbolFileDWARF::GetTypeForDIE(DWARFDIE const&, bool) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12ae62e)
#11 0x00007f6cfa22c8ee SymbolFileDWARF::ResolveType(DWARFDIE const&, bool, bool) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12ae8ee)
#12 0x00007f6cfa253e6a DWARFASTParserClang::GetClangDeclContextForDIE(DWARFDIE const&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12d5e6a)
#13 0x00007f6cfa2545a9 DWARFASTParserClang::GetDeclContextForUIDFromDWARF(DWARFDIE const&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12d65a9)
#14 0x00007f6cfa226fb7 SymbolFileDWARF::GetDeclContextForUID(unsigned long) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12a8fb7)
#15 0x00007f6cfabed4bb lldb_private::ClangUserExpression::ScanContext(lldb_private::ExecutionContext&, lldb_private::Status&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x1c6f4bb)
#16 0x00007f6cfabee939 lldb_private::ClangUserExpression::PrepareForParsing(lldb_private::DiagnosticManager&, lldb_private::ExecutionContext&, bool) (.part.279) ClangUserExpression.cpp:0:0
#17 0x00007f6cfabef0b3 lldb_private::ClangUserExpression::Parse(lldb_private::DiagnosticManager&, lldb_private::ExecutionContext&, lldb_private::ExecutionPolicy, bool, bool) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x1c710b3)
#18 0x00007f6cf9dedda1 lldb_private::UserExpression::Evaluate(lldb_private::ExecutionContext&, lldb_private::EvaluateExpressionOptions const&, llvm::StringRef, llvm::StringRef, std::shared_ptr<lldb_private::ValueObject>&, lldb_private::Status&, std::string*, lldb_private::ValueObject*) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xe6fda1)
#19 0x00007f6cf9f0c184 lldb_private::Target::EvaluateExpression(llvm::StringRef, lldb_private::ExecutionContextScope*, std::shared_ptr<lldb_private::ValueObject>&, lldb_private::EvaluateExpressionOptions const&, std::string*, lldb_private::ValueObject*) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xf8e184)
#20 0x00007f6cfaaeab22 lldb_private::CommandObjectExpression::EvaluateExpression(llvm::StringRef, lldb_private::Stream&, lldb_private::Stream&, lldb_private::CommandReturnObject&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x1b6cb22)
#21 0x00007f6cfaaebd0f lldb_private::CommandObjectExpression::DoExecute(llvm::StringRef, lldb_private::CommandReturnObject&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x1b6dd0f)
#22 0x00007f6cf9e2c2c0 lldb_private::CommandObjectRaw::Execute(char const*, lldb_private::CommandReturnObject&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xeae2c0)
#23 0x00007f6cf9e29a3c lldb_private::CommandInterpreter::HandleCommand(char const*, lldb_private::LazyBool, lldb_private::CommandReturnObject&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xeaba3c)
#24 0x00007f6cf9e2a084 lldb_private::CommandInterpreter::IOHandlerInputComplete(lldb_private::IOHandler&, std::string&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xeac084)
#25 0x00007f6cf9d61149 lldb_private::IOHandlerEditline::Run() (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xde3149)
#26 0x00007f6cf9d3d442 lldb_private::Debugger::RunIOHandlers() (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xdbf442)
#27 0x00007f6cf9e1cdf3 lldb_private::CommandInterpreter::RunCommandInterpreter(lldb_private::CommandInterpreterRunOptions&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xe9edf3)
#28 0x00007f6cf99e31ff lldb::SBDebugger::RunCommandInterpreter(bool, bool) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xa651ff)
#29 0x000000000040780f Driver::MainLoop() (/usr/local/llvm-13.0.0/bin/lldb+0x40780f)
#30 0x000000000040675d main (/usr/local/llvm-13.0.0/bin/lldb+0x40675d)
#31 0x00007f6cf7b67545 __libc_start_main (/lib64/libc.so.6+0x22545)
#32 0x0000000000406915 _start (/usr/local/llvm-13.0.0/bin/lldb+0x406915)
```

To reproduce:
* build debug version of lldb using gcc 7.3.1
* open debug version of lldb
* attach lldb to debug version of lldb
* set breakpoint at `CommandObjectTargetCreate::DoExecute`
* in debug version of lldb, run `target create <some binary> --core <some core>`
* step into line 333: `PlatformSP platform_sp = target_sp->GetPlatform();`
* run `p m_platform_sp`

I'd offer the core file, but it's 5Gb.

**Comment by dmlary** [comment]
crash also occurs with lldb build with llvm-13.0.0.

**Comment by PRESIDENT810** [comment]
I'm a little bit confused here. I'm not sure I completely get how you reproduce this bug.
This is what I've done:
1. I built a debug version of LLDB (let's call it LLDB_A)
2. I started LLDB_A
3. I attached to LLDB_A using the same LLDB binary (let's call it LLDB_B)
4. In LLDB_B, I set a breakpoint at line 333 of CommandObjectTarget.cpp
5. I enter "target create <some binary> --core <some core>" in LLDB_A's console
6. LLDB_B then stopped at the breakpoint I set at line 333
7. I enter "p m_platform_sp" in LLDB_B's console
8. And I got this output in LLDB_B's console, and my LLDB_B does not crash:
```
(lldb) p m_platform_sp
warning: could not find Objective-C class data in the process. This may reduce the quality of type information available.
error: <user expression 0>:1:1: use of undeclared identifier 'm_platform_sp'
m_platform_sp
^
```

Am I doing it right? I think I might misunderstood something here...

**Comment by dmlary** [comment]
Attempting to clarify the reproduce directions, and found a shorter path.

Given debug build of lldb, called `lldb-debug` (in this example I'm using v14.0.1 as the inferior process, but it reproduced originally on 13.0.0), and release build v13.0.0 of lldb, called `lldb-release`.  We're going to cause a crash in the v13.0.0 release build of lldb, trying to print a variable from the debug build.
  
```txt
# in one shell, open lldb-debug
$ lldb-debug

# in a second shell, attach to lldb-debug with lldb-release, and
# set a breakpoint for `Target::GetPlatform()`
$ lldb-release ./bin/lldb-debug -p 12345
(lldb-release) process attach --pid 12345
(lldb-release) b Target::GetPlatform
Breakpoint 1: 2 locations.
(lldb-release) c
Process 12345 resuming

# in lldb-debug, create a new target
(lldb-debug) target create ./hello_world

# in lldb-release, try to print `m_platform_sp`
Process 12345 stopped
* thread #1, name = 'lldb', stop reason = breakpoint 1.2
    frame #0: 0x00007f52b5d4e182 liblldb.so.14`lldb_private::Target::GetPlatform(this=0x00000000011361b0) at Target.h:1374:20
   1371	    return (*pos).second;
   1372	  }
   1373
-> 1374	  lldb::PlatformSP GetPlatform() { return m_platform_sp; }
   1375
   1376	  void SetPlatform(const lldb::PlatformSP &platform_sp) {
   1377	    m_platform_sp = platform_sp;
(lldb) p m_platform_sp
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: lldb ./bin/lldb -p 20681
 #0 0x000000000042043c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/llvm-13.0.0/bin/lldb+0x42043c)
 #1 0x000000000041e994 llvm::sys::RunSignalHandlers() (/usr/local/llvm-13.0.0/bin/lldb+0x41e994)
 #2 0x000000000041ed53 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f1ddf12b630 __restore_rt sigaction.c:0:0
 #4 0x00007f1ddaf22594 SymbolFileDWARF::GetTypeSystem(DWARFUnit&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12a4594)
 #5 0x00007f1ddaf26d82 SymbolFileDWARF::GetDWARFParser(DWARFUnit&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12a8d82)
 #6 0x00007f1ddaf54dc2 DWARFASTParserClang::CopyUniqueClassMethodTypes(DWARFDIE const&, DWARFDIE const&, lldb_private::Type*, std::vector<DWARFDIE, std::allocator<DWARFDIE> >&) (.part.672) DWARFASTParserClang.cpp:0:0
 #7 0x00007f1ddaf5696e DWARFASTParserClang::ParseSubroutine(DWARFDIE const&, ParsedDWARFTypeAttributes&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12d896e)
 #8 0x00007f1ddaf5b384 DWARFASTParserClang::ParseTypeFromDWARF(lldb_private::SymbolContext const&, DWARFDIE const&, bool*) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12dd384)
 #9 0x00007f1ddaf2ba33 SymbolFileDWARF::ParseType(lldb_private::SymbolContext const&, DWARFDIE const&, bool*) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12ada33)
#10 0x00007f1ddaf2c62e SymbolFileDWARF::GetTypeForDIE(DWARFDIE const&, bool) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12ae62e)
#11 0x00007f1ddaf2c8ee SymbolFileDWARF::ResolveType(DWARFDIE const&, bool, bool) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12ae8ee)
#12 0x00007f1ddaf53e6a DWARFASTParserClang::GetClangDeclContextForDIE(DWARFDIE const&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12d5e6a)
#13 0x00007f1ddaf545a9 DWARFASTParserClang::GetDeclContextForUIDFromDWARF(DWARFDIE const&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12d65a9)
#14 0x00007f1ddaf26fb7 SymbolFileDWARF::GetDeclContextForUID(unsigned long) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x12a8fb7)
#15 0x00007f1ddb8ed4bb lldb_private::ClangUserExpression::ScanContext(lldb_private::ExecutionContext&, lldb_private::Status&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x1c6f4bb)
#16 0x00007f1ddb8ee939 lldb_private::ClangUserExpression::PrepareForParsing(lldb_private::DiagnosticManager&, lldb_private::ExecutionContext&, bool) (.part.279) ClangUserExpression.cpp:0:0
#17 0x00007f1ddb8ef0b3 lldb_private::ClangUserExpression::Parse(lldb_private::DiagnosticManager&, lldb_private::ExecutionContext&, lldb_private::ExecutionPolicy, bool, bool) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x1c710b3)
#18 0x00007f1ddaaedda1 lldb_private::UserExpression::Evaluate(lldb_private::ExecutionContext&, lldb_private::EvaluateExpressionOptions const&, llvm::StringRef, llvm::StringRef, std::shared_ptr<lldb_private::ValueObject>&, lldb_private::Status&, std::string*, lldb_private::ValueObject*) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xe6fda1)
#19 0x00007f1ddac0c184 lldb_private::Target::EvaluateExpression(llvm::StringRef, lldb_private::ExecutionContextScope*, std::shared_ptr<lldb_private::ValueObject>&, lldb_private::EvaluateExpressionOptions const&, std::string*, lldb_private::ValueObject*) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xf8e184)
#20 0x00007f1ddb7eab22 lldb_private::CommandObjectExpression::EvaluateExpression(llvm::StringRef, lldb_private::Stream&, lldb_private::Stream&, lldb_private::CommandReturnObject&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x1b6cb22)
#21 0x00007f1ddb7ebd0f lldb_private::CommandObjectExpression::DoExecute(llvm::StringRef, lldb_private::CommandReturnObject&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0x1b6dd0f)
#22 0x00007f1ddab2c2c0 lldb_private::CommandObjectRaw::Execute(char const*, lldb_private::CommandReturnObject&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xeae2c0)
#23 0x00007f1ddab29a3c lldb_private::CommandInterpreter::HandleCommand(char const*, lldb_private::LazyBool, lldb_private::CommandReturnObject&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xeaba3c)
#24 0x00007f1ddab2a084 lldb_private::CommandInterpreter::IOHandlerInputComplete(lldb_private::IOHandler&, std::string&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xeac084)
#25 0x00007f1ddaa61149 lldb_private::IOHandlerEditline::Run() (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xde3149)
#26 0x00007f1ddaa3d442 lldb_private::Debugger::RunIOHandlers() (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xdbf442)
#27 0x00007f1ddab1cdf3 lldb_private::CommandInterpreter::RunCommandInterpreter(lldb_private::CommandInterpreterRunOptions&) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xe9edf3)
#28 0x00007f1dda6e31ff lldb::SBDebugger::RunCommandInterpreter(bool, bool) (/usr/local/llvm-13.0.0/bin/../lib/liblldb.so.13+0xa651ff)
#29 0x000000000040780f Driver::MainLoop() (/usr/local/llvm-13.0.0/bin/lldb+0x40780f)
#30 0x000000000040675d main (/usr/local/llvm-13.0.0/bin/lldb+0x40675d)
#31 0x00007f1dd8866555 __libc_start_main (/lib64/libc.so.6+0x22555)
#32 0x0000000000406915 _start (/usr/local/llvm-13.0.0/bin/lldb+0x406915)
Segmentation fault
```

**Comment by PRESIDENT810** [comment]
Hummm... I'm a MacOS user and it seems LLDB works fine for me after I followed steps above. This is my output:

```
./lldb /Users/bytedance/github/llvm-project/build/bin/lldb -p 13767
(lldb) process attach --pid 13767
Process 13767 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007ff81d769d5a libsystem_kernel.dylib`__select + 10
libsystem_kernel.dylib`:
->  0x7ff81d769d5a <+10>: jae    0x7ff81d769d64            ; <+20>
    0x7ff81d769d5c <+12>: movq   %rax, %rdi
    0x7ff81d769d5f <+15>: jmp    0x7ff81d762db9            ; cerror
    0x7ff81d769d64 <+20>: retq
Executable module set to "/Users/bytedance/github/llvm-project/build/bin/lldb".
Architecture set to: x86_64h-apple-macosx-.
(lldb) b Target::GetPlatform
Breakpoint 2: 2 locations.
(lldb) c
Process 13767 resuming
Process 13767 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 2.1
    frame #0: 0x000000013a29a9ae liblldb.15.0.0git.dylib`lldb_private::Target::GetPlatform(this=0x00007faa6382ec00) at Target.h:1389:43
   1386     return (*pos).second;
   1387   }
   1388 
-> 1389   lldb::PlatformSP GetPlatform() { return m_platform_sp; }
   1390 
   1391   void SetPlatform(const lldb::PlatformSP &platform_sp) {
   1392     m_platform_sp = platform_sp;
(lldb) p m_platform_sp
(lldb::PlatformSP) $0 = std::__1::shared_ptr<lldb_private::Platform>::element_type @ 0x00007faa848050a0 strong=6 weak=1 {
  __ptr_ = 0x00007faa848050a0
}
(lldb) version
lldb version 15.0.0git (https://github.com/llvm/llvm-project.git revision c1adefa33d3f68d5abf0f9ae7dceb1bf47aa606b)
  clang revision c1adefa33d3f68d5abf0f9ae7dceb1bf47aa606b
  llvm revision c1adefa33d3f68d5abf0f9ae7dceb1bf47aa606b
```

I built my LLDB using clang from Xcode toolchain, and I plan to try to build it with llvm's clang later. Maybe that will produce this error.
