### ISSUE TITLE
Can't build LLDB 13 with older linux kernel

### ISSUE THREAD

**Issue by calebzulawski** [llvm/llvm-project#51259]
|  |  |
| --- | --- |
| Bugzilla Link | [51917](https://llvm.org/bz51917) |
| Version | unspecified |
| OS | Linux |
| CC | @JDevlieghere,@labath,@tstellar |

## Extended Description 
I am trying to build with a kernel older than 4.1, and get the following error:

llvm-project-13.0.0rc3.src/lldb/source/Plugins/Process/Linux/IntelPTManager.cpp:148:23: error: 'struct perf_event_mmap_page' has no member named 'aux_size'
  148 |   return m_mmap_meta->aux_size;
      | 

aux_size was added in Linux 4.1.  It appears the Intel PT plugin was added in LLVM 13, I can currently build LLVM 12 and hope to be able to upgrade to 13 when it's released.

**Comment by DavidSpickett** [comment]
[Above patch ](https://reviews.llvm.org/D110269) was merged, closing.
