### ISSUE TITLE
Clang is unable to match calls to functions with a std::initializer_list when modules are enabled and a class with a virtual destructor is defined before #include <initializer_list>

### ISSUE THREAD

**Issue by alanzhao1** [llvm/llvm-project#60929]
I have commit b673135bb833a54b16c32e2073d2d7b83c90de66 checked out

Repro steps:

1. Build and install libc++:
```console
$ cmake -G Ninja -B build -S runtimes -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DLIBCXX_ABI_UNSTABLE=On
$ cd build
$ ninja cxx cxxabi unwind
$ ninja install-cxx install-cxxabi install-unwind
```

2. Build Clang
3. Attempt to compile the following file against the aforementioned installed libc++
```cpp
// initlist_test.cc
class X {
 public:
  virtual ~X() {}
};

#include <initializer_list>

void takesil(std::initializer_list<int> il) {}

void passesil() { takesil({1}); }
```

```console
$ /path/to/built/clang++ -nostdinc++ -isystem/path/to/installed/libc++/include/c++/v1 -fmodules -fbuiltin-module-map -fmodule-map-file=/path/to/installed/libc++/include/c++/v1/module.modulemap -c -o initlist_test initlist_test.cc
```

Expected result:

Clang should compile the file without any errors

Actual result:

Clang fails to match the call to `takesil(...)` in `passesil()`:

```console
initlist_test.cc:11:19: error: no matching function for call to 'takesil'
void passesil() { takesil({1});}
                  ^~~~~~~
initlist_test.cc:9:6: note: candidate function not viable: cannot convert initializer list argument to 'std::initializer_list<int>'
void takesil(std::initializer_list<int> il) {}
     ^
1 error generated.
```

**Comment by alanzhao1** [comment]
This seems to be fixed as of 53430bfd5c9d0074dd6de06dccea366e1d40bce4

I'll do a git bisect to see what changed

**Comment by alanzhao1** [comment]
I think I figured out what's going on. Unfortunately, I have no idea how to fix this:

1. When Clang encounters a class with a virtual destructor, Clang calls `Sema::DeclareGlobalNewDelete()`, which in turn [calls `getOrCreateStdNamespace()`](https://github.com/llvm/llvm-project/blob/d34125a1a825208b592cfa8f5fc3566303d691a4/clang/lib/Sema/SemaExprCXX.cpp#L3005). If the virtual destructor isn't present, then we [set the `Sema::StdNamespace` member to the one obtained by deserializing the header module](https://github.com/llvm/llvm-project/blob/2b4efd2a1abca06c2a1a2d64496c7f1303ca36eb/clang/lib/Serialization/ASTReader.cpp#L8021-L8022).
2. Later, when Clang analyzes the call `takesil({1})`, Clang calls `TryListConversion(...)` as part of its overload resolution logic. `TryListConversion(...)` [calls `Sema::isStdInitializerList(...)`](https://github.com/llvm/llvm-project/blob/777eb4bcfc3265359edb7c979d3e5ac699ad4641/clang/lib/Sema/SemaOverload.cpp#L5193)
3. `Sema::isStdInitializerList(...)` performs the following check ([source](https://github.com/llvm/llvm-project/blob/8f833f88ab78265a8e0ebb0d1522771d67c708a9/clang/lib/Sema/SemaDeclCXX.cpp#L11593-L11599)).

```cpp
// Haven't recognized std::initializer_list yet, maybe this is it.
CXXRecordDecl *TemplateClass = Template->getTemplatedDecl();
if (TemplateClass->getIdentifier() !=
        &PP.getIdentifierTable().get("initializer_list") ||
    !getStdNamespace()->InEnclosingNamespaceSetOf(
        TemplateClass->getDeclContext()))
  return false;
```

4. This conditional statement fails in the example because `getStdNamespace()` is a `NamespaceDecl` object created by calling `getOrCreateStdNamespace()` while processing this file, while `TemplateClass`, which comes from deserializing the header module, belongs to the `NamespaceDecl` from the header module. If the virtual private destructor didn't exist, then `getStdNamespace()` would be the `NamespaceDecl` from the deserialized module, and the conditional statement succeeds.

**Comment by zygoloid** [comment]
I think the problem here is that, when trying to merge the imported `std` namespace, we don't find the one implicitly created by `Sema` because it's not in the name lookup table for the translation unit. We could perhaps fix that by adding that `std` namespace to the lookup table, and hiding it from name lookup by instead setting its `IdentifierNamespace` to `0` or otherwise marking it so that regular name lookup doesn't find it. Ideally we'd mark it in such a way that it is still found by redeclaration lookup but not by the lookup performed for uses of the name `std`, so that we can also remove [the special-case code in namespace declaration handling](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaDeclCXX.cpp#L11275) that works around name lookup not finding the implicitly injected namespace `std`.

**Comment by alanzhao1** [comment]
Patch:  https://reviews.llvm.org/D150001

**Comment by alanzhao1** [comment]
Closing as https://reviews.llvm.org/D150001 has been merged.
