### ISSUE TITLE
[regression][LLVM][Passes] Cannot compile llvm/lib/Passes/PassBuilderPipelines.cpp

### ISSUE THREAD

**Issue by pawosm-arm** [llvm/llvm-project#209472]
Cannot compile llvm/lib/Passes/PassBuilderPipelines.cpp today:

```
13:34:26  /workspace/src/llvm/lib/Passes/PassBuilderPipelines.cpp: In member function 'llvm::ModulePassManager llvm::PassBuilder::buildLTODefaultPipeline(llvm::OptimizationLevel, llvm::ModuleSummaryIndex*)':
13:34:26  /workspace/src/llvm/lib/Passes/PassBuilderPipelines.cpp:2248:46: error: request for member 'getSpeedupLevel' in 'Level', which is of non-class type 'llvm::OptimizationLevel'
13:34:26   2248 |     OmaxLPM.addPass(LoopFullUnrollPass(Level.getSpeedupLevel(),
13:34:26        |
```

Looking at the git log and the time where it started to occur, there is a good chance it has been caused by #209424.

**Comment by aengelke** [comment]
Huh? this source line doesn't exist in the file upstream?

**Comment by pawosm-arm** [comment]
@voltur01 seems we have problem.

**Comment by pawosm-arm** [comment]
Closing as downstream issue.
CC @davemgreen and @VladiKrapp-Arm
