### PR TITLE
[llvm-exegesis] Add support for pinning benchmarking process to a CPU

### PR DESCRIPTION
**Pull request by boomanaiden154**
This patch adds in support for pinning a benchmarking process to a specific CPU (in the subprocess benchmarking mode on Linux). This is intended to be used in environments where a certain set of CPUs is isolated from the scheduler using something like cgroups and thus should present less potential for noise than normal. This also opens up the door for doing multithreaded benchmarking as we can now pin benchmarking processes to specific CPUs that we know won't interfere with each other.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
@legrosbuffle bump on this when you get a chance. Thanks!

**Comment by legrosbuffle** [comment]
Why can't we use `taskset llvm-exegesis ...` ? On linux I think chidren inherit the affinity of the parent.

**Comment by boomanaiden154** [comment]
Right, the child will inherit the affinity of the parent, but we don't want the child to have the same affinity as the parent. The main llvm-exegesis process isn't sensitive to the core at all, just running things like the assembler, so doesn't need special affinity. When pinning to a single core that has been set aside using something like `isolcpu` or cgroups, pinning both the main `llvm-exegesis` process and the benchmarking process to the same core will require the scheduler to swap them in and out a couple times, which isn't what is desired. This approach only puts the benchmarking subprocess on a specific core to prevent this issue, at the cost of some complexity.

**Comment by legrosbuffle** [comment]
> both the main `llvm-exegesis` process and the benchmarking process to the same core will require the scheduler to swap them in and out a couple times, which isn't what is desired.

Is this happening in practice, and does it make a significant difference on the output ?

**Comment by boomanaiden154** [comment]
> Is this happening in practice, and does it make a significant difference on the output ?

Yes, at least if the system is doing other things/isn't quiet. The source of https://github.com/llvm/llvm-project/issues/80957 from what I can tell is that the benchmarking process gets swapped in and out, changing the values enough that there is a reasonable probability the reported result is negative. This patch won't fix that issue, but does prevent any potential interference from other processes.

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp [hunk 1]
```diff
@@ -310,6 +321,29 @@ class SubProcessFunctionExecutorImpl
     }
 
     if (ParentOrChildPID == 0) {
+      if (BenchmarkProcessCPU) {
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:324]: [nit] `BenchmarkProcessCPU.has_value()`

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp [hunk 2]
```diff
@@ -310,6 +321,29 @@ class SubProcessFunctionExecutorImpl
...
+        }
+
+        // Check (if assertions are enabled) that we are actually running on the
+        // CPU that was specified by the user.
+        unsigned int CurrentCPU;
+        assert(getcpu(&CurrentCPU, nullptr) == 0 &&
+               "Expected getcpu call to succeed.");
+        assert(static_cast<int>(CurrentCPU) == *BenchmarkProcessCPU &&
+               "Expected current CPU to equal the CPU requested by the user");
+      }
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:345]: Please move this to a separate function.

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp [hunk 3]
```diff
@@ -175,6 +179,7 @@ class InProcessFunctionExecutorImpl : public BenchmarkRunner::FunctionExecutor {
   const LLVMState &State;
   const ExecutableFunction Function;
   BenchmarkRunner::ScratchSpace *const Scratch;
+  const std::optional<int> BenchmarkProcessCPU;
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:182]: Why do we have this member ? It's never read and the feature is not supported in this mode.

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp [hunk 4]
```diff
@@ -577,11 +612,11 @@ BenchmarkRunner::getRunnableConfiguration(
 Expected<std::unique_ptr<BenchmarkRunner::FunctionExecutor>>
 BenchmarkRunner::createFunctionExecutor(
     object::OwningBinary<object::ObjectFile> ObjectFile,
-    const BenchmarkKey &Key) const {
+    const BenchmarkKey &Key, std::optional<int> BenchmarkProcessCPU) const {
   switch (ExecutionMode) {
   case ExecutionModeE::InProcess: {
     auto InProcessExecutorOrErr = InProcessFunctionExecutorImpl::create(
-        State, std::move(ObjectFile), Scratch.get());
+        State, std::move(ObjectFile), Scratch.get(), BenchmarkProcessCPU);
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:619]: Let's check `BenchmarkProcessCPU` before calling `InProcessFunctionExecutorImpl::create` and return an error right away.

File: llvm/tools/llvm-exegesis/llvm-exegesis.cpp [hunk 5]
```diff
@@ -418,8 +423,15 @@ static void runBenchmarkConfigurations(
         std::optional<StringRef> DumpFile;
         if (DumpObjectToDisk.getNumOccurrences())
           DumpFile = DumpObjectToDisk;
+        std::optional<int> BenchmarkCPU = std::nullopt;
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/llvm-exegesis.cpp:426]: After the suggestion above, this can be:
`const std::optional<int> BenchmarkCPU = BenchmarkProcessCPU != -1 ? std::nullopt : std::make_optional(BenchmarkProcessCPU);`

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp [hunk 6]
```diff
@@ -98,21 +98,24 @@ class InProcessFunctionExecutorImpl : public BenchmarkRunner::FunctionExecutor {
...
+        new InProcessFunctionExecutorImpl(State, std::move(*EF), Scratch,
+                                          BenchmarkProcessCPU));
   }
 
 private:
   InProcessFunctionExecutorImpl(const LLVMState &State,
                                 ExecutableFunction Function,
-                                BenchmarkRunner::ScratchSpace *Scratch)
+                                BenchmarkRunner::ScratchSpace *Scratch,
+                                std::optional<int> BenchmarkCPU)
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:118]: you can remove this now

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp [hunk 7]
```diff
@@ -98,21 +98,24 @@ class InProcessFunctionExecutorImpl : public BenchmarkRunner::FunctionExecutor {
 public:
   static Expected<std::unique_ptr<InProcessFunctionExecutorImpl>>
   create(const LLVMState &State, object::OwningBinary<object::ObjectFile> Obj,
-         BenchmarkRunner::ScratchSpace *Scratch) {
+         BenchmarkRunner::ScratchSpace *Scratch,
+         std::optional<int> BenchmarkProcessCPU) {
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:102]: you can remove this now

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp [hunk 8]
```diff
@@ -384,6 +393,31 @@ class SubProcessFunctionExecutorImpl
     return make_error<SnippetSignal>(ChildSignalInfo.si_signo);
   }
 
+  void setCPUAffinityIfRequested() const {
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:396]: [nit] `static void setCPUAffinity(int) {` here, and `if (BenchmarkProcessCPU.has_value()) { setCPUAffinity(*value); }` at the call site.

**Review by legrosbuffle — APPROVED** [review]

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp (hunk 6 above)
Comment (boomanaiden154) [reply llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp]: Thanks for the catch! Removed it as a class member and apparently totally missed it in the constructor.

**Comment by jplehr** [comment]
I believe this broke on of our buildbots: https://lab.llvm.org/staging/#/builders/130/builds/4873

**Comment by mikaelholmen** [comment]
This patch broke trunk for me.
I compile on a RHEL8 machine with clang 15.0.5 and I get
```
../tools/llvm-exegesis/lib/BenchmarkRunner.cpp:416:12: error: use of undeclared identifier 'getcpu'; did you mean 'getcwd'?
    assert(getcpu(&CurrentCPU, nullptr) == 0 &&
           ^~~~~~
           getcwd
/usr/include/assert.h:90:27: note: expanded from macro 'assert'
     (static_cast <bool> (expr)                                         \
                          ^
/usr/include/unistd.h:511:14: note: 'getcwd' declared here
extern char *getcwd (char *__buf, size_t __size) __THROW __wur;
             ^
../tools/llvm-exegesis/lib/BenchmarkRunner.cpp:416:19: error: cannot initialize a parameter of type 'char *' with an rvalue of type 'unsigned int *'
    assert(getcpu(&CurrentCPU, nullptr) == 0 &&
                  ^~~~~~~~~~~
/usr/include/assert.h:90:27: note: expanded from macro 'assert'
     (static_cast <bool> (expr)                                         \
                          ^~~~
/usr/include/unistd.h:511:28: note: passing argument to parameter '__buf' here
extern char *getcwd (char *__buf, size_t __size) __THROW __wur;
                           ^
2 errors generated.
```
Similar to the buildbot failure in the previous comment.

**Comment by steelannelida** [comment]
> This patch broke trunk for me. I compile on a RHEL8 machine with clang 15.0.5 and I get
> 
> ```
> ../tools/llvm-exegesis/lib/BenchmarkRunner.cpp:416:12: error: use of undeclared identifier 'getcpu'; did you mean 'getcwd'?
>     assert(getcpu(&CurrentCPU, nullptr) == 0 &&
>            ^~~~~~
>            getcwd
> /usr/include/assert.h:90:27: note: expanded from macro 'assert'
>      (static_cast <bool> (expr)                                         \
>                           ^
> /usr/include/unistd.h:511:14: note: 'getcwd' declared here
> extern char *getcwd (char *__buf, size_t __size) __THROW __wur;
>              ^
> ../tools/llvm-exegesis/lib/BenchmarkRunner.cpp:416:19: error: cannot initialize a parameter of type 'char *' with an rvalue of type 'unsigned int *'
>     assert(getcpu(&CurrentCPU, nullptr) == 0 &&
>                   ^~~~~~~~~~~
> /usr/include/assert.h:90:27: note: expanded from macro 'assert'
>      (static_cast <bool> (expr)                                         \
>                           ^~~~
> /usr/include/unistd.h:511:28: note: passing argument to parameter '__buf' here
> extern char *getcwd (char *__buf, size_t __size) __THROW __wur;
>                            ^
> 2 errors generated.
> ```
> 
> Similar to the buildbot failure in the previous comment.

Same in our setup. How about reverting this?

**Comment by boomanaiden154** [comment]
I've reverted this for now.
