### ISSUE TITLE
clang: std::sort with std::ref(comparator) using recent libstdc++ fails compilation with "exception specification uses itself"

### ISSUE THREAD

**Issue by avelanarius** [llvm/llvm-project#53049]
#### Original reproducer
The following code fails to compile under Clang 13.0.0 with a recent version of libstdc++: ([godbolt link](https://godbolt.org/z/nPecfeqf9))
```cpp
#include <functional>
#include <vector>
#include <algorithm>

int main() {
    std::function<bool(const int&, const int&)> comp 
        = [](const int& a, const int& b) { return a < b; };

    std::vector<int> vec;
    std::sort(vec.begin(), vec.end(), std::ref(comp)); // Doesn't compile
}
```
With `clang version 13.0.0 (Fedora 13.0.0-3.fc35)` and `libstdc++-devel-11.2.1-7.fc35` it fails to compile with the following error message:
```
In file included from test.cpp:1:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/functional:58:
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/refwrap.h:319:40: error: exception specification of 'function<__gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>, void>' uses itself
                = decltype(reference_wrapper::_S_fun(std::declval<_Up>()))>
                                                     ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/refwrap.h:319:40: note: in instantiation of exception specification for 'function<__gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>, void>' requested here
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/refwrap.h:321:2: note: in instantiation of default argument for 'reference_wrapper<__gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>, void>' required here
        reference_wrapper(_Up&& __uref)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/type_traits:1017:57: note: while substituting deduced template arguments into function template 'reference_wrapper' [with _Up = __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>, $1 = (no value), $2 = (no value)]
      = __bool_constant<__is_nothrow_constructible(_Tp, _Args...)>;
                                                        ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/type_traits:1023:14: note: in instantiation of template type alias '__is_nothrow_constructible_impl' requested here
    : public __is_nothrow_constructible_impl<_Tp, _Args...>::type
             ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/type_traits:153:14: note: in instantiation of template class 'std::is_nothrow_constructible<__gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>>' requested here
    : public conditional<_B1::value, _B2, _B1>::type
             ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:298:11: note: (skipping 7 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
          return __and_<typename _Base::_Local_storage,
                 ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:1917:12: note: in instantiation of function template specialization 'std::__heap_select<__gnu_cxx::__normal_iterator<int *, std::vector<int>>, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>>' requested here
      std::__heap_select(__first, __middle, __last, __comp);
           ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:1933:13: note: in instantiation of function template specialization 'std::__partial_sort<__gnu_cxx::__normal_iterator<int *, std::vector<int>>, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>>' requested here
              std::__partial_sort(__first, __last, __last, __comp);
                   ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:1954:9: note: in instantiation of function template specialization 'std::__introsort_loop<__gnu_cxx::__normal_iterator<int *, std::vector<int>>, long, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>>' requested here
          std::__introsort_loop(__first, __last,
               ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:4875:12: note: in instantiation of function template specialization 'std::__sort<__gnu_cxx::__normal_iterator<int *, std::vector<int>>, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<std::function<bool (const int &, const int &)>>>>' requested here
      std::__sort(__first, __last, __gnu_cxx::__ops::__iter_comp_iter(__comp));
           ^
test.cpp:11:10: note: in instantiation of function template specialization 'std::sort<__gnu_cxx::__normal_iterator<int *, std::vector<int>>, std::reference_wrapper<std::function<bool (const int &, const int &)>>>' requested here
    std::sort(vec.begin(), vec.end(), std::ref(comp)); // Doesn't compile
         ^
1 error generated.
```

The code compiles fine with `g++ (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)` and the same version of libstdc++. With a slightly older version of libstdc++ (`libstdc++-devel-11.2.1-1.fc35`) it compiles fine with both Clang and GCC (bisected the change in libstdc++ to this commit: https://github.com/gcc-mirror/gcc/commit/d38d26be33aba5d4c12429478375a47c474124d2). This particular reproducer compiles fine with libc++.

As I was unsure if this is a libstdc++ bug, I reduced the reproducer further, as described below.

#### First reduced reproducer
With a guide of the error message, I manually reduced the original reproducer. It fails to compile with the same error type and should be representative of the original reproducer. ([godbolt link](https://godbolt.org/z/Kfa7EM86a))

```cpp
#include <functional>
#include <type_traits>

struct item {
    template<typename T>
    item(T& t) 
        noexcept(std::is_copy_constructible<T>::value) {}
};

struct holder {
    holder(std::reference_wrapper<item> ref_item) {}
};

int main() {
    auto val = std::is_copy_constructible<holder>::value; // Fails to compile
}
```

This reproducer variant fails to compile with Clang 9.0.0+ (with libstdc++), Clang 13.0.0+ (with libc++), but compiles fine with all nonarchaic GCC versions. I tested it on godbolt with their respective libstdc++/libc++ version pairing for each Clang release. With Clang 13.0.0 with libc++, this reproducer fails with the following error:
```
In file included from <source>:1:
In file included from /opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/functional:490:
In file included from /opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__algorithm/search.h:15:
In file included from /opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__iterator/iterator_traits.h:14:
In file included from /opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__iterator/incrementable_traits.h:14:
In file included from /opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/concepts:134:
In file included from /opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__functional_base:17:
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__functional/reference_wrapper.h:49:110: error: exception specification of 'item<const holder>' uses itself
    template <class _Up, class = _EnableIf<!__is_same_uncvref<_Up, reference_wrapper>::value, decltype(__fun(declval<_Up>())) >>
                                                                                                             ^
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__functional/reference_wrapper.h:49:110: note: in instantiation of exception specification for 'item<const holder>' requested here
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__functional/reference_wrapper.h:51:5: note: in instantiation of default argument for 'reference_wrapper<const holder &>' required here
    reference_wrapper(_Up&& __u) _NOEXCEPT_(noexcept(__fun(declval<_Up>()))) {
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/type_traits:3174:62: note: while substituting deduced template arguments into function template 'reference_wrapper' [with _Up = const holder &, $1 = (no value)]
    : public integral_constant<bool, __is_constructible(_Tp, _Args...)>
                                                             ^
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/type_traits:3229:14: note: in instantiation of template class 'std::is_constructible<const holder, const holder &>' requested here
    : public is_constructible<_Tp,
             ^
<source>:7:23: note: in instantiation of template class 'std::is_copy_constructible<const holder>' requested here
        noexcept(std::is_copy_constructible<T>::value) {}
                      ^
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__functional/reference_wrapper.h:49:110: note: in instantiation of exception specification for 'item<const holder>' requested here
    template <class _Up, class = _EnableIf<!__is_same_uncvref<_Up, reference_wrapper>::value, decltype(__fun(declval<_Up>())) >>
                                                                                                             ^
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/__functional/reference_wrapper.h:51:5: note: in instantiation of default argument for 'reference_wrapper<const holder &>' required here
    reference_wrapper(_Up&& __u) _NOEXCEPT_(noexcept(__fun(declval<_Up>()))) {
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/type_traits:3174:62: note: while substituting deduced template arguments into function template 'reference_wrapper' [with _Up = const holder &, $1 = (no value)]
    : public integral_constant<bool, __is_constructible(_Tp, _Args...)>
                                                             ^
/opt/compiler-explorer/clang-13.0.0/bin/../include/c++/v1/type_traits:3229:14: note: in instantiation of template class 'std::is_constructible<holder, const holder &>' requested here
    : public is_constructible<_Tp,
             ^
<source>:15:21: note: in instantiation of template class 'std::is_copy_constructible<holder>' requested here
    auto val = std::is_copy_constructible<holder>::value; // Fails to compile
                    ^
1 error generated.
```
#### Second reduced reproducer
Removing the dependency on `std::reference_wrapper` implementation, I constructed the following reproducer. It fails to compile with the same error type and should be representative of the original problem. ([godbolt link](https://godbolt.org/z/cYWoqKsbK))

```cpp
#include <utility>

struct item {
    template<typename T>
    item(T& t) noexcept(std::is_copy_constructible<T>::value) {}
};

struct holder {
    // holder(const holder& h) = default;
        // GCC sees a perfect match
        // and does not try the
        // templated version.

    template<typename T, typename = decltype(item(std::declval<T>()))>
    holder(T& t) {}
};

int main() { 
    auto val = std::is_copy_constructible<holder>::value; // Fails to compile
}
```

This reproducer fails to compile with all versions of Clang, but it compiles with GCC 11.1+.
Clang 13.0.0 error message:
```
<source>:14:46: error: exception specification of 'item<const holder>' uses itself
    template<typename T, typename = decltype(item(std::declval<T>()))>
                                             ^
<source>:14:46: note: in instantiation of exception specification for 'item<const holder>' requested here
<source>:15:5: note: in instantiation of default argument for 'holder<const holder>' required here
    holder(T& t) {}
    ^~~~~~~~~~~~~~~
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/type_traits:906:30: note: while substituting deduced template arguments into function template 'holder' [with T = const holder, $1 = (no value)]
    : public __bool_constant<__is_constructible(_Tp, _Args...)>
                             ^
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/type_traits:936:14: note: in instantiation of template class 'std::__is_constructible_impl<const holder, const holder &>' requested here
    : public __is_constructible_impl<_Tp, const _Tp&>
             ^
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/type_traits:942:14: note: in instantiation of template class 'std::__is_copy_constructible_impl<const holder, true>' requested here
    : public __is_copy_constructible_impl<_Tp>
             ^
<source>:5:30: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    item(T& t) noexcept(std::is_copy_constructible<T>::value) {}
                             ^
<source>:15:5: note: in instantiation of default argument for 'holder<const holder>' required here
    holder(T& t) {}
    ^~~~~~~~~~~~~~~
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/type_traits:906:30: note: while substituting deduced template arguments into function template 'holder' [with T = const holder, $1 = (no value)]
    : public __bool_constant<__is_constructible(_Tp, _Args...)>
                             ^
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/type_traits:936:14: note: in instantiation of template class 'std::__is_constructible_impl<holder, const holder &>' requested here
    : public __is_constructible_impl<_Tp, const _Tp&>
             ^
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/type_traits:942:14: note: in instantiation of template class 'std::__is_copy_constructible_impl<holder, true>' requested here
    : public __is_copy_constructible_impl<_Tp>
             ^
<source>:19:21: note: in instantiation of template class 'std::is_copy_constructible<holder>' requested here
    auto val = std::is_copy_constructible<holder>::value; // Fails to compile
                    ^
1 error generated.
```

Surprisingly, with GCC <= 10.3 it also fails to compile, printing a similar error message:
```
<source>: In substitution of 'template<class T, class> holder::holder(T&) [with T = const holder; <template-parameter-1-2> = <missing>]':
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/type_traits:901:30:   required from 'struct std::__is_constructible_impl<const holder, const holder&>'
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/type_traits:930:12:   required from 'struct std::__is_copy_constructible_impl<const holder, true>'
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/type_traits:936:12:   required from 'struct std::is_copy_constructible<const holder>'
<source>:5:56:   required from 'item::item(T&) [with T = const holder]'
<source>:14:46:   required by substitution of 'template<class T, class> holder::holder(T&) [with T = const holder; <template-parameter-1-2> = <missing>]'
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/type_traits:901:30:   required from 'struct std::__is_constructible_impl<holder, const holder&>'
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/type_traits:930:12:   required from 'struct std::__is_copy_constructible_impl<holder, true>'
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/type_traits:936:12:   required from 'struct std::is_copy_constructible<holder>'
<source>:19:50:   required from here
<source>:5:56: error: exception specification of 'item::item(T&) [with T = const holder]' depends on itself
    5 |     item(T& t) noexcept(std::is_copy_constructible<T>::value) {}
      |                                                        ^~~~~
```

I bisected GCC and they fixed it in this commit: https://github.com/gcc-mirror/gcc/commit/187d0d58 - if GCC sees a non-templated function candidate with all arguments perfect matching (`holder(const holder& h) = default;`), it does not consider the templated candidates (`holder(T& t)`).
