### ISSUE TITLE
Template code failing to compile after f46d146

### ISSUE THREAD

**Issue by dyung** [llvm/llvm-project#94194]
As part of our testing, we build external codebases including the compile-time-regular-expressions codebase (hanickadot/compile-time-regular-expressions). After commit f46d146, the code started to fail to compile with an error:
```
include\ctre\wrapper.hpp:173:27: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  170 |                 return Method::template exec();
      |                                         ^
1 error generated.
```
You can see the sources that are failing to compile at https://github.com/hanickadot/compile-time-regular-expressions/blob/eb9577aae3515d14e6c5564f9aeb046d2e7c1124/include/ctre/wrapper.hpp#L173.

This code compiles correctly with the previous compiler, and is also accepted by gcc. @evelez7 can you verify that this code whether this code is correctly being rejected by the compiler? And if so, how should it be fixed?

**Comment by dyung** [comment]
A smaller reduced example that shows the error is the following code:
```c++
template <typename Method> struct regular_expression {
  void exec() { Method::template exec0; }
};
```
Here is the result of compiling the code:
```
$ ~/src/upstream/458a31562aee703c15224dd9fcde19f67834a8f9-linux/bin/clang -c preproc.cpp
$ ~/src/upstream/f46d1463b835560d90ad3ac02b63c771e4ebe566-linux/bin/clang -c preproc.cpp
preproc.cpp:2:34: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
    2 |   void exec() { Method::template exec0; }
      |                                  ^
1 error generated.
```

**Comment by cor3ntin** [comment]
Clang is correct. The diagnostic can be disabled with `-Wno-missing-template-arg-list-after-template-kw`, but maybe the bug could be fixed in ctre @hanickadot

**Comment by shafik** [comment]
> Clang is correct. The diagnostic can be disabled with `-Wno-missing-template-arg-list-after-template-kw`, but maybe the bug could be fixed in ctre @hanickadot

Yeah, this looks like a gcc/MSVC bug: https://godbolt.org/z/veE6Y8v3a

see https://eel.is/c++draft/temp.names#6 and https://eel.is/c++draft/depr.template.template

**Comment by hanickadot** [comment]
@dyung can you please create an issue for CTRE and I will fix it once I will get back?

**Comment by dyung** [comment]
Thanks everyone for confirming this is an issue with the original source code.

> @dyung can you please create an issue for CTRE and I will fix it once I will get back?

@hanickadot I have filed hanickadot/compile-time-regular-expressions#307 for this issue.
