### PR TITLE
[flang-rt] Use posix_memalign instead of std::aligned_alloc

### PR DESCRIPTION
**Pull request by ceseo**
MallocWrapper called std::aligned_alloc for over-aligned requests, but that C11 function is only available on macOS 10.15 and newer. flang-rt builds with a Darwin deployment target of 10.7 (set in AddFlangRT.cmake), so the build failed under -Werror=unguarded-availability-new.

Use posix_memalign instead, as it is available on all supported POSIX targets.

### CODE REVIEW

**Review by Jason-Van-Beusekom — CHANGES_REQUESTED** [review]
``` bash
llvm-project/flang-rt/include/flang-rt/runtime/allocator-registry.h:39:9: error: use of undeclared identifier 'posix_memalign'
   39 |     if (posix_memalign(&ptr, alignment, size) != 0) {
      |         ^~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
FAILED: runtimes/runtimes-amdgcn-amd-amdhsa-stamps/runtimes-amdgcn-amd-amdhsa-build /llvm-project/build/runtimes/runtimes-amdgcn-amd-amdhsa-stamps/runtimes-amdgcn-amd-amdhsa-build 
cd /llvm-project/build/runtimes/runtimes-amdgcn-amd-amdhsa-bins && /usr/bin/cmake --build .
ninja: build stopped: subcommand failed.
```

amdgcn,  build fails for this. I think the simplest solution would be to just disable this change for amdgcn targets, or just used aligned_alloc for that target

**Comment by eugeneepshteyn** [comment]
> disable this change for amdgcn targets, or just used aligned_alloc for that target

I suspect that a POSIX function may be missing for other GPU targets. My recommendation would be to specialize `posix_memalign()` usage to MacOS only and use the standard function elsewhere.

**Comment by ceseo** [comment]
@eugeneepshteyn Done.

@Jason-Van-Beusekom see if it works on amdgcn now.

**Review by Jason-Van-Beusekom — APPROVED** [review]
LGTM, verified that the build works on amdgcn, thanks for the fix!

**Review by eugeneepshteyn — APPROVED** [review]
LGTM
