### PR TITLE
[lldb] Fix build after FileSpec::GetDirectory() ConstString removal

### PR DESCRIPTION
**Pull request by sylvestre**
FileSpec::GetDirectory() now returns llvm::StringRef instead of ConstString, so the .GetStringRef() call no longer compiles.

Regressed by f9b5264523b1 ("[lldb] Remove ConstString getters from FileSpec", #206802).

failed with
```

/build/source/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleSaver.cpp:276:44: error: no member named 'GetStringRef' in 'llvm::StringRef'
  276 |         path_to_copy_module.GetDirectory().GetStringRef());
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```

### CODE REVIEW

**Review by bulbazord — APPROVED** [review]
Thanks for fixing!
