### PR TITLE
[Clang] only inherit the parent eval context inside of lambdas

### LINKED ISSUE #118000: Call to consteval function in member initializer cause compilation error
If consteval function called in method initializer and this class used in both consteval and not consteval functions, compilation fails with 
```
<source>:4:17: error: cannot take address of consteval function 'baz' outside of an immediate invocation
    int mSize = baz();
```

```c++
consteval int baz() { return 0;}

struct S {
    int mSize = baz();
};

consteval void bar() {
    S s;
}

void foo() {
    S s;
}
```

This bug is present in 16.x.x and >=18.0.0. (https://godbolt.org/z/o6EnWvvW7)

Issue was introduced in https://github.com/llvm/llvm-project/commit/ca619613801233ef2def8c3cc7d311d5ed0033cb
After it was fixed in https://github.com/llvm/llvm-project/commit/467688527017efb611b09c0cbf92f2d3ecdd1724
And happens again after https://github.com/llvm/llvm-project/commit/baf6bd303bd58a521809d456dd9b179636982fc5

### PR DESCRIPTION
**Pull request by cor3ntin**
As we create defaul constructors lazily, we should not inherit from the parent evaluation context.
However, we need to make an exception for lambdas (in particular their conversion operators, which are also implicitly defined).

As a drive-by, we introduce a generic way to query whether a function is a member of a lambda.

This fixes a regression introduced by baf6bd3.

Fixes #118000

### CODE REVIEW

File: clang/include/clang/Sema/Sema.h [hunk 1]
```diff
@@ -13108,14 +13109,16 @@ class Sema final : public SemaBase {
               ? ExpressionEvaluationContext::ImmediateFunctionContext
               : ExpressionEvaluationContext::PotentiallyEvaluated);
       if (FD) {
+        auto &Current = S.currentEvaluationContext(),
+             Parent = S.parentEvaluationContext();
```
Comment (Sirraide) [inline clang/include/clang/Sema/Sema.h:13113]:
```suggestion
        auto &Current = S.currentEvaluationContext();
        auto &Parent = S.parentEvaluationContext();
```
I think this is a bit clearer, because I don’t think you meant to copy the parent evaluation context here, right?

File: clang/include/clang/AST/ASTLambda.h [hunk 2]
```diff
@@ -35,6 +36,12 @@ inline bool isLambdaCallOperator(const DeclContext *DC) {
   return isLambdaCallOperator(cast<CXXMethodDecl>(DC));
 }
 
+inline bool isLambdaMethod(const DeclContext *DC) {
+  if (auto *MD = dyn_cast_or_null<CXXMethodDecl>(DC); MD)
```
Comment (tbaederr) [inline clang/include/clang/AST/ASTLambda.h:40]:
```suggestion
  if (const auto *MD = dyn_cast_if_present<CXXMethodDecl>(DC))
```

**Review by erichkeane — APPROVED** [review]
