### ISSUE TITLE
Overloaded function template instantiation with decltype recurses infinitely

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#20013]
|  |  |
| --- | --- |
| Bugzilla Link | [19639](https://llvm.org/bz19639) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
---- testcase ----
```cpp
struct Number { };

template<typename T1, typename T2>
static int foo(T1&, T2&) { return 1; }

template<typename T1>
static auto foo(T1 &a, int) -> decltype(foo(a, *new Number())) { return foo(a, *new Number()); }

int main() { return foo(*new Number(), 8); }
```
---- error ----
```
testcase.cpp:4:12: fatal error: recursive template instantiation exceeded maximum depth of 256
static int foo(T1&, T2&) { return 1; }
           ^
testcase.cpp:7:13: note: while substituting deduced template arguments into function template 'foo' [with T1 = Number]
```
The code works in g++ 4.8. It also works when declaring an explicit return type.

**Comment by llvmbot** [comment]
@llvm/issue-subscribers-clang-frontend

Author: None (llvmbot)

<details>
|  |  |
| --- | --- |
| Bugzilla Link | [19639](https://llvm.org/bz19639) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 
---- testcase ----
```cpp
struct Number { };

template&lt;typename T1, typename T2&gt;
static int foo(T1&amp;, T2&amp;) { return 1; }

template&lt;typename T1&gt;
static auto foo(T1 &amp;a, int) -&gt; decltype(foo(a, *new Number())) { return foo(a, *new Number()); }

int main() { return foo(*new Number(), 8); }
```
---- error ----
```
testcase.cpp:4:12: fatal error: recursive template instantiation exceeded maximum depth of 256
static int foo(T1&amp;, T2&amp;) { return 1; }
           ^
testcase.cpp:7:13: note: while substituting deduced template arguments into function template 'foo' [with T1 = Number]
```
The code works in g++ 4.8. It also works when declaring an explicit return type.
</details>

**Comment by shafik** [comment]
clang now accepts and implementations agree: https://godbolt.org/z/P96YWsfPK
