### ISSUE TITLE
Cannot create a non-constant pointer to member function error with using-declaration

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#27932]
|  |  |
| --- | --- |
| Bugzilla Link | [27558](https://llvm.org/bz27558) |
| Version | 3.8 |
| OS | Linux |
| Attachments | [Small example to reproduce the issue](https://user-images.githubusercontent.com/60944935/143753429-089eae27-c951-455f-a6a4-2701dcf22c16.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 

Clang 3.8 refuses to provide the member function pointer when the member function was introduced via a using-declaration and its origin has a dependent name.

The attached snippet fails to compile with:
```
member-fn.cpp:11:19: error: cannot create a non-constant pointer to member function
                auto memberfn = &B<Args...>::f;
```
As a workaround the name of the base class can be used to retrieve the member function pointer.

The example compiles with Clang 3.7, GCC 5.3/6 and MSVC++ 12.0.

**Comment by wheatman** [comment]
This code still does not compile with post 18 trunk(d9a9872ec4760762fdc467ef283cea302a3742e5)
https://godbolt.org/z/f5PGre8js

code 
```cpp
template <typename... Args>
struct A
{
	void f() {};
};

template <typename... Args>
struct B : A<Args...>
{
	B() {
		auto memberfn = &B<Args...>::f;
	}
private:
	using A<Args...>::f;
};

int main(int argc, char *argv[])
{
	B<> b;
	return 0;
}

```

clang error
```
<source>:11:19: error: cannot create a non-constant pointer to member function
   11 |                 auto memberfn = &B<Args...>::f;
      |                                 ^~~~~~~~~~~~~~
<source>:19:6: note: in instantiation of member function 'B<>::B' requested here
   19 |         B<> b;
      |             ^
1 error generated.
Compiler returned: 1
```

the code compiles on all of gcc 13.2, msvc 19.38, and EDG 6.6

**Comment by llvmbot** [comment]
@llvm/issue-subscribers-clang-frontend

Author: None (llvmbot)

<details>
|  |  |
| --- | --- |
| Bugzilla Link | [27558](https://llvm.org/bz27558) |
| Version | 3.8 |
| OS | Linux |
| Attachments | [Small example to reproduce the issue](https://user-images.githubusercontent.com/60944935/143753429-089eae27-c951-455f-a6a4-2701dcf22c16.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 


Clang 3.8 refuses to provide the member function pointer when the member function was introduced via a using-declaration and its origin has a dependent name.

The attached snippet fails to compile with:

member-fn.cpp:11:19: error: cannot create a non-constant pointer to member function
                auto memberfn = &amp;B&lt;Args...&gt;::f;

As a workaround the name of the base class can be used to retrieve the member function pointer.

The example compiles with Clang 3.7, GCC 5.3/6 and MSVC++ 12.0.
</details>

**Comment by ldalessa** [comment]
Seems to be resolved in trunk.
