### PR TITLE
Reapply [flang][OpenMP] Avoid early returns, NFC #117231

### PR DESCRIPTION
**Pull request by kparzysz**
Two PRs were merged at the same time: one that modified `maybeApplyToV` function, and shortly afterwards, this (the reverted) one that had the old definition.

During the merge both definitions were retained leading to compilation errors.

Reapply the reverted PR (1a08b15589) with the duplicate removed.

### CODE REVIEW

**Review by kazutakahirata — APPROVED** [review]
LGTM.  This PR builds without a problem.  Thanks!
