### ISSUE TITLE
Fails to build libclc `Could not find a package configuration file provided by "LLVM" with any of`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#59153]
Very recent regression
```
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:44 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/build/source/libclc/build/CMakeFiles/CMakeOutput.log".
ninja: error: loading 'build.ninja': No such file or directory
make[1]: *** [debian/rules:737: debian-libclc-build] Error 1
make[1]: Leaving directory '/build/source'
make: *** [debian/rules:474: binary] Error 2
```

With:
```

cd libclc/build && \
cmake ../ \
-G Ninja \
-DCMAKE_C_COMPILER_LAUNCHER=/opt/sccache/sccache -DCMAKE_CXX_COMPILER_LAUNCHER=/opt/sccache/sccache \
-DCMAKE_C_COMPILER=/build/source/build-llvm/tools/clang/stage2-bins/bin/clang \
-DCMAKE_CXX_COMPILER=/build/source/build-llvm/tools/clang/stage2-bins/bin/clang++ \
-DCMAKE_C_FLAGS="-O2 -DNDEBUG -g1 -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2" \
-DCMAKE_CXX_FLAGS="-O2 -DNDEBUG -g1 -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2" \
-DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id -L/build/source/build-llvm/tools/clang/stage2-bins/lib" \
-DCMAKE_MODULE_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id -L/build/source/build-llvm/tools/clang/stage2-bins/lib" \
-DCMAKE_EXE_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id -L/build/source/build-llvm/tools/clang/stage2-bins/lib" \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCMAKE_INSTALL_DATADIR=lib \
-DCMAKE_INSTALL_INCLUDEDIR=include \
-DLLVM_CONFIG=/build/source/build-llvm/tools/clang/stage2-bins/bin/llvm-config \
 \
-DLIBCLC_TARGETS_TO_BUILD="amdgcn--;amdgcn--amdhsa;amdgcn-mesa-mesa3d;r600--;nvptx--;nvptx64--;nvptx--nvidiacl;nvptx64--nvidiacl"; \
ninja -j 32 -v
-- The CXX compiler identification is Clang 16.0.0
-- The C compiler identification is Clang 16.0.0
-- Check for working CXX compiler: /build/source/build-llvm/tools/clang/stage2-bins/bin/clang++
-- Check for working CXX compiler: /build/source/build-llvm/tools/clang/stage2-bins/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /build/source/build-llvm/tools/clang/stage2-bins/bin/clang
-- Check for working C compiler: /build/source/build-llvm/tools/clang/stage2-bins/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
```

**Comment by svenvh** [comment]
Could that be due to https://reviews.llvm.org/D137854 ?

**Comment by sylvestre** [comment]
Looks like it
cc @tstellar  @mgorny

**Comment by mgorny** [comment]
Well, obviously `LLVM_CONFIG` isn't going to work anymore. You can either use `LLVM_CMAKE_DIR` or just put the `bin` directory on `PATH`, and CMake will find cmakedir relative to the it.

**Comment by sylvestre** [comment]
@mgorny I replaced it by

`-DLLVM_CMAKE_DIR=/build/llvm-toolchain-snapshot-16~++20221124045322+a6eb76f57c4a/build-llvm/tools/clang/stage2-bins/bin \`

but still fail with:

```

-- Detecting C compile features - done
CMake Error at CMakeLists.txt:44 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/build/llvm-toolchain-snapshot-16~++20221124045322+a6eb76f57c4a/libclc/build/CMakeFiles/CMakeOutput.log".
ninja: error: loading 'build.ninja': No such file or directory
```

Am I doing something wrong ?

**Comment by mgorny** [comment]
Try pointing it to `stage2-bins`, without `/bin`.

**Comment by sylvestre** [comment]
oh, thanks

**Comment by sylvestre** [comment]
It causes some errors later:
```

"/build/llvm-toolchain-snapshot-16~++20221124053739+34b4672f92d2/build-llvm/tools/clang/stage2-bins/bin/clang++" -DHAVE_LLVM=0x1600 -I"/build/llvm-toolchain-snapshot-16~++20221124053739+34b4672f92d2/build-llvm/tools/clang/stage2-bins/include" -O2 -DNDEBUG -g1 -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2  -fno-exceptions -fno-rtti -fno-exceptions -MD -MT CMakeFiles/prepare_builtins.dir/utils/prepare-builtins.cpp.o -MF CMakeFiles/prepare_builtins.dir/utils/prepare-builtins.cpp.o.d -o CMakeFiles/prepare_builtins.dir/utils/prepare-builtins.cpp.o -c '/build/llvm-toolchain-snapshot-16~++20221124053739+34b4672f92d2/libclc/utils/prepare-builtins.cpp'
/build/llvm-toolchain-snapshot-16~++20221124053739+34b4672f92d2/libclc/utils/prepare-builtins.cpp:2:10: fatal error: 'llvm/Bitcode/BitcodeReader.h' file not found
#include "llvm/Bitcode/BitcodeReader.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by mgorny** [comment]
Does `/build/llvm-toolchain-snapshot-16~++20221124053739+34b4672f92d2/build-llvm/tools/clang/stage2-bins/include` contain the needed header?

**Comment by sylvestre** [comment]
@mgorny no, `find build-llvm/tools/clang/stage2-bins/ -iname BitcodeReader.h `
returns nothing

**Comment by sylvestre** [comment]
The file is only in ./llvm/include/llvm/Bitcode/BitcodeReader.h

**Comment by mgorny** [comment]
Hmm, so `stage2-bins` are a build tree and not an install tree? I suppose the easiest way would be to install it into a prefix then, and use that. Not sure if it's possible to build against build tree anymore.

**Comment by sylvestre** [comment]
yeah, libclc is built separately than the rest of llvm/clang.
