### ISSUE TITLE
clang fails to build with gcc 6 on Debian stretch with `expected primary-expression before '>' token`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#55626]
I am well aware that both Debian stretch and gcc 6 aren't supported anymore but filling to have a trace (and share a workaround once I have one)

```
/usr/bin/g++-6  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/lib/AST -I"/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST" -I"/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/include" -Itools/clang/include -Iinclude -I"/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/llvm/include" -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -no-canonical-prefixes -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG    -fno-exceptions -std=c++14 -MD -MT tools/clang/lib/AST/CMakeFiles/obj.clangAST.dir/Interp/ByteCodeExprGen.cpp.o -MF tools/clang/lib/AST/CMakeFiles/obj.clangAST.dir/Interp/ByteCodeExprGen.cpp.o.d -o tools/clang/lib/AST/CMakeFiles/obj.clangAST.dir/Interp/ByteCodeExprGen.cpp.o -c '/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp'
/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp: In member function 'const clang::RecordType* clang::interp::ByteCodeExprGen<Emitter>::getRecordTy(clang::QualType)':
/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp:500:50: error: expected primary-expression before '>' token
     return PT->getPointeeType()->getAs<RecordType>();
                                                  ^
```

**Comment by sylvestre** [comment]
it was working May 9th revision 8a92c45e07dc

**Comment by sylvestre** [comment]
git bisect told me that the issue has ben introduced by f156b51aecc676a9051136f6f5cb74e37dd574d1

**Comment by bzcheeseman** [comment]
I'm not sure what could be causing that problem. I assume gcc-6 has C++14 support? I looked at that code and I'm honestly not sure what could be going on other than maybe auto is being deduced incorrectly somehow? I don't have a gcc-6 build setup to repro with.

**Comment by sylvestre** [comment]
it seems it does:
https://gcc.gnu.org/gcc-6/changes.html
but gcc 6 might just have bugs too :)

**Comment by sylvestre** [comment]
Any recommendation on how to do this ? :)

**Comment by sylvestre** [comment]
@bzcheeseman
I see

```
 /root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp: In instantiation of 'const clang::RecordType* clang::interp::ByteCodeExprGen<Emitter>::getRecordTy(clang::QualType) [with Emitter = clang::interp::ByteCodeEmitter]':
/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp:579:16:   required from here
/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp:501:28: error: 'nothing' is not a member of 'const clang::PointerType*'
     bool x = decltype(PT)::nothing;
                            ^~~~~~~
```

With:
```
template <class Emitter>
const RecordType *ByteCodeExprGen<Emitter>::getRecordTy(QualType Ty) {
  if (auto *PT = dyn_cast<PointerType>(Ty))
{
    bool x = decltype(PT)::nothing;
    return PT->getPointeeType()->getAs<RecordType>();
}

```

And:
```
/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp: In instantiation of 'const clang::RecordType* clang::interp::ByteCodeExprGen<Emitter>::getRecordTy(clang::QualType) [with Emitter = clang::interp::ByteCodeEmitter]':
/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp:579:16:   required from here
/root/llvm-toolchain-snapshot-15~++20220520102608+59726668f1dc/clang/lib/AST/Interp/ByteCodeExprGen.cpp:501:46: error: 'nothing' is not a member of 'clang::QualType'
     bool x = decltype(PT->getPointeeType())::nothing;
                                              ^~~~~~~

```
with:
```
template <class Emitter>
const RecordType *ByteCodeExprGen<Emitter>::getRecordTy(QualType Ty) {
  if (auto *PT = dyn_cast<PointerType>(Ty))
{
    bool x = decltype(PT->getPointeeType())::nothing;
    return PT->getPointeeType()->getAs<RecordType>();
}

```

**Comment by bzcheeseman** [comment]
Alright that's good at least - now the question is: "is `getAs` defined on QualType and are we calling it correctly?"

**Comment by sunho** [comment]
I'm also getting this compilation error in GCC 7.1.0.

**Comment by bzcheeseman** [comment]
I do believe we have builders that check if LLVM builds with GCC and they haven't reported the issue as far as I know, can you share the exact compilation line that's failing?

**Comment by sunho** [comment]
It's the exact same line as the original issue. `return PT->getPointeeType()->getAs<RecordType>();`

**Comment by bzcheeseman** [comment]
Sure; what I'm trying to ascertain is whether the compiler actually being called is gcc-7 or gcc-6 - you said your system compiler is gcc-6 but the env variable is gcc-7. If it's the exact same bug I'd guess it's on gcc-6 by accident.

**Comment by sunho** [comment]
Changing auto to llvm::CastInfo<clang::PointerType, const clang::Type*, void>::CastReturnType is a viable workaround. As for my setup, I think it's just using gcc-6 for some weird reason.

**Comment by sylvestre** [comment]
Maybe we should update the upstream code with this workaround?
While we don't support gcc 6 officially anymore, it is the main (only?) issue with gcc-6?

**Comment by sunho** [comment]
Yeah if I do that workaround gcc-6 seems to work out of shelf. No special flag is even needed.

**Comment by bzcheeseman** [comment]
So to be clear, the auto that is changed is this one?

```if (auto *PT = dyn_cast<PointerType>(Ty))```

That makes me a little nervous because the CastReturnType `using` declaration is not part of the CastInfo contract, so there's no guarantee that will continue to be there in the future.

**Comment by sunho** [comment]
Yes it's that auto. I might be good if you can figure out a clean way to solve it if there exists.

**Comment by bzcheeseman** [comment]
Does just using `PointerType` not work here? That's what it's being casted to

**Comment by sunho** [comment]
Nope. Here are the error messages I got:
```
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp: In member function 'const clang::RecordType* clang::interp::ByteCodeExprGen<Emitter>::getRecordTy(clang::QualType)':
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:500:14: error: base operand of '->' has non-pointer type 'clang::PointerType'
     return PT->getPointeeType()->getAs<RecordType>();
              ^~
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:500:50: error: expected primary-expression before '>' token
     return PT->getPointeeType()->getAs<RecordType>();
                                                  ^
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:500:52: error: expected primary-expression before ')' token
     return PT->getPointeeType()->getAs<RecordType>();
                                                    ^
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp: In instantiation of 'const clang::RecordType* clang::interp::ByteCodeExprGen<Emitter>::getRecordTy(clang::QualType) [with Emitter = clang::interp::ByteCodeEmitter]':
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:576:16:   required from here
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:499:45: error: conversion from 'llvm::CastInfo<clang::PointerType, const clang::Type*, void>::CastReturnType {aka const clang::PointerType*}' to non-scalar type 'clang::PointerType' requested
   if (PointerType PT = dyn_cast<PointerType>(Ty))
                        ~~~~~~~~~~~~~~~~~~~~~^~~~
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:499:3: error: could not convert 'PT' from 'clang::PointerType' to 'bool'
   if (PointerType PT = dyn_cast<PointerType>(Ty))
   ^~
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp: In instantiation of 'const clang::RecordType* clang::interp::ByteCodeExprGen<Emitter>::getRecordTy(clang::QualType) [with Emitter = clang::interp::EvalEmitter]':
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:577:16:   required from here
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:499:45: error: conversion from 'llvm::CastInfo<clang::PointerType, const clang::Type*, void>::CastReturnType {aka const clang::PointerType*}' to non-scalar type 'clang::PointerType' requested
   if (PointerType PT = dyn_cast<PointerType>(Ty))
                        ~~~~~~~~~~~~~~~~~~~~~^~~~
/home/llvmguest/dvyukov/llvm-project/clang/lib/AST/Interp/ByteCodeExprGen.cpp:499:3: error: could not convert 'PT' from 'clang::PointerType' to 'bool'
   if (PointerType PT = dyn_cast<PointerType>(Ty))
```

**Comment by sunho** [comment]
PointerType* also doesn't work too

**Comment by sunho** [comment]
Oh const PointerType* works.

**Comment by sunho** [comment]
I've posted a patch https://reviews.llvm.org/D129049

**Comment by sunho** [comment]
Commited. @sylvestre Can you confirm again it works?

**Comment by sylvestre** [comment]
I restarted a build to test this
thanks

**Comment by bzcheeseman** [comment]
Thanks folks :)

**Comment by sylvestre** [comment]
Confirmed, issue fixed! thanks
