### ISSUE TITLE
flang runtime build error on FreeBSD x86

### ISSUE THREAD

**Issue by VoxSciurorum** [llvm/llvm-project#57965]
Revision a707675dbba9ca3ec6e668f86fea2240a85ca171 enables 128 bit float unconditionally when compiling with recent versions of clang.  This breaks my build on FreeBSD 13.1 (x86) because 128 bit float support is not enabled for FreeBSD.

```
[ 87%] Building CXX object tools/flang/lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Numeric.cpp.o
In file included from /data/llvm/llvm-dev/flang/lib/Optimizer/Builder/Runtime/Numeric.cpp:15:
In file included from /data/llvm/llvm-dev/flang/include/flang/Runtime/numeric.h:15:
/data/llvm/llvm-dev/flang/include/flang/Runtime/cpp-type.h:55:25: error: __float128 is not supported on this target
using CppFloat128Type = __float128;
                        ^
```

There is a feature test macro `__FLOAT128__` that could be used instead of or in addition to testing compiler versions.
