### ISSUE TITLE
[OpenMP] linker failure when std::complex is used in kernels with amdgpu

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#60191]
The issue only appears on AMD only. first bad commit 572a757fa78722fddeb9b651120607f8eee5d13f.
```
commit 572a757fa78722fddeb9b651120607f8eee5d13f (refs/bisect/bad)
Author: Alexandros Lamprineas <alexandros.lamprineas@arm.com>
Date:   Wed Jan 11 11:50:32 2023 +0000

    [IPSCCP] Enable specialization of functions.
    
    Re-enable the optimization after having fixed the compilation error
    found in SPEC/CINT2017rate/502.gcc_r when both LTO and PGO are in use
    (see https://reviews.llvm.org/D141474).
    
    Differential Revision: https://reviews.llvm.org/D140210
```
It is also possible this commit just exposed a bug.

Reproducer
```console
$ git clone https://github.com/QMCPACK/qmcpack.git
$ mkdir qmcpack/build_clang_offload_cplx; cd qmcpack/build_clang_offload_cplx
$ cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DQMC_MPI=OFF -DENABLE_OFFLOAD=ON -DOFFLOAD_TARGET=amdgcn-amd-amdhsa -DOFFLOAD_ARCH=gfx90a -DQMC_COMPLEX=ON ..
$ make -j32 test_wavefunction_sposet
clang-linker-wrapper: /home/yeluo/opt/llvm-clang/llvm-project/llvm/lib/Analysis/InlineCost.cpp:2617: llvm::InlineResult {anonymous}::CallAnalyzer::analyze(): Assertion `CAI != CandidateCall.arg_end()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /soft/llvm/master-nightly/bin/clang-linker-wrapper --host-triple=x86_64-unknown-linux-gnu --linker-path=/usr/bin/ld -- -pie -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o test_wavefunction_sposet /usr/lib/x86_64-linux-gnu/Scrt1.o /usr/lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/9/crtfastmath.o -L/soft/llvm/main-20230121/bin/../lib/x86_64-unknown-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/lib -L/usr/lib CMakeFiles/test_wavefunction_sposet.dir/test_spo_collection_input_spline.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_spo_collection_input_LCAO_xml.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_spo_collection_input_MSD_LCAO_h5.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_einset.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_einset_spinor.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_CompositeSPOSet.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_hybridrep.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_pw.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_pyscf_complex_MO.cpp.o CMakeFiles/test_wavefunction_sposet.dir/test_MO_spinor.cpp.o -rpath /soft/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/openblas-0.3.20-bce4367eljcnzafqnnnew7ob27b3645t/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial:/soft/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/fftw-3.3.10-f3d2ekpr3qoethtjkmwog5n72g3yhack/lib ../../Message/libcatch_main.a ../libqmcwfs.a ../libqmcwfs_omptarget.a ../../Particle/libqmcparticle_omptarget.a ../../Platforms/libplatform_runtime.a ../../Utilities/for_testing/libutilities_for_test.a ../../Containers/tests/libcontainer_testing.a ../../Platforms/OMPTarget/libplatform_omptarget_LA.a ../../Particle/libqmcparticle.a ../../Particle/libqmcparticle_omptarget.a ../../Utilities/libqmcutil.a ../../Utilities/libqmcrng.a ../../Platforms/CPU/libplatform_cpu_LA.a /soft/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/openblas-0.3.20-bce4367eljcnzafqnnnew7ob27b3645t/lib/libopenblas.so -lm -ldl ../../Numerics/libqmcnumerics.a ../../io/hdf/libqmcio_hdf.a ../../Message/libmessage.a /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libsz.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libdl.so -lm ../../io/OhmmsData/libqmcio_xml.a ../../Utilities/libcxx_helpers.a /usr/lib/x86_64-linux-gnu/libxml2.so ../../einspline/libeinspline.a /soft/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/fftw-3.3.10-f3d2ekpr3qoethtjkmwog5n72g3yhack/lib/libfftw3.so ../../Utilities/for_testing/libutilities_for_test.a ../../Containers/libcontainers.a ../../Platforms/libplatform_runtime.a ../../Platforms/Host/libplatform_host_runtime.a ../../Platforms/OMPTarget/libplatform_omptarget_runtime.a -lstdc++ -lm -lomp -lomptarget -rpath /soft/llvm/main-20230121/lib -L/soft/llvm/main-20230121/lib -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/x86_64-linux-gnu/crtn.o
 #0 0x00005606cfcceccf llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x165accf)
 #1 0x00005606cfccc954 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f5b7729c420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f5b76d3900b raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #4 0x00007f5b76d18859 abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81:7
 #5 0x00007f5b76d18729 get_sysdep_segment_value /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:509:8
 #6 0x00007f5b76d18729 _nl_load_domain /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:970:34
 #7 0x00007f5b76d29fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x00005606d12a6631 (anonymous namespace)::CallAnalyzer::analyze() (.part.0) InlineCost.cpp:0:0
 #9 0x00005606d12a6cf5 llvm::getInlineCost(llvm::CallBase&, llvm::Function*, llvm::InlineParams const&, llvm::TargetTransformInfo&, llvm::function_ref<llvm::AssumptionCache& (llvm::Function&)>, llvm::function_ref<llvm::TargetLibraryInfo const& (llvm::Function&)>, llvm::function_ref<llvm::BlockFrequencyInfo& (llvm::Function&)>, llvm::ProfileSummaryInfo*, llvm::OptimizationRemarkEmitter*) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x2c32cf5)
#10 0x00005606d0a9012d llvm::FunctionSpecializer::getSpecializationBonus(llvm::Argument*, llvm::Constant*, llvm::LoopInfo const&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x241c12d)
#11 0x00005606d0a96b6f llvm::FunctionSpecializer::findSpecializations(llvm::Function*, llvm::InstructionCost, llvm::SmallVectorImpl<llvm::Spec>&, llvm::DenseMap<llvm::Function*, std::pair<unsigned int, unsigned int>, llvm::DenseMapInfo<llvm::Function*, void>, llvm::detail::DenseMapPair<llvm::Function*, std::pair<unsigned int, unsigned int>>>&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x2422b6f)
#12 0x00005606d0a97364 llvm::FunctionSpecializer::run() (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x2423364)
#13 0x00005606d0a6bd3b runIPSCCP(llvm::Module&, llvm::DataLayout const&, llvm::AnalysisManager<llvm::Function>*, std::function<llvm::TargetLibraryInfo const& (llvm::Function&)>, std::function<llvm::TargetTransformInfo& (llvm::Function&)>, std::function<llvm::AssumptionCache& (llvm::Function&)>, llvm::function_ref<llvm::AnalysisResultsForFn (llvm::Function&)>, bool) SCCP.cpp:0:0
#14 0x00005606d0a6d6f3 llvm::IPSCCPPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x23f96f3)
#15 0x00005606cfb612c6 llvm::detail::PassModel<llvm::Module, llvm::IPSCCPPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x14ed2c6)
#16 0x00005606d025b3ae runNewPMPasses(llvm::lto::Config const&, llvm::Module&, llvm::TargetMachine*, unsigned int, bool, llvm::ModuleSummaryIndex*, llvm::ModuleSummaryIndex const*) LTOBackend.cpp:0:0
#17 0x00005606d025da78 llvm::lto::opt(llvm::lto::Config const&, llvm::TargetMachine*, unsigned int, llvm::Module&, bool, llvm::ModuleSummaryIndex*, llvm::ModuleSummaryIndex const*, std::vector<unsigned char, std::allocator<unsigned char>> const&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x1be9a78)
#18 0x00005606d025ea84 llvm::lto::backend(llvm::lto::Config const&, std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x1beaa84)
#19 0x00005606d0253cc3 llvm::lto::LTO::runRegularLTO(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x1bdfcc3)
#20 0x00005606d02542e5 llvm::lto::LTO::run(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, std::function<llvm::Expected<std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>> (unsigned int, llvm::StringRef, llvm::Twine const&)>) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x1be02e5)
#21 0x00005606ceb88046 (anonymous namespace)::linkBitcodeFiles(llvm::SmallVectorImpl<llvm::object::OffloadFile>&, llvm::SmallVectorImpl<llvm::StringRef>&, llvm::opt::ArgList const&) (.constprop.0) ClangLinkerWrapper.cpp:0:0
#22 0x00005606ceb8beba llvm::Error (anonymous namespace)::linkAndWrapDeviceFiles(llvm::SmallVectorImpl<llvm::object::OffloadFile>&, llvm::opt::InputArgList const&, char**, int)::'lambda'(auto&)::operator()<llvm::SmallVector<llvm::object::OffloadFile, 3u>>(auto&) const ClangLinkerWrapper.cpp:0:0
#23 0x00005606ceb915ef (anonymous namespace)::linkAndWrapDeviceFiles(llvm::SmallVectorImpl<llvm::object::OffloadFile>&, llvm::opt::InputArgList const&, char**, int) ClangLinkerWrapper.cpp:0:0
#24 0x00005606ceae205c main (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x46e05c)
#25 0x00007f5b76d1a083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#26 0x00005606ceb7990e _start (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x50590e)
 #0 0x00005606cfcceccf llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x165accf)
 #1 0x00005606cfccc954 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f5b7729c420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f5b76d3900b raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #4 0x00007f5b76d18859 abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81:7
 #5 0x00007f5b76d18729 get_sysdep_segment_value /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:509:8
 #6 0x00007f5b76d18729 _nl_load_domain /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:970:34
 #7 0x00007f5b76d29fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x00005606d12a6631 (anonymous namespace)::CallAnalyzer::analyze() (.part.0) InlineCost.cpp:0:0
 #9 0x00005606d12a6cf5 llvm::getInlineCost(llvm::CallBase&, llvm::Function*, llvm::InlineParams const&, llvm::TargetTransformInfo&, llvm::function_ref<llvm::AssumptionCache& (llvm::Function&)>, llvm::function_ref<llvm::TargetLibraryInfo const& (llvm::Function&)>, llvm::function_ref<llvm::BlockFrequencyInfo& (llvm::Function&)>, llvm::ProfileSummaryInfo*, llvm::OptimizationRemarkEmitter*) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x2c32cf5)
#10 0x00005606d0a9012d llvm::FunctionSpecializer::getSpecializationBonus(llvm::Argument*, llvm::Constant*, llvm::LoopInfo const&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x241c12d)
#11 0x00005606d0a96b6f llvm::FunctionSpecializer::findSpecializations(llvm::Function*, llvm::InstructionCost, llvm::SmallVectorImpl<llvm::Spec>&, llvm::DenseMap<llvm::Function*, std::pair<unsigned int, unsigned int>, llvm::DenseMapInfo<llvm::Function*, void>, llvm::detail::DenseMapPair<llvm::Function*, std::pair<unsigned int, unsigned int>>>&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x2422b6f)
#12 0x00005606d0a97364 llvm::FunctionSpecializer::run() (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x2423364)
#13 0x00005606d0a6bd3b runIPSCCP(llvm::Module&, llvm::DataLayout const&, llvm::AnalysisManager<llvm::Function>*, std::function<llvm::TargetLibraryInfo const& (llvm::Function&)>, std::function<llvm::TargetTransformInfo& (llvm::Function&)>, std::function<llvm::AssumptionCache& (llvm::Function&)>, llvm::function_ref<llvm::AnalysisResultsForFn (llvm::Function&)>, bool) SCCP.cpp:0:0
#14 0x00005606d0a6d6f3 llvm::IPSCCPPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x23f96f3)
#15 0x00005606cfb612c6 llvm::detail::PassModel<llvm::Module, llvm::IPSCCPPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x14ed2c6)
#16 0x00005606d025b3ae runNewPMPasses(llvm::lto::Config const&, llvm::Module&, llvm::TargetMachine*, unsigned int, bool, llvm::ModuleSummaryIndex*, llvm::ModuleSummaryIndex const*) LTOBackend.cpp:0:0
#17 0x00005606d025da78 llvm::lto::opt(llvm::lto::Config const&, llvm::TargetMachine*, unsigned int, llvm::Module&, bool, llvm::ModuleSummaryIndex*, llvm::ModuleSummaryIndex const*, std::vector<unsigned char, std::allocator<unsigned char>> const&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x1be9a78)
#18 0x00005606d025ea84 llvm::lto::backend(llvm::lto::Config const&, std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex&) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x1beaa84)
#19 0x00005606d0253cc3 llvm::lto::LTO::runRegularLTO(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x1bdfcc3)
#20 0x00005606d02542e5 llvm::lto::LTO::run(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, std::function<llvm::Expected<std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>> (unsigned int, llvm::StringRef, llvm::Twine const&)>) (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x1be02e5)
#21 0x00005606ceb88046 (anonymous namespace)::linkBitcodeFiles(llvm::SmallVectorImpl<llvm::object::OffloadFile>&, llvm::SmallVectorImpl<llvm::StringRef>&, llvm::opt::ArgList const&) (.constprop.0) ClangLinkerWrapper.cpp:0:0
#22 0x00005606ceb8beba llvm::Error (anonymous namespace)::linkAndWrapDeviceFiles(llvm::SmallVectorImpl<llvm::object::OffloadFile>&, llvm::opt::InputArgList const&, char**, int)::'lambda'(auto&)::operator()<llvm::SmallVector<llvm::object::OffloadFile, 3u>>(auto&) const ClangLinkerWrapper.cpp:0:0
#23 0x00005606ceb915ef (anonymous namespace)::linkAndWrapDeviceFiles(llvm::SmallVectorImpl<llvm::object::OffloadFile>&, llvm::opt::InputArgList const&, char**, int) ClangLinkerWrapper.cpp:0:0
#24 0x00005606ceae205c main (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x46e05c)
#25 0x00007f5b76d1a083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#26 0x00005606ceb7990e _start (/soft/llvm/master-nightly/bin/clang-linker-wrapper+0x50590e)
clang-16: error: unable to execute command: Aborted (core dumped)
clang-16: error: linker command failed due to signal (use -v to see invocation)
```
When setting `-DQMC_COMPLEX=OFF`, this issue goes away.

**Comment by jhuber6** [comment]
I don't think this is a linker error per-se since it's happening in the LTO phase. it should be reproducible in IR. Maybe we can get the temporary file and `llvm-reduce` on it and pass it on to @labrinea or similar.

**Comment by jhuber6** [comment]
@labrinea here is a reproducer I reduced https://godbolt.org/z/vr6nYrx6Y. With https://github.com/llvm/llvm-project/commit/572a757fa78722fddeb9b651120607f8eee5d13f reverted, or with assertions disabled, it reduces to an `unreachable`.

**Comment by davemgreen** [comment]
There are calls in that function with both 7 and 8 args:
```
call void %0(ptr null, ptr null, ptr %15, ptr %16, ptr %17, ptr %18, ptr %19)
..
call void %0(ptr %12, ptr %13, ptr %21, ptr %22, ptr %23, ptr %24, ptr %25, ptr %26)
```
I'm not sure how valid that is, or how it was produced, but we would probably want to disable functional specialization in that case to prevent it hitting the assert.

**Comment by jhuber6** [comment]
> There are calls in that function with both 7 and 8 args:
> 
> ```
> call void %0(ptr null, ptr null, ptr %15, ptr %16, ptr %17, ptr %18, ptr %19)
> ..
> call void %0(ptr %12, ptr %13, ptr %21, ptr %22, ptr %23, ptr %24, ptr %25, ptr %26)
> ```
> 
> I'm not sure how valid that is, or how it was produced, but we would probably want to disable functional specialization in that case to prevent it hitting the assert.

The code was generated via `llvm-reduce` from the above QMCPACK program, so it's just a minimal reproducer that hits the assertion. It's not likely to have any semantic significance. We have a parallel outlined function in the OpenMP that will be called with different arguments, most likely where it came from. That seems like a reasonable fix, as this doesn't seem to be a problem without assertions on.

**Comment by davidbolvansky** [comment]
>> We have a parallel outlined function in the OpenMP that will be called with different arguments

is this allowed and documented somewhere (langref?)

**Comment by jhuber6** [comment]
> is this allowed and documented somewhere (langref?)

The only document I know of for that is an old PDF that I'm pretty sure is a dead link now. Suffice it to say, when we create a parallel region in OpenMP, we outline the region into a separate function and pass it to the runtime. The runtime then uses that function pointer to call into the outlined parallel region with some number of arguments. I'm assuming it looks weirder because this is a minimal reproducer with all semantic relevance removed.

**Comment by jdoerfert** [comment]
> There are calls in that function with both 7 and 8 args:
> 
> ```
> call void %0(ptr null, ptr null, ptr %15, ptr %16, ptr %17, ptr %18, ptr %19)
> ..
> call void %0(ptr %12, ptr %13, ptr %21, ptr %22, ptr %23, ptr %24, ptr %25, ptr %26)
> ```
> 
> I'm not sure how valid that is, or how it was produced, but we would probably want to disable functional specialization in that case to prevent it hitting the assert.

This is valid IR. Even if they would be executed together, which they are not, this was valid IR.
The analysis should not crash on valid IR.


> > > We have a parallel outlined function in the OpenMP that will be called with different arguments
> 
> is this allowed and documented somewhere (langref?)

This is regular IR. Nothing in the Langref says you can't do this. Forget OpenMP, this is really just basic indirection.

Here is the C example which might help:

```c
void func(void (*f)(...), int N, int *A) {
  switch (N) {
  case 2:
     return f(A[0], A[1]);
  case 1:
     return f(A[0]);
  case 0:
     return f();
  };
}
void f2(int, int);
void f1(int);
void f(void);
void caller() {
  int A[2] = {1,2};
  func(f0, 0, NULL);
  func(f1, 1, &A[0]);
  func(f2, 2, &A[0]);
}
```

**Comment by labrinea** [comment]
Hi, thanks for bringing this to my attention. I'll try understand what's going on and fix it.

**Comment by labrinea** [comment]
Patch for review https://reviews.llvm.org/D142444

**Comment by labrinea** [comment]
The above patch has landed. I am closing the issue.

**Comment by jhuber6** [comment]
> The above patch has landed. I am closing the issue.

For future reference, if you put the number or a link to the issue in the commit it will close automatically once committed. E.g.
```
Fixes #60191
```
