### ISSUE TITLE
Building LLVM fails with older versions of VC++ compiler after adding /permissive- switch in df6291a6

### ISSUE THREAD

**Issue by dyung** [llvm/llvm-project#56173]
We hit an issue internally where our Windows build bots were suddenly failing to build LLVM which I bisected back to be caused by df6291a666d3be784e2bbd00e4dbcdcceaf0196f.

According to the LLVM documentation at https://llvm.org/docs/GettingStarted.html, the minimum required toolchain for building using Visual Studio is Visual Studio 2019 16.7. According to wikipedia, Visual Studio 2019 16.7 corresponds to the 19.27 version of the Visual C++ compiler. The version installed on our build machines is 19.28.29915.0, which should be a supported version of Visual C++. However, when we attempt to build LLVM with the newly added `/permissive-` switch, we get many errors similar to the following:
```
C:\src\upstream\llvm_clean_git\clang\include\clang/Basic/Sanitizers.def(41,1): error C2131: expression did not evaluate to a constant [C:\src\upstream\df6291a666d3-PS4-Release\tools\clang\lib\Basic\obj.clangBasic.vcxproj]
C:\src\upstream\llvm_clean_git\clang\include\clang/Basic/Sanitizers.def(41,1): message : failure was caused by call of undefined function or one not declared 'constexpr' [C:\src\upstream\df6291a666d3-PS4-Release\tools\clang\lib\Basic\obj.clangBasic.vcxproj]
C:\src\upstream\llvm_clean_git\clang\include\clang/Basic/Sanitizers.def(41,1): message : see usage of 'clang::SanitizerMask::bitPosToMask' [C:\src\upstream\df6291a666d3-PS4-Release\tools\clang\lib\Basic\obj.clangBasic.vcxproj]
```
I did note however that a later version of the Visual C++ compiler that I have installed on my local machine, 19.29.30141.0, was able to compile the code with no errors when using `/permissive-`, so it appears that it may be a problem with an older, but still supported version of the Visual C++ compiler.

I am attaching a zipped preprocessed file ([repro3.zip](https://github.com/llvm/llvm-project/files/8965792/repro3.zip)) that when compiled with the older version of Visual C++ (`cl.exe /c /permissive- repro3.cpp`) it will give the error mentioned above, while using a more recent version like what I have installed on my local machine compiles it with no errors. We should fix this so that it works with all currently supported versions of the host toolchain.

**Comment by efriedma-quic** [comment]
I tried out the given file with various Visual Studio versions at https://godbolt.org/ , and I didn't manage to reproduce.  I think that has all the same versions available through the Visual Studio installer, so I don't have any way to get the exact compiler you're using.  (Maybe the issue was fixed in some 16.7 patch release?)

If you can suggest some workaround, we can consider it.

**Comment by dyung** [comment]
It seems it might be a problem with the exact version we have installed on our build bots. I looked at godbolt and yes, it doesn't appear to have the same version that we are using available. If you have a copy of Visual Studio 2019 installed, here is a copy of [c1xx.zip](https://github.com/llvm/llvm-project/files/8970298/c1xx.zip) that you can use to reproduce the problem. Simply unzip the dll file, and then compile the repro3.cpp with a command similar to this: `cl.exe -Bx <full path to unzipped c1xx.dll> /c /permissive- repro3.cpp` and that should reproduce the problem I mentioned in the original comment.

As for a work-around, internally I have just disabled the `/permissive-` flag to get it working for us, but not sure if that is acceptable upstream.

**Comment by efriedma-quic** [comment]
I see the following possibilities:

- Declare the exact version you're using unsupported, and require a more recent 16.9 release if you're using 16.9.
- Revert the patch until we bump the minimum version requirement for some other reason.
- Add some CMake check for the exact compiler version you're using, and turn off /permissive- for that version specifically.
- Hack the source code in some way that works around the issue.

I guess the one thing I'm not sure about is what exactly a source code hack would look like.

**Comment by efriedma-quic** [comment]
Of those options, reverting the patch entirely is probably the one I like least; I'd like to catch any errors caused by /permissive- sooner rather than later.

**Comment by MehdiChinoune** [comment]
Which Windows SDK version are you using?
Windows SDKs < 10.0.16299.0 fail to compile with `/permissive-`

**Comment by dyung** [comment]
> Which Windows SDK version are you using? Windows SDKs < 10.0.16299.0 fail to compile with `/permissive-`

I don't think the Windows SDK version matters here. The preprocessed file that I provided above does not require any external references, and it compiles fine using `/permissive-` with 19.29.30141.0, but fails with 19.28.29915.0.

**Comment by dyung** [comment]
My preference would be to hack the source code to work around the issue, but like you mentioned, not sure how that would look like. Second preference would be to detect this particular version of the VC++ compiler (if that is even possible) and possibly disable `/permissive-` for that version.

**Comment by efriedma-quic** [comment]
In terms of possible source-code hacks, maybe you can avoid the constexpr call by turning the function into a macro?  The error message seems to point to something about the call...
