### PR TITLE
[flang-rt][unittests] Define MAP_ANONYMOUS fallback for AIX in Assign tests

### PR DESCRIPTION
**Pull request by DanielCChen**
We ran into 
```
flang-rt/unittests/Runtime/Assign.cpp:497:21: error: use of undeclared identifier 'MAP_ANONYMOUS'
  497 |       MAP_PRIVATE | MAP_ANONYMOUS, -1, 0)};
  ```
  
On AIX, `flang-rt` is built with `_XOPEN_SOURCE=700` and without `_ALL_SOURCE`, which prevents `<sys/mman.h> `from exposing `MAP_ANONYMOUS` / `MAP_ANON`. Provide a fallback definition so mmap unit tests introduced in PR #222101 compile successfully on AIX.

### CODE REVIEW

**Review by eugeneepshteyn — APPROVED** [review]
LGTM

**Comment by kkwli** [comment]
We encountered a similar situation in https://github.com/llvm/llvm-project/pull/183108#issuecomment-4013030826. Instead of hardcoding `MAP_ANONYMOUS`, the portable way is to map it to `/dev/zero`.

https://github.com/llvm/llvm-project/blob/f98bf7b005c268504e36df0a7da3a2170f698119/flang-rt/lib/runtime/trampoline.cpp#L239-L251

**Review by kkwli — APPROVED** [review]
LG. Thanks.
