### PR TITLE
Reapply "Reland "[llvm-profgen] Add support for ETM trace decoding"" …

### PR DESCRIPTION
**Pull request by gulfemsavrun**
…(#194695)

This relands the original commit e3bd61890e68303a33fdd33fbdd9abeda1037450 (#191584).

The original change was reverted in the following commits:

1) ec9d7d18bdfe21c30c94c02f14f3613f7b69a17b (#194087) 
2) c26ae41c8765fdd073c71061f21a83a161598901 (#194695)

This reland incorporates the following fixes:

1) Change LLVM_ENABLE_OPENCSD to default to OFF (opt-in).

2) Parse the OpenCSD version from ocsd_if_version.h and gate OpenCSD support on a minimum version of 1.5.4 to avoid compilation errors.

3) Refactor the test feature detection to use a
configure-time LLVM_HAVE_OPENCSD variable instead of runtime checks in lit.local.cfg.

### CODE REVIEW

**Comment by nathanchance** [comment]
I can confirm this appears to resolve the test failure I reported in #194465.

**Comment by gulfemsavrun** [comment]
> I can confirm this appears to resolve the test failure I reported in #194465.

Thank you very much for confirming this.

**Comment by madhur13490** [comment]
Changes in CMake files look ok to me. Thanks!

File: llvm/lib/ProfileData/CMakeLists.txt [hunk 1]
```diff
@@ -39,4 +40,60 @@ add_llvm_component_library(LLVMProfileData
...
+        "(${OPENCSD_VERSION}) is older than the required "
+        "${LLVM_OPENCSD_MIN_VERSION}. Install a newer OpenCSD or "
+        "configure with -DLLVM_ENABLE_OPENCSD=OFF.")
+    else()
+      message(STATUS
+        "LLVMProfileData: OpenCSD ${OPENCSD_VERSION} is older than "
+        "${LLVM_OPENCSD_MIN_VERSION}; ETM decoding support disabled.")
+    endif()
+  else()
+    if(LLVM_ENABLE_OPENCSD STREQUAL "ON")
```
Comment (petrhosek) [inline llvm/lib/ProfileData/CMakeLists.txt:91]: For other dependencies, we support three values: `OFF`, `ON` and `FORCE_ON`. In the case of `ON` we would proceed even if the dependency wasn't found, we would only report the error in the `FORCE_ON` case. We should do the same for `LLVM_ENABLE_OPENCSD` for consistency.

Comment (gulfemsavrun) [reply llvm/lib/ProfileData/CMakeLists.txt:91]: I uploaded https://github.com/llvm/llvm-project/pull/194973 to address this.
