### PR TITLE
[flang][OpenMP] Properly resolve CRITICAL construct names

### LINKED ISSUE #205855: [Flang][OpenMP] critical region with "omp_" leading name regression.
Consider the following code: 

```fortran
module repro_mod
  implicit none
  type :: t
  contains
    procedure :: sub
  end type t
contains
  logical function skip_unit(u)
    integer, intent(in) :: u
    logical :: opened
    inquire(unit=u, opened=opened)
    skip_unit = .not. opened
  end function skip_unit
  subroutine sub(this, text, us)
    class(t), intent(in) :: this
    character(len=*), intent(in) :: text
    integer, intent(in) :: us(:)
    integer :: i
    do i = 1, size(us)
      if (skip_unit(us(i))) cycle
      !$omp critical(omp_c)
      write(us(i), '(a)') text
      flush(us(i))
      !$omp end critical(omp_c)
    end do
  end subroutine sub
end module repro_mod
```

Compiling this code emits the following error message: 

```
scamp$ flang test.F90 -fopenmp -c
error: Semantic errors in test.F90
test.F90:21:22: error: Internal: no symbol found for 'omp_c'
        !$omp critical(omp_c)
                       ^^^^^
test.F90:21:22: error: CRITICAL argument should be a name
        !$omp critical(omp_c)
                       ^^^^^
test.F90:21:22: error: 'OMP_C' is not a valid locator
        !$omp critical(omp_c)
                       ^^^^^
test.F90:24:26: error: Internal: no symbol found for 'omp_c'
        !$omp end critical(omp_c)
                           ^^^^^
test.F90:24:26: error: CRITICAL argument should be a name
        !$omp end critical(omp_c)
                           ^^^^^
test.F90:24:26: error: 'OMP_C' is not a valid locator
        !$omp end critical(omp_c)
                           ^^^^^
```

If I change the "omp_c" name to "c" - then it compiles as previously expected. From regression testing we know that it passed before c656cb11639b5e6bd43fc691b3dab91a5d42ce37 and failed after a1cdfebb72880cb1b5039611cafee7ca3af7a368. In that range, I immediately look suspiciously at 

14840af5d694f40dbc8b1733330da2db4000335c
[flang][OpenMP] Check that IF clause applies to at most one leaf 

846793e2a57a39c90a4e57a61ea940127bbabf1a
[flang][OpenMP][NFC] Hoist variant match-info construction into Semantics 

1cf4a0cb7909cb7b9e0bf15757fc77dc9b02c796
[flang][OpenMP] Lower task reduction modifier

e68e8d35c91b4fd3ba0ae3ef12d79b41d92580b2
[flang][OpenMP] Parsing and semantics of locators as part of OmpObject 

This fell out from testing a large, important application in our stack. Pinging the authors of the suspicious commits: @kparzysz @Saieiei @abidh

### PR DESCRIPTION
**Pull request by kparzysz**
Resolve the names of CRITICAL constructs even if they are reserved names.
This also limits locator parsing to known reserved names.

Fixes https://github.com/llvm/llvm-project/issues/205855

### CODE REVIEW

**Comment by Saieiei** [comment]
This looks correct to me, and the cleanup is a real improvement. Replacing the previous `Internal: no symbol found` / `CRITICAL argument should be a name` / `is not a valid locator` cascade with a single diagnostic, and resolving the lock symbol in `ResolveCriticalName`, both look right.

One optional consistency/severity question, not a blocker: OpenMP 5.2 §4 does reserve names beginning with `omp_` / `ompx_`, so the diagnostic is spec-backed. But under the same rule, ordinary declarations like `integer :: omp_c` / `logical :: omp_available` would also be non-conforming, and Flang appears to accept those today. So this currently enforces the prefix rule for `critical` names but not for ordinary declarations.

Given that, and given the compatibility concern in #205855, do we intentionally want this as a hard error here, or would a warning/portability diagnostic be a better fit until reserved-name checking is applied more uniformly? The existing `CRITICAL construct name ... conflicts with a previous declaration` case is also a warning, so I wanted to ask before approving the severity choice.

**Comment by eugeneepshteyn** [comment]
I strongly recommend that these kinds of errors should be a warning, so that the user could promote them to errors or turn them off, depending on their needs. This behavior could be documented as OpenMP extension.

**Comment by kparzysz** [comment]
> I strongly recommend that these kinds of errors should be a warning, so that the user could promote them to errors or turn them off, depending on their needs. This behavior could be documented as OpenMP extension.

The original fix actually did that, but since I had to make changes to lowering to handle reserved identifiers where only a designator was expected before, I was worried that allowing this could open some unforeseen can of worms.

I can come up with a solution that improves how we deal with reserved names (and emits a warning instead) if you're willing to wait until next week.

**Comment by kparzysz** [comment]
This is a quick fix that ignores reserved names except for predefined locator names.  It won't emit any diagnostics for the testcase in the issue, but a future PR will add those as warnings.

**Comment by Saieiei** [comment]
Thanks for reworking this. The new direction looks good to me.

One small request before I approve: since the previous reserved-name tests were removed when the behavior changed, could we keep/add a direct regression test showing that `critical(omp_c)` / `end critical(omp_c)` is accepted now? That would lock in the actual fix for #205855.

**Comment by sscalpone** [comment]
Thanks for the quick action!   We are seeing similar errors pop up in a few more contexts in real applications and in lots of test cases.  @scamp-nvidia will file a few more issues to track in case you'd like to expand this PR.  We're committed to informing our upstream users and modifying our tests to comply with the OpenMP standard but the quick relief proposed in this PR is very welcome!

**Comment by kparzysz** [comment]
> One small request before I approve: since the previous reserved-name tests were removed when the behavior changed, could we keep/add a direct regression test showing that `critical(omp_c)` / `end critical(omp_c)` is accepted now? That would lock in the actual fix for #205855.

I'd rather not add a test that checks for behavior that's strictly speaking incorrect.  I'll add checks for diagnostics in the PR that shows them.

**Comment by kparzysz** [comment]
I'm going to merge this, since it fixes the biggest problem.
