### PR TITLE
[CodeGen] Gate rematerializer unit tests on AMDGPU target being enabled

### PR DESCRIPTION
**Pull request by lucas-rami**
Issue introduced in #197575. Initialization functions for the AMDGPU target only work if the target is enabled.

### CODE REVIEW

**Review by arsenm — COMMENTED** [review]
Don't these usually use 
```  
  if (!TM)
    GTEST_SKIP();
```

Combined with avoiding building in cmake?

**Comment by lucas-rami** [comment]
Yes this currently happens in `SetUp` instead of `SetUpTestCase`

```cpp
const Target *T = TargetRegistry::lookupTarget("", TT, Error);
if (!T)
  GTEST_SKIP();
```

Adding an `#else` section with `GTEST_SKIP();` after the `#if LLVM_HAS_AMDGPU_TARGET` section achieves the same effect and avoids querying the same missing target many times, so I just added one.

**Comment by lucas-rami** [comment]
> Combined with avoiding building in cmake?

AFAIU there is no target-conditional building, tests usually initialize all available targets, then query a specific one and skip the test if it's not available.

**Review by MacDue — APPROVED** [review]

**Comment by pawosm-arm** [comment]
I'm still seeing this in our CI:
```
17:54:25  # | /workspace/src/flang/test/Driver/target-cpu-features.f90:79:17: error: CHECK-AMDGPU: expected string not found in input
17:54:25  # | ! CHECK-AMDGPU: "-fc1" "-triple" "amdgcn-amd-amdhsa"
```

**Comment by lucas-rami** [comment]
> I'm still seeing this in our CI:

That looks unrelated? This was an issue in the `unittests`.
