### PR TITLE
Reapply "[Clang][Sema] Refactor collection of multi-level template argument lists (#106585, #111173)"

### PR DESCRIPTION
**Pull request by sdkrystian**
This patch reapplies #111173, fixing a bug when instantiating dependent expressions that name a member template that is later explicitly specialized for a class specialization that is implicitly instantiated.

The bug is addressed by adding the `hasMemberSpecialization` function, which return `true` if _any_ redeclaration is a member specialization. This is then used when determining the instantiation pattern for a specialization of a template, and when collecting template arguments for a specialization of a template.

### CODE REVIEW

**Comment by sdkrystian** [comment]
@mstorsjo Tested this patch with QT and it builds without issue.

**Comment by mstorsjo** [comment]
> @mstorsjo Tested this patch with QT and it builds without issue.

Nice, thanks!

File: clang/include/clang/AST/DeclTemplate.h [hunk 1]
```diff
@@ -860,6 +860,16 @@ class RedeclarableTemplateDecl : public TemplateDecl,
...
   bool isMemberSpecialization() const { return Common.getInt(); }
 
+  /// Determines whether any redeclaration of this template was
+  /// a specialization of a member template.
+  bool hasMemberSpecialization() const {
+    for (const auto *D : redecls()) {
+      if (D->isMemberSpecialization())
+        return true;
+    }
+    return false;
```
Comment (mizvekov) [inline clang/include/clang/AST/DeclTemplate.h:870]: At least for RedeclarableTemplate, there is a common area which is shared by all redeclarations of a decl.
This could be implemented as a bit there, which would make sense in case the common area is used, thus allocated, for these users anyway.

Not required, just pointing out the possibility.

**Review by mizvekov — APPROVED** [review]

File: clang/include/clang/AST/DeclTemplate.h (hunk 1 above)
Comment (sdkrystian) [reply clang/include/clang/AST/DeclTemplate.h:870]: I've actually been investigating implementing a "common data" structure shared by all redeclarations of `Redeclarable` derived types for a while now (at least since last year). For now, I'd like to just merge a patch that works. In the future. I plan to further enhance this implementation once I unify how we store data common to all redeclarations.

**Comment by ilya-biryukov** [comment]
Looking through the patch, I think the `getTemplateInstantiationPattern` is what's really changed here.

**Comment by sdkrystian** [comment]
@ilya-biryukov This is caused by the change to `CheckFunctionTemplateSpecialization` in `SemaTemplate.cpp`; we previously called `DeduceTemplateArguments` with the canonical declaration of the primary template, but now we call it with the passed in primary template declaration. Since lookup typically finds the most recent visible declaration, the primary template used for the explicit specialization is `#2`.

**Comment by ilya-biryukov** [comment]
Could you dive a little deeper why this change is necessary? E.g. does the most recent redecl have some properties that the canonical declaration (which would be the first one) does not?

Also, how do we emulate the old behavior in places that are needed? E.g. in the example above, the code prefers the first redeclaration as a heuristic to find the public declaration instead of the (implementation detail) definition that usually follows later. It's slightly surprising that the call to `func = func->getCanonicalDecl();` does not end up with the first redeclaration.
Do you have an idea why that happens and what could be done to restore the old behavior?

I understand that Clang APIs are not stable, but we would need some migration path for our tools.

**Comment by sdkrystian** [comment]
> Could you dive a little deeper why this change is necessary? E.g. does the most recent redecl have some properties that the canonical declaration (which would be the first one) does not?

@ilya-biryukov When instantiating a template from a member template that was explicitly specialized for a given implicitly instantiated specialization of its enclosing class template, we need to keep track of which template was actually used as the primary template (since we consider the specialization to be a redeclaration of the (instantiated) member template). Since the initial declaration & the specialized declaration have different template depths, this (may) result in `getTemplateInstantiationArgs` returning an incomplete set of template arguments for an entity.

**Comment by ilya-biryukov** [comment]
> @ilya-biryukov When instantiating a template from a member template that was explicitly specialized for a given implicitly instantiated specialization of its enclosing class template, we need to keep track of which template was actually used as the primary template (since we consider the specialization to be a redeclaration of the (instantiated) member template). Since the initial declaration & the specialized declaration have different template depths, this (may) result in `getTemplateInstantiationArgs` returning an incomplete set of template arguments for an entity.


so this is for cases like this, right?
```cpp
template <class T>
struct Foo {
    template <class>
    struct Bar {
        int foo = 10;
    };
};

template <>
template <class T>
struct Foo<int>::Bar {
    int foo = 10;
};
```

who do we strictly need to change what we pick in the simpler cases above? (my guess would be that we want simpler code, but I want to confirm it)


Do you have any ideas on how to revert back to the old behavior? In the code example above, I would've expected that using canonical declaration after getting template instantiation pattern would give us the same results as before.
Any idea why that isn't happening?

**Comment by ilya-biryukov** [comment]
cc @gribozavr because this commit seems to break the nullability analysis (not upstream, but we've had previous discussions about it and have made changes to keep it working)

**Comment by shafik** [comment]
It looks like this is linked to this crash: https://github.com/llvm/llvm-project/issues/112222

**Comment by sdkrystian** [comment]
I've (unfortunately) stumbled upon a crash caused by this patch:
```cpp 
template<typename T>
struct A
{
    template<bool U>
    static constexpr bool f() requires U
    {
        return true;
    }
};

template<>
template<bool U>
constexpr bool A<short>::f() requires U
{
    return A<long>::f<U>();
}

template<>
template<bool U>
constexpr bool A<long>::f() requires U
{
    return true;
}

static_assert(A<short>::f<true>()); // crash here
```
I'll investigate tomorrow.

**Comment by steelannelida** [comment]
There's a weird error after this change + #112381. It only reproduces with multiple modules

* Module 1, `dep_lib.h`:

```
#ifndef DEB_LIB_H_
#define DEB_LIB_H_

#include <string>
#include <vector>

namespace f{
template<typename T>
class strm;
namespace t {
template <typename T>
std::vector<T> A(strm<T> stream);
}

template<typename T>
class strm{
template <typename V>
friend std::vector<V> t::A(strm<V> stream);
};

template <typename T>
strm<T> B(std::vector<T> elems);

inline strm<std::string> B(
    std::initializer_list<const char*> elems) {
  return B(std::vector<std::string>(elems.begin(), elems.end()));
}
}
#endif  // DEB_LIB_H_

```

* Module 2, `another_lib.h`; depends on module 1

```
#ifndef ANOTHER_LIB_H_
#define ANOTHER_LIB_H_

#include "deb_lib.h"

namespace f {
namespace t {

template<typename T>
std::vector<T> A(strm<T> stream) {
  std::vector<T> ret;
  return ret;
}

}
}
#endif  // ANOTHER_LIB_H_
```

* Module 3, consists also of `another_lib.h` and depends on module 2.

* Binary (depends on Module 1 & 3):

```

#include <vector>

#include "another_lib.h"

namespace {

namespace {

struct E {};

}  // namespace

class T {
 protected:
  void momo() {
    f::strm<E> x;
    f::t::A(x);
  }
};

}  // namespace
int main(int argc, char** argv) { return 0; }
```

When compiling the binary, I'm getting:

```
another_lib.h:12:10: error: no viable conversion from returned value of type 'vector<std::string>' to function return type 'vector<(anonymous namespace)::(anonymous namespace)::E>'
   12 |   return ret;
      |          ^~~
test_lib.cc:18:11: note: in instantiation of function template specialization 'f::t::A<(anonymous namespace)::(anonymous namespace)::E>' requested here
   18 |     f::t::A(x);
      |           ^
/include/vector:558:55: note: candidate constructor not viable: no known conversion from 'std::vector<string>' to 'const vector<E> &' for 1st argument
  558 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(const vector& __x);
      |                                                       ^      ~~~~~~~~~~~~~~~~~
/include/vector:564:55: note: candidate constructor not viable: no known conversion from 'std::vector<string>' to 'initializer_list<value_type>' (aka 'initializer_list<(anonymous namespace)::(anonymous namespace)::E>') for 1st argument
  564 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(initializer_list<value_type> __il);
      |                                                       ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/include/vector:575:55: note: candidate constructor not viable: no known conversion from 'std::vector<string>' to 'vector<E> &&' for 1st argument
  575 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(vector&& __x)
      |                                                       ^      ~~~~~~~~~~~~
/include/vector:447:64: note: explicit constructor is not a candidate
  447 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI explicit vector(const allocator_type& __a)
      |                                                                ^
/include/vector:456:64: note: explicit constructor is not a candidate
  456 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI explicit vector(size_type __n) {
      |        
```

I'm still working on getting the full commandline from our build system, but maybe this gives some idea on what's wrong

**Comment by sdkrystian** [comment]
@steelannelida I'm unable to reproduce this error... by "module" do you mean C++ module (a la `export module ...`)? If you can provide a godbolt like that would be greatly appreciated :)

**Comment by usx95** [comment]
I can reproduce this. I do not know how to build modules in godbolt. Here is the script and the relevant files: https://github.com/llvm/llvm-project/commit/518572d4e701d9e784268d2e78e4d9a9334b7971

The new breakage is:
```
./module_reproducer/args.sh
In module 'another_lib':
module_reproducer/another_lib.h:10:10: error: no viable conversion from returned value of type 'vector<std::basic_string<char>>' to function return type 'vector<int>'
   10 |   return std::vector<T>{};
      |          ^~~~~~~~~~~~~~~~
module_reproducer/test_lib.cc:4:6: note: in instantiation of function template specialization 'f::A<int>' requested here
    4 |   f::A<int>();
      |      ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:598:7: note: candidate constructor not viable: no known conversion from 'std::vector<basic_string<char, char_traits<char>, allocator<char>>>' to 'const vector<int> &' for 1st argument
  598 |       vector(const vector& __x)
      |       ^      ~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:617:7: note: candidate constructor not viable: no known conversion from 'std::vector<basic_string<char, char_traits<char>, allocator<char>>>' to 'vector<int> &&' for 1st argument
  617 |       vector(vector&&) noexcept = default;
      |       ^      ~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:675:7: note: candidate constructor not viable: no known conversion from 'std::vector<basic_string<char, char_traits<char>, allocator<char>>>' to 'initializer_list<value_type>' (aka 'initializer_list<int>') for 1st argument
  675 |       vector(initializer_list<value_type> __l,
      |       ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:539:7: note: explicit constructor is not a candidate
  539 |       vector(const allocator_type& __a) _GLIBCXX_NOEXCEPT
      |       ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:553:7: note: explicit constructor is not a candidate
  553 |       vector(size_type __n, const allocator_type& __a = allocator_type())
      |       ^
1 error generated.
```
Please let me know if you can reproduce or need help reproducing it.
Please also consider reverting this and fixing forward later.

**Comment by asmok-g** [comment]
Any updates on this ? This is blocking us in google. When do we expect the fix to be submitted ?

**Comment by sdkrystian** [comment]
@adam-smnk Should have the fix merged today

**Comment by sdkrystian** [comment]
@asmok-g @usx95 @steelannelida I have a fix ready in #114258

**Comment by shafik** [comment]
Note this is also linked to this crash: https://github.com/llvm/llvm-project/issues/114758

**Comment by alexfh** [comment]
> @asmok-g @usx95 @steelannelida I have a fix ready in #114258

Unfortunately, #114258 (and its second iteration - https://github.com/llvm/llvm-project/pull/114569 / https://github.com/llvm/llvm-project/commit/b24650e814e55d90acfc40acf045456c98f32b9c) don't fix the original problem. It looks like something important was lost in the reduction process. We'll try to come up with another reproducer, but this usually takes significant time, and then who knows how many more iterations are needed to fix all issues triggered by this revision. I wonder if it would be possible to temporarily back off this change in order to return the tree to a good state?

**Comment by sdkrystian** [comment]
@alexfh I can have a comprehensive reversion commit ready tomorrow. If possible, please provide a minimal repro :)

**Comment by alexfh** [comment]
> @alexfh I can have a comprehensive reversion commit ready tomorrow. If possible, please provide a minimal repro :)

We appreciate that! We'll try to provide new reduced cases soon.

**Comment by wlei-llvm** [comment]
Hi @sdkrystian , FYI, we also hit an error/assertion that bisected to this https://github.com/llvm/llvm-project/pull/114569

```
lvm-project/clang/lib/AST/ExprConstant.cpp:16601: bool clang::Expr::EvaluateAsConstantExpr(EvalResult &, const ASTContext &, ConstantExprKind) const: Assertion `!isValueDependent() && "Expression evaluator can't be called on a dependent expression."' failed.
```
I'm trying working on reducing the repro(it seems very slow).

**Comment by alexfh** [comment]
We've also found a clang crash and a few new compilation errors after https://github.com/llvm/llvm-project/pull/114569. We definitely need to revert it as well as this commit.

**Comment by sdkrystian** [comment]
Reverted in #115156, #115157, and #115159.

**Comment by sdkrystian** [comment]
@alexfh @wlei-llvm Please send a repro when you can!

**Comment by alexfh** [comment]
@kadircet is working on a repro for the crash we're seeing. @usx95 is looking at the compilation errors.

**Comment by usx95** [comment]
For module related compilation issue: I added the reproducer here: https://github.com/usx95/llvm-project/commit/8886dbecaf04f5c117e70d50e342bf264947cc64

Fails with:
<details>
```
sh module-reproducer/args.sh
In module 'libB':
module-reproducer/flume_test_utils.h:26:10: error: no viable conversion from returned value of type 'vector<std::basic_string<char>>' to function return type 'vector<S>'
   26 |   return ret;
      |          ^~~
module-reproducer/access_boundaries_test.cc:5:6: note: in instantiation of function template specialization 'N::Friend<S>' requested here
    5 |   N::Friend<S>({});
      |      ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:598:7: note: candidate constructor not viable: no known conversion from 'std::vector<basic_string<char, char_traits<char>, allocator<char>>>' to 'const vector<S> &' for 1st argument
  598 |       vector(const vector& __x)
      |       ^      ~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:617:7: note: candidate constructor not viable: no known conversion from 'std::vector<basic_string<char, char_traits<char>, allocator<char>>>' to 'vector<S> &&' for 1st argument
  617 |       vector(vector&&) noexcept = default;
      |       ^      ~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:675:7: note: candidate constructor not viable: no known conversion from 'std::vector<basic_string<char, char_traits<char>, allocator<char>>>' to 'initializer_list<value_type>' (aka 'initializer_list<S>') for 1st argument
  675 |       vector(initializer_list<value_type> __l,
      |       ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:539:7: note: explicit constructor is not a candidate
  539 |       vector(const allocator_type& __a) _GLIBCXX_NOEXCEPT
      |       ^
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:553:7: note: explicit constructor is not a candidate
  553 |       vector(size_type __n, const allocator_type& __a = allocator_type())
      |       ^
1 error generated.
```
</details>

**Comment by kadircet** [comment]
i've posted another reduced test case in https://github.com/llvm/llvm-project/pull/114569, as crash bisected to that commit specifically

**Comment by hokein** [comment]
The module issue caused by #114569, I reported a reproducer in https://github.com/llvm/llvm-project/pull/114569#issuecomment-2462556416.
