### PR TITLE
Reapply "[Clang] Implement resolution for CWG1835 (#92957)"

### PR DESCRIPTION
**Pull request by sdkrystian**
Reapplies #92957, fixing an instance where the `template` keyword was missing prior to a dependent name in `llvm/ADT/ArrayRef.h`. An _alias-declaration_ is used to work around [a bug affecting GCC releases before 11.1](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94799) which rejects the use of the `template` keyword prior to the _nested-name-specifier_ in the class member access (godbolt example [here](https://godbolt.org/z/nEzbnPqbP)).

### CODE REVIEW

**Review by Endilll — COMMENTED** [review]
Changes to DR tests look good.

**Comment by sdkrystian** [comment]
@chapuni This fixes the Ubuntu-20.04 g++ build issues you brought up in #98252.

**Review by chapuni — APPROVED** [review]
I've confirmed it's fine. Thanks!

**Comment by glandium** [comment]
This broke building abseil-cpp (cd75cb4ae32c46c84cef9a9c78b42174f22ed0ac as of writing).

STR:
- Clone https://github.com/abseil/abseil-cpp
- `cmake -B build -S abseil-cpp -DCMAKE_CXX_COMPILER=clang++ -GNinja`
- `ninja -C build`

**Comment by glandium** [comment]
Well, I guess this is working as intended, as adding `template` before `StorageT` fixes it.

**Comment by sdkrystian** [comment]
@glandium Yes, clang considers `std::move(*this)` to be dependent so `template` is required there.

**Comment by glandium** [comment]
The sad part is that MSVC and some old versions of GCC don't like `template` being added here :(

**Comment by pranavk** [comment]
Could we perhaps put this behind a flag to help with the transition?

Some cases can already be silenced with -Wno-missing-dependent-template-keyword but cases like above in absl are hard errors and there are no workarounds.

**Comment by sdkrystian** [comment]
@pranavk see #98613

**Comment by shafik** [comment]
> The sad part is that MSVC and some old versions of GCC don't like `template` being added here :(

It looks like the description provides a workaround for gcc but a bug report against MSVC should be filed if we don' have one already.

**Comment by hokein** [comment]
> @pranavk see #98613.
> 
> edit: sorry, the error recovery that is currently performed will not detect cases where the template argument list does not contain a a type. i can look into this monday.

Some analysis:

given the example `this->StorageT<I>` where `I` is an `int`, the error recovery mechanism uses `isTemplateArgumentList` [here](https://github.com/llvm/llvm-project/blob/main/clang/lib/Parse/ParseExprCXX.cpp#L563) to check if the current token sequence `< I >` forms a `< template-argument-list >`. However, since `I` is an expression, this becomes an ambiguous case—it could be interpreted as a less than comparison. Consequently, the error recovery doesn't activate for this case, and a hard error is emitted.

We might be able to tweak or improve the heuristic, but I don't have a good idea for an easy fix.

**Comment by hokein** [comment]
Summaries of changes after this patch:

1) for type template parameters and template template parameters, clang emits a warning, which can be suppressed by `-Wno-missing-dependent-templat-keyword` (after #98613);
2) for non-type template parameters, clang emits a hard `no_member` error

The 2) is not an uncommon scenario (the abseil failure is an example), and unfortunately, there is currently no way to suppress these errors (we're hitting when integrating the LLVM upstream into our codebase).

**Comment by hokein** [comment]
@sdkrystian, I think we need to temporarily revert your patch (and sorry for that), as there is no way to fully preserve the old behavior of clang (our integration has been blocking since last week, and I think other large projects may encounter this issue as well):

- The `-Wno-missing-dependent-template-keyword` flag only partially addresses the issue and doesn't work for non-type template parameters. Teaching the error recovery to handle this case might take some time, see my [comment](https://github.com/llvm/llvm-project/pull/98547#issuecomment-2227871325);
- Adding all the missing `template` keyword in a large codebase is not feasible in the short term. For example, when addressing the abseil failure, and we seem to encounter another [Clang issue](https://github.com/llvm/llvm-project/issues/98878);
- Maintaining a local revert internally is not a sustainable option due to the extensive changes in this patch, which affects > 1K lines of code;

I think the next reland needs to cover the non-type template case, so that we have a way to suppress the warning for all cases (this gives developer time to do the cleanup transition).

Thank you for your understanding.

**Comment by lukel97** [comment]
I'm also seeing a error when building the 510.parest_r benchmark from SPEC CPU 2017

**Comment by cor3ntin** [comment]
@opensdd You might want to know that CWG1835 is causing some disruption in the wild

I wonder if we should consider deploying that change *NOT* as a DR such that it would only affect C++23+ conformance,
that might alleviate some of the pain points.

**Comment by sdkrystian** [comment]
> @opensdd You might want to know that CWG1835 is causing some disruption in the wild
> 
> I wonder if we should consider deploying that change _NOT_ as a DR such that it would only affect C++23+ conformance, that might alleviate some of the pain points.

*@opensdh

**Comment by opensdh** [comment]
> You might want to know that CWG1835 is causing some disruption in the wild

I believe it, although the alternative (having to write `(it->end) < it->end` in the issue's example) seems like it would be just as user-hostile.

> I wonder if we should consider deploying that change _NOT_ as a DR such that it would only affect C++23+ conformance, that might alleviate some of the pain points.

If you think that would create fewer problems (like skew between libraries on their clients) than it solves, I'm not opposed to bringing that up in CWG.

**Comment by sdkrystian** [comment]
> I think the next reland needs to cover the non-type template case, so that we have a way to suppress the warning for all cases (this gives developer time to do the cleanup transition).

@hokein The problem with the non-type template case is that we would have to check the validity of constructs outside the potential _template-argument-list_ in order to disambiguate. For example, `w.x<y>::z` may be a valid expression (interpreted as `((w.x) < y) > ::z`) if the type of `w` is a class type that declares a member `x`, `::z` exists, and both `<` and `>` comparisons are valid. 

> I wonder if we should consider deploying that change NOT as a DR such that it would only affect C++23+ conformance, that might alleviate some of the pain points.

@cor3ntin Yes, this is what I was thinking and is the resolution I prefer.

**Comment by AaronBallman** [comment]
Given the amount of pain involved, I think this should be applied as a C++23 change rather than applied as a DR. I'd like to avoid adding a feature flag for this if possible (I'd prefer warning-default-as-error instead, but that doesn't seem particularly plausible here), but the cross-compiler behavior story may be sufficiently painful to make it worth considering.

**Comment by cor3ntin** [comment]
I sent an email to core. There seems to be some support to reconsider as gcc is having the same issue we are.

I propose the following:
 - Do nothing for clang 19
 - wait to see what wg21 decides to do - hopefully they come up with something workable in the coming months
- If the status quo of the standard remains, only apply the change in C++23 mode and try to improve recovery and diagnostics to help with transition.

Hopefully this works for everyone.
Sorry @sdkrystian , I know a lot of work went into this.

**Comment by sdkrystian** [comment]
@cor3ntin Well, if the alternative is not implementing the resolution at all I'll look into the feasibility of identifying missing `template` keywords in the non-type template parameter case. If I can get that working, I think it's pretty safe to reland this patch.

Also, I replied to your post on the core reflector. I find it rather unlikely that CWG will implement a mitigation mechanism as doing so would effectively revert the resolution to CWG1835.

**Comment by sdkrystian** [comment]
I have a [new branch](https://github.com/sdkrystian/llvm-project/tree/reapply-cwg-1835-again) ready where:
- We only apply the resolution to CWG1835 in C++23 and later, and
- We issue a diagnostic when its application results in a missing template keyword that breaks whatever construct that follows the intended template name. e.g.
```cpp
template<int I>
struct A {
  int x;
};

template<int I>
struct B : A<I> {
  void f() {
    this->A<I>::f(); // with -std=c++20 and earlier: no error
                     // with -std=c++23 and later: 
                     //     error: no member named 'f' in the global namespace
                     //     error: missing 'template' keyword prior to dependent template name 'A'
  }
};
```
WDYAT?

**Comment by mizvekov** [comment]
> WDYAT?

We generally try to avoid issuing more than one error diagnostic for the same problem.

Couldn't we instead issue a note `note: maybe missing 'template' keyword prior to dependent template name 'A'`
attached to the first error instead?

**Comment by mizvekov** [comment]
Another option would be to apply the resolution to all modes, but recover and issue a warning instead of an error.
How feasible would that be?

**Comment by sdkrystian** [comment]
> Another option would be to apply the resolution to all modes, but recover and issue a warning instead of an error. How feasible would that be?

@mizvekov Without unannotated tentative parsing (to be _properly_ introduced by #96364), issuing a warning is infeasible. Either way, by the time we detect the error we could be who knows how deep into the second operand of a `>` operator.

**Comment by mizvekov** [comment]
> @mizvekov Without unannotated tentative parsing (to be _properly_ introduced by #96364), issuing a warning is infeasible. Either way, by the time we detect the error we could be who knows how deep into the second operand of a `>` operator.

So when we are parsing `this->A`.
Suppose what follows it looks like a template argument list.
Then we see if `this->template A` would have found a template.
if it does find the template `A`, we issue the warning and proceed as if the user had written `this->template A`

Do you think that's workable?

**Comment by sdkrystian** [comment]
> > @mizvekov Without unannotated tentative parsing (to be _properly_ introduced by #96364), issuing a warning is infeasible. Either way, by the time we detect the error we could be who knows how deep into the second operand of a `>` operator.
> 
> So when we are parsing `this->A`. Suppose what follows it looks like a template argument list. Then we see if `this->template A` would have found a template. if it does find the template `A`, we issue the warning and proceed as if the user had written `this->template A`
> 
> Do you think that's workable?

We already do that :) the problem is when what follows `A` _doesn't_ unambiguously look like a template argument list:

``cpp
int x = 0;

template<int I>
struct f { };

template<typename T>
void g(T t)
{
    t.f<0>::x; // could be interpreted as '((t.f) < 0) > (::x)'
}
```

**Comment by mizvekov** [comment]
> We already do that :) the problem is when what follows `A` _doesn't_ unambiguously look like a template argument list:

Sure, but before CWG1835, we would perform the lookup anyway and treat the `<0>` as a template argument list, even if it isn't unambiguously a template argument list.

So we could try to do this just as well if A doesn't unambiguously look like a template argument list.

That seems better than not trying to apply the new rule at all.

**Comment by KyunLFA** [comment]
> I'm also seeing a hard "missing 'template' keyword prior to dependent template name" error when building the 510.parest_r benchmark from SPEC CPU 2017

Hitting this same error compiling the ares emulator on 19.

**Comment by nico** [comment]
Independent of the other issues, it looks like this also re-introduces #98878

**Comment by sdkrystian** [comment]
> > I'm also seeing a hard "missing 'template' keyword prior to dependent template name" error when building the 510.parest_r benchmark from SPEC CPU 2017
> 
> Hitting this same error compiling the ares emulator on 19.

Could either of you provide an example @KyunLFA @lukel97 ?

**Comment by sdkrystian** [comment]
> Independent of the other issues, it looks like this also re-introduces #98878

@nico #98878 still occurs without this patch applied:
```cpp
struct A 
{
    void f();
};

template<typename T>
int g(T t)
{
    using U = A; // clang 18.1: 'warning: unused type alias 'U''
    t.U::f();
}
```

**Comment by sdkrystian** [comment]
> > We already do that :) the problem is when what follows `A` _doesn't_ unambiguously look like a template argument list:
> 
> Sure, but before CWG1835, we would perform the lookup anyway and treat the `<0>` as a template argument list, even if it isn't unambiguously a template argument list.
> 
> So we could try to do this just as well if A doesn't unambiguously look like a template argument list.
> 
> That seems better than not trying to apply the new rule at all.

I'm not sure I follow. If we "treat the `<0>` as a template argument list, even if it isn't unambiguously a template argument list.", then aren't applying CWG1835 at all.

**Comment by mizvekov** [comment]
> I'm not sure I follow. If we "treat the `<0>` as a template argument list, even if it isn't unambiguously a template argument list.", then aren't applying CWG1835 at all. 

Yes, in that case. But I am arguing for selectively applying it. I thought that could work, but I am not sure, that's what I am asking.

**Comment by sdkrystian** [comment]
@mizvekov Consider a slightly altered version of the motivating example [in the DR](https://cplusplus.github.io/CWG/issues/1835.html):
```cpp
template<int I> void end();

template<typename T>
bool Foo(T it0, T it1) 
{
    return it0->end < it1->end || it0->end > it1->end;
}
```
`< it1->end || it0->end >` _looks_ like a template-argument-list, but the alternate interpretation (`(it0->end < it1->end) || (it0->end > it1->end)`) is also valid and reasonable.

**Comment by sdkrystian** [comment]
[Ping](https://github.com/llvm/llvm-project/pull/98547#issuecomment-2240040530) @cor3ntin @AaronBallman.

**Comment by KyunLFA** [comment]
@sdkrystian Sure do.

The offending code lives at https://github.com/ares-emulator/ares/blob/master/nall/shared-pointer.hpp

The error reads:
```
../nall/shared-pointer.hpp:65:5: error: missing 'template' keyword prior to dependent template name 'operator='
   65 |     operator=<U>(source);
      |     ^        ~~~
../nall/shared-pointer.hpp:70:5: error: missing 'template' keyword prior to dependent template name 'operator='
   70 |     operator=<U>(std::move(source));
      |     ^        ~~~
../nall/shared-pointer.hpp:75:5: error: missing 'template' keyword prior to dependent template name 'operator='
   75 |     operator=<U>(source);
      |     ^        ~~~
3 errors generated.
```

The offending code block:

```
template<typename T>
struct shared_pointer {
  template<typename... P> static auto create(P&&... p) {
    return shared_pointer<T>{new T(std::forward<P>(p)...)};
  }

  using type = T;
  shared_pointer_manager* manager = nullptr;

  template<typename U>
  struct is_compatible {
    static constexpr bool value = is_base_of<T, U>::value || is_base_of<U, T>::value;
  };

  shared_pointer() {
  }

  shared_pointer(T* source) {
    operator=(source);
  }

  shared_pointer(T* source, const function<void (T*)>& deleter) {
    operator=(source);
    manager->deleter = function<void (void*)>([=](void* p) {
      deleter((T*)p);
    });
  }

  shared_pointer(const shared_pointer& source) {
    operator=(source);
  }

  shared_pointer(shared_pointer&& source) {
    operator=(std::move(source));
  }

  template<typename U, typename = enable_if_t<is_compatible<U>::value>>
  shared_pointer(const shared_pointer<U>& source) {
    operator=<U>(source);
  }

  template<typename U, typename = enable_if_t<is_compatible<U>::value>>
  shared_pointer(shared_pointer<U>&& source) {
    operator=<U>(std::move(source));
  }

  template<typename U, typename = enable_if_t<is_compatible<U>::value>>
  shared_pointer(const shared_pointer_weak<U>& source) {
    operator=<U>(source);
  }

  template<typename U, typename = enable_if_t<is_compatible<U>::value>>
  shared_pointer(const shared_pointer<U>& source, T* pointer) {
    if((bool)source && (T*)source.manager->pointer == pointer) {
      manager = source.manager;
      manager->strong++;
    }
  }

  ~shared_pointer() {
    reset();
  }

  auto operator=(T* source) -> shared_pointer& {
    reset();
    if(source) {
      manager = new shared_pointer_manager((void*)source);
      manager->strong++;
      if constexpr(is_base_of_v<shared_pointer_this_base, T>) {
        source->weak = *this;
      }
    }
    return *this;
  }

  auto operator=(const shared_pointer& source) -> shared_pointer& {
    if(this != &source) {
      reset();
      if((bool)source) {
        manager = source.manager;
        manager->strong++;
      }
    }
    return *this;
  }

  auto operator=(shared_pointer&& source) -> shared_pointer& {
    if(this != &source) {
      reset();
      manager = source.manager;
      source.manager = nullptr;
    }
    return *this;
  }

  template<typename U, typename = enable_if_t<is_compatible<U>::value>>
  auto operator=(const shared_pointer<U>& source) -> shared_pointer& {
    if((uintptr)this != (uintptr)&source) {
      reset();
      if((bool)source) {
        manager = source.manager;
        manager->strong++;
      }
    }
    return *this;
  }

  template<typename U, typename = enable_if_t<is_compatible<U>::value>>
  auto operator=(shared_pointer&& source) -> shared_pointer& {
    if((uintptr)this != (uintptr)&source) {
      reset();
      manager = source.manager;
      source.manager = nullptr;
    }
    return *this;
  }

  template<typename U, typename = enable_if_t<is_compatible<U>::value>>
  auto operator=(const shared_pointer_weak<U>& source) -> shared_pointer& {
    reset();
    if((bool)source) {
      manager = source.manager;
      manager->strong++;
    }
    return *this;
  }

  auto data() -> T* {
    if(manager) return (T*)manager->pointer;
    return nullptr;
  }

  auto data() const -> const T* {
    if(manager) return (T*)manager->pointer;
    return nullptr;
  }

  auto operator->() -> T* { return data(); }
  auto operator->() const -> const T* { return data(); }

  auto operator*() -> T& { return *data(); }
  auto operator*() const -> const T& { return *data(); }

  auto operator()() -> T& { return *data(); }
  auto operator()() const -> const T& { return *data(); }

  template<typename U>
  auto operator==(const shared_pointer<U>& source) const -> bool {
    return manager == source.manager;
  }

  template<typename U>
  auto operator!=(const shared_pointer<U>& source) const -> bool {
    return manager != source.manager;
  }

  explicit operator bool() const {
    return manager && manager->strong;
  }

  auto unique() const -> bool {
    return manager && manager->strong == 1;
  }

  auto references() const -> u32 {
    return manager ? manager->strong : 0;
  }

  auto reset() -> void {
    if(manager && manager->strong) {
      //pointer may contain weak references; if strong==0 it may destroy manager
      //as such, we must destroy strong before decrementing it to zero
      if(manager->strong == 1) {
        if(manager->deleter) {
          manager->deleter(manager->pointer);
        } else {
          delete (T*)manager->pointer;
        }
        manager->pointer = nullptr;
      }
      if(--manager->strong == 0) {
        if(manager->weak == 0) {
          delete manager;
        }
      }
    }
    manager = nullptr;
  }

  template<typename U>
  auto cast() -> shared_pointer<U> {
    if(auto pointer = dynamic_cast<U*>(data())) {
      return {*this, pointer};
    }
    return {};
  }
};
```

Errors on 19, does not error on 18.1.8.

**Comment by sdkrystian** [comment]
@KyunLFA Could you send the commit hash of the clang build which you're using? I'm unable to reproduce.

**Comment by KyunLFA** [comment]
> @KyunLFA Could you send the commit hash of the clang build which you're using? I'm unable to reproduce the errors.

Sure, it's https://github.com/llvm/llvm-project/commit/43213002b99e32d618f2afbbaaeb2ff8dfc84e33 .

Also, just to make sure, have you tried building the whole ares emulator project with `make` on the root dir of https://github.com/ares-emulator/ares.git ?

**Comment by KyunLFA** [comment]
No longer errors for me...
