### PR TITLE
[NFC] fix build failure

### LINKED ISSUE #100296: LLVM incorrectly assumes `long double` is the same type as `_Float128` on ppc64le
```
/build/source/llvm/llvm/lib/Analysis/ConstantFolding.cpp:2129:34: error: invalid conversion from '_Float128 (*)(_Float128) noexcept' to 'long double (*)(long double)' [-fpermissive]
 2129 |         return ConstantFoldFP128(logf128, Op->getValueAPF(), Ty);
      |                                  ^~~~~~~
      |                                  |
      |                                  _Float128 (*)(_Float128) noexcept
/build/source/llvm/llvm/lib/Analysis/ConstantFolding.cpp:1787:43: note:   initializing argument 1 of 'llvm::Constant* {anonymous}::ConstantFoldFP128(long double (*)(long double), const llvm::APFloat&, llvm::Type*)'
 1787 | Constant *ConstantFoldFP128(long double (*NativeFP)(long double),
      |                             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
```

`ConstantFoldFP128`'s definition:
https://github.com/llvm/llvm-project/blob/599f8e1120db8c8c7a5e42134ea52650e8fb0f1c/llvm/lib/Analysis/ConstantFolding.cpp#L1786-L1798

Where it's called with mismatched types:
https://github.com/llvm/llvm-project/blob/599f8e1120db8c8c7a5e42134ea52650e8fb0f1c/llvm/lib/Analysis/ConstantFolding.cpp#L2129

### PR DESCRIPTION
**Pull request by chenzheng1030**
Fix the build failure caused by https://github.com/llvm/llvm-project/pull/94944

Fixes https://github.com/llvm/llvm-project/issues/100296

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

**Comment by aaronpuchert** [comment]
Any thoughts about picking this to the LLVM 19 release branch? It seems relatively harmless and fixes a build error.

**Comment by mgorny** [comment]
> Any thoughts about picking this to the LLVM 19 release branch? It seems relatively harmless and fixes a build error.

I agree (and had someone in Gentoo ping me about it), so I've requested the backport in the linked bug.
