### ISSUE TITLE
compiler-rt/s390x: `error: out-of-line definition of 'patchFunctionEntry' does not match any declaration in namespace '__xray'`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#115129]
On ubuntu lunar s390x: 
https://llvm-jenkins.debian.net/job/llvm-toolchain-lunar-binaries/architecture=s390x,distribution=lunar,label=s390x/1039/console
```
ib/linux/libclang_rt.asan-s390x.a
[3/50] Building CXX object compiler-rt/lib/xray/CMakeFiles/RTXray.s390x.dir/xray_s390x.cpp.o
FAILED: compiler-rt/lib/xray/CMakeFiles/RTXray.s390x.dir/xray_s390x.cpp.o 
/build/source/build-llvm/tools/clang/stage2-bins/./bin/clang++ --target=s390x-linux-gnu -DSANITIZER_COMMON_NO_REDEFINE_BUILTINS -DXRAY_HAS_EXCEPTIONS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/source/compiler-rt/lib/xray/.. -I/build/source/compiler-rt/lib/xray/../../include -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/source/build-llvm/tools/clang/stage2-bins/runtimes/runtimes-bins=../../../../../../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -Wall -Wno-unused-parameter -O2 -DNDEBUG -g1 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -ftrivial-auto-var-init=pattern -Wno-format -fno-rtti -std=c++17 -MD -MT compiler-rt/lib/xray/CMakeFiles/RTXray.s390x.dir/xray_s390x.cpp.o -MF compiler-rt/lib/xray/CMakeFiles/RTXray.s390x.dir/xray_s390x.cpp.o.d -o compiler-rt/lib/xray/CMakeFiles/RTXray.s390x.dir/xray_s390x.cpp.o -c /build/source/compiler-rt/lib/xray/xray_s390x.cpp
/build/source/compiler-rt/lib/xray/xray_s390x.cpp:20:14: error: out-of-line definition of 'patchFunctionEntry' does not match any declaration in namespace '__xray'
   20 | bool __xray::patchFunctionEntry(const bool Enable, uint32_t FuncId,
      |              ^~~~~~~~~~~~~~~~~~
/build/source/compiler-rt/lib/xray/xray_s390x.cpp:44:14: error: out-of-line definition of 'patchFunctionExit' does not match any declaration in namespace '__xray'
   44 | bool __xray::patchFunctionExit(const bool Enable, uint32_t FuncId,
      |              ^~~~~~~~~~~~~~~~~
/build/source/compiler-rt/lib/xray/xray_s390x.cpp:68:14: error: out-of-line definition of 'patchFunctionTailExit' does not match any declaration in namespace '__xray'
   68 | bool __xray::patchFunctionTailExit(const bool Enable, const uint32_t FuncId,
      |              ^~~~~~~~~~~~~~~~~~~~~
/build/source/compiler-rt/lib/xray/xray_s390x.cpp:71:10: error: no matching function for call to 'patchFunctionExit'
   71 |   return patchFunctionExit(Enable, FuncId, Sled);
      |          ^~~~~~~~~~~~~~~~~
/build/source/compiler-rt/lib/xray/xray_interface_internal.h:144:6: note: candidate function not viable: requires 4 arguments, but 3 were provided
  144 | bool patchFunctionExit(bool Enable, uint32_t FuncId, const XRaySledEntry &Sled,
      |      ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  145 |                        const XRayTrampolines &Trampolines);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
```

**Comment by sylvestre** [comment]
caused by https://github.com/llvm/llvm-project/pull/113252

**Comment by redstar** [comment]
Sorry, checking...

**Comment by sylvestre** [comment]
No worries. This is why we have a ci

**Comment by redstar** [comment]
Yes, the issue can be closed.
