### PR TITLE
[Modules] Handle decl attributes on deserialization the same as during parsing.

### PR DESCRIPTION
**Pull request by vsapsai**
Replace manual handling of 2 attributes with `Sema::mergeDeclAttributes`, which is called during parsing too. Also propagate attributes not from a previous redeclaration but from a previous redeclaration outside of the current module. This is done to avoid double propagation because attributes from a previous decl in the same module are already handled when a module is built.

Call `ASTDeclReader::attachLatestDecl` after each decl is added to a redeclaration chain, not once per `ASTReader::loadPendingDeclChain` call. This is done to maintain correct redeclaration chain for each `ASTDeclReader::attachPreviousDecl` call because [newly added] `mergeDeclAttributes` requires a correct redeclaration chain.

Separated `Parser::Initialize` and `Parser::ConsumeToken` so can move the initialization earlier. This way `Parser::Initialize`, `Sema::Initialize`, `ASTReader::InitializeSema` are executed before deserialization. This specific case is verified by "Modules/decl-attr-merge-explicit-modules.c".

rdar://175997317

### CODE REVIEW

**Comment by vsapsai** [comment]
Considered extending "clang/test/Modules/decl-attr-merge.mm" but decided not to overcomplicate the test with dissimilar files. That's why added "clang/test/Modules/decl-attr-merge2.c".

**Comment by vsapsai** [comment]
Moved `t_vxv` in "clang/test/OpenMP/declare_variant_construct_codegen_1.c" to have consistent `p_vxv, t_vxv` order in declarations. /cc @chichunchen as the author of the test.

**Comment by vsapsai** [comment]
cc for visibility:
* @vgvassilev about `IncrementalParser` change
* @inbelic about `HandleRootSignatureTarget` change
* @kevinlzh1108 about availability attribute change

**Comment by vsapsai** [comment]
Added Michael as a review because of https://reviews.llvm.org/D127182 And added Aaron for guidance on Parser changes.

**Review by ChuanqiXu9 — APPROVED** [review]
Serialization change LGTM

**Review by vgvassilev — APPROVED** [review]
The IncrementalParser changes LGTM!

**Comment by vsapsai** [comment]
Want to notify people I'm still working on this issue. Don't have much experience with lldb-api tests, so debugging them takes some time.

**Comment by vsapsai** [comment]
Looks like
> lldb-api :: commands/gui/spawn-threads/TestGuiSpawnThreads.py

was a flaky test. Not seeing it anymore.

File: clang/lib/Sema/Sema.cpp [hunk 1]
```diff
@@ -616,6 +616,8 @@ Sema::~Sema() {
   if (ExternalSemaSource *ExternalSema
         = dyn_cast_or_null<ExternalSemaSource>(Context.getExternalSource()))
     ExternalSema->ForgetSema();
+  if (ExternalSource)
+    ExternalSource->ForgetSema();
```
Comment (vsapsai) [inline clang/lib/Sema/Sema.cpp:627]: I don't like that we have different kinds of `ExternalSemaSource` in Sema and we treat them in a different way. But I believe fixing that is out of scope for this PR (though can be convinced otherwise).

File: clang/lib/Parse/ParseAST.cpp
Comment (vsapsai) [inline clang/lib/Parse/ParseAST.cpp:141]: I'd like to get @AaronBallman opinion on the change in `Parser::Initialize` API. Separating initialization from `ConsumeToken` is driven by the need to initialize the parser before `ExternalASTSource::StartTranslationUnit` which can start deserializing decls [and using Sema]. Calling `ConsumeToken` explicitly is somewhat clunky but doesn't seem like a terribly complicated API.

In general, I believe it is reasonable for `StartTranslationUnit` to assume that all other components have been initialized when it is called. And I think it is debatable to start actual work during initialization. I believe moving `ConsumeToken` out of `Parser::Initialize` makes the code easier to compose and not to rely on a specific order of calls so much.

File: clang/include/clang/Parse/Parser.h [hunk 2]
```diff
@@ -304,8 +304,9 @@ class Parser : public CodeCompletionHandler {
   typedef OpaquePtr<DeclGroupRef> DeclGroupPtrTy;
   typedef OpaquePtr<TemplateName> TemplateTy;
 
-  /// Initialize - Warm up the parser.
+  /// Prepare the parser and its components.
   ///
+  /// The lack of initialization can lead to missing functionality.
```
Comment (AaronBallman) [inline clang/include/clang/Parse/Parser.h]: Should we be calling `Initialize()` from the parser constructor instead of two-step initialization? It seems to me we now call `Initialize()` immediately after construction everywhere anyway.

File: clang/lib/Parse/ParseAST.cpp
Comment (AaronBallman) [reply clang/lib/Parse/ParseAST.cpp:141]: My first thought was that `Initialize()` *should* consume the token because the parser isn't actually initialized without there being a current token due to things like `getCurToken()`. However, the `Parser` constructor still honors the contract because `getCurToken()` will return a valid token (representing an EOF) if we've not called `ConsumeToken()` yet.

> In general, I believe it is reasonable for StartTranslationUnit to assume that all other components have been initialized when it is called. And I think it is debatable to start actual work during initialization. I believe moving ConsumeToken out of Parser::Initialize makes the code easier to compose and not to rely on a specific order of calls so much.

On balance, I think I agree.

Not signing you up for this as part of this PR, but if you wanted to update https://clang.llvm.org/docs/InternalsManual.html#the-parser-library at some point to mention the initialization dance, that might also help folks.

File: clang/lib/Parse/Parser.cpp [hunk 3]
```diff
@@ -578,9 +578,6 @@ void Parser::Initialize() {
   }
 
   Actions.Initialize();
-
-  // Prime the lexer look-ahead.
-  ConsumeToken();
```
Comment (AaronBallman) [inline clang/lib/Parse/Parser.cpp:583]: One thing I don't have a good intuition for is whether this will bite downstreams. I can't quite tell whether this is special enough we should alert downstreams that this change might break them or if this is a refactoring just like any other, mostly because this has been the parser behavior for so long and it's a somewhat subtle initialization change. Thoughts?

File: clang/include/clang/Parse/Parser.h (hunk 2 above)
Comment (vsapsai) [reply clang/include/clang/Parse/Parser.h]: You are right, this is a great suggestion. It simplifies API significantly and caught 1 place where I called `Initialize()` too late.

File: clang/lib/Parse/Parser.cpp (hunk 3 above)
Comment (vsapsai) [reply clang/lib/Parse/Parser.cpp:583]: I've tried bringing `ConsumeToken` back into `Parser::Initialize` like
```diff
   // Prime the lexer look-ahead.
-  ConsumeToken();
+  if (PP.getCurrentLexer())
+    ConsumeToken();
```
and it creates a more fragile API. `ConsumeToken` can affect the lexer presence, so in `clang::ParseAST`
```c++
bool HaveLexer = S.getPreprocessor().getCurrentLexer();
P.Initialize();
```
is fine but

```c++
P.Initialize();
bool HaveLexer = S.getPreprocessor().getCurrentLexer();
```
is a diSAstEr. This is super non-obvious and I don't wish anyone to debug it.

Following your suggestion to call `Parser::Initialize` from the constructor now the change is downstream-friendly. Now you need to call `Parser::ConsumeToken` instead of `Parser::Initialize` that causes a compilation error due to being private. So there is no silent breakage and a fix is pretty straightforward.

File: clang/lib/Parse/ParseAST.cpp
Comment (vsapsai) [reply clang/lib/Parse/ParseAST.cpp:141]: After calling `Initialize` from the constructor we don't have complicated requirements for the correct call order as you cannot call `Initialize` at the wrong moment. So there is no real need to document it. And now the requirement to call `ConsumeToken()` when you want to parse/lex doesn't look so annoying/non-obvious.

**Comment by vsapsai** [comment]
Premerge failures are unrelated, it is already tracked by #211393.

**Comment by vgvassilev** [comment]
Have you considered a larger change that might fix the whole initialization aspect of the parser: perhaps we could move it in the Action class itself...

File: clang/lib/Parse/Parser.cpp (hunk 3 above)
Comment (vsapsai) [reply clang/lib/Parse/Parser.cpp:583]: I have considered putting `Initialize` content directly into the constructor and keeping there only `ConsumeToken()`. This way Parser clients shouldn't have to make any changes. But I don't like that we are reinforcing that calling `Initialize()` is optional, not really that important. That's why I'm not a fan of this idea.

**Comment by vsapsai** [comment]
> Have you considered a larger change that might fix the whole initialization aspect of the parser: perhaps we could move it in the Action class itself...

I don't understand what exactly you mean. Are you talking about the need to call `Parser::Initialize()` and to call it at a specific time? Because with `Initialize()` called from the constructor both of those parts are handled automatically by creating a Parser (I guess, that is kinda a rationale for constructors).

**Comment by vgvassilev** [comment]
> > Have you considered a larger change that might fix the whole initialization aspect of the parser: perhaps we could move it in the Action class itself...
> 
> I don't understand what exactly you mean. Are you talking about the need to call `Parser::Initialize()` and to call it at a specific time? Because with `Initialize()` called from the constructor both of those parts are handled automatically by creating a Parser (I guess, that is kinda a rationale for constructors).

I was thinking to move the entire parser object under the frontend action class but that is much larger refactoring which I believe will drop the need for scattering Initialize and ConsumeToken around.

**Comment by vsapsai** [comment]
> > I don't understand what exactly you mean. Are you talking about the need to call `Parser::Initialize()` and to call it at a specific time? Because with `Initialize()` called from the constructor both of those parts are handled automatically by creating a Parser (I guess, that is kinda a rationale for constructors).
> 
> I was thinking to move the entire parser object under the frontend action class but that is much larger refactoring which I believe will drop the need for scattering Initialize and ConsumeToken around.

I see. `ParseAST` is already the abstraction to hide lower-level work with `Parser`. In the tests it is usually called from `ASTFrontendAction::ExecuteAction()`, so I don't think moving logic behind the frontend action would gain us much.

**Comment by vsapsai** [comment]
I would like to land this feature before the end of the week, so if anybody has objections or wants to take another look, that's the great time to do so.

And failing
> lldb-api :: functionalities/scripted_frame_provider/circular_dependency/TestFrameProviderCircularDependency.py

seems to be like an earlier intermittently failing LLDB test (different one, sigh).

**Comment by ChuanqiXu9** [comment]
This introduces a regression: https://github.com/llvm/llvm-project/issues/214091

Given this is not landed too long, I prefer to revert this.

File: clang/lib/Parse/Parser.cpp (hunk 3 above)
Comment (zygoloid) [reply clang/lib/Parse/Parser.cpp:583]: This PR got reverted. When this gets re-landed, please consider:

* Renaming `Initialize` to something else.
* Keeping a public `Initialize` function that just calls `ConsumeToken`.

That way, downstream consumers need *no* changes, and still get a semantically meaningful name for the initialization function that they have to call. (Calling `ConsumeToken` to initialize the parser is exposing an implementation detail.)

Comment (vsapsai) [reply clang/lib/Parse/Parser.cpp:583]: Ok. My motivation was to make `Initialize` to be called unconditionally (I mean not just for Parser but everywhere-ish). But nobody is excited about it and I don't like it enough to keep pushing. So will minimize the changes downstream.
